version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
    - default-jre-headless
  jobs:
    pre_install:
      - wget "https://github.com/plantuml/plantuml/releases/download/v1.2026.6/plantuml.jar" -O "/tmp/plantuml.jar"
      - echo "89948f14c93756c7a3fb7b69078ff37e8489fd79dd430c582b931e2f65358690" "/tmp/plantuml.jar" | sha256sum -c
sphinx:
  builder: html
  configuration: doc/htmldoc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
