---
extends: existence
message: Avoid gender-specific language when not necessary.
link: 'https://github.com/Homebrew/brew/blob/master/docs/Prose-Style-Guidelines.md#personal-pronouns'
level: warning
ignorecase: true
tokens:
  - him
  - her
  - she
  - he
  - his
  - hers
  - himself
  - herself
