# -*- coding: utf-8 -*-
#
# test_getstatus_39_compatibility.py
#
# This file is part of NEST.
#
# Copyright (C) 2004 The NEST Initiative
#
# NEST is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# NEST is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NEST.  If not, see <http://www.gnu.org/licenses/>.

"""
A rather brute-force test to ensure that GetStatus() in NEST 3.10 is backward compatible.

The test works as follows: When run with NEST prior to NEST 3.10 (pre PyNEST-NG), it will
collect output from various get()/GetStatus() calls in a dictionary and write that to a
Python file. This file has then be included in the function reference() below as hard-coded
expectation.

When run with NEST 3.10 or later, tests are executed normally and results of get()/GetStatus()
calls are compared with the reference from NEST 3.9.
"""

import json

import nest
import numpy as np
import pytest

try:
    version = nest.build_info["version"]
    mode = "perform_test"
except AttributeError:
    mode = "generate_reference"


@pytest.fixture
def multimeters():
    """
    Network nodes to query. We use multimeters to test status containing nested dictionaries.
    """

    nest.ResetKernel()
    n = nest.Create("iaf_psc_alpha", n=3, params={"I_e": [100, 200, 300]})
    mm = nest.Create("multimeter", n=3, params={"record_from": ["V_m", "I_syn_ex"]})
    nest.Connect(mm, n, "one_to_one")
    nest.Simulate(5)

    return mm


@pytest.fixture(scope="module")
def reference_file():
    # setup
    if mode == "generate_reference":
        rf = open("test_getstatus_39_reference.py", "w")
        rf.write("""def reference():\n    return {\n""")
    else:
        rf = None
    yield rf

    # teardown
    if rf:
        rf.write("""}\n""")
        rf.close()


def convert_to_lists(obj):
    """
    Convert to pure Python types to allow json serialization.

    Skip values that may change for good reason, currently only model_id.

    Created based on suggestions by Claude Sonnet 4.6.
    """

    if isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, (list, tuple)):
        return [convert_to_lists(item) for item in obj]
    elif isinstance(obj, dict):
        return {key: convert_to_lists(val) for key, val in obj.items()}
    else:
        return obj


def remove_keys(obj):
    """
    Skip values that may change for good reason, currently only model_id.

    Created based on suggestions by Claude Sonnet 4.6.
    """

    skip_keys = ["model_id"]
    if isinstance(obj, dict):
        return {key: remove_keys(val) for key, val in obj.items() if key not in skip_keys}
    elif isinstance(obj, (list, tuple)):
        return type(obj)(remove_keys(item) for item in obj)
    else:
        return obj


@pytest.mark.parametrize("output", ["", "json"])
@pytest.mark.parametrize("use_get", [True, False])  # n.get() vs GetStatus(n)
@pytest.mark.parametrize("selection", [None, 0])  # entire NodeCollection vs single neuron
@pytest.mark.parametrize(
    "keys",
    [
        [],
        ["start"],
        [["start"]],
        [["start", "stop"]],
        [["events", "start", "stop"]],
        # Hierarchical indexing works for get() only, we mark this
        # by giving the keys as tuple() instead of list.
        ("events", "times", "V_m"),
        ("events", ["times", "V_m"]),
    ],
)
def test_gs(reference_file, multimeters, output, use_get, selection, keys):

    if selection is None:
        n = multimeters
    else:
        n = multimeters[selection]

    if use_get:
        res = n.get(*keys, output=output)
    else:
        if not keys:
            res = nest.GetStatus(n, output=output)
        elif not isinstance(keys, tuple):
            res = nest.GetStatus(n, keys[0], output=output)
        else:
            return  # no hierarchial indexing with GetStatus

    res = convert_to_lists(res)  # avoid numpy-array issues
    tag = f"{output}-{use_get}-{selection}-{keys}"
    if mode == "perform_test":
        ref = reference()[tag]
        if output == "json":
            # Compare deserialized data to insulate from entry ordering and be able to filter keys
            res = json.loads(res)
            ref = json.loads(ref)
        # Do not compare keys with values that may change between versions, e.g., model_id
        assert remove_keys(res) == remove_keys(ref)
    else:
        reference_file.write(f'    "{tag}": ')
        reference_file.write(repr(res))
        reference_file.write(",\n")


def reference():
    """Generated by running tests with NEST 3.9 under macOS 26.4.1 built with Apple Clang 21 and pasted in here."""

    return {
        "-True-None-[]": {
            "element_type": ["recorder", "recorder", "recorder"],
            "events": [
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [1, 1, 1, 1],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
                },
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [2, 2, 2, 2],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512],
                },
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [3, 3, 3, 3],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767],
                },
            ],
            "frozen": [False, False, False],
            "global_id": [4, 5, 6],
            "interval": [1.0, 1.0, 1.0],
            "label": ["", "", ""],
            "local": [True, True, True],
            "model": ["multimeter", "multimeter", "multimeter"],
            "model_id": [98, 98, 98],
            "n_events": [4, 4, 4],
            "node_uses_wfr": [False, False, False],
            "offset": [0.0, 0.0, 0.0],
            "origin": [0.0, 0.0, 0.0],
            "record_from": [["V_m", "I_syn_ex"], ["V_m", "I_syn_ex"], ["V_m", "I_syn_ex"]],
            "record_to": ["memory", "memory", "memory"],
            "start": [0.0, 0.0, 0.0],
            "stop": [1.7976931348623157e308, 1.7976931348623157e308, 1.7976931348623157e308],
            "thread": [0, 0, 0],
            "thread_local_id": [3, 4, 5],
            "time_in_steps": [False, False, False],
            "vp": [0, 0, 0],
        },
        "json-True-None-[]": '{"element_type": ["recorder", "recorder", "recorder"], "events": [{"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [2, 2, 2, 2], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512]}, {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [3, 3, 3, 3], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767]}], "frozen": [false, false, false], "global_id": [4, 5, 6], "interval": [1.0, 1.0, 1.0], "label": ["", "", ""], "local": [true, true, true], "model": ["multimeter", "multimeter", "multimeter"], "model_id": [98, 98, 98], "n_events": [4, 4, 4], "node_uses_wfr": [false, false, false], "offset": [0.0, 0.0, 0.0], "origin": [0.0, 0.0, 0.0], "record_from": [["V_m", "I_syn_ex"], ["V_m", "I_syn_ex"], ["V_m", "I_syn_ex"]], "record_to": ["memory", "memory", "memory"], "start": [0.0, 0.0, 0.0], "stop": [1.7976931348623157e+308, 1.7976931348623157e+308, 1.7976931348623157e+308], "thread": [0, 0, 0], "thread_local_id": [3, 4, 5], "time_in_steps": [false, false, false], "vp": [0, 0, 0]}',
        "-False-None-[]": [
            {
                "element_type": "recorder",
                "events": {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [1, 1, 1, 1],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
                },
                "frozen": False,
                "global_id": 4,
                "interval": 1.0,
                "label": "",
                "local": True,
                "model": "multimeter",
                "model_id": 98,
                "n_events": 4,
                "node_uses_wfr": False,
                "offset": 0.0,
                "origin": 0.0,
                "record_from": ["V_m", "I_syn_ex"],
                "record_to": "memory",
                "start": 0.0,
                "stop": 1.7976931348623157e308,
                "thread": 0,
                "thread_local_id": 3,
                "time_in_steps": False,
                "vp": 0,
            },
            {
                "element_type": "recorder",
                "events": {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [2, 2, 2, 2],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512],
                },
                "frozen": False,
                "global_id": 5,
                "interval": 1.0,
                "label": "",
                "local": True,
                "model": "multimeter",
                "model_id": 98,
                "n_events": 4,
                "node_uses_wfr": False,
                "offset": 0.0,
                "origin": 0.0,
                "record_from": ["V_m", "I_syn_ex"],
                "record_to": "memory",
                "start": 0.0,
                "stop": 1.7976931348623157e308,
                "thread": 0,
                "thread_local_id": 4,
                "time_in_steps": False,
                "vp": 0,
            },
            {
                "element_type": "recorder",
                "events": {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [3, 3, 3, 3],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767],
                },
                "frozen": False,
                "global_id": 6,
                "interval": 1.0,
                "label": "",
                "local": True,
                "model": "multimeter",
                "model_id": 98,
                "n_events": 4,
                "node_uses_wfr": False,
                "offset": 0.0,
                "origin": 0.0,
                "record_from": ["V_m", "I_syn_ex"],
                "record_to": "memory",
                "start": 0.0,
                "stop": 1.7976931348623157e308,
                "thread": 0,
                "thread_local_id": 5,
                "time_in_steps": False,
                "vp": 0,
            },
        ],
        "json-False-None-[]": '[{"element_type": "recorder", "events": {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, "frozen": false, "global_id": 4, "interval": 1.0, "label": "", "local": true, "model": "multimeter", "model_id": 98, "n_events": 4, "node_uses_wfr": false, "offset": 0.0, "origin": 0.0, "record_from": ["V_m", "I_syn_ex"], "record_to": "memory", "start": 0.0, "stop": 1.7976931348623157e+308, "thread": 0, "thread_local_id": 3, "time_in_steps": false, "vp": 0}, {"element_type": "recorder", "events": {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [2, 2, 2, 2], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512]}, "frozen": false, "global_id": 5, "interval": 1.0, "label": "", "local": true, "model": "multimeter", "model_id": 98, "n_events": 4, "node_uses_wfr": false, "offset": 0.0, "origin": 0.0, "record_from": ["V_m", "I_syn_ex"], "record_to": "memory", "start": 0.0, "stop": 1.7976931348623157e+308, "thread": 0, "thread_local_id": 4, "time_in_steps": false, "vp": 0}, {"element_type": "recorder", "events": {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [3, 3, 3, 3], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767]}, "frozen": false, "global_id": 6, "interval": 1.0, "label": "", "local": true, "model": "multimeter", "model_id": 98, "n_events": 4, "node_uses_wfr": false, "offset": 0.0, "origin": 0.0, "record_from": ["V_m", "I_syn_ex"], "record_to": "memory", "start": 0.0, "stop": 1.7976931348623157e+308, "thread": 0, "thread_local_id": 5, "time_in_steps": false, "vp": 0}]',
        "-True-0-[]": {
            "element_type": "recorder",
            "events": {
                "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                "senders": [1, 1, 1, 1],
                "times": [1.0, 2.0, 3.0, 4.0],
                "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
            },
            "frozen": False,
            "global_id": 4,
            "interval": 1.0,
            "label": "",
            "local": True,
            "model": "multimeter",
            "model_id": 98,
            "n_events": 4,
            "node_uses_wfr": False,
            "offset": 0.0,
            "origin": 0.0,
            "record_from": ["V_m", "I_syn_ex"],
            "record_to": "memory",
            "start": 0.0,
            "stop": 1.7976931348623157e308,
            "thread": 0,
            "thread_local_id": 3,
            "time_in_steps": False,
            "vp": 0,
        },
        "json-True-0-[]": '{"element_type": "recorder", "events": {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, "frozen": false, "global_id": 4, "interval": 1.0, "label": "", "local": true, "model": "multimeter", "model_id": 98, "n_events": 4, "node_uses_wfr": false, "offset": 0.0, "origin": 0.0, "record_from": ["V_m", "I_syn_ex"], "record_to": "memory", "start": 0.0, "stop": 1.7976931348623157e+308, "thread": 0, "thread_local_id": 3, "time_in_steps": false, "vp": 0}',
        "-False-0-[]": [
            {
                "element_type": "recorder",
                "events": {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [1, 1, 1, 1],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
                },
                "frozen": False,
                "global_id": 4,
                "interval": 1.0,
                "label": "",
                "local": True,
                "model": "multimeter",
                "model_id": 98,
                "n_events": 4,
                "node_uses_wfr": False,
                "offset": 0.0,
                "origin": 0.0,
                "record_from": ["V_m", "I_syn_ex"],
                "record_to": "memory",
                "start": 0.0,
                "stop": 1.7976931348623157e308,
                "thread": 0,
                "thread_local_id": 3,
                "time_in_steps": False,
                "vp": 0,
            }
        ],
        "json-False-0-[]": '[{"element_type": "recorder", "events": {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, "frozen": false, "global_id": 4, "interval": 1.0, "label": "", "local": true, "model": "multimeter", "model_id": 98, "n_events": 4, "node_uses_wfr": false, "offset": 0.0, "origin": 0.0, "record_from": ["V_m", "I_syn_ex"], "record_to": "memory", "start": 0.0, "stop": 1.7976931348623157e+308, "thread": 0, "thread_local_id": 3, "time_in_steps": false, "vp": 0}]',
        "-True-None-['start']": [0.0, 0.0, 0.0],
        "json-True-None-['start']": "[0.0, 0.0, 0.0]",
        "-False-None-['start']": [0.0, 0.0, 0.0],
        "json-False-None-['start']": "[0.0, 0.0, 0.0]",
        "-True-0-['start']": 0.0,
        "json-True-0-['start']": "0.0",
        "-False-0-['start']": [0.0],
        "json-False-0-['start']": "[0.0]",
        "-True-None-[['start']]": {"start": [0.0, 0.0, 0.0]},
        "json-True-None-[['start']]": '{"start": [0.0, 0.0, 0.0]}',
        "-False-None-[['start']]": [[0.0], [0.0], [0.0]],
        "json-False-None-[['start']]": "[[0.0], [0.0], [0.0]]",
        "-True-0-[['start']]": {"start": 0.0},
        "json-True-0-[['start']]": '{"start": 0.0}',
        "-False-0-[['start']]": [[0.0]],
        "json-False-0-[['start']]": "[[0.0]]",
        "-True-None-[['start', 'stop']]": {
            "start": [0.0, 0.0, 0.0],
            "stop": [1.7976931348623157e308, 1.7976931348623157e308, 1.7976931348623157e308],
        },
        "json-True-None-[['start', 'stop']]": '{"start": [0.0, 0.0, 0.0], "stop": [1.7976931348623157e+308, 1.7976931348623157e+308, 1.7976931348623157e+308]}',
        "-False-None-[['start', 'stop']]": [
            [0.0, 1.7976931348623157e308],
            [0.0, 1.7976931348623157e308],
            [0.0, 1.7976931348623157e308],
        ],
        "json-False-None-[['start', 'stop']]": "[[0.0, 1.7976931348623157e+308], [0.0, 1.7976931348623157e+308], [0.0, 1.7976931348623157e+308]]",
        "-True-0-[['start', 'stop']]": {"start": 0.0, "stop": 1.7976931348623157e308},
        "json-True-0-[['start', 'stop']]": '{"start": 0.0, "stop": 1.7976931348623157e+308}',
        "-False-0-[['start', 'stop']]": [[0.0, 1.7976931348623157e308]],
        "json-False-0-[['start', 'stop']]": "[[0.0, 1.7976931348623157e+308]]",
        "-True-None-[['events', 'start', 'stop']]": {
            "events": [
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [1, 1, 1, 1],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
                },
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [2, 2, 2, 2],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512],
                },
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [3, 3, 3, 3],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767],
                },
            ],
            "start": [0.0, 0.0, 0.0],
            "stop": [1.7976931348623157e308, 1.7976931348623157e308, 1.7976931348623157e308],
        },
        "json-True-None-[['events', 'start', 'stop']]": '{"events": [{"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [2, 2, 2, 2], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512]}, {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [3, 3, 3, 3], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767]}], "start": [0.0, 0.0, 0.0], "stop": [1.7976931348623157e+308, 1.7976931348623157e+308, 1.7976931348623157e+308]}',
        "-False-None-[['events', 'start', 'stop']]": [
            [
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [1, 1, 1, 1],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
                },
                0.0,
                1.7976931348623157e308,
            ],
            [
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [2, 2, 2, 2],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512],
                },
                0.0,
                1.7976931348623157e308,
            ],
            [
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [3, 3, 3, 3],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767],
                },
                0.0,
                1.7976931348623157e308,
            ],
        ],
        "json-False-None-[['events', 'start', 'stop']]": '[[{"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, 0.0, 1.7976931348623157e+308], [{"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [2, 2, 2, 2], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512]}, 0.0, 1.7976931348623157e+308], [{"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [3, 3, 3, 3], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767]}, 0.0, 1.7976931348623157e+308]]',
        "-True-0-[['events', 'start', 'stop']]": {
            "events": {
                "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                "senders": [1, 1, 1, 1],
                "times": [1.0, 2.0, 3.0, 4.0],
                "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
            },
            "start": 0.0,
            "stop": 1.7976931348623157e308,
        },
        "json-True-0-[['events', 'start', 'stop']]": '{"events": {"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, "start": 0.0, "stop": 1.7976931348623157e+308}',
        "-False-0-[['events', 'start', 'stop']]": [
            [
                {
                    "I_syn_ex": [0.0, 0.0, 0.0, 0.0],
                    "senders": [1, 1, 1, 1],
                    "times": [1.0, 2.0, 3.0, 4.0],
                    "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
                },
                0.0,
                1.7976931348623157e308,
            ]
        ],
        "json-False-0-[['events', 'start', 'stop']]": '[[{"I_syn_ex": [0.0, 0.0, 0.0, 0.0], "senders": [1, 1, 1, 1], "times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}, 0.0, 1.7976931348623157e+308]]',
        "-True-None-('events', 'times', 'V_m')": [
            [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
            [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512],
            [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767],
        ],
        "json-True-None-('events', 'times', 'V_m')": "[[-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255], [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512], [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767]]",
        "-True-0-('events', 'times', 'V_m')": [
            -69.61934967214384,
            -69.27492301231193,
            -68.96327288272687,
            -68.68128018414255,
        ],
        "json-True-0-('events', 'times', 'V_m')": "[-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]",
        "-True-None-('events', ['times', 'V_m'])": {
            "times": [[1.0, 2.0, 3.0, 4.0], [1.0, 2.0, 3.0, 4.0], [1.0, 2.0, 3.0, 4.0]],
            "V_m": [
                [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
                [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512],
                [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767],
            ],
        },
        "json-True-None-('events', ['times', 'V_m'])": '{"times": [[1.0, 2.0, 3.0, 4.0], [1.0, 2.0, 3.0, 4.0], [1.0, 2.0, 3.0, 4.0]], "V_m": [[-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255], [-69.23869934428768, -68.54984602462386, -67.92654576545374, -67.36256036828512], [-68.85804901643152, -67.82476903693578, -66.88981864818061, -66.04384055242767]]}',
        "-True-0-('events', ['times', 'V_m'])": {
            "times": [1.0, 2.0, 3.0, 4.0],
            "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255],
        },
        "json-True-0-('events', ['times', 'V_m'])": '{"times": [1.0, 2.0, 3.0, 4.0], "V_m": [-69.61934967214384, -69.27492301231193, -68.96327288272687, -68.68128018414255]}',
    }
