Document: nest
Title: Debian nest Manual
Author: <insert document author here>
Abstract: This manual describes what nest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nest/nest.sgml.gz

Format: postscript
Files: /usr/share/doc/nest/nest.ps.gz

Format: text
Files: /usr/share/doc/nest/nest.text.gz

Format: HTML
Index: /usr/share/doc/nest/html/index.html
Files: /usr/share/doc/nest/html/*.html

  
