nest::MultiChannelInputBuffer
std::vector< std::array< double, num_channels > > nest::MultiChannelInputBuffer< num_channels >::buffer_
Buffered data stored in a vector of arrays of double values 1st dimension: ring buffer slot (index into outer vector) 2nd dimension: channel (index into inner array)
nest::MultiChannelInputBuffer< num_channels >::MultiChannelInputBuffer()
void nest::MultiChannelInputBuffer< num_channels >::add_value(const index slot, const index channel, const double value)
Referenced by nest::iaf_psc_alpha::handle.
const std::array< double, num_channels > & nest::MultiChannelInputBuffer< num_channels >::get_values_all_channels(const index slot) const
Referenced by nest::iaf_psc_alpha::update.
void nest::MultiChannelInputBuffer< num_channels >::reset_values_all_channels(const index slot)
Referenced by nest::iaf_psc_alpha::update.
void nest::MultiChannelInputBuffer< num_channels >::clear()
Referenced by nest::iaf_psc_alpha::init_buffers_.
void nest::MultiChannelInputBuffer< num_channels >::resize()
References nest::KernelManager::connection_manager, nest::ConnectionManager::get_max_delay, nest::ConnectionManager::get_min_delay, nest::kernel.
size_t nest::MultiChannelInputBuffer< num_channels >::size() const