nest::Device
Parameters_ nest::Device::P_
Referenced by get_status.
Variables_ nest::Device::V_
nest::Device::Device()
nest::Device::Device(const Device &n)
virtual nest::Device::~Device()
virtual void nest::Device::init_state()
Reset dynamic state to that of model.
virtual void nest::Device::init_buffers()
Reset buffers.
Referenced by nest::poisson_generator_ps::init_buffers_.
void nest::Device::pre_run_hook()
Set internal variables before calls to SimulationManager::run()
Referenced by nest::StimulationDevice::pre_run_hook, nest::RecordingDevice::pre_run_hook.
void nest::Device::get_status(DictionaryDatum &) const
References nest::Device::Parameters_::get, P_.
Referenced by nest::correlation_detector::get_status, nest::correlomatrix_detector::get_status, nest::correlospinmatrix_detector::get_status, nest::RecordingDevice::get_status, nest::StimulationDevice::get_status.
void nest::Device::set_status(const DictionaryDatum &)
References nest::Device::Parameters_::set.
Referenced by nest::correlation_detector::set_status, nest::correlomatrix_detector::set_status, nest::correlospinmatrix_detector::set_status, nest::RecordingDevice::set_status, nest::StimulationDevice::set_status.
virtual bool nest::Device::is_active(Time const &T) const =0
Returns true if the device is active at the given time stamp.
Semantics are implemented by subclasses.
long nest::Device::get_t_min_() const
Return lower limit in steps.
TodoShould be protected, but is temporarily public to solve inheritance problems in AnalogSamplingDevice.
Referenced by nest::PseudoRecordingDevice::is_active, nest::RecordingDevice::is_active.
long nest::Device::get_t_max_() const
Return upper limit in steps.
TodoShould be protected, but is temporarily public to solve inheritance problems in AnalogSamplingDevice.
Referenced by nest::PseudoRecordingDevice::is_active, nest::RecordingDevice::is_active.
nest::Time const & nest::Device::get_origin() const
Referenced by nest::RecordingBackendSIONlib::enroll, nest::poisson_generator_ps::pre_run_hook, nest::spike_generator::set_data_from_stimulation_backend, nest::spike_generator::set_status, nest::poisson_generator_ps::update, nest::spike_generator::update.
nest::Time const & nest::Device::get_start() const
Referenced by nest::RecordingBackendSIONlib::enroll, nest::poisson_generator_ps::pre_run_hook, nest::poisson_generator_ps::update.
nest::Time const & nest::Device::get_stop() const
Referenced by nest::RecordingBackendSIONlib::enroll, nest::poisson_generator_ps::update.