nest::SecondaryTargetDataFields
unsigned int nest::SecondaryTargetDataFields::recv_buffer_pos_
Referenced by get_recv_buffer_pos, set_recv_buffer_pos.
unsigned char nest::SecondaryTargetDataFields::syn_id_
Referenced by get_syn_id, set_syn_id.
void nest::SecondaryTargetDataFields::set_recv_buffer_pos(const size_t pos)
References nest::names::max, recv_buffer_pos_.
Referenced by nest::SourceTable::populate_target_data_fields_.
size_t nest::SecondaryTargetDataFields::get_recv_buffer_pos() const
References recv_buffer_pos_.
Referenced by nest::TargetTable::add_target.
void nest::SecondaryTargetDataFields::set_syn_id(const synindex syn_id)
References nest::names::max, syn_id_.
Referenced by nest::SourceTable::populate_target_data_fields_.
synindex nest::SecondaryTargetDataFields::get_syn_id() const
References syn_id_.
Referenced by nest::TargetTable::add_target.