nest::ConnectionCreator
ConnectionType
ConnectionType nest::ConnectionCreator::type_
Referenced by connect, ConnectionCreator.
bool nest::ConnectionCreator::allow_autapses_
Referenced by connect_to_target_, ConnectionCreator, fixed_indegree_, fixed_outdegree_.
bool nest::ConnectionCreator::allow_multapses_
Referenced by ConnectionCreator, fixed_indegree_, fixed_outdegree_.
bool nest::ConnectionCreator::allow_oversized_
Referenced by ConnectionCreator, fixed_indegree_, fixed_outdegree_, pairwise_bernoulli_on_source_, pairwise_bernoulli_on_target_.
std::shared_ptr< Parameter > nest::ConnectionCreator::number_of_connections_
Referenced by ConnectionCreator, fixed_indegree_, fixed_outdegree_.
std::shared_ptr< AbstractMask > nest::ConnectionCreator::mask_
Referenced by ConnectionCreator, fixed_indegree_, fixed_outdegree_, pairwise_bernoulli_on_source_, pairwise_bernoulli_on_target_.
std::shared_ptr< Parameter > nest::ConnectionCreator::kernel_
Referenced by connect_to_target_, ConnectionCreator, fixed_indegree_, fixed_outdegree_.
std::vector< index > nest::ConnectionCreator::synapse_model_
Referenced by connect_to_target_, ConnectionCreator, extract_params_, fixed_indegree_, fixed_outdegree_.
std::vector< std::vector< DictionaryDatum > > nest::ConnectionCreator::param_dicts_
Referenced by connect_to_target_, ConnectionCreator, fixed_indegree_, fixed_outdegree_.
std::vector< std::shared_ptr< Parameter > > nest::ConnectionCreator::weight_
Referenced by connect_to_target_, ConnectionCreator, extract_params_, fixed_indegree_, fixed_outdegree_.
std::vector< std::shared_ptr< Parameter > > nest::ConnectionCreator::delay_
Referenced by connect_to_target_, ConnectionCreator, extract_params_, fixed_indegree_, fixed_outdegree_.
nest::ConnectionCreator::ConnectionCreator(DictionaryDatum dict)
Construct a ConnectionCreator with the properties defined in the given dictionary.
Parameters for a ConnectionCreator are: "connection_type": Either "convergent" or "divergent". "allow_autapses": Boolean, true if autapses are allowed. "allow_multapses": Boolean, true if multapses are allowed. "allow_oversized": Boolean, true if oversized masks are allowed. "number_of_connections": Integer, number of connections to make for each source or target. "mask": Mask definition (dictionary or masktype). "kernel": Kernel definition (dictionary, parametertype, or double). "synapse_model": The synapse model to use. "targets": Which targets (model or lid) to select (dictionary). "sources": Which targets (model or lid) to select (dictionary). "weight": Synaptic weight (dictionary, parametertype, or double). "delay": Synaptic delays (dictionary, parametertype, or double). other parameters are interpreted as synapse parameters, and may be defined by a dictionary, parametertype, or double. dict dictionary containing properties for the connections.
References ALL_ENTRIES_ACCESSED, nest::names::allow_autapses, allow_autapses_, nest::names::allow_multapses, allow_multapses_, allow_oversized_, nest::names::allow_oversized_mask, nest::names::connection_type, nest::NestModule::create_mask, nest::NestModule::create_parameter, nest::names::delay, delay_, extract_params_, Fixed_indegree, Fixed_outdegree, nest::ModelManager::get_connector_defaults, nest::ModelManager::get_synapse_model_id, nest::names::has_delay, nest::kernel, nest::names::kernel, kernel_, nest::names::mask, mask_, nest::KernelManager::model_manager, numerics::nan, nest::names::number_of_connections, number_of_connections_, Pairwise_bernoulli_on_source, nest::names::pairwise_bernoulli_on_source, Pairwise_bernoulli_on_target, nest::names::pairwise_bernoulli_on_target, param_dicts_, synapse_model_, nest::names::synapse_parameters, type_, nest::names::weight, weight_.
void nest::ConnectionCreator::connect(Layer< D > &source, NodeCollectionPTR source_nc, Layer< D > &target, NodeCollectionPTR target_nc)
Connect two layers.
source source layer. source NodeCollection of the source. target target layer. target NodeCollection of the target.
References Fixed_indegree, fixed_indegree_, Fixed_outdegree, fixed_outdegree_, Pairwise_bernoulli_on_source, pairwise_bernoulli_on_source_, Pairwise_bernoulli_on_target, pairwise_bernoulli_on_target_, nest::names::source, nest::names::target, type_.
Referenced by nest::Layer< D >::connect.
void nest::ConnectionCreator::extract_params_(const DictionaryDatum &, std::vector< DictionaryDatum > &)
References nest::NestModule::create_parameter, nest::names::delay, delay_, nest::ModelManager::get_connector_defaults, nest::ModelManager::get_synapse_model_id, nest::names::has_delay, nest::kernel, nest::KernelManager::model_manager, numerics::nan, nest::names::params, nest::names::receptor_type, nest::names::synapse_label, nest::names::synapse_model, synapse_model_, nest::names::weight, weight_.
Referenced by ConnectionCreator.
void nest::ConnectionCreator::connect_to_target_(Iterator from, Iterator to, Node *tgt_ptr, const Position< D > &tgt_pos, thread tgt_thread, const Layer< D > &source)
References allow_autapses_, nest::ConnectionManager::connect, nest::KernelManager::connection_manager, delay_, nest::BaseRandomGenerator::drand, nest::Node::get_node_id, nest::Position< D, T >::get_vector, nest::get_vp_specific_rng, nest::kernel, kernel_, param_dicts_, nest::names::source, synapse_model_, weight_.
Referenced by pairwise_bernoulli_on_source_, pairwise_bernoulli_on_target_.
void nest::ConnectionCreator::pairwise_bernoulli_on_source_(Layer< D > &source, NodeCollectionPTR source_nc, Layer< D > &target, NodeCollectionPTR target_nc)
References allow_oversized_, nest::ConnectionCreator::PoolWrapper_< D >::begin, connect_to_target_, nest::ConnectionCreator::PoolWrapper_< D >::define, nest::ConnectionCreator::PoolWrapper_< D >::end, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, nest::Node::is_proxy, nest::kernel, mask_, nest::ConnectionCreator::PoolWrapper_< D >::masked_begin, nest::ConnectionCreator::PoolWrapper_< D >::masked_end, nest::KernelManager::node_manager, nest::names::source, nest::names::target, nest::KernelManager::vp_manager.
Referenced by connect.
void nest::ConnectionCreator::pairwise_bernoulli_on_target_(Layer< D > &source, NodeCollectionPTR source_nc, Layer< D > &target, NodeCollectionPTR target_nc)
References allow_oversized_, nest::ConnectionCreator::PoolWrapper_< D >::begin, connect_to_target_, nest::ConnectionCreator::PoolWrapper_< D >::define, nest::ConnectionCreator::PoolWrapper_< D >::end, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, nest::Node::has_proxies, nest::Node::is_proxy, nest::kernel, mask_, nest::ConnectionCreator::PoolWrapper_< D >::masked_begin, nest::ConnectionCreator::PoolWrapper_< D >::masked_end, nest::KernelManager::node_manager, nest::names::source, nest::names::target, nest::KernelManager::vp_manager.
Referenced by connect.
void nest::ConnectionCreator::fixed_indegree_(Layer< D > &source, NodeCollectionPTR source_nc, Layer< D > &target, NodeCollectionPTR target_nc)
References allow_autapses_, allow_multapses_, allow_oversized_, nest::MaskedLayer< D >::begin, nest::ConnectionManager::connect, nest::KernelManager::connection_manager, nest::names::d, delay_, nest::distance, nest::MaskedLayer< D >::end, nest::NodeManager::get_node_or_proxy, nest::Node::get_thread, nest::Position< D, T >::get_vector, nest::get_vp_specific_rng, nest::Node::has_proxies, nest::Node::is_proxy, nest::kernel, kernel_, mask_, nest::KernelManager::node_manager, number_of_connections_, nest::RandomDistribution< DistributionT >::param, param_dicts_, nest::names::positions, nest::names::source, synapse_model_, nest::names::target, nest::names::target_thread, nest::BaseRandomGenerator::ulrand, nest::names::w, weight_.
Referenced by connect.
void nest::ConnectionCreator::fixed_outdegree_(Layer< D > &source, NodeCollectionPTR source_nc, Layer< D > &target, NodeCollectionPTR target_nc)
References allow_autapses_, allow_multapses_, allow_oversized_, nest::MaskedLayer< D >::begin, nest::ConnectionManager::connect, nest::KernelManager::connection_manager, delay_, nest::distance, nest::MaskedLayer< D >::end, nest::NodeManager::get_node_or_proxy, nest::get_rank_synced_rng, nest::Node::get_thread, nest::Position< D, T >::get_vector, nest::Node::has_proxies, nest::Node::is_proxy, nest::kernel, kernel_, mask_, nest::KernelManager::node_manager, nest::names::number_of_connections, number_of_connections_, nest::RandomDistribution< DistributionT >::param, param_dicts_, nest::names::source, synapse_model_, nest::names::target, nest::names::target_thread, weight_.
Referenced by connect.