nest::RecordingDevice
Type
struct nest::RecordingDevice::Parameters_ nest::RecordingDevice::P_
Referenced by get_status, set_status, write.
struct nest::RecordingDevice::State_ nest::RecordingDevice::S_
Referenced by get_status, set_status, write.
DictionaryDatum nest::RecordingDevice::backend_params_
Referenced by get_status, set_status.
nest::RecordingDevice::RecordingDevice()
nest::RecordingDevice::RecordingDevice(const RecordingDevice &)
void nest::RecordingDevice::pre_run_hook(const std::vector< Name > &, const std::vector< Name > &)
References nest::KernelManager::io_manager, nest::kernel, nest::Device::pre_run_hook, nest::IOManager::set_recording_value_names.
bool nest::RecordingDevice::is_active(Time const &T) const override
Returns true if the device is active at the given time stamp.
Semantics are implemented by subclasses.
References nest::Time::get_steps, nest::Device::get_t_max_, nest::Device::get_t_min_.
Referenced by nest::multimeter::handle, nest::weight_recorder::handle.
virtual Type nest::RecordingDevice::get_type() const =0
Referenced by nest::RecordingBackendMPI::enroll, nest::RecordingBackendSIONlib::enroll.
const std::string & nest::RecordingDevice::get_label() const
Referenced by nest::RecordingBackendSIONlib::enroll, nest::RecordingBackendMPI::get_port.
void nest::RecordingDevice::set_status(const DictionaryDatum &) override
References backend_params_, nest::IOManager::check_recording_backend_device_status, nest::names::d, nest::IOManager::enroll_recorder, nest::Node::get_node_id, nest::KernelManager::io_manager, nest::kernel, P_, nest::RecordingDevice::Parameters_::record_to_, S_, nest::RecordingDevice::Parameters_::set, nest::RecordingDevice::State_::set, nest::Device::set_status.
Referenced by nest::multimeter::set_status, nest::spike_recorder::set_status, nest::spin_detector::set_status, nest::weight_recorder::set_status.
void nest::RecordingDevice::get_status(DictionaryDatum &) const override
References backend_params_, nest::names::d, nest::names::element_type, nest::RecordingDevice::Parameters_::get, nest::RecordingDevice::State_::get, nest::Node::get_node_id, nest::IOManager::get_recording_backend_device_defaults, nest::IOManager::get_recording_backend_device_status, nest::Device::get_status, nest::KernelManager::io_manager, nest::kernel, P_, nest::RecordingDevice::Parameters_::record_to_, nest::names::recorder, S_.
Referenced by nest::multimeter::get_status, nest::spike_recorder::get_status, nest::spin_detector::get_status, nest::weight_recorder::get_status.
void nest::Device::pre_run_hook()
Set internal variables before calls to SimulationManager::run()
Referenced by nest::multimeter::pre_run_hook, nest::spike_recorder::pre_run_hook, nest::spin_detector::pre_run_hook, nest::weight_recorder::pre_run_hook.
virtual void nest::Node::pre_run_hook()=0
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
void nest::RecordingDevice::write(const Event &, const std::vector< double > &, const std::vector< long > &)
References nest::KernelManager::io_manager, nest::kernel, nest::RecordingDevice::State_::n_events_, P_, nest::RecordingDevice::Parameters_::record_to_, S_, nest::IOManager::write.
Referenced by nest::multimeter::handle, nest::weight_recorder::handle.
void nest::RecordingDevice::set_initialized_() override
References nest::IOManager::enroll_recorder, nest::KernelManager::io_manager, nest::kernel.