sli::pool
size_t sli::pool::initial_block_size
size_t sli::pool::growth_factor
Referenced by alloc.
size_t sli::pool::block_size
number of elements per chunk
Referenced by alloc.
size_t sli::pool::el_size
sizeof an element
Referenced by get_el_size, size_of.
size_t sli::pool::instantiations
number of instantiated elements
Referenced by alloc, available, free, get_instantiations.
size_t sli::pool::total
total number of allocated elements
Referenced by available, get_total.
size_t sli::pool::capacity
number of free elements
chunk* sli::pool::chunks
linked list of memory chunks
link* sli::pool::head
head of free list
Referenced by alloc, free.
bool sli::pool::initialized_
True if the pool is initialized.
void sli::pool::grow(size_t)
make pool larger by n elements
void sli::pool::grow()
make pool larger
Referenced by alloc.
sli::pool::pool()
Create pool for objects of size n.
Initial is the initial allocation block size, i.e. the number of objects per block. growth is the factor by which the allocations block increases after each growth.
sli::pool::pool(const pool &)
sli::pool & sli::pool::operator=(const pool &)
sli::pool::pool(size_t n, size_t initial=100, size_t growth=1)
void sli::pool::init(size_t n, size_t initial=100, size_t growth=1)
sli::pool::~pool()
deallocate ALL memory
void sli::pool::reserve_additional(size_t n)
Increase the pools capacity (free slots) by n.
reserve_additional() ensures that the pool has at least n empty slots, i.e., that the pool can store at least n additional elements before more memory needs to be allocated from the operating system.
size_t sli::pool::available() const
References instantiations, total.
void * sli::pool::alloc()
allocate one element
References block_size, grow, growth_factor, head, instantiations, sli::pool::link::next.
Referenced by AggregateDatum< C, slt >::operator new, FunctionDatum::operator new, NumericDatum< D, slt >::operator new, TrieDatum::operator new.
void sli::pool::free(void *p)
put element back into the pool
References head, instantiations.
Referenced by AggregateDatum< C, slt >::operator delete, FunctionDatum::operator delete, NumericDatum< D, slt >::operator delete, TrieDatum::operator delete.
size_t sli::pool::size_of() const
References el_size.
Referenced by AggregateDatum< C, slt >::operator delete, NumericDatum< D, slt >::operator delete, TrieDatum::operator delete, AggregateDatum< C, slt >::operator new, NumericDatum< D, slt >::operator new, TrieDatum::operator new.
size_t sli::pool::get_el_size() const
References el_size.
size_t sli::pool::get_instantiations() const
References instantiations.
size_t sli::pool::get_total() const
References total.