nest::DataSecondaryEvent
std::set< synindex > nest::DataSecondaryEvent< DataType, Subclass >::supported_syn_ids_
Referenced by nest::DataSecondaryEvent< DataType, Subclass >::add_syn_id, nest::DataSecondaryEvent< DataType, Subclass >::get_supported_syn_ids, nest::DataSecondaryEvent< DataType, Subclass >::reset_supported_syn_ids.
size_t nest::DataSecondaryEvent< DataType, Subclass >::coeff_length_
Referenced by nest::DataSecondaryEvent< DataType, Subclass >::operator<<, nest::DataSecondaryEvent< DataType, Subclass >::set_coeff_length, nest::DataSecondaryEvent< DataType, Subclass >::set_coeffarray, nest::DataSecondaryEvent< DataType, Subclass >::size.
union nest::DataSecondaryEvent::CoeffarrayBegin nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_begin_
Referenced by nest::DataSecondaryEvent< DataType, Subclass >::begin, nest::DataSecondaryEvent< DataType, Subclass >::operator<<, nest::DataSecondaryEvent< DataType, Subclass >::operator>>, nest::DataSecondaryEvent< DataType, Subclass >::set_coeffarray.
union nest::DataSecondaryEvent::CoeffarrayEnd nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_end_
Referenced by nest::DataSecondaryEvent< DataType, Subclass >::end, nest::DataSecondaryEvent< DataType, Subclass >::operator<<, nest::DataSecondaryEvent< DataType, Subclass >::operator>>, nest::DataSecondaryEvent< DataType, Subclass >::set_coeffarray.
void nest::DataSecondaryEvent< DataType, Subclass >::add_syn_id(const synindex synid) override
This function adds the ids of connection models that use this event type.
This is called when the model is registered with the kernel and when the corresponded connector model is copied. This function needs to be a virtual function of the base class DataSecondaryEvent as it is usually called from a pointer or reference of type SecondaryEvent. See also:
References nest::VPManager::assert_single_threaded, nest::DataSecondaryEvent< DataType, Subclass >::supported_syn_ids_.
const std::set< synindex >& nest::DataSecondaryEvent< DataType, Subclass >::get_supported_syn_ids() const override
References nest::DataSecondaryEvent< DataType, Subclass >::supported_syn_ids_.
void nest::DataSecondaryEvent< DataType, Subclass >::reset_supported_syn_ids() override
Resets the vector of supported syn ids to those originally registered via ModelsModule or user defined Modules, i.e., removes all syn ids created by CopyModel.
This is important to maintain consistency across ResetKernel, which removes all copied models.
References nest::DataSecondaryEvent< DataType, Subclass >::supported_syn_ids_.
void nest::DataSecondaryEvent< DataType, Subclass >::set_coeffarray(std::vector< DataType > &ca)
References nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayBegin::as_DataType, nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayEnd::as_DataType, nest::DataSecondaryEvent< DataType, Subclass >::coeff_length_, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_begin_, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_end_.
Referenced by nest::step_rate_generator::update, nest::rate_neuron_ipn< TNonlinearities >::update_, nest::rate_neuron_opn< TNonlinearities >::update_, nest::rate_transformer_node< TNonlinearities >::update_.
std::vector< unsigned int >::iterator& nest::DataSecondaryEvent< DataType, Subclass >::operator<<(std::vector< unsigned int >::iterator &pos) override
The following operator is used to read the information of the DataSecondaryEvent from the buffer in EventDeliveryManager::deliver_events.
References nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayBegin::as_uint, nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayEnd::as_uint, nest::DataSecondaryEvent< DataType, Subclass >::coeff_length_, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_begin_, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_end_.
std::vector< unsigned int >::iterator& nest::DataSecondaryEvent< DataType, Subclass >::operator>>(std::vector< unsigned int >::iterator &pos) override
The following operator is used to write the information of the DataSecondaryEvent into the secondary_events_buffer_.
All DataSecondaryEvents are identified by the synid of the first element in supported_syn_ids_.
References nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayBegin::as_DataType, nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayEnd::as_DataType, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_begin_, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_end_, nest::write_to_comm_buffer.
size_t nest::DataSecondaryEvent< DataType, Subclass >::size() override
size of event in units of unsigned int
References nest::DataSecondaryEvent< DataType, Subclass >::coeff_length_.
const std::vector< unsigned int >::iterator& nest::DataSecondaryEvent< DataType, Subclass >::begin()
References nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayBegin::as_uint, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_begin_.
const std::vector< unsigned int >::iterator& nest::DataSecondaryEvent< DataType, Subclass >::end()
References nest::DataSecondaryEvent< DataType, Subclass >::CoeffarrayEnd::as_uint, nest::DataSecondaryEvent< DataType, Subclass >::coeffarray_end_.
DataType nest::DataSecondaryEvent< DataType, Subclass >::get_coeffvalue(std::vector< unsigned int >::iterator &pos)
References nest::read_from_comm_buffer.
static void nest::DataSecondaryEvent< DataType, Subclass >::set_coeff_length(const size_t coeff_length)
References nest::VPManager::assert_single_threaded, nest::DataSecondaryEvent< DataType, Subclass >::coeff_length_.