nest::bernoulli_synapse
typedef CommonSynapseProperties nest::bernoulli_synapse< targetidentifierT >::CommonPropertiesType
typedef Connection< targetidentifierT > nest::bernoulli_synapse< targetidentifierT >::ConnectionBase
constexpr ConnectionModelProperties nest::bernoulli_synapse< targetidentifierT >::properties
double nest::bernoulli_synapse< targetidentifierT >::weight_
Referenced by nest::bernoulli_synapse< targetidentifierT >::send, nest::bernoulli_synapse< targetidentifierT >::set_weight.
double nest::bernoulli_synapse< targetidentifierT >::p_transmit_
Referenced by nest::bernoulli_synapse< targetidentifierT >::send.
nest::bernoulli_synapse< targetidentifierT >::bernoulli_synapse()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
nest::bernoulli_synapse< targetidentifierT >::bernoulli_synapse(const bernoulli_synapse &rhs)=default
Copy constructor from a property object.
Needs to be defined properly in order for GenericConnector to work.
bernoulli_synapse& nest::bernoulli_synapse< targetidentifierT >::operator=(const bernoulli_synapse &rhs)=default
void nest::bernoulli_synapse< targetidentifierT >::check_connection(Node &s, Node &t, rport receptor_type, const CommonPropertiesType &)
References nest::Connection< targetidentifierT >::check_connection_, nest::names::receptor_type.
void nest::bernoulli_synapse< targetidentifierT >::send(Event &e, thread t, const CommonSynapseProperties &)
References nest::BaseRandomGenerator::drand, numerics::e, nest::bernoulli_synapse< targetidentifierT >::get_delay_steps, nest::SpikeEvent::get_multiplicity, nest::bernoulli_synapse< targetidentifierT >::get_rport, nest::bernoulli_synapse< targetidentifierT >::get_target, nest::get_vp_specific_rng, nest::names::n, nest::bernoulli_synapse< targetidentifierT >::p_transmit_, nest::SpikeEvent::set_multiplicity, nest::bernoulli_synapse< targetidentifierT >::weight_.
void nest::bernoulli_synapse< targetidentifierT >::get_status(DictionaryDatum &d) const
References nest::names::d, nest::names::p_transmit, nest::names::size_of, nest::names::weight.
void nest::bernoulli_synapse< targetidentifierT >::set_status(const DictionaryDatum &d, ConnectorModel &cm)
References nest::names::d, nest::names::p_transmit, nest::names::weight.
void nest::bernoulli_synapse< targetidentifierT >::set_weight(double w)
References nest::names::w, nest::bernoulli_synapse< targetidentifierT >::weight_.
long nest::Connection< targetidentifierT >::get_delay_steps() const
Return the delay of the connection in steps.
Referenced by nest::bernoulli_synapse< targetidentifierT >::send.
rport nest::Connection< targetidentifierT >::get_rport() const
Referenced by nest::bernoulli_synapse< targetidentifierT >::send.
Node* nest::Connection< targetidentifierT >::get_target(const thread tid) const
Referenced by nest::bernoulli_synapse< targetidentifierT >::send.