nest::NodeCollectionPrimitive
using nest::NodeCollectionPrimitive::const_iterator = nc_const_iterator
friend class nc_const_iterator
index nest::NodeCollectionPrimitive::first_
The first node ID in the primitive.
Referenced by assert_consistent_model_ids_, contains, find, local_begin, MPI_local_begin, NodeCollectionPrimitive, nest::nc_const_iterator::operator*, operator+, operator==, operator[], overlapping, print_primitive, size, slice.
index nest::NodeCollectionPrimitive::last_
The last node ID in the primitive.
Referenced by assert_consistent_model_ids_, contains, empty, find, is_contiguous_ascending, NodeCollectionPrimitive, nest::nc_const_iterator::operator*, operator+, operator==, operator[], overlapping, print_primitive, size.
index nest::NodeCollectionPrimitive::model_id_
Model ID of the node IDs.
Referenced by is_contiguous_ascending, NodeCollectionPrimitive, nest::nc_const_iterator::operator*, operator+, operator==, print_primitive, slice.
NodeCollectionMetadataPTR nest::NodeCollectionPrimitive::metadata_
Pointer to the metadata of the node IDs.
Referenced by get_metadata, operator+, operator==, print_me, set_metadata, slice.
bool nest::NodeCollectionPrimitive::nodes_have_no_proxies_
Whether the primitive contains devices or not.
Referenced by has_proxies, NodeCollectionPrimitive.
void nest::NodeCollectionPrimitive::assert_consistent_model_ids_(index) const
Raise an error if the model IDs of all nodes in the primitive are not the same as the expected model id.
For use in the constructor only. model_id Expected model id.
References first_, nest::ModelRangeManager::get_model_id, nest::ModelRangeManager::get_model_of_node_id, nest::Model::get_name, nest::kernel, last_, nest::KernelManager::modelrange_manager.
Referenced by NodeCollectionPrimitive.
nest::NodeCollectionPrimitive::NodeCollectionPrimitive(index first, index last, index model_id, NodeCollectionMetadataPTR)
Create a primitive from a range of node IDs, with provided model ID and metadata pointer.
first The first node ID in the primitive last The last node ID in the primitive model_id Model ID of the node IDs meta Metadata pointer of the node IDs
References assert_consistent_model_ids_, first_, last_, model_id_.
nest::NodeCollectionPrimitive::NodeCollectionPrimitive(index first, index last, index model_id)
Create a primitive from a range of node IDs, with provided model ID.
first The first node ID in the primitive last The last node ID in the primitive model_id Model ID of the node IDs
References first_, last_.
nest::NodeCollectionPrimitive::NodeCollectionPrimitive(index first, index last)
Create a primitive from a range of node IDs.
The model ID has to be found by the constructor. first The first node ID in the primitive last The last node ID in the primitive
References first_, nest::ModelRangeManager::get_model_id, nest::ModelManager::get_node_model, nest::Model::has_proxies, nest::kernel, last_, model_id_, nest::KernelManager::model_manager, nest::KernelManager::modelrange_manager, nodes_have_no_proxies_.
nest::NodeCollectionPrimitive::NodeCollectionPrimitive(const NodeCollectionPrimitive &)=default
Primitive copy constructor.
rhs Primitive to copy
NodeCollectionPrimitive & nest::NodeCollectionPrimitive::operator=(const NodeCollectionPrimitive &)=default
Primitive assignment operator.
rhs Primitive to assign
nest::NodeCollectionPrimitive::NodeCollectionPrimitive()
Create empty NodeCollection.
This is only for use by SPBuilder.
Referenced by operator+.
void nest::NodeCollectionPrimitive::print_me(std::ostream &) const override
Print out the contents of the NodeCollection in a pretty and informative way.
References empty, metadata_, print_primitive.
void nest::NodeCollectionPrimitive::print_primitive(std::ostream &) const
References first_, nest::Model::get_name, nest::ModelManager::get_node_model, nest::kernel, last_, model_id_, nest::KernelManager::model_manager, size.
Referenced by print_me.
index nest::NodeCollectionPrimitive::operator[](const size_t) const override
Get the node ID in the specified index in the NodeCollection.
idx Index in the NodeCollection a node ID
References first_, last_.
NodeCollectionPTR nest::NodeCollectionPrimitive::operator+(NodeCollectionPTR rhs) const override
Join two NodeCollections.
May return a primitive or composite, depending on the input. rhs NodeCollection pointer to the NodeCollection to be added a NodeCollection pointer
References empty, first_, get_metadata, last_, metadata_, model_id_, NodeCollectionPrimitive, overlapping, nest::NodeCollection::valid.
bool nest::NodeCollectionPrimitive::operator==(const NodeCollectionPTR rhs) const override
References first_, last_, metadata_, model_id_.
bool nest::NodeCollectionPrimitive::operator==(const NodeCollectionPrimitive &rhs) const
References first_, last_, metadata_, model_id_.
NodeCollectionPrimitive::const_iterator nest::NodeCollectionPrimitive::begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection
Referenced by to_array.
NodeCollectionPrimitive::const_iterator nest::NodeCollectionPrimitive::local_begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection, in a parallel context.
References first_, nest::VPManager::get_num_virtual_processes, nest::kernel, nest::VPManager::node_id_to_vp, size, nest::VPManager::thread_to_vp, nest::KernelManager::vp_manager.
NodeCollectionPrimitive::const_iterator nest::NodeCollectionPrimitive::MPI_local_begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection, in an MPI-parallel context.
References first_, nest::MPIManager::get_num_processes, nest::MPIManager::get_process_id_of_vp, nest::MPIManager::get_rank, nest::kernel, nest::KernelManager::mpi_manager, size.
NodeCollectionPrimitive::const_iterator nest::NodeCollectionPrimitive::end(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the end of the NodeCollection.
offset Index of element NC that iterator points to an iterator representing the end of the NodeCollection, taking offset into account
References size.
Referenced by slice, to_array.
ArrayDatum nest::NodeCollectionPrimitive::to_array() const override
Returns an ArrayDatum filled with node IDs from the primitive.
References begin, end, size.
size_t nest::NodeCollectionPrimitive::size() const override
Returns total number of node IDs in the primitive.
References first_, last_.
Referenced by end, local_begin, MPI_local_begin, nest::nc_const_iterator::nc_const_iterator, nest::nc_const_iterator::operator++, print_primitive, slice, to_array.
size_t nest::NodeCollectionPrimitive::step() const override
Returns the step between node IDs in the primitive.
Referenced by slice.
bool nest::NodeCollectionPrimitive::contains(index node_id) const override
Check if the NodeCollection contains a specified node ID.
node_id node ID to see if exists in the NodeCollection true if the NodeCollection contains the node ID, false otherwise
References first_, last_.
NodeCollectionPTR nest::NodeCollectionPrimitive::slice(size_t start, size_t end, size_t step=1) const override
Slices the NodeCollection to the boundaries, with an optional step parameter.
Note that the boundaries being specified are inclusive. start Index of the NodeCollection to start at end One past the index of the NodeCollection to stop at step Number of places between node IDs to skip. Defaults to 1 a NodeCollection pointer to the new, sliced NodeCollection.
References end, first_, metadata_, model_id_, size, step, nest::NodeCollection::valid.
void nest::NodeCollectionPrimitive::set_metadata(NodeCollectionMetadataPTR) override
Sets the metadata of the NodeCollection.
meta A Metadata pointer
References metadata_.
NodeCollectionMetadataPTR nest::NodeCollectionPrimitive::get_metadata() const override
Gets the metadata of the NodeCollection.
A Metadata pointer
References metadata_.
Referenced by nest::NodeCollectionComposite::operator+, operator+.
bool nest::NodeCollectionPrimitive::is_range() const override
bool nest::NodeCollectionPrimitive::empty() const override
Checks if the NodeCollection has no elements.
true if the NodeCollection is empty, false otherwise
References last_.
Referenced by operator+, print_me.
long nest::NodeCollectionPrimitive::find(const index) const override
Returns index of node with given node ID in NodeCollection.
Index of node with given node ID; -1 if node not in NodeCollection.
References first_, last_.
bool nest::NodeCollectionPrimitive::has_proxies() const override
Returns whether the NodeCollection contains any nodes with proxies or not.
true if any nodes in the NodeCollection has proxies, false otherwise.
References nodes_have_no_proxies_.
bool nest::NodeCollectionPrimitive::is_contiguous_ascending(NodeCollectionPrimitive &other) const
Checks if node IDs in another primitive is a continuation of node IDs in this primitive.
other Primitive to check for continuity True if the first element in the other primitive is the next after the last element in this primitive, and they both have the same model ID. Otherwise false.
References last_, model_id_.
bool nest::NodeCollectionPrimitive::overlapping(const NodeCollectionPrimitive &rhs) const
Checks if node IDs of another primitive is overlapping node IDs of this primitive.
rhs Primitive to be checked. True if the other primitive overlaps, false otherwise.
References first_, last_.
Referenced by operator+.