nest::rate_neuron_opn
typedef Node nest::rate_neuron_opn< TNonlinearities >::base
TNonlinearities nest::rate_neuron_opn< TNonlinearities >::nonlinearities_
Parameters_ nest::rate_neuron_opn< TNonlinearities >::P_
State_ nest::rate_neuron_opn< TNonlinearities >::S_
Referenced by nest::rate_neuron_opn< TNonlinearities >::get_noise_, nest::rate_neuron_opn< TNonlinearities >::get_noisy_rate_, nest::rate_neuron_opn< TNonlinearities >::get_rate_.
Variables_ nest::rate_neuron_opn< TNonlinearities >::V_
Buffers_ nest::rate_neuron_opn< TNonlinearities >::B_
friend class RecordablesMap< rate_neuron_opn< TNonlinearities > >
friend class UniversalDataLogger< rate_neuron_opn< TNonlinearities > >
RecordablesMap< rate_neuron_opn< TNonlinearities > > nest::rate_neuron_opn< TNonlinearities >::recordablesMap_
Mapping of recordables names to access functions.
Referenced by nest::rate_neuron_opn< TNonlinearities >::Parameters_::Parameters_, nest::rate_neuron_opn< TNonlinearities >::rate_neuron_opn.
nest::rate_neuron_opn< TNonlinearities >::rate_neuron_opn()
References nest::kernel, nest::rate_neuron_opn< TNonlinearities >::recordablesMap_, nest::Node::set_node_uses_wfr.
nest::rate_neuron_opn< TNonlinearities >::rate_neuron_opn(const rate_neuron_opn &)
References nest::kernel, nest::Node::set_node_uses_wfr.
void nest::rate_neuron_opn< TNonlinearities >::handle(InstantaneousRateConnectionEvent &) override
Handler for rate neuron events.
handle(thread, InstantaneousRateConnectionEvent&) UnexpectedEvent
References numerics::e.
void nest::rate_neuron_opn< TNonlinearities >::handle(DelayedRateConnectionEvent &) override
Handler for delay rate neuron events.
handle(thread, DelayedRateConnectionEvent&) UnexpectedEvent
References numerics::e.
void nest::rate_neuron_opn< TNonlinearities >::handle(DataLoggingRequest &) override
Handler for universal data logging request.
handle(SpikeEvent&) UnexpectedEvent
References numerics::e.
port nest::rate_neuron_opn< TNonlinearities >::handles_test_event(InstantaneousRateConnectionEvent &, rport) override
References nest::names::receptor_type.
port nest::rate_neuron_opn< TNonlinearities >::handles_test_event(DelayedRateConnectionEvent &, rport) override
References nest::names::receptor_type.
port nest::rate_neuron_opn< TNonlinearities >::handles_test_event(DataLoggingRequest &, rport) override
References nest::names::receptor_type.
void nest::rate_neuron_opn< TNonlinearities >::sends_secondary_event(InstantaneousRateConnectionEvent &) override
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::rate_neuron_opn< TNonlinearities >::sends_secondary_event(DelayedRateConnectionEvent &) override
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::rate_neuron_opn< TNonlinearities >::get_status(DictionaryDatum &) const override
Export properties of the node by setting entries in the status dictionary.
d Dictionary.
References nest::names::d, nest::ArchivingNode::get_status, nest::names::recordables.
void nest::rate_neuron_opn< TNonlinearities >::set_status(const DictionaryDatum &) override
Change properties of the node according to the entries in the dictionary.
d Dictionary with named parameter settings.
References nest::names::d, nest::rate_neuron_opn< TNonlinearities >::Parameters_::set, nest::rate_neuron_opn< TNonlinearities >::State_::set, nest::ArchivingNode::set_status.
void nest::Node::handle(SpikeEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(WeightRecorderEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(RateEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DataLoggingRequest &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DataLoggingReply &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(CurrentEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(ConductanceEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DoubleDataEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(GapJunctionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(InstantaneousRateConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DiffusionConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DelayedRateConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
port nest::Node::handles_test_event(SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event(). handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle. See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3. The semantics of all other handles_test_event() functions is identical. IllegalConnection
port nest::Node::handles_test_event(WeightRecorderEvent &, rport receptor_type)
port nest::Node::handles_test_event(RateEvent &, rport receptor_type)
port nest::Node::handles_test_event(DataLoggingRequest &, rport receptor_type)
port nest::Node::handles_test_event(CurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(ConductanceEvent &, rport receptor_type)
port nest::Node::handles_test_event(DoubleDataEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSSpikeEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSCurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(GapJunctionEvent &, rport receptor_type)
port nest::Node::handles_test_event(InstantaneousRateConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DiffusionConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DelayedRateConnectionEvent &, rport receptor_type)
void nest::Node::sends_secondary_event(GapJunctionEvent &ge)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::Node::sends_secondary_event(InstantaneousRateConnectionEvent &re)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::Node::sends_secondary_event(DiffusionConnectionEvent &de)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::Node::sends_secondary_event(DelayedRateConnectionEvent &re)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::rate_neuron_opn< TNonlinearities >::init_buffers_() override
Configure persistent internal data structures.
Let node configure persistent internal data structures, such as input buffers or ODE solvers, to runtime information prior to first simulation.
References nest::names::buffer_size, nest::ArchivingNode::clear_history, nest::KernelManager::connection_manager, nest::ConnectionManager::get_min_delay, nest::get_vp_specific_rng, nest::kernel, numerics::nan.
void nest::rate_neuron_opn< TNonlinearities >::pre_run_hook() override
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
References numerics::expm1, nest::Time::get_ms, nest::Time::get_resolution, nest::names::h.
bool nest::rate_neuron_opn< TNonlinearities >::update_(Time const &, const long, const long, const bool)
This is the actual update function.
The additional boolean parameter determines if the function is called by update (false) or wfr_update (true)
References nest::names::buffer_size, nest::KernelManager::connection_manager, nest::KernelManager::event_delivery_manager, nest::ConnectionManager::get_min_delay, nest::get_vp_specific_rng, nest::SimulationManager::get_wfr_tol, nest::kernel, numerics::nan, nest::names::origin, nest::EventDeliveryManager::send_secondary, nest::DataSecondaryEvent< DataType, Subclass >::set_coeffarray, nest::KernelManager::simulation_manager, nest::names::wfr_tol.
void nest::rate_neuron_opn< TNonlinearities >::update(Time const &, const long, const long) override
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to. Time network time at beginning of time slice. long initial step inside time slice long post-final step inside time slice
References nest::names::origin.
bool nest::rate_neuron_opn< TNonlinearities >::wfr_update(Time const &, const long, const long) override
Bring the node from state $t$ to $t+n*dt$, sends SecondaryEvents (e.g.
Default implementation of wfr_update just throws UnexpectedEvent. GapJunctionEvent) and resets state variables to values at $t$. n->wfr_update(T, from, to) performs the update steps beginning at T+from .. T+to-1. Does not emit spikes, does not log state variables. throws UnexpectedEvent if not reimplemented in derived class Time network time at beginning of time slice. long initial step inside time slice long post-final step inside time slice
References nest::names::origin.
double nest::rate_neuron_opn< TNonlinearities >::get_rate_() const
Read out the rate.
References nest::rate_neuron_opn< TNonlinearities >::State_::rate_, nest::rate_neuron_opn< TNonlinearities >::S_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::rate_neuron_opn< TNonlinearities >::get_noise_() const
Read out the noise.
References nest::rate_neuron_opn< TNonlinearities >::State_::noise_, nest::rate_neuron_opn< TNonlinearities >::S_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::rate_neuron_opn< TNonlinearities >::get_noisy_rate_() const
Read out the noisy rate.
References nest::rate_neuron_opn< TNonlinearities >::State_::noisy_rate_, nest::rate_neuron_opn< TNonlinearities >::S_.
Referenced by nest::RecordablesMap< HostNode >::create.