nest::RandomDistribution
using nest::RandomDistribution< DistributionT >::result_type = typename DistributionT::result_type
using nest::RandomDistribution< DistributionT >::param_type = typename DistributionT::param_type
DistributionT nest::RandomDistribution< DistributionT >::distribution_
Wrapped RandomDistribution.
Referenced by nest::RandomDistribution< DistributionT >::max, nest::RandomDistribution< DistributionT >::min, nest::RandomDistribution< DistributionT >::operator(), nest::RandomDistribution< DistributionT >::param.
nest::RandomDistribution< DistributionT >::RandomDistribution()=default
Constructs a distribution object with its default parameters.
nest::RandomDistribution< DistributionT >::~RandomDistribution()=default
result_type nest::RandomDistribution< DistributionT >::operator()(RngPtr g)
Generating function.
This function just flips the call, to call the RNG wrapper with the distribution. This is done so that the native C++ distribution can be called with the native C++ generator. g Pointer to the RNG wrapper.
References nest::RandomDistribution< DistributionT >::distribution_, nest::names::g.
result_type nest::RandomDistribution< DistributionT >::operator()(RngPtr g, param_type &params)
Generating function.
This function just flips the call, to call the RNG wrapper with the distribution. This is done so that the native C++ distribution can be called with the native C++ generator. g Pointer to the RNG wrapper. params Distribution parameter set to use.
References nest::RandomDistribution< DistributionT >::distribution_, nest::names::g, nest::names::params.
void nest::RandomDistribution< DistributionT >::param(const param_type &params)
Sets the distribution's associated parameter set to params.
params New contents of the distribution's associated parameter set.
References nest::RandomDistribution< DistributionT >::distribution_, nest::names::params.
Referenced by nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_, nest::LognormalParameter::LognormalParameter, nest::NormalParameter::NormalParameter.
result_type nest::RandomDistribution< DistributionT >::min() const
Returns the minimum value potentially generated by the distribution.
References nest::RandomDistribution< DistributionT >::distribution_.
result_type nest::RandomDistribution< DistributionT >::max() const
Returns the maximum value potentially generated by the distribution.
References nest::RandomDistribution< DistributionT >::distribution_.