nest::Parameter
bool nest::Parameter::is_spatial_
Referenced by nest::ExpDistParameter::ExpDistParameter, is_spatial, nest::MinParameter::MinParameter.
bool nest::Parameter::returns_int_only_
Referenced by nest::ConstantParameter::ConstantParameter, returns_int_only.
nest::Parameter::Parameter(bool is_spatial=false, bool returns_int_only=false)
Creates a Parameter, with optionally specified attributes.
is_spatial true if the Parameter contains spatial elements returns_int_only true if the value of the parameter can only be an integer
nest::Parameter::Parameter(const Parameter &p)=default
Copy constructor.
virtual nest::Parameter::~Parameter()=default
Virtual destructor.
virtual double nest::Parameter::value(RngPtr rng, Node *node)=0
Generates a value based on parameter specifications and arguments.
Used when getting a parameter value based on random values or node attributes, like position. Note that not all parameters support all overloaded versions. rng pointer to the random number generator node pointer to the node, used when the node position is relevant the value of the parameter.
Referenced by apply, value, value_is_integer_.
double nest::Parameter::value(RngPtr rng, const std::vector< double > &source_pos, const std::vector< double > &target_pos, const AbstractLayer &layer, Node *node)
Generates a value based on parameter specifications and arguments.
Used when connecting spatial nodes. Note that not all parameters support all overloaded versions. rng pointer to the random number generator source_pos position of the source node target_pos position of the target node layer spatial layer node target node, required for normal and lognormal parameters the value of the parameter.
References value.
std::vector< double > nest::Parameter::apply(const NodeCollectionPTR &, const TokenArray &)
Applies a parameter on a single-node ID NodeCollection and given array of positions.
array of result values, one per position in the TokenArray.
References nest::get_rank_synced_rng, TokenArray::size, value.
bool nest::Parameter::is_spatial() const
Check if the Parameter is based on spatial properties.
true if the Parameter is based on spatial properties, false otherwise.
References is_spatial_.
bool nest::Parameter::returns_int_only() const
Check if the Parameter only returns integer values.
true if the Parameter only returns integers, false otherwise.
References returns_int_only_.
Referenced by nest::ParameterConnParameterWrapper::provides_long.
bool nest::Parameter::value_is_integer_(const double value) const
References value.
Referenced by nest::ConstantParameter::ConstantParameter.