nest::MPIManager
int nest::MPIManager::num_processes_
number of MPI processes
Referenced by get_num_processes, get_process_id_of_vp, set_num_processes.
int nest::MPIManager::rank_
rank of the MPI process
Referenced by get_rank.
int nest::MPIManager::send_buffer_size_
expected size of send buffer
int nest::MPIManager::recv_buffer_size_
size of receive buffer
bool nest::MPIManager::use_mpi_
whether MPI is used
Referenced by is_mpi_used.
size_t nest::MPIManager::buffer_size_target_data_
total size of MPI buffer for
Referenced by get_buffer_size_target_data, increase_buffer_size_target_data, set_buffer_size_target_data.
size_t nest::MPIManager::buffer_size_spike_data_
total size of MPI buffer for
Referenced by decrease_buffer_size_spike_data, get_buffer_size_spike_data, increase_buffer_size_spike_data, set_buffer_size_spike_data.
size_t nest::MPIManager::max_buffer_size_target_data_
maximal size of MPI buffer for
Referenced by increase_buffer_size_target_data, set_buffer_size_target_data.
size_t nest::MPIManager::max_buffer_size_spike_data_
maximal size of MPI buffer for
Referenced by increase_buffer_size_spike_data, set_buffer_size_spike_data.
bool nest::MPIManager::adaptive_target_buffers_
whether MPI buffers for communication of
Referenced by adaptive_target_buffers, increase_buffer_size_target_data.
bool nest::MPIManager::adaptive_spike_buffers_
whether MPI buffers for communication of
Referenced by adaptive_spike_buffers, decrease_buffer_size_spike_data, increase_buffer_size_spike_data.
double nest::MPIManager::growth_factor_buffer_spike_data_
Referenced by increase_buffer_size_spike_data.
double nest::MPIManager::growth_factor_buffer_target_data_
Referenced by increase_buffer_size_target_data.
double nest::MPIManager::shrink_factor_buffer_spike_data_
Referenced by decrease_buffer_size_spike_data.
unsigned int nest::MPIManager::send_recv_count_spike_data_per_rank_
Referenced by communicate_off_grid_spike_data_Alltoall, communicate_spike_data_Alltoall, get_send_recv_count_spike_data_per_rank, set_buffer_size_spike_data.
unsigned int nest::MPIManager::send_recv_count_target_data_per_rank_
Referenced by communicate_target_data_Alltoall, get_send_recv_count_target_data_per_rank, set_buffer_size_target_data.
std::vector< int > nest::MPIManager::recv_counts_secondary_events_in_int_per_rank_
how many secondary elements (in ints) will be received from each rank
Referenced by get_recv_buffer_size_secondary_events_in_int, get_recv_count_secondary_events_in_int, set_recv_counts_secondary_events_in_int_per_rank.
std::vector< int > nest::MPIManager::send_counts_secondary_events_in_int_per_rank_
how many secondary elements (in ints) will be sent to each rank
Referenced by get_send_buffer_size_secondary_events_in_int, get_send_count_secondary_events_in_int.
std::vector< int > nest::MPIManager::recv_displacements_secondary_events_in_int_per_rank_
offset in the MPI receive buffer (in
ints) at which elements received from each rank will be written
Referenced by get_recv_buffer_size_secondary_events_in_int, get_recv_displacement_secondary_events_in_int, set_recv_counts_secondary_events_in_int_per_rank.
std::vector< int > nest::MPIManager::send_displacements_secondary_events_in_int_per_rank_
offset in the MPI send buffer (in ints)
from which elements send to each rank will be read
Referenced by get_send_buffer_size_secondary_events_in_int, get_send_displacement_secondary_events_in_int.
nest::MPIManager::MPIManager()
nest::MPIManager::~MPIManager() override
void nest::MPIManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References LOG, nest::M_FATAL.
void nest::MPIManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
void nest::MPIManager::set_status(const DictionaryDatum &) override
References nest::names::adaptive_spike_buffers, nest::names::adaptive_target_buffers, nest::names::buffer_size_spike_data, nest::names::buffer_size_target_data, nest::names::growth_factor_buffer_spike_data, nest::names::growth_factor_buffer_target_data, nest::names::max_buffer_size_spike_data, nest::names::max_buffer_size_target_data, nest::names::shrink_factor_buffer_spike_data.
void nest::MPIManager::get_status(DictionaryDatum &) override
References nest::names::adaptive_spike_buffers, nest::names::adaptive_target_buffers, nest::names::buffer_size_spike_data, nest::names::buffer_size_target_data, nest::names::growth_factor_buffer_spike_data, nest::names::growth_factor_buffer_target_data, nest::names::max_buffer_size_spike_data, nest::names::max_buffer_size_target_data, nest::names::num_processes, nest::names::recv_buffer_size_secondary_events, nest::names::send_buffer_size_secondary_events.
void nest::MPIManager::init_mpi(int *argc, char **argv[])
References nest::kernel, nest::KernelManager::mpi_manager, set_buffer_size_spike_data, set_buffer_size_target_data.
Referenced by nest::init_nest.
thread nest::MPIManager::get_num_processes() const
Return the number of processes used during simulation.
This functions returns the number of processes. Since each process has the same number of threads, the total number of threads is given by get_num_threads()*get_num_processes().
References num_processes_.
Referenced by nest::SimulationManager::call_update_, nest::ConnectionManager::compute_target_data_buffer_size, decrease_buffer_size_spike_data, nest::EventDeliveryManager::deliver_events_, nest::ConnectionManager::deliver_secondary_events, nest::EventDeliveryManager::distribute_target_data_buffers_, nest::VPManager::get_num_virtual_processes, nest::VPManager::get_vp, nest::FreeLayer< D >::lid_to_position_id_, set_buffer_size_spike_data, set_buffer_size_target_data, nest::VPManager::set_status, nest::VPManager::thread_to_vp, nest::VPManager::vp_to_thread, nest::EventDeliveryManager::write_done_marker_secondary_events_.
void nest::MPIManager::set_num_processes(thread n_procs)
Set the number of processes state variable.
This is used by dryrun_mode.
References num_processes_.
Referenced by nest::enable_dryrun_mode.
thread nest::MPIManager::get_rank() const
Get rank of MPI process.
References rank_.
Referenced by nest::ConnectionManager::compute_target_data_buffer_size, nest::VPManager::get_vp, nest::VPManager::is_local_vp, nest::RecordingBackendSIONlib::open_files_, nest::VPManager::thread_to_vp, nest::ConnectionManager::update_delay_extrema_.
nest::thread nest::MPIManager::get_process_id_of_vp(const thread vp) const
Return the process id for a given virtual process.
The real process' id of a virtual process is defined by the relation: p = (vp mod P), where P is the total number of processes.
References num_processes_, nest::names::vp.
Referenced by nest::VPManager::is_local_vp.
nest::thread nest::MPIManager::get_process_id_of_node_id(const index node_id) const
Referenced by nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources, nest::ConnectionManager::compute_compressed_secondary_recv_buffer_positions, nest::SourceTable::get_next_target_data, nest::SourceTable::source_should_be_processed_.
void nest::MPIManager::mpi_finalize(int exitcode)
Finalize MPI communication (needs to be separate from MPIManager::finalize when compiled with MUSIC since spikes can arrive and handlers called here)
Referenced by nestshutdown.
void nest::MPIManager::mpi_abort(int exitcode)
If MPI is available, this method calls MPI_Abort with the exitcode.
void nest::MPIManager::communicate(std::vector< long > &send_buffer, std::vector< long > &recv_buffer)
Referenced by nest::FreeLayer< D >::communicate_positions_, nest::ConnectionManager::compute_target_data_buffer_size, nest::SPManager::delete_synapses_from_post, nest::SPManager::delete_synapses_from_pre, nest::NodeManager::get_nodes, nest::ConnectionManager::update_delay_extrema_, nest::SPManager::update_structural_plasticity.
void nest::MPIManager::communicate(std::vector< unsigned int > &send_buffer, std::vector< unsigned int > &recv_buffer, std::vector< int > &displacements)
communicate (on-grid) if compiled without MPI
void nest::MPIManager::communicate(std::vector< OffGridSpike > &send_buffer, std::vector< OffGridSpike > &recv_buffer, std::vector< int > &displacements)
communicate (off-grid) if compiled without MPI
void nest::MPIManager::communicate(std::vector< double > &send_buffer, std::vector< double > &recv_buffer, std::vector< int > &displacements)
void nest::MPIManager::communicate(std::vector< unsigned long > &send_buffer, std::vector< unsigned long > &recv_buffer, std::vector< int > &displacements)
void nest::MPIManager::communicate(std::vector< int > &send_buffer, std::vector< int > &recv_buffer, std::vector< int > &displacements)
void nest::MPIManager::communicate(double, std::vector< double > &)
void nest::MPIManager::communicate(std::vector< int > &)
void nest::MPIManager::communicate(std::vector< long > &)
void nest::MPIManager::communicate_Allreduce_sum_in_place(double buffer)
void nest::MPIManager::communicate_Allreduce_sum_in_place(std::vector< double > &buffer)
void nest::MPIManager::communicate_Allreduce_sum_in_place(std::vector< int > &buffer)
void nest::MPIManager::communicate_Allreduce_sum(std::vector< double > &send_buffer, std::vector< double > &recv_buffer)
bool nest::MPIManager::equal_cross_ranks(const double value)
Equal across all ranks.
value value on calling rank true if values across all ranks are equal, false otherwise or if any rank passes -inf as value
std::string nest::MPIManager::get_processor_name()
bool nest::MPIManager::is_mpi_used()
References use_mpi_.
size_t nest::MPIManager::get_buffer_size_target_data() const
Returns total size of MPI buffer for communication of connections.
References buffer_size_target_data_.
Referenced by set_buffer_size_target_data.
unsigned int nest::MPIManager::get_send_recv_count_target_data_per_rank() const
Returns size of MPI buffer for connections divided by number of processes.
References send_recv_count_target_data_per_rank_.
Referenced by nest::EventDeliveryManager::distribute_target_data_buffers_.
size_t nest::MPIManager::get_buffer_size_spike_data() const
Returns total size of MPI buffer for communication of spikes.
References buffer_size_spike_data_.
Referenced by set_buffer_size_spike_data.
unsigned int nest::MPIManager::get_send_recv_count_spike_data_per_rank() const
Returns size of MPI buffer for spikes divided by number of processes.
References send_recv_count_spike_data_per_rank_.
Referenced by nest::EventDeliveryManager::deliver_events_.
size_t nest::MPIManager::get_send_buffer_size_secondary_events_in_int() const
Returns total size of MPI send buffer for communication of secondary events.
References send_counts_secondary_events_in_int_per_rank_, send_displacements_secondary_events_in_int_per_rank_.
size_t nest::MPIManager::get_recv_buffer_size_secondary_events_in_int() const
Returns total size of MPI recv buffer for communication of secondary events.
References recv_counts_secondary_events_in_int_per_rank_, recv_displacements_secondary_events_in_int_per_rank_.
void nest::MPIManager::communicate_Alltoall(std::vector< D > &send_buffer, std::vector< D > &recv_buffer, const unsigned int send_recv_count)
Referenced by communicate_off_grid_spike_data_Alltoall, communicate_spike_data_Alltoall, communicate_target_data_Alltoall.
void nest::MPIManager::communicate_target_data_Alltoall(std::vector< D > &send_buffer, std::vector< D > &recv_buffer)
References communicate_Alltoall, send_recv_count_target_data_per_rank_.
Referenced by nest::EventDeliveryManager::gather_target_data.
void nest::MPIManager::communicate_spike_data_Alltoall(std::vector< D > &send_buffer, std::vector< D > &recv_buffer)
References communicate_Alltoall, send_recv_count_spike_data_per_rank_.
Referenced by nest::EventDeliveryManager::gather_spike_data_.
void nest::MPIManager::communicate_off_grid_spike_data_Alltoall(std::vector< D > &send_buffer, std::vector< D > &recv_buffer)
References communicate_Alltoall, send_recv_count_spike_data_per_rank_.
Referenced by nest::EventDeliveryManager::gather_spike_data_.
void nest::MPIManager::communicate_secondary_events_Alltoallv(std::vector< D > &send_buffer, std::vector< D > &recv_buffer)
Referenced by nest::EventDeliveryManager::gather_secondary_events.
void nest::MPIManager::synchronize()
Referenced by nest::SimulationManager::call_update_, nest::NestModule::SyncProcessesFunction::execute.
bool nest::MPIManager::any_true(const bool)
Referenced by nest::ConnectionManager::check_secondary_connections_exist, nest::NodeManager::check_wfr_use, nest::ConnectionManager::sync_has_primary_connections.
double nest::MPIManager::time_communicate(int num_bytes, int samples=1000)
Benchmark communication time of different MPI methods.
The methods time_communicate* can be used to benchmark the timing of different MPI communication methods.
Referenced by nest::NestModule::TimeCommunication_i_i_bFunction::execute.
double nest::MPIManager::time_communicatev(int num_bytes, int samples=1000)
Referenced by nest::NestModule::TimeCommunicationv_i_iFunction::execute.
double nest::MPIManager::time_communicate_offgrid(int num_bytes, int samples=1000)
Referenced by nest::NestModule::TimeCommunication_i_i_bFunction::execute.
double nest::MPIManager::time_communicate_alltoall(int num_bytes, int samples=1000)
Referenced by nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute.
double nest::MPIManager::time_communicate_alltoallv(int num_bytes, int samples=1000)
Referenced by nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute.
void nest::MPIManager::set_buffer_size_target_data(size_t buffer_size)
References nest::names::buffer_size, buffer_size_target_data_, get_buffer_size_target_data, get_num_processes, max_buffer_size_target_data_, send_recv_count_target_data_per_rank_.
Referenced by nest::ConnectionManager::compute_target_data_buffer_size, increase_buffer_size_target_data, init_mpi.
void nest::MPIManager::set_buffer_size_spike_data(size_t buffer_size)
References nest::names::buffer_size, buffer_size_spike_data_, get_buffer_size_spike_data, get_num_processes, max_buffer_size_spike_data_, send_recv_count_spike_data_per_rank_.
Referenced by decrease_buffer_size_spike_data, increase_buffer_size_spike_data, init_mpi.
bool nest::MPIManager::increase_buffer_size_target_data()
Increases the size of the MPI buffer for communication of connections if it needs to be increased.
Returns whether the size was changed.
References adaptive_target_buffers_, buffer_size_target_data_, growth_factor_buffer_target_data_, max_buffer_size_target_data_, set_buffer_size_target_data.
Referenced by nest::EventDeliveryManager::gather_target_data.
bool nest::MPIManager::increase_buffer_size_spike_data()
Increases the size of the MPI buffer for communication of spikes if it needs to be increased.
Returns whether the size was changed.
References adaptive_spike_buffers_, buffer_size_spike_data_, growth_factor_buffer_spike_data_, max_buffer_size_spike_data_, set_buffer_size_spike_data.
Referenced by nest::EventDeliveryManager::gather_spike_data_.
void nest::MPIManager::decrease_buffer_size_spike_data()
Decreases the size of the MPI buffer for communication of spikes if it can be decreased.
References adaptive_spike_buffers_, buffer_size_spike_data_, get_num_processes, set_buffer_size_spike_data, shrink_factor_buffer_spike_data_.
Referenced by nest::EventDeliveryManager::gather_spike_data_.
bool nest::MPIManager::adaptive_target_buffers() const
Returns whether MPI buffers for communication of connections are adaptive.
References adaptive_target_buffers_.
bool nest::MPIManager::adaptive_spike_buffers() const
Returns whether MPI buffers for communication of spikes are adaptive.
References adaptive_spike_buffers_.
void nest::MPIManager::set_recv_counts_secondary_events_in_int_per_rank(const std::vector< int > &recv_counts_in_int_per_rank)
Sets the recvcounts parameter of Alltoallv for communication of secondary events, i.e., the number of elements (in ints) to recv from the corresponding rank.
References recv_counts_secondary_events_in_int_per_rank_, recv_displacements_secondary_events_in_int_per_rank_.
Referenced by nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources.
size_t nest::MPIManager::get_recv_count_secondary_events_in_int(const size_t source_rank) const
Returns the recvcounts parameter of Alltoallv for communication of secondary events, i.e., the number of elements (in ints) to recv from source_rank.
References recv_counts_secondary_events_in_int_per_rank_.
Referenced by get_done_marker_position_in_secondary_events_recv_buffer.
size_t nest::MPIManager::get_recv_displacement_secondary_events_in_int(const size_t source_rank) const
Returns the rdispls parameter of Alltoallv for communication of secondary events, i.e., the offset in the MPI buffer where elements from source_rank are written.
References recv_displacements_secondary_events_in_int_per_rank_.
Referenced by nest::ConnectionManager::compute_compressed_secondary_recv_buffer_positions, get_done_marker_position_in_secondary_events_recv_buffer, nest::SourceTable::populate_target_data_fields_.
size_t nest::MPIManager::get_send_count_secondary_events_in_int(const size_t target_rank) const
Returns the number of elements (in ints) to be sent to target_rank.
References send_counts_secondary_events_in_int_per_rank_.
Referenced by get_done_marker_position_in_secondary_events_send_buffer.
size_t nest::MPIManager::get_send_displacement_secondary_events_in_int(const size_t target_rank) const
Returns the send displacement of elements (in ints) to be sent to rank target_rank.
References send_displacements_secondary_events_in_int_per_rank_.
Referenced by nest::TargetTable::add_target, get_done_marker_position_in_secondary_events_send_buffer.
size_t nest::MPIManager::get_done_marker_position_in_secondary_events_send_buffer(const size_t target_rank) const
Returns where the done marker is located in the MPI send buffer for target_rank.
References get_send_count_secondary_events_in_int, get_send_displacement_secondary_events_in_int.
Referenced by nest::EventDeliveryManager::write_done_marker_secondary_events_.
size_t nest::MPIManager::get_done_marker_position_in_secondary_events_recv_buffer(const size_t source_rank) const
Returns where the done marker is located in the MPI recv buffer for source_rank.
References get_recv_count_secondary_events_in_int, get_recv_displacement_secondary_events_in_int.
Referenced by nest::ConnectionManager::deliver_secondary_events.
void nest::MPIManager::communicate_recv_counts_secondary_events()
Referenced by nest::SimulationManager::update_connection_infrastructure.