TokenStack
TokenStack::TokenStack(Index n)
TokenStack::TokenStack(const TokenArray &ta)
void TokenStack::clear()
References TokenArrayObj::begin, TokenArrayObj::end, TokenArrayObj::erase.
Referenced by QuitFunction::execute, CloseinputFunction::execute, StopFunction::execute, StartFunction::execute, ClearFunction::execute, Parser::operator(), SLIInterpreter::~SLIInterpreter.
void TokenStack::push(const Token &e)
References TokenArrayObj::push_back.
Referenced by SLIInterpreter::debug_commandline, SLIInterpreter::execute, OstrstreamFunction::execute, nest::NestModule::GetStatus_gFunction::execute, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::NestModule::GetMetadata_gFunction::execute, nest::NestModule::GetKernelStatus_Function::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::GetConnections_DFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::PrintNodesToStreamFunction::execute, nest::NestModule::RankFunction::execute, nest::NestModule::NumProcessesFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::ProcessorNameFunction::execute, nest::NestModule::Cvdict_CFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::Cvnodecollection_iaFunction::execute, nest::NestModule::Cvnodecollection_ivFunction::execute, nest::NestModule::Cva_gFunction::execute, nest::NestModule::Size_gFunction::execute, nest::NestModule::ValidQ_gFunction::execute, nest::NestModule::Join_g_gFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::eq_gFunction::execute, nest::NestModule::BeginIterator_gFunction::execute, nest::NestModule::EndIterator_gFunction::execute, nest::NestModule::GetNodeID_qFunction::execute, nest::NestModule::GetNodeIDModelID_qFunction::execute, nest::NestModule::Eq_q_qFunction::execute, nest::NestModule::Lt_q_qFunction::execute, nest::NestModule::Get_g_iFunction::execute, nest::NestModule::Take_g_aFunction::execute, nest::NestModule::Mul_P_PFunction::execute, nest::NestModule::Div_P_PFunction::execute, nest::NestModule::Add_P_PFunction::execute, nest::NestModule::Sub_P_PFunction::execute, nest::NestModule::Compare_P_P_DFunction::execute, nest::NestModule::Conditional_P_P_PFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Exp_PFunction::execute, nest::NestModule::Sin_PFunction::execute, nest::NestModule::Cos_PFunction::execute, nest::NestModule::Pow_P_dFunction::execute, nest::NestModule::Dimension2d_P_PFunction::execute, nest::NestModule::Dimension3d_P_P_PFunction::execute, nest::NestModule::CreateParameter_DFunction::execute, nest::NestModule::GetValue_PFunction::execute, nest::NestModule::IsSpatial_PFunction::execute, nest::NestModule::Apply_P_DFunction::execute, nest::NestModule::Apply_P_gFunction::execute, nest::NestModule::CreateLayer_D_DFunction::execute, nest::NestModule::GetPosition_gFunction::execute, nest::NestModule::Displacement_g_gFunction::execute, nest::NestModule::Displacement_a_gFunction::execute, nest::NestModule::Distance_g_gFunction::execute, nest::NestModule::Distance_a_gFunction::execute, nest::NestModule::Distance_aFunction::execute, nest::NestModule::CreateMask_DFunction::execute, nest::NestModule::GetLayerStatus_gFunction::execute, nest::NestModule::Inside_a_MFunction::execute, nest::NestModule::And_M_MFunction::execute, nest::NestModule::Or_M_MFunction::execute, nest::NestModule::Sub_M_MFunction::execute, nest::NestModule::Cvdict_MFunction::execute, nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, FilesystemModule::CompareFilesFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::WaitPIDFunction::execute, Processes::AvailableFunction::execute, Processes::CtermidFunction::execute, Processes::Isatty_isFunction::execute, Processes::Isatty_osFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IFailFunction::execute, OGoodFunction::execute, IEofFunction::execute, OEofFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, CallbacktypeFunction::execute, XIstreamtypeFunction::execute, XIfstreamtypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::ValidFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, SLIArrayModule::Iforall_ivFunction::execute, SLIArrayModule::Iforall_dvFunction::execute, IiterateFunction::execute, IloopFunction::execute, IrepeatFunction::execute, IforFunction::execute, IforallarrayFunction::execute, IforallindexedarrayFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, CloseinputFunction::execute, StopFunction::execute, CurrentnameFunction::execute, LookupFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, CyclesFunction::execute, CodeAccessedFunction::execute, CodeExecutedFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, DebugFunction::execute, Get_a_aFunction::execute, Empty_aFunction::execute, Shrink_aFunction::execute, Empty_sFunction::execute, Search_sFunction::execute, Search_aFunction::execute, IrepeatanyFunction::execute, RepeatanyFunction::execute, DictFunction::execute, ClonedictFunction::execute, Cva_dFunction::execute, KeysFunction::execute, ValuesFunction::execute, SLIgraphics::ReadPGMFunction::execute, Frexp_dFunction::execute, RegexpModule::RegcompFunction::execute, SLIStartup::GetenvFunction::execute, Cva_tFunction::execute, ToUppercase_sFunction::execute, ToLowercase_sFunction::execute, index, SLIStartup::init, Parser::operator(), SLIInterpreter::raiseagain, SLIInterpreter::raiseerror.
void TokenStack::push_move(Token &e)
References TokenArrayObj::push_back_move.
Referenced by StrFunction::execute, FilesystemModule::FileNamesFunction::execute, FilesystemModule::DirectoryFunction::execute, FilesystemModule::TmpNamFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::ForkFunction::execute, Processes::Sysexec_aFunction::execute, Processes::WaitPIDFunction::execute, Processes::PipeFunction::execute, Processes::GetPIDFunction::execute, Processes::GetPPIDFunction::execute, Processes::GetPGRPFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, Cvx_fFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, DatatypeFunction::execute, CallbacktypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::FlattenFunction::execute, SLIArrayModule::TransposeFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, LoopFunction::execute, IfFunction::execute, IfelseFunction::execute, RepeatFunction::execute, StoppedFunction::execute, IparsestdinFunction::execute, ParsestdinFunction::execute, IparseFunction::execute, LoadFunction::execute, LookupFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, ExecFunction::execute, TypeinfoFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CounttomarkFunction::execute, TimeFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, VerbosityFunction::execute, DebugFunction::execute, Get_aFunction::execute, Allocations_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Length_sFunction::execute, Length_aFunction::execute, Length_pFunction::execute, Length_lpFunction::execute, Capacity_aFunction::execute, Size_aFunction::execute, References_aFunction::execute, Capacity_sFunction::execute, Size_sFunction::execute, Get_sFunction::execute, Search_sFunction::execute, Search_aFunction::execute, RepeatanyFunction::execute, DictgetFunction::execute, DictstackFunction::execute, CurrentdictFunction::execute, CountdictstackFunction::execute, Length_dFunction::execute, RegexpModule::RegcompFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute, CountFunction::execute, ExecstackFunction::execute, OperandstackFunction::execute, SLIStartup::GetenvFunction::execute, TrieFunction::execute, Cvt_aFunction::execute, TypeFunction::execute, SLIStartup::init, Parser::operator(), SLIInterpreter::raiseagain.
void TokenStack::push_by_ref(const Token &e)
Push a Token with a valid datum to the stack.
This function expects that sufficient space is on the stack to fit the datum. This function increases the reference count of the datum.
References TokenArrayObj::push_back_by_ref.
Referenced by ProceduretypeFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, LoopFunction::execute, RepeatFunction::execute, ForFunction::execute, Forall_aFunction::execute.
void TokenStack::push_by_pointer(Datum *rhs)
Push a valid datum to the stack.
This function expects that sufficient space is on the stack to fit the datum. This function increases the reference count of the datum.
References TokenArrayObj::push_back_by_pointer.
Referenced by eq_execute, ProceduretypeFunction::execute, LitproceduretypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, IforallindexedarrayFunction::execute, IforallstringFunction::execute, LoopFunction::execute, RepeatFunction::execute, StoppedFunction::execute, ForFunction::execute, Forall_aFunction::execute, Empty_DFunction::execute, Modf_dFunction::execute, EqFunction::execute, NeqFunction::execute, Geq_iiFunction::execute, Geq_idFunction::execute, Geq_diFunction::execute, Geq_ddFunction::execute, Leq_iiFunction::execute, Leq_idFunction::execute, Leq_diFunction::execute, Leq_ddFunction::execute, Gt_iiFunction::execute, Gt_ddFunction::execute, Gt_idFunction::execute, Gt_diFunction::execute, Gt_ssFunction::execute, Lt_iiFunction::execute, Lt_ddFunction::execute, Lt_idFunction::execute, Lt_diFunction::execute, Lt_ssFunction::execute, UnitStep_iFunction::execute, UnitStep_dFunction::execute, UnitStep_iaFunction::execute, UnitStep_daFunction::execute.
void TokenStack::pop()
References TokenArrayObj::pop_back.
Referenced by eq_execute, nest::NestModule::Disconnect_aFunction::execute, OstrstreamFunction::execute, StrFunction::execute, nest::NestModule::GetStatus_gFunction::execute, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::NestModule::GetMetadata_gFunction::execute, nest::NestModule::GetKernelStatus_Function::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::SetStatus_CDFunction::execute, nest::NestModule::SetKernelStatus_DFunction::execute, nest::NestModule::Cva_CFunction::execute, nest::NestModule::SetStatus_aaFunction::execute, nest::NestModule::SetDefaults_l_DFunction::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::CopyModel_l_l_DFunction::execute, nest::NestModule::GetConnections_DFunction::execute, nest::NestModule::SimulateFunction::execute, nest::NestModule::PrepareFunction::execute, nest::NestModule::RunFunction::execute, nest::NestModule::CleanupFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::ResetKernelFunction::execute, nest::NestModule::MemoryInfoFunction::execute, nest::NestModule::PrintNodesFunction::execute, nest::NestModule::PrintNodesToStreamFunction::execute, nest::NestModule::RankFunction::execute, nest::NestModule::NumProcessesFunction::execute, nest::NestModule::SetFakeNumProcesses_iFunction::execute, nest::NestModule::SyncProcessesFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::ProcessorNameFunction::execute, nest::NestModule::Cvdict_CFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::Cvnodecollection_iaFunction::execute, nest::NestModule::Cvnodecollection_ivFunction::execute, nest::NestModule::Cva_gFunction::execute, nest::NestModule::Size_gFunction::execute, nest::NestModule::ValidQ_gFunction::execute, nest::NestModule::Join_g_gFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::eq_gFunction::execute, nest::NestModule::BeginIterator_gFunction::execute, nest::NestModule::EndIterator_gFunction::execute, nest::NestModule::GetNodeID_qFunction::execute, nest::NestModule::GetNodeIDModelID_qFunction::execute, nest::NestModule::Next_qFunction::execute, nest::NestModule::Eq_q_qFunction::execute, nest::NestModule::Lt_q_qFunction::execute, nest::NestModule::Get_g_iFunction::execute, nest::NestModule::Take_g_aFunction::execute, nest::NestModule::EnableStructuralPlasticity_Function::execute, nest::NestModule::DisableStructuralPlasticity_Function::execute, nest::NestModule::SetStdpEps_dFunction::execute, nest::NestModule::Mul_P_PFunction::execute, nest::NestModule::Div_P_PFunction::execute, nest::NestModule::Add_P_PFunction::execute, nest::NestModule::Sub_P_PFunction::execute, nest::NestModule::Compare_P_P_DFunction::execute, nest::NestModule::Conditional_P_P_PFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Exp_PFunction::execute, nest::NestModule::Sin_PFunction::execute, nest::NestModule::Cos_PFunction::execute, nest::NestModule::Pow_P_dFunction::execute, nest::NestModule::Dimension2d_P_PFunction::execute, nest::NestModule::Dimension3d_P_P_PFunction::execute, nest::NestModule::CreateParameter_DFunction::execute, nest::NestModule::GetValue_PFunction::execute, nest::NestModule::IsSpatial_PFunction::execute, nest::NestModule::Apply_P_DFunction::execute, nest::NestModule::Apply_P_gFunction::execute, nest::NestModule::CreateLayer_D_DFunction::execute, nest::NestModule::GetPosition_gFunction::execute, nest::NestModule::Displacement_g_gFunction::execute, nest::NestModule::Displacement_a_gFunction::execute, nest::NestModule::Distance_g_gFunction::execute, nest::NestModule::Distance_a_gFunction::execute, nest::NestModule::Distance_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute, nest::NestModule::CreateMask_DFunction::execute, nest::NestModule::GetLayerStatus_gFunction::execute, nest::NestModule::Inside_a_MFunction::execute, nest::NestModule::And_M_MFunction::execute, nest::NestModule::Or_M_MFunction::execute, nest::NestModule::Sub_M_MFunction::execute, nest::NestModule::DumpLayerNodes_os_gFunction::execute, nest::NestModule::DumpLayerConnections_os_g_g_lFunction::execute, nest::NestModule::Cvdict_MFunction::execute, nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, FilesystemModule::FileNamesFunction::execute, FilesystemModule::DirectoryFunction::execute, FilesystemModule::TmpNamFunction::execute, FilesystemModule::CompareFilesFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::ForkFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::PipeFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::AvailableFunction::execute, Processes::GetPIDFunction::execute, Processes::GetPPIDFunction::execute, Processes::GetPGRPFunction::execute, Processes::MkfifoFunction::execute, Processes::SetNonblockFunction::execute, Processes::CtermidFunction::execute, Processes::Isatty_isFunction::execute, Processes::Isatty_osFunction::execute, MathLinkPutStringFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IClearFunction::execute, OClearFunction::execute, IFailFunction::execute, OGoodFunction::execute, Cvx_fFunction::execute, IEofFunction::execute, OEofFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, DatatypeFunction::execute, LitproceduretypeFunction::execute, FunctiontypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::ReverseFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::FlattenFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::TransposeFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::ValidFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Put_iv_i_iFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, SLIArrayModule::Iforall_ivFunction::execute, SLIArrayModule::Iforall_dvFunction::execute, IlookupFunction::execute, IsetcallbackFunction::execute, IiterateFunction::execute, IrepeatFunction::execute, IforFunction::execute, IforallarrayFunction::execute, IforallindexedarrayFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, Backtrace_onFunction::execute, Backtrace_offFunction::execute, OStackdumpFunction::execute, EStackdumpFunction::execute, LoopFunction::execute, ExitFunction::execute, IfFunction::execute, IfelseFunction::execute, RepeatFunction::execute, CloseinputFunction::execute, StoppedFunction::execute, StopFunction::execute, CurrentnameFunction::execute, IparsestdinFunction::execute, ParsestdinFunction::execute, IparseFunction::execute, DefFunction::execute, SetFunction::execute, LoadFunction::execute, LookupFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, RaiseerrorFunction::execute, PrinterrorFunction::execute, RaiseagainFunction::execute, CyclesFunction::execute, CodeAccessedFunction::execute, CodeExecutedFunction::execute, ExecFunction::execute, TypeinfoFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CaseFunction::execute, CounttomarkFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, TimeFunction::execute, Sleep_dFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, SetGuardFunction::execute, RemoveGuardFunction::execute, MessageFunction::execute, SetVerbosityFunction::execute, VerbosityFunction::execute, NoopFunction::execute, DebugOnFunction::execute, DebugOffFunction::execute, DebugFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Allocations_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Append_aFunction::execute, Append_pFunction::execute, Append_sFunction::execute, Prepend_aFunction::execute, Prepend_pFunction::execute, Prepend_sFunction::execute, Join_sFunction::execute, Join_aFunction::execute, Join_pFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Length_sFunction::execute, Length_aFunction::execute, Length_pFunction::execute, Length_lpFunction::execute, Capacity_aFunction::execute, Size_aFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Empty_aFunction::execute, References_aFunction::execute, Shrink_aFunction::execute, Capacity_sFunction::execute, Size_sFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Empty_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Cvx_aFunction::execute, Cvlit_nFunction::execute, Cvlit_pFunction::execute, Cvlp_pFunction::execute, Cvn_sFunction::execute, Cvn_lFunction::execute, Cvi_sFunction::execute, Cvd_sFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, Search_sFunction::execute, Search_aFunction::execute, IrepeatanyFunction::execute, RepeatanyFunction::execute, DictFunction::execute, DictputFunction::execute, DictgetFunction::execute, DictbeginFunction::execute, DictendFunction::execute, DictinfoFunction::execute, DicttopinfoFunction::execute, WhoFunction::execute, DictconstructFunction::execute, DictstackFunction::execute, CurrentdictFunction::execute, CountdictstackFunction::execute, CleardictstackFunction::execute, Length_dFunction::execute, Empty_DFunction::execute, CleardictFunction::execute, ClonedictFunction::execute, UndefFunction::execute, KnownFunction::execute, Cva_dFunction::execute, KeysFunction::execute, ValuesFunction::execute, RestoredstackFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, Add_diFunction::execute, Add_iiFunction::execute, Add_idFunction::execute, Add_ddFunction::execute, Sub_diFunction::execute, Sub_iiFunction::execute, Sub_idFunction::execute, Sub_ddFunction::execute, Mul_diFunction::execute, Mul_iiFunction::execute, Mul_idFunction::execute, Mul_ddFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute, Sin_dFunction::execute, Asin_dFunction::execute, Cos_dFunction::execute, Acos_dFunction::execute, Exp_dFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqr_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, Modf_dFunction::execute, Frexp_dFunction::execute, Ldexp_diFunction::execute, Dexp_iFunction::execute, Abs_iFunction::execute, Abs_dFunction::execute, Neg_iFunction::execute, Neg_dFunction::execute, Inv_dFunction::execute, EqFunction::execute, NeqFunction::execute, AndFunction::execute, OrFunction::execute, And_iiFunction::execute, Or_iiFunction::execute, XorFunction::execute, Not_bFunction::execute, Not_iFunction::execute, Geq_iiFunction::execute, Geq_idFunction::execute, Geq_diFunction::execute, Geq_ddFunction::execute, Leq_iiFunction::execute, Leq_idFunction::execute, Leq_diFunction::execute, Leq_ddFunction::execute, Gt_iiFunction::execute, Gt_ddFunction::execute, Gt_idFunction::execute, Gt_diFunction::execute, Gt_ssFunction::execute, Lt_iiFunction::execute, Lt_ddFunction::execute, Lt_idFunction::execute, Lt_diFunction::execute, Lt_ssFunction::execute, IntegerFunction::execute, DoubleFunction::execute, UnitStep_iFunction::execute, UnitStep_dFunction::execute, UnitStep_iaFunction::execute, UnitStep_daFunction::execute, Round_dFunction::execute, Floor_dFunction::execute, Ceil_dFunction::execute, Max_i_iFunction::execute, Max_i_dFunction::execute, Max_d_iFunction::execute, Max_d_dFunction::execute, Min_i_iFunction::execute, Min_i_dFunction::execute, Min_d_iFunction::execute, Min_d_dFunction::execute, RegexpModule::RegcompFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute, PopFunction::execute, NpopFunction::execute, DupFunction::execute, ExchFunction::execute, IndexFunction::execute, RollFunction::execute, RolluFunction::execute, RolldFunction::execute, RotFunction::execute, OverFunction::execute, CountFunction::execute, CopyFunction::execute, ClearFunction::execute, ExecstackFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, OperandstackFunction::execute, SLIStartup::GetenvFunction::execute, TrieFunction::execute, TrieInfoFunction::execute, AddtotrieFunction::execute, Cva_tFunction::execute, Cvt_aFunction::execute, TypeFunction::execute, ToUppercase_sFunction::execute, ToLowercase_sFunction::execute, SLIInterpreter::raiseerror.
void TokenStack::pop_move(Token &e)
References TokenArrayObj::end, TokenArrayObj::pop_back.
Referenced by Processes::Sysexec_aFunction::execute, IsetcallbackFunction::execute, RaiseerrorFunction::execute, Parser::operator().
void TokenStack::pop(size_t n)
References TokenArrayObj::end, TokenArrayObj::erase.
Token & TokenStack::top()
References TokenArrayObj::end.
Referenced by StrFunction::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::SetStatus_CDFunction::execute, nest::NestModule::SetKernelStatus_DFunction::execute, nest::NestModule::Cva_CFunction::execute, nest::NestModule::SetStatus_aaFunction::execute, nest::NestModule::SimulateFunction::execute, nest::NestModule::RunFunction::execute, nest::NestModule::SetStdpEps_dFunction::execute, FilesystemModule::FileNamesFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::AvailableFunction::execute, Processes::MkfifoFunction::execute, Processes::SetNonblockFunction::execute, MathLinkPutStringFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IClearFunction::execute, OClearFunction::execute, IFailFunction::execute, OGoodFunction::execute, Cvx_fFunction::execute, IEofFunction::execute, OEofFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, DatatypeFunction::execute, NametypeFunction::execute, ProceduretypeFunction::execute, LitproceduretypeFunction::execute, FunctiontypeFunction::execute, TrietypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::ReverseFunction::execute, SLIArrayModule::FlattenFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::TransposeFunction::execute, SLIArrayModule::ValidFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, IsetcallbackFunction::execute, IforallstringFunction::execute, LoopFunction::execute, IfFunction::execute, RepeatFunction::execute, CloseinputFunction::execute, StoppedFunction::execute, StopFunction::execute, CurrentnameFunction::execute, DefFunction::execute, SetFunction::execute, LoadFunction::execute, LookupFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, PrinterrorFunction::execute, ExecFunction::execute, TypeinfoFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, SetGuardFunction::execute, SetVerbosityFunction::execute, DebugFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Append_aFunction::execute, Append_pFunction::execute, Prepend_aFunction::execute, Prepend_pFunction::execute, InsertElement_aFunction::execute, Length_sFunction::execute, Length_aFunction::execute, Length_pFunction::execute, Length_lpFunction::execute, Capacity_aFunction::execute, Size_aFunction::execute, Empty_aFunction::execute, References_aFunction::execute, Shrink_aFunction::execute, Capacity_sFunction::execute, Size_sFunction::execute, Empty_sFunction::execute, Cvx_aFunction::execute, Cvlit_nFunction::execute, Cvlit_pFunction::execute, Cvlp_pFunction::execute, Cvn_sFunction::execute, Cvn_lFunction::execute, Cvi_sFunction::execute, Cvd_sFunction::execute, Get_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, DictputFunction::execute, DictbeginFunction::execute, DictinfoFunction::execute, DicttopinfoFunction::execute, WhoFunction::execute, DictconstructFunction::execute, Length_dFunction::execute, Empty_DFunction::execute, CleardictFunction::execute, ClonedictFunction::execute, KnownFunction::execute, Cva_dFunction::execute, KeysFunction::execute, ValuesFunction::execute, RestoredstackFunction::execute, SLIgraphics::ReadPGMFunction::execute, Dexp_iFunction::execute, Abs_iFunction::execute, Abs_dFunction::execute, Neg_iFunction::execute, Neg_dFunction::execute, Inv_dFunction::execute, Not_bFunction::execute, Not_iFunction::execute, IntegerFunction::execute, DoubleFunction::execute, NpopFunction::execute, IndexFunction::execute, RollFunction::execute, CopyFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, SLIStartup::GetenvFunction::execute, TrieFunction::execute, TrieInfoFunction::execute, AddtotrieFunction::execute, Cva_tFunction::execute, TypeFunction::execute, ToUppercase_sFunction::execute, ToLowercase_sFunction::execute, SLIInterpreter::execute_, SLIInterpreter::execute_debug_, SLIInterpreter::getcurrentname, Parser::operator(), SLIInterpreter::raiseerror.
const Token & TokenStack::top() const
References TokenArrayObj::end.
const Token & TokenStack::pick(size_t i) const
References TokenArrayObj::end.
Referenced by SLIArrayModule::IMapFunction::backtrace, SLIArrayModule::IMap_ivFunction::backtrace, SLIArrayModule::IMap_dvFunction::backtrace, SLIArrayModule::IMapThreadFunction::backtrace, SLIArrayModule::IMapIndexedFunction::backtrace, SLIArrayModule::Iforall_ivFunction::backtrace, SLIArrayModule::Iforall_dvFunction::backtrace, IiterateFunction::backtrace, IloopFunction::backtrace, IrepeatFunction::backtrace, IforFunction::backtrace, IforallarrayFunction::backtrace, IforallindexedarrayFunction::backtrace, IforallindexedstringFunction::backtrace, IforallstringFunction::backtrace, dump, eq_execute, nest::NestModule::Disconnect_aFunction::execute, nest::NestModule::GetStatus_gFunction::execute, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::NestModule::GetMetadata_gFunction::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::SetStatus_CDFunction::execute, nest::NestModule::SetStatus_aaFunction::execute, nest::NestModule::SetDefaults_l_DFunction::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::CopyModel_l_l_DFunction::execute, nest::NestModule::GetConnections_DFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::SetFakeNumProcesses_iFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::Cvdict_CFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::Cvnodecollection_iaFunction::execute, nest::NestModule::Cvnodecollection_ivFunction::execute, nest::NestModule::Cva_gFunction::execute, nest::NestModule::Size_gFunction::execute, nest::NestModule::ValidQ_gFunction::execute, nest::NestModule::Join_g_gFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::eq_gFunction::execute, nest::NestModule::BeginIterator_gFunction::execute, nest::NestModule::EndIterator_gFunction::execute, nest::NestModule::GetNodeID_qFunction::execute, nest::NestModule::GetNodeIDModelID_qFunction::execute, nest::NestModule::Next_qFunction::execute, nest::NestModule::Eq_q_qFunction::execute, nest::NestModule::Lt_q_qFunction::execute, nest::NestModule::Get_g_iFunction::execute, nest::NestModule::Take_g_aFunction::execute, nest::NestModule::Mul_P_PFunction::execute, nest::NestModule::Div_P_PFunction::execute, nest::NestModule::Add_P_PFunction::execute, nest::NestModule::Sub_P_PFunction::execute, nest::NestModule::Compare_P_P_DFunction::execute, nest::NestModule::Conditional_P_P_PFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Exp_PFunction::execute, nest::NestModule::Sin_PFunction::execute, nest::NestModule::Cos_PFunction::execute, nest::NestModule::Pow_P_dFunction::execute, nest::NestModule::Dimension2d_P_PFunction::execute, nest::NestModule::Dimension3d_P_P_PFunction::execute, nest::NestModule::CreateParameter_DFunction::execute, nest::NestModule::GetValue_PFunction::execute, nest::NestModule::IsSpatial_PFunction::execute, nest::NestModule::Apply_P_DFunction::execute, nest::NestModule::Apply_P_gFunction::execute, nest::NestModule::CreateLayer_D_DFunction::execute, nest::NestModule::GetPosition_gFunction::execute, nest::NestModule::Displacement_g_gFunction::execute, nest::NestModule::Displacement_a_gFunction::execute, nest::NestModule::Distance_g_gFunction::execute, nest::NestModule::Distance_a_gFunction::execute, nest::NestModule::Distance_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute, nest::NestModule::CreateMask_DFunction::execute, nest::NestModule::GetLayerStatus_gFunction::execute, nest::NestModule::Inside_a_MFunction::execute, nest::NestModule::And_M_MFunction::execute, nest::NestModule::Or_M_MFunction::execute, nest::NestModule::Sub_M_MFunction::execute, nest::NestModule::DumpLayerNodes_os_gFunction::execute, nest::NestModule::DumpLayerConnections_os_g_g_lFunction::execute, nest::NestModule::Cvdict_MFunction::execute, nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, FilesystemModule::CompareFilesFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::SetNonblockFunction::execute, Processes::Isatty_isFunction::execute, Processes::Isatty_osFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, EndsFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Put_iv_i_iFunction::execute, SLIArrayModule::ArangeFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, SLIArrayModule::Iforall_ivFunction::execute, SLIArrayModule::Iforall_dvFunction::execute, IiterateFunction::execute, IloopFunction::execute, IrepeatFunction::execute, IforFunction::execute, IforallarrayFunction::execute, IforallindexedarrayFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, ExitFunction::execute, IfFunction::execute, IfelseFunction::execute, RepeatFunction::execute, CloseinputFunction::execute, StopFunction::execute, CurrentnameFunction::execute, IparseFunction::execute, DefFunction::execute, SetFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CaseFunction::execute, CounttomarkFunction::execute, Sleep_dFunction::execute, MessageFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Append_aFunction::execute, Append_pFunction::execute, Append_sFunction::execute, Prepend_aFunction::execute, Prepend_pFunction::execute, Prepend_sFunction::execute, Join_sFunction::execute, Join_aFunction::execute, Join_pFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, Search_sFunction::execute, Search_aFunction::execute, IrepeatanyFunction::execute, RepeatanyFunction::execute, DictputFunction::execute, DictgetFunction::execute, DictinfoFunction::execute, DictconstructFunction::execute, UndefFunction::execute, KnownFunction::execute, SLIgraphics::WritePGMFunction::execute, Add_diFunction::execute, Add_iiFunction::execute, Add_idFunction::execute, Add_ddFunction::execute, Sub_diFunction::execute, Sub_iiFunction::execute, Sub_idFunction::execute, Sub_ddFunction::execute, Mul_diFunction::execute, Mul_iiFunction::execute, Mul_idFunction::execute, Mul_ddFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute, Sin_dFunction::execute, Asin_dFunction::execute, Cos_dFunction::execute, Acos_dFunction::execute, Exp_dFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqr_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, Modf_dFunction::execute, Frexp_dFunction::execute, Ldexp_diFunction::execute, Dexp_iFunction::execute, EqFunction::execute, NeqFunction::execute, AndFunction::execute, OrFunction::execute, And_iiFunction::execute, Or_iiFunction::execute, XorFunction::execute, Geq_iiFunction::execute, Geq_idFunction::execute, Geq_diFunction::execute, Geq_ddFunction::execute, Leq_iiFunction::execute, Leq_idFunction::execute, Leq_diFunction::execute, Leq_ddFunction::execute, Gt_iiFunction::execute, Gt_ddFunction::execute, Gt_idFunction::execute, Gt_diFunction::execute, Gt_ssFunction::execute, Lt_iiFunction::execute, Lt_ddFunction::execute, Lt_idFunction::execute, Lt_diFunction::execute, Lt_ssFunction::execute, IntegerFunction::execute, DoubleFunction::execute, UnitStep_iFunction::execute, UnitStep_dFunction::execute, UnitStep_iaFunction::execute, UnitStep_daFunction::execute, Round_dFunction::execute, Floor_dFunction::execute, Ceil_dFunction::execute, Max_i_iFunction::execute, Max_i_dFunction::execute, Max_d_iFunction::execute, Max_d_dFunction::execute, Min_i_iFunction::execute, Min_i_dFunction::execute, Min_d_iFunction::execute, Min_d_dFunction::execute, RegexpModule::RegcompFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute, RollFunction::execute, TrieInfoFunction::execute, AddtotrieFunction::execute, Cvt_aFunction::execute, index, TypeTrie::lookup, SLIInterpreter::stack_backtrace.
Token & TokenStack::pick(size_t i)
References TokenArrayObj::end.
void TokenStack::swap()
References TokenArrayObj::end, swap.
Referenced by IparseFunction::execute, CaseFunction::execute, Add_idFunction::execute, Sub_idFunction::execute, Mul_idFunction::execute, Div_idFunction::execute, Max_i_iFunction::execute, Max_i_dFunction::execute, Max_d_iFunction::execute, Max_d_dFunction::execute, Min_i_iFunction::execute, Min_i_dFunction::execute, Min_d_iFunction::execute, Min_d_dFunction::execute, ExchFunction::execute, swap.
void TokenStack::swap(Token &e)
References TokenArrayObj::end, swap.
void TokenStack::index(Index i)
References pick, push.
Referenced by DupFunction::execute, IndexFunction::execute, OverFunction::execute, CopyFunction::execute.
void TokenStack::roll(size_t n, long k)
References TokenArrayObj::end, TokenArrayObj::rotate.
Referenced by RollFunction::execute, RolluFunction::execute, RolldFunction::execute, RotFunction::execute.
Index TokenStack::size() const
References TokenArrayObj::capacity.
Referenced by TrieInfoFunction::execute, Cva_tFunction::execute, Cvt_aFunction::execute.
Index TokenStack::load() const
References TokenArrayObj::size.
Referenced by SLIInterpreter::assert_stack_load, SLIInterpreter::debug_commandline, dump, eq_execute, Processes::Sysexec_aFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::AvailableFunction::execute, Processes::MkfifoFunction::execute, Processes::SetNonblockFunction::execute, Processes::Isatty_isFunction::execute, Processes::Isatty_osFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::FlattenFunction::execute, SLIArrayModule::TransposeFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::ValidFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, LoopFunction::execute, ExitFunction::execute, IfFunction::execute, IfelseFunction::execute, RepeatFunction::execute, CloseinputFunction::execute, StoppedFunction::execute, StopFunction::execute, CurrentnameFunction::execute, DefFunction::execute, SetFunction::execute, LookupFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CounttomarkFunction::execute, Token_sFunction::execute, Symbol_sFunction::execute, MessageFunction::execute, SetVerbosityFunction::execute, DebugFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Append_aFunction::execute, Append_pFunction::execute, Append_sFunction::execute, Prepend_aFunction::execute, Prepend_pFunction::execute, Prepend_sFunction::execute, Join_sFunction::execute, Join_aFunction::execute, Join_pFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Length_sFunction::execute, Length_aFunction::execute, Length_pFunction::execute, Length_lpFunction::execute, Capacity_aFunction::execute, Size_aFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Empty_aFunction::execute, References_aFunction::execute, Shrink_aFunction::execute, Capacity_sFunction::execute, Size_sFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Empty_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Cvx_aFunction::execute, Cvlit_nFunction::execute, Cvlit_pFunction::execute, Cvlp_pFunction::execute, Cvn_sFunction::execute, Cvn_lFunction::execute, Cvi_sFunction::execute, Cvd_sFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, Search_sFunction::execute, Search_aFunction::execute, DictputFunction::execute, DictgetFunction::execute, DictbeginFunction::execute, DictinfoFunction::execute, DicttopinfoFunction::execute, WhoFunction::execute, DictconstructFunction::execute, Length_dFunction::execute, Empty_DFunction::execute, UndefFunction::execute, Cva_dFunction::execute, KeysFunction::execute, ValuesFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, Add_diFunction::execute, Add_iiFunction::execute, Add_idFunction::execute, Add_ddFunction::execute, Sub_diFunction::execute, Sub_iiFunction::execute, Sub_idFunction::execute, Sub_ddFunction::execute, Mul_diFunction::execute, Mul_iiFunction::execute, Mul_idFunction::execute, Mul_ddFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute, Sin_dFunction::execute, Asin_dFunction::execute, Cos_dFunction::execute, Acos_dFunction::execute, Exp_dFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqr_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, Modf_dFunction::execute, Frexp_dFunction::execute, Ldexp_diFunction::execute, Dexp_iFunction::execute, Abs_iFunction::execute, Abs_dFunction::execute, Neg_iFunction::execute, Neg_dFunction::execute, Inv_dFunction::execute, EqFunction::execute, NeqFunction::execute, AndFunction::execute, OrFunction::execute, And_iiFunction::execute, Or_iiFunction::execute, XorFunction::execute, Not_bFunction::execute, Not_iFunction::execute, Geq_iiFunction::execute, Geq_idFunction::execute, Geq_diFunction::execute, Geq_ddFunction::execute, Leq_iiFunction::execute, Leq_idFunction::execute, Leq_diFunction::execute, Leq_ddFunction::execute, Gt_iiFunction::execute, Gt_ddFunction::execute, Gt_idFunction::execute, Gt_diFunction::execute, Gt_ssFunction::execute, Lt_iiFunction::execute, Lt_ddFunction::execute, Lt_idFunction::execute, Lt_diFunction::execute, Lt_ssFunction::execute, IntegerFunction::execute, DoubleFunction::execute, UnitStep_iFunction::execute, UnitStep_dFunction::execute, UnitStep_iaFunction::execute, UnitStep_daFunction::execute, Round_dFunction::execute, Floor_dFunction::execute, Ceil_dFunction::execute, Max_i_iFunction::execute, Max_i_dFunction::execute, Max_d_iFunction::execute, Max_d_dFunction::execute, Min_i_iFunction::execute, Min_i_dFunction::execute, Min_d_iFunction::execute, Min_d_dFunction::execute, RegexpModule::RegcompFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute, PopFunction::execute, NpopFunction::execute, DupFunction::execute, ExchFunction::execute, IndexFunction::execute, RollFunction::execute, RolluFunction::execute, RolldFunction::execute, RotFunction::execute, OverFunction::execute, CountFunction::execute, CopyFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, TrieFunction::execute, AddtotrieFunction::execute, TypeFunction::execute, SLIInterpreter::execute_, SLIInterpreter::execute_debug_, TypeTrie::lookup, SLIInterpreter::stack_backtrace, SLIInterpreter::startup.
void TokenStack::dump(std::ostream &) const
References load, pick, Token::pprint.
Referenced by SLIInterpreter::debug_commandline, OStackdumpFunction::execute, EStackdumpFunction::execute, SLIInterpreter::execute_, SLIInterpreter::execute_debug_.
TokenArray TokenStack::toArray() const
Referenced by ExecstackFunction::execute, OperandstackFunction::execute, SLIInterpreter::raiseerror.
bool TokenArrayObj::reserve(size_t)
void TokenArrayObj::reserve_token(size_t n)
Referenced by SLIArrayModule::ArrayloadFunction::execute.
bool TokenArrayObj::empty() const
Referenced by Parser::operator().