nest::TargetTable
std::vector< std::vector< std::vector< Target > > > nest::TargetTable::targets_
Stores targets of local neurons Three dimensional objects:
first dim: threads second dim: local neurons third dim: targets
Referenced by clear, get_targets, initialize.
std::vector< std::vector< std::vector< std::vector< size_t > > > > nest::TargetTable::secondary_send_buffer_pos_
Stores MPI send buffer positions for secondary targets of local neurons.
Four dimensional object: first dim: threads second dim: local neurons third dim: synapse types fourth dim: MPI send buffer positions
Referenced by clear, get_secondary_send_buffer_positions, initialize.
void nest::TargetTable::initialize()
Initializes data structures.
References nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, nest::kernel, secondary_send_buffer_pos_, targets_, nest::KernelManager::vp_manager.
void nest::TargetTable::finalize()
Deletes data structure.
void nest::TargetTable::prepare(const thread tid)
Adjusts targets_ to number of local nodes.
References nest::NodeManager::get_max_num_local_nodes, nest::kernel, nest::KernelManager::node_manager.
Referenced by nest::ConnectionManager::prepare_target_table.
void nest::TargetTable::add_target(const thread tid, const thread target_rank, const TargetData &target_data)
Adds entry to targets_.
References nest::TargetDataFields::get_lcid, nest::SecondaryTargetDataFields::get_recv_buffer_pos, nest::MPIManager::get_send_displacement_secondary_events_in_int, nest::TargetData::get_source_lid, nest::TargetDataFields::get_syn_id, nest::SecondaryTargetDataFields::get_syn_id, nest::TargetDataFields::get_tid, vector_util::grow, nest::TargetData::is_primary, nest::kernel, nest::KernelManager::mpi_manager, nest::TargetData::secondary_data, nest::TargetData::target_data.
Referenced by nest::ConnectionManager::add_target.
const std::vector< Target > & nest::TargetTable::get_targets(const thread tid, const index lid) const
Returns all targets of a neuron.
Used for filling EventDeliveryManager::emitted_spikes_register_.
References targets_.
Referenced by nest::ConnectionManager::get_remote_targets_of_local_node.
const std::vector< size_t > & nest::TargetTable::get_secondary_send_buffer_positions(const thread tid, const index lid, const synindex syn_id) const
Returns all MPI send buffer positions of a neuron.
Used to fill MPI buffer in EventDeliveryManager.
References secondary_send_buffer_pos_.
Referenced by nest::ConnectionManager::get_secondary_send_buffer_positions.
void nest::TargetTable::clear(const thread tid)
Clears all entries of targets_.
References secondary_send_buffer_pos_, targets_.
Referenced by nest::ConnectionManager::restructure_connection_tables.
void nest::TargetTable::compress_secondary_send_buffer_pos(const thread tid)
Removes identical MPI send buffer positions to avoid writing data multiple times.