nest::GenericFactory
typedef BaseT *(* nest::GenericFactory< BaseT >::CreatorFunction) (const DictionaryDatum &d))(const DictionaryDatum &d)
typedef std::map< Name, CreatorFunction > nest::GenericFactory< BaseT >::AssocMap
AssocMap nest::GenericFactory< BaseT >::associations_
BaseT * nest::GenericFactory< BaseT >::create(const Name &name, const DictionaryDatum &d) const
Factory function.
name Subtype. d Dictionary containing parameters for this subtype. dynamically allocated new object.
References Name::toString.
Referenced by nest::NestModule::create_mask, nest::NestModule::create_parameter.
bool nest::GenericFactory< BaseT >::register_subtype(const Name &name)
Register a new subtype.
The type name must not already exist. The class for the subtype is supplied via the template argument. This class should have a constructor taking a const DictionaryDatum& as parameter. name subtype name. true if subtype was successfully registered.
Referenced by nest::NestModule::register_mask, nest::NestModule::register_parameter.
bool nest::GenericFactory< BaseT >::register_subtype(const Name &name, CreatorFunction creator)
Register a new subtype.
The type name must not already exist. name Subtype name. creator A factory function creating objects of this subtype from a const DictionaryDatum& containing parameters true if mask was successfully registered.
BaseT * nest::GenericFactory< BaseT >::new_from_dict_(const DictionaryDatum &d)