nest::Layer
Position< D > nest::Layer< D >::lower_left_
lower left corner (minimum coordinates) of layer
Referenced by nest::Layer< D >::get_center, nest::Layer< D >::get_lower_left, nest::GridLayer< D >::masked_iterator::masked_iterator.
Position< D > nest::Layer< D >::extent_
size of layer
Referenced by nest::Layer< D >::get_center, nest::Layer< D >::get_extent, nest::GridLayer< D >::masked_iterator::masked_iterator.
std::bitset< D > nest::Layer< D >::periodic_
periodic b.c.
Referenced by nest::Layer< D >::get_periodic_mask, nest::GridLayer< D >::masked_iterator::masked_iterator.
std::shared_ptr< Ntree< D, index > > nest::Layer< D >::cached_ntree_
Global position information for a single layer.
std::vector< std::pair< Position< D >, index > > * nest::Layer< D >::cached_vector_
friend class MaskedLayer< D >
nest::Layer< D >::Layer()
Creates an empty layer.
nest::Layer< D >::Layer(const Layer &other_layer)
Copy constructor.
nest::Layer< D >::~Layer() override
Virtual destructor.
void nest::Layer< D >::set_status(const DictionaryDatum &) override
Change properties of the layer according to the entries in the dictionary.
d Dictionary with named parameter settings.
References nest::names::edge_wrap, getValue< bool >.
Referenced by nest::FreeLayer< D >::set_status, nest::GridLayer< D >::set_status.
void nest::Layer< D >::get_status(DictionaryDatum &) const override
Export properties of the layer by setting entries in the status dictionary.
d Dictionary.
References nest::names::center, nest::names::edge_wrap, nest::names::extent.
Referenced by nest::FreeLayer< D >::get_status, nest::GridLayer< D >::get_status.
unsigned int nest::Layer< D >::get_num_dimensions() const override
const Position< D > & nest::Layer< D >::get_lower_left() const
The bottom left position of the layer
References nest::Layer< D >::lower_left_.
const Position< D > & nest::Layer< D >::get_extent() const
extent of layer.
References nest::Layer< D >::extent_.
Referenced by nest::MaskedLayer< D >::check_mask_.
Position< D > nest::Layer< D >::get_center() const
center of layer.
References nest::Layer< D >::extent_, nest::Layer< D >::lower_left_.
std::bitset< D > nest::Layer< D >::get_periodic_mask() const
a bitmask specifying which directions are periodic
References nest::Layer< D >::periodic_.
Referenced by nest::MaskedLayer< D >::check_mask_.
virtual Position< D > nest::Layer< D >::get_position(index sind) const =0
Get position of node.
Only possible for local nodes. sind index of node position of node.
std::vector< double > nest::Layer< D >::get_position_vector(const index sind) const override
sind index of node position of node as std::vector
References nest::get_position.
Position< D > nest::Layer< D >::compute_displacement(const Position< D > &from_pos, const Position< D > &to_pos) const
Returns displacement of a position from another position.
When using periodic boundary conditions, will return minimum displacement. from_pos position vector in layer to_pos position to which displacement is to be computed vector pointing from from_pos to to_pos
Referenced by nest::Layer< D >::dump_connections.
double nest::Layer< D >::compute_displacement(const std::vector< double > &from_pos, const std::vector< double > &to_pos, const unsigned int dimension) const override
References nest::displacement.
Position< D > nest::Layer< D >::compute_displacement(const Position< D > &from_pos, const index to) const
Returns displacement of node from given position.
When using periodic boundary conditions, will return minimum displacement. from_pos position vector in layer to node in layer to which displacement is to be computed vector pointing from from_pos to node to's position
References nest::get_position.
std::vector< double > nest::Layer< D >::compute_displacement(const std::vector< double > &from_pos, const index to) const override
Returns displacement of node from given position.
When using periodic boundary conditions, will return minimum displacement. from_pos position vector in layer to node in layer to which displacement is to be computed vector pointing from from_pos to node to's position
double nest::Layer< D >::compute_distance(const Position< D > &from_pos, const index lid) const
Returns distance to node from given position.
When using periodic boundary conditions, will return minimum distance. from_pos position vector in layer to node in layer to which displacement is to be computed length of vector pointing from from_pos to node to's position
double nest::Layer< D >::compute_distance(const std::vector< double > &from_pos, const index lid) const override
Returns distance to node from given position.
When using periodic boundary conditions, will return minimum distance. from_pos position vector in layer to node in layer to which displacement is to be computed length of vector pointing from from_pos to node to's position
double nest::Layer< D >::compute_distance(const std::vector< double > &from_pos, const std::vector< double > &to_pos) const override
References nest::displacement.
std::shared_ptr< Ntree< D, index > > nest::Layer< D >::get_global_positions_ntree(NodeCollectionPTR node_collection)
Get positions for all nodes in layer, including nodes on other MPI processes.
The positions will be cached so that subsequent calls for the same layer are fast. One one layer is cached at the time, so the user should group together all ConnectLayers calls using the same pool layer.
Referenced by nest::MaskedLayer< D >::MaskedLayer.
std::shared_ptr< Ntree< D, index > > nest::Layer< D >::get_global_positions_ntree(std::bitset< D > periodic, Position< D > lower_left, Position< D > extent, NodeCollectionPTR node_collection)
Get positions globally, overriding the dimensions of the layer and the periodic flags.
The supplied lower left corner and extent coordinates are only used for the dimensions where the supplied periodic flag is set.
std::vector< std::pair< Position< D >, index > > * nest::Layer< D >::get_global_positions_vector(NodeCollectionPTR node_collection)
std::vector< std::pair< Position< D >, index > > nest::Layer< D >::get_global_positions_vector(const MaskDatum &mask, const Position< D > &anchor, bool allow_oversized, NodeCollectionPTR node_collection)
References nest::MaskedLayer< D >::begin, nest::MaskedLayer< D >::end.
std::vector< index > nest::Layer< D >::get_global_nodes(const MaskDatum &mask, const std::vector< double > &anchor, bool allow_oversized, NodeCollectionPTR node_collection) override
Return a vector with the node IDs of the nodes inside the mask.
References nest::MaskedLayer< D >::begin, nest::MaskedLayer< D >::end.
void nest::Layer< D >::connect(NodeCollectionPTR source_nc, AbstractLayerPTR target, NodeCollectionPTR target_nc, ConnectionCreator &connector) override
Connect this layer to the given target layer.
The actual connections are made in class ConnectionCreator. source_nc NodeCollection to the source layer. target target layer to connect to. Must have same dimension as this layer. target_nc NodeCollection to the target layer. connector connection properties
References nest::ConnectionCreator::connect.
void nest::Layer< D >::dump_nodes(std::ostream &os) const override
Write layer data to stream.
For each node in layer, write one line to stream containing: node ID x-position y-position [z-position] os output stream
References nest::get_position, AggregateDatum< C, slt >::print.
void nest::Layer< D >::dump_connections(std::ostream &out, NodeCollectionPTR node_collection, AbstractLayerPTR target_layer, const Token &syn_model) override
Dumps information about all connections of the given type having their source in the given layer to the given output stream.
For distributed simulations this function will dump the connections with local targets only. out output stream node_collection NodeCollection of the layer target_layer Target layer synapse_id type of connection
References nest::Layer< D >::compute_displacement, nest::KernelManager::connection_manager, nest::NodeCollection::create, def, nest::names::delay, nest::ConnectionManager::get_connections, nest::ConnectionManager::get_synapse_status, getValue< double >, getValue< long >, nest::kernel, nest::AbstractLayer::node_collection_, nest::names::source, nest::names::synapse_model, nest::names::target, nest::names::weight.
void nest::Layer< D >::clear_ntree_cache_() const override
Clear the cache for global position information.
void nest::Layer< D >::clear_vector_cache_() const override
Clear the cache for global position information.
std::shared_ptr< Ntree< D, index > > nest::Layer< D >::do_get_global_positions_ntree_(NodeCollectionPTR node_collection)
virtual void nest::Layer< D >::insert_global_positions_ntree_(Ntree< D, index > &tree, NodeCollectionPTR node_collection)=0
Insert global position info into ntree.
virtual void nest::Layer< D >::insert_global_positions_vector_(std::vector< std::pair< Position< D >, index > > &, NodeCollectionPTR)=0
Insert global position info into vector.