nest::Na
double nest::Na::m_Na_
double nest::Na::h_Na_
double nest::Na::gbar_Na_
Referenced by Na.
double nest::Na::e_Na_
Referenced by Na.
double nest::Na::q10_
nest::Na::Na()
nest::Na::Na(const DictionaryDatum &channel_params)
References e_Na_, gbar_Na_.
nest::Na::~Na()
void nest::Na::pre_run_hook()
Referenced by nest::CompartmentCurrents::pre_run_hook.
void nest::Na::append_recordables(std::map< Name, double * > *recordables, const long compartment_idx)
Referenced by nest::CompartmentCurrents::get_recordables.
std::pair< double, double > nest::Na::f_numstep(const double v_comp)
References nest::names::dt, numerics::e, nest::names::g_Na, nest::Time::get_ms, nest::Time::get_resolution.
Referenced by nest::CompartmentCurrents::f_numstep.