nest::Connector
BlockVector< ConnectionT > nest::Connector< ConnectionT >::C_
Referenced by nest::Connector< ConnectionT >::disable_connection, nest::Connector< ConnectionT >::find_first_target, nest::Connector< ConnectionT >::find_matching_target, nest::Connector< ConnectionT >::get_all_connections, nest::Connector< ConnectionT >::get_connection, nest::Connector< ConnectionT >::get_connection_with_specified_targets, nest::Connector< ConnectionT >::get_source_lcids, nest::Connector< ConnectionT >::get_synapse_status, nest::Connector< ConnectionT >::get_target_node_id, nest::Connector< ConnectionT >::get_target_node_ids, nest::Connector< ConnectionT >::push_back, nest::Connector< ConnectionT >::remove_disabled_connections, nest::Connector< ConnectionT >::send, nest::Connector< ConnectionT >::send_to_all, nest::Connector< ConnectionT >::set_source_has_more_targets, nest::Connector< ConnectionT >::set_synapse_status, nest::Connector< ConnectionT >::size, nest::Connector< ConnectionT >::sort_connections, nest::Connector< ConnectionT >::trigger_update_weight, nest::Connector< ConnectionT >::~Connector.
const synindex nest::Connector< ConnectionT >::syn_id_
Referenced by nest::Connector< ConnectionT >::get_connection, nest::Connector< ConnectionT >::get_connection_with_specified_targets, nest::Connector< ConnectionT >::get_syn_id, nest::Connector< ConnectionT >::send, nest::Connector< ConnectionT >::send_to_all, nest::Connector< ConnectionT >::trigger_update_weight.
nest::Connector< ConnectionT >::Connector(const synindex syn_id)
nest::Connector< ConnectionT >::~Connector() override
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::clear.
synindex nest::Connector< ConnectionT >::get_syn_id() const override
Return syn_id_ of the synapse type of this Connector (index in list of synapse prototypes).
References nest::Connector< ConnectionT >::syn_id_.
size_t nest::Connector< ConnectionT >::size() const override
Return the number of connections in this Connector.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::size.
void nest::Connector< ConnectionT >::get_synapse_status(const thread tid, const index lcid, DictionaryDatum &dict) const override
Write status of the connection at position lcid to the dictionary dict.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::size, nest::names::target.
void nest::Connector< ConnectionT >::set_synapse_status(const index lcid, const DictionaryDatum &dict, ConnectorModel &cm) override
Set status of the connection at position lcid according to the dictionary dict.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::size.
void nest::Connector< ConnectionT >::push_back(const ConnectionT &c)
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::push_back.
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection_.
void nest::Connector< ConnectionT >::get_connection(const index source_node_id, const index target_node_id, const thread tid, const index lcid, const long synapse_label, std::deque< ConnectionID > &conns) const override
Add ConnectionID with given source_node_id and lcid to conns.
If target_node_id is given, only add connection if target_node_id matches the node_id of the target of the connection.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::push_back, nest::Connector< ConnectionT >::syn_id_, nest::UNLABELED_CONNECTION.
Referenced by nest::Connector< ConnectionT >::get_all_connections.
void nest::Connector< ConnectionT >::get_connection_with_specified_targets(const index source_node_id, const std::vector< size_t > &target_neuron_node_ids, const thread tid, const index lcid, const long synapse_label, std::deque< ConnectionID > &conns) const override
Add ConnectionID with given source_node_id and lcid to conns.
If target_neuron_node_ids is given, only add connection if target_neuron_node_ids contains the node ID of the target of the connection.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::push_back, nest::Connector< ConnectionT >::syn_id_, nest::UNLABELED_CONNECTION.
void nest::Connector< ConnectionT >::get_all_connections(const index source_node_id, const index target_node_id, const thread tid, const long synapse_label, std::deque< ConnectionID > &conns) const override
Add ConnectionIDs with given source_node_id to conns, looping over all lcids.
If target_node_id is given, only add connection if target_node_id matches the node ID of the target of the connection.
References nest::Connector< ConnectionT >::C_, nest::Connector< ConnectionT >::get_connection, BlockVector< value_type_ >::size.
void nest::Connector< ConnectionT >::get_source_lcids(const thread tid, const index target_node_id, std::vector< index > &source_lcids) const override
For a given target_node_id add lcids of all connections with matching node ID of target to source_lcids.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::push_back, BlockVector< value_type_ >::size.
void nest::Connector< ConnectionT >::get_target_node_ids(const thread tid, const index start_lcid, const std::string &post_synaptic_element, std::vector< index > &target_node_ids) const override
For a given start_lcid add node IDs of all targets that belong to the same source to target_node_ids.
References nest::Connector< ConnectionT >::C_.
index nest::Connector< ConnectionT >::get_target_node_id(const thread tid, const unsigned int lcid) const override
For a given lcid return the node ID of the target of the connection.
References nest::Connector< ConnectionT >::C_.
void nest::Connector< ConnectionT >::send_to_all(const thread tid, const std::vector< ConnectorModel * > &cm, Event &e) override
Send the event e to all connections of this Connector.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::size, nest::Connector< ConnectionT >::syn_id_.
index nest::Connector< ConnectionT >::send(const thread tid, const index lcid, const std::vector< ConnectorModel * > &cm, Event &e) override
Send the event e to the connection at position lcid.
Return bool indicating whether the following connection belongs to the same source.
References nest::Connector< ConnectionT >::C_, nest::Connector< ConnectionT >::send_weight_event, nest::Connector< ConnectionT >::syn_id_.
void nest::Connector< ConnectionT >::send_weight_event(const thread tid, const unsigned int lcid, Event &e, const CommonSynapseProperties &cp) override
References nest::NodeManager::get_node_or_proxy, nest::CommonSynapseProperties::get_weight_recorder, nest::CommonSynapseProperties::get_wr_node_id, nest::kernel, nest::KernelManager::node_manager, nest::Event::set_delay_steps, nest::Event::set_port, nest::Event::set_receiver, nest::WeightRecorderEvent::set_receiver_node_id, nest::Event::set_rport, nest::Event::set_sender, nest::Event::set_sender_node_id, nest::Event::set_stamp, nest::Event::set_weight.
Referenced by nest::Connector< ConnectionT >::send.
void nest::Connector< ConnectionT >::trigger_update_weight(const long vt_node_id, const thread tid, const std::vector< spikecounter > &dopa_spikes, const double t_trig, const std::vector< ConnectorModel * > &cm) override
Update weights of dopamine modulated STDP connections.
References nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::size, nest::Connector< ConnectionT >::syn_id_.
void nest::Connector< ConnectionT >::sort_connections(BlockVector< Source > &sources) override
Sort connections according to source node IDs.
References nest::Connector< ConnectionT >::C_, nest::sort.
void nest::Connector< ConnectionT >::set_source_has_more_targets(const index lcid, const bool has_more_targets) override
Set a flag in the connection indicating whether the following connection belongs to the same source.
References nest::Connector< ConnectionT >::C_.
index nest::Connector< ConnectionT >::find_first_target(const thread tid, const index start_lcid, const index target_node_id) const override
Return lcid of the first connection after start_lcid (inclusive) where the node_id of the target matches target_node_id.
If there are no matches, the function returns invalid_index.
References nest::Connector< ConnectionT >::C_.
index nest::Connector< ConnectionT >::find_matching_target(const thread tid, const std::vector< index > &matching_lcids, const index target_node_id) const override
Return lcid of first connection where the node ID of the target matches target_node_id; consider only the connections with lcids given in matching_lcids.
If there is no match, the function returns invalid_index.
References nest::Connector< ConnectionT >::C_.
void nest::Connector< ConnectionT >::disable_connection(const index lcid) override
Disable the transfer of events through the connection at position lcid.
References nest::Connector< ConnectionT >::C_.
void nest::Connector< ConnectionT >::remove_disabled_connections(const index first_disabled_index) override
Remove disabled connections from the connector.
References BlockVector< value_type_ >::begin, nest::Connector< ConnectionT >::C_, BlockVector< value_type_ >::end, BlockVector< value_type_ >::erase.