nest::Node
friend class NodeManager
friend class ModelManager
friend class proxynode
friend class Synapse
friend class Model
friend class SimulationManager
DeprecationWarning nest::Node::deprecation_warning
Member of DeprecationWarning class to be used by models if parameters are deprecated.
index nest::Node::node_id_
Global Element ID (node ID).
The node ID is unique within the network. The smallest valid node ID is 1.
Referenced by get_node_id, set_node_id_.
index nest::Node::thread_lid_
Local id of this node in the thread-local vector of nodes.
Referenced by get_thread_lid, set_thread_lid.
int nest::Node::model_id_
Model ID.
It is only set for actual node instances, not for instances of class Node representing model prototypes. Model prototypes always have model_id_==-1. get_model_id(), set_model_id()
Referenced by get_model_, get_model_id, get_name, nest::proxynode::get_status, set_model_id.
thread nest::Node::thread_
thread node is assigned to
Referenced by get_thread, set_thread.
thread nest::Node::vp_
virtual process node is assigned to
Referenced by get_vp, is_model_prototype, set_vp.
bool nest::Node::frozen_
node shall not be updated if true
Referenced by is_frozen, set_frozen_, set_status_base.
bool nest::Node::initialized_
state and buffers have been initialized
Referenced by init, nest::pp_psc_delta::State_::set.
bool nest::Node::node_uses_wfr_
node uses waveform relaxation method
Referenced by node_uses_wfr, set_node_uses_wfr.
NodeCollectionPTR nest::Node::nc_ptr_
Original NodeCollection of this node, used to extract node-specific metadata.
Referenced by get_nc, set_nc_.
Node& nest::Node::operator=(const Node &)
not implemented
void nest::Node::set_node_id_(index)
Set global node id.
References node_id_.
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_, nest::ModelManager::get_proxy_node, nest::proxynode::proxynode.
void nest::Node::set_nc_(NodeCollectionPTR)
Set the original NodeCollection of this node.
References nc_ptr_.
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_.
DictionaryDatum nest::Node::get_status_dict_()
Return a new dictionary datum .
This function is called by get_status_base() and returns a new empty dictionary by default. Some nodes may contain a permanent status dictionary which is then returned by get_status_dict_().
Referenced by get_status_base.
nest::Node::Node()
nest::Node::Node(Node const &)
nest::Node::~Node()
virtual Node* nest::Node::clone() const
Virtual copy constructor.
This function should create a new object by calling the derived class' copy constructor and return its pointer.
bool nest::Node::has_proxies() const
Returns true if the node has proxies on remote threads.
This is used to discriminate between different types of nodes, when adding new nodes to the network.
Referenced by nest::SparseNodeArray::add_local_node, nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_, nest::NodeManager::get_mpi_local_node_or_device_head, nest::ConnectionCreator::pairwise_bernoulli_on_target_.
bool nest::Node::supports_urbanczik_archiving() const
Returns true if the node supports the Urbanczik-Senn plasticity rule.
bool nest::Node::local_receiver() const
Returns true if the node only receives events from nodes/devices on the same thread.
bool nest::Node::one_node_per_process() const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
This is used to discriminate between different types of nodes, when adding new nodes to the network. TODO: Is this true for any model at all? Maybe MUSIC related?
bool nest::Node::is_off_grid() const
Returns true if the node sends/receives off-grid events.
This is used to discriminate between different types of nodes when adding new nodes to the network.
bool nest::Node::is_proxy() const
Returns true if the node is a proxy node.
This is implemented because the use of RTTI is rather expensive.
Referenced by nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_, get_status_base, nest::ConnectionCreator::pairwise_bernoulli_on_source_, nest::ConnectionCreator::pairwise_bernoulli_on_target_.
std::string nest::Node::get_name() const
Return class name.
Returns name of node model (e.g. "iaf_psc_alpha") as string. This name is identical to the name that is used to identify the model in the interpreter's model dictionary.
References nest::Model::get_name, nest::ModelManager::get_node_model, nest::kernel, model_id_, nest::KernelManager::model_manager.
Referenced by nest::RecordingBackendASCII::enroll, nest::RecordingBackendSIONlib::enroll, get_status_base, nest::ac_generator::handles_test_event, nest::dc_generator::handles_test_event, nest::noise_generator::handles_test_event, nest::sinusoidal_poisson_generator::handles_test_event, nest::step_current_generator::handles_test_event, nest::step_rate_generator::handles_test_event, nest::iaf_psc_exp_ps_lossless::handles_test_event, nest::amat2_psc_exp::handles_test_event, nest::cm_default::handles_test_event, nest::correlation_detector::handles_test_event, nest::correlomatrix_detector::handles_test_event, nest::correlospinmatrix_detector::handles_test_event, nest::gif_psc_exp::handles_test_event, nest::gif_psc_exp_multisynapse::handles_test_event, nest::iaf_chs_2007::handles_test_event, nest::iaf_psc_alpha::handles_test_event, nest::iaf_psc_alpha_multisynapse::handles_test_event, nest::iaf_psc_alpha_ps::handles_test_event, nest::iaf_psc_delta::handles_test_event, nest::iaf_psc_delta_ps::handles_test_event, nest::iaf_psc_exp::handles_test_event, nest::iaf_psc_exp_htum::handles_test_event, nest::iaf_psc_exp_multisynapse::handles_test_event, nest::iaf_psc_exp_ps::handles_test_event, nest::izhikevich::handles_test_event, nest::mat2_psc_exp::handles_test_event, nest::parrot_neuron::handles_test_event, nest::parrot_neuron_ps::handles_test_event, nest::pp_psc_delta::handles_test_event, nest::spike_dilutor::handles_test_event, nest::spike_recorder::handles_test_event, nest::spin_detector::handles_test_event, nest::volume_transmitter::handles_test_event, nest::weight_recorder::handles_test_event, set_status_base.
Name nest::Node::get_element_type() const
Return the element type of the node.
The returned Name is a free label describing the class of network elements a node belongs to. Currently used values are "neuron", "recorder", "stimulator", and "other", which are all defined as static Name objects in the names namespace. This function is overwritten with a corresponding value in the derived classes
References nest::names::neuron.
Referenced by get_status_base.
index nest::Node::get_node_id() const
Return global Network ID.
Returns the global network ID of the Node. Each node has a unique network ID which can be used to access the Node comparable to a pointer. The smallest valid node ID is 1.
References node_id_.
Referenced by nest::SparseNodeArray::add_local_node, nest::RecordingBackendASCII::compute_vp_node_id_string_, nest::ConnectionCreator::connect_to_target_, nest::RecordingBackendASCII::disenroll, nest::RecordingBackendMemory::disenroll, nest::RecordingBackendMPI::disenroll, nest::RecordingBackendScreen::disenroll, nest::RecordingBackendSIONlib::disenroll, nest::StimulationBackendMPI::disenroll, nest::RecordingBackendASCII::enroll, nest::RecordingBackendMemory::enroll, nest::RecordingBackendMPI::enroll, nest::RecordingBackendScreen::enroll, nest::RecordingBackendSIONlib::enroll, nest::StimulationBackendMPI::enroll, nest::RecordingBackendASCII::get_device_status, nest::RecordingBackendMemory::get_device_status, nest::RecordingBackendScreen::get_device_status, nest::NodePosParameter::get_node_pos_, nest::RecordingBackendMPI::get_port, nest::StimulationBackendMPI::get_port, nest::Event::get_receiver_node_id, nest::weight_recorder::get_status, nest::RecordingDevice::get_status, nest::STDPDopaCommonProperties::get_status, nest::TargetIdentifierPtrRport::get_status, nest::StimulationDevice::get_status, get_status_base, nest::STDPDopaCommonProperties::get_vt_node_id, nest::RecordingDevice::set_status, nest::StimulationDevice::set_status, set_status_base, nest::RecordingBackendASCII::set_value_names, nest::RecordingBackendMemory::set_value_names, nest::RecordingBackendSIONlib::set_value_names, nest::NormalParameter::value, nest::LognormalParameter::value, nest::RecordingBackendASCII::write, nest::RecordingBackendMemory::write, nest::RecordingBackendMPI::write, nest::RecordingBackendScreen::write, nest::RecordingBackendSIONlib::write.
NodeCollectionPTR nest::Node::get_nc() const
Return lockpointer to the NodeCollection that created this node.
References nc_ptr_.
Referenced by nest::distance, nest::NodePosParameter::get_node_pos_, nest::get_position.
int nest::Node::get_model_id() const
Return model ID of the node.
Returns the model ID of the model for this node. Model IDs start with 0. The model ID is not stored in the model prototype instance. It is only set when actual nodes are created from a prototype.
References model_id_.
Referenced by get_status_base, nest::proxynode::send_test_event, nest::proxynode::sends_secondary_event, nest::proxynode::sends_signal.
virtual std::string nest::Node::print_network(int, int, std::string="")
Prints out one line of the tree view of the network.
bool nest::Node::is_frozen() const
Returns true if node is frozen, i.e., shall not be updated.
References frozen_.
Referenced by get_status_base.
bool nest::Node::node_uses_wfr() const
Returns true if the node uses the waveform relaxation method.
References node_uses_wfr_.
Referenced by get_status_base.
void nest::Node::set_node_uses_wfr(const bool)
Sets node_uses_wfr_ member variable (to be able to set it to "true" for any class derived from Node)
References node_uses_wfr_.
Referenced by nest::rate_neuron_ipn< TNonlinearities >::rate_neuron_ipn, nest::rate_neuron_opn< TNonlinearities >::rate_neuron_opn, nest::rate_transformer_node< TNonlinearities >::rate_transformer_node.
void nest::Node::init()
Initialize node prior to first simulation after node has been created.
init() allows the node to configure internal data structures prior to being simulated. The method has an effect only the first time it is called on a given node, otherwise it returns immediately. init() calls virtual functions init_state_() and init_buffers_().
References init_buffers_, init_state_, initialized_.
virtual void nest::Node::pre_run_hook()=0
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
virtual void nest::Node::calibrate_time(const TimeConverter &)
Re-calculate time-based properties of the node.
This function is called after a change in resolution.
virtual void nest::Node::post_run_cleanup()
Cleanup node after Run.
Override this function if a node needs to "wrap up" things after a call to Run, i.e., before SimulationManager::run() returns. Typical use-cases are devices that need to flush buffers.
virtual void nest::Node::finalize()
Finalize node.
Override this function if a node needs to "wrap up" things after a full simulation, i.e., a cycle of Prepare, Run, Cleanup. Typical use-cases are devices that need to close files.
virtual void nest::Node::update(Time const &, const long, const long)=0
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to. Time network time at beginning of time slice. long initial step inside time slice long post-final step inside time slice
bool nest::Node::wfr_update(Time const &, const long, const long)
Bring the node from state $t$ to $t+n*dt$, sends SecondaryEvents (e.g.
Default implementation of wfr_update just throws UnexpectedEvent. GapJunctionEvent) and resets state variables to values at $t$. n->wfr_update(T, from, to) performs the update steps beginning at T+from .. T+to-1. Does not emit spikes, does not log state variables. throws UnexpectedEvent if not reimplemented in derived class Time network time at beginning of time slice. long initial step inside time slice long post-final step inside time slice
virtual void nest::Node::set_status(const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
d Dictionary with named parameter settings.
Referenced by set_status_base.
virtual void nest::Node::get_status(DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
d Dictionary.
Referenced by get_status_base.
port nest::Node::send_test_event(Node &receiving_node, rport receptor_type, synindex syn_id, bool dummy_target)
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws IllegalConnection. This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node. If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
port nest::Node::handles_test_event(SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event(). handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle. See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3. The semantics of all other handles_test_event() functions is identical. IllegalConnection
Referenced by nest::DiffusionConnection< targetidentifierT >::check_connection, nest::GapJunction< targetidentifierT >::check_connection, nest::RateConnectionDelayed< targetidentifierT >::check_connection, nest::RateConnectionInstantaneous< targetidentifierT >::check_connection.
port nest::Node::handles_test_event(WeightRecorderEvent &, rport receptor_type)
port nest::Node::handles_test_event(RateEvent &, rport receptor_type)
port nest::Node::handles_test_event(DataLoggingRequest &, rport receptor_type)
port nest::Node::handles_test_event(CurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(ConductanceEvent &, rport receptor_type)
port nest::Node::handles_test_event(DoubleDataEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSSpikeEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSCurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(GapJunctionEvent &, rport receptor_type)
port nest::Node::handles_test_event(InstantaneousRateConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DiffusionConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DelayedRateConnectionEvent &, rport receptor_type)
void nest::Node::sends_secondary_event(GapJunctionEvent &ge)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
Referenced by nest::DiffusionConnection< targetidentifierT >::check_connection, nest::GapJunction< targetidentifierT >::check_connection, nest::RateConnectionDelayed< targetidentifierT >::check_connection, nest::RateConnectionInstantaneous< targetidentifierT >::check_connection.
void nest::Node::sends_secondary_event(InstantaneousRateConnectionEvent &re)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::Node::sends_secondary_event(DiffusionConnectionEvent &de)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::Node::sends_secondary_event(DelayedRateConnectionEvent &re)
Required to check, if source neuron may send a SecondaryEvent.
This base class implementation throws IllegalConnection and needs to be overwritten in the derived class. IllegalConnection
void nest::Node::register_stdp_connection(double, double)
Register a STDP connection.
Default implementation of register_stdp_connection() just throws IllegalConnection. IllegalConnection
Referenced by nest::clopath_synapse< targetidentifierT >::check_connection, nest::jonke_synapse< targetidentifierT >::check_connection, nest::stdp_nn_pre_centered_synapse< targetidentifierT >::check_connection, nest::stdp_nn_restr_synapse< targetidentifierT >::check_connection, nest::stdp_nn_symm_synapse< targetidentifierT >::check_connection, nest::stdp_pl_synapse_hom< targetidentifierT >::check_connection, nest::stdp_synapse< targetidentifierT >::check_connection, nest::stdp_facetshw_synapse_hom< targetidentifierT >::check_connection, nest::stdp_synapse_hom< targetidentifierT >::check_connection, nest::stdp_triplet_synapse< targetidentifierT >::check_connection, nest::urbanczik_synapse< targetidentifierT >::check_connection, nest::vogels_sprekeler_synapse< targetidentifierT >::check_connection, nest::stdp_dopamine_synapse< targetidentifierT >::check_connection.
void nest::Node::handle(SpikeEvent &e)
Handle incoming spike events.
Default implementation of event handlers just throws an UnexpectedEvent exception. thrd Id of the calling thread. e Event object. This handler has to be implemented if a Node should accept spike events. class SpikeEvent class UnexpectedEvent UnexpectedEvent This is the default event to throw.
Referenced by nest::SpikeEvent::operator(), nest::WeightRecorderEvent::operator(), nest::RateEvent::operator(), nest::CurrentEvent::operator(), nest::DataLoggingRequest::operator(), nest::DataLoggingReply::operator(), nest::ConductanceEvent::operator(), nest::DoubleDataEvent::operator(), nest::GapJunctionEvent::operator(), nest::InstantaneousRateConnectionEvent::operator(), nest::DelayedRateConnectionEvent::operator(), nest::DiffusionConnectionEvent::operator().
void nest::Node::handle(WeightRecorderEvent &e)
Handle incoming weight recording events.
thrd Id of the calling thread. e Event object. This handler has to be implemented if a Node should accept weight recording events. class WeightRecordingEvent
void nest::Node::handle(RateEvent &e)
Handler for rate events.
handle(SpikeEvent&) UnexpectedEvent
void nest::Node::handle(DataLoggingRequest &e)
Handler for universal data logging request.
handle(SpikeEvent&) UnexpectedEvent
void nest::Node::handle(DataLoggingReply &e)
Handler for universal data logging request.
handle(SpikeEvent&) UnexpectedEvent There is no connect_sender() for DataLoggingReply, since this event is only used as "back channel" for DataLoggingRequest.
void nest::Node::handle(CurrentEvent &e)
Handler for current events.
handle(thread, SpikeEvent&) UnexpectedEvent
void nest::Node::handle(ConductanceEvent &e)
Handler for conductance events.
handle(thread, SpikeEvent&) UnexpectedEvent
void nest::Node::handle(DoubleDataEvent &e)
Handler for DoubleData events.
handle(thread, SpikeEvent&) UnexpectedEvent
void nest::Node::handle(GapJunctionEvent &e)
Handler for gap junction events.
handle(thread, GapJunctionEvent&) UnexpectedEvent
void nest::Node::handle(InstantaneousRateConnectionEvent &e)
Handler for rate neuron events.
handle(thread, InstantaneousRateConnectionEvent&) UnexpectedEvent
void nest::Node::handle(DiffusionConnectionEvent &e)
Handler for rate neuron events.
handle(thread, InstantaneousRateConnectionEvent&) UnexpectedEvent
void nest::Node::handle(DelayedRateConnectionEvent &e)
Handler for delay rate neuron events.
handle(thread, DelayedRateConnectionEvent&) UnexpectedEvent
virtual double nest::Node::get_Ca_minus() const
Return the Ca_minus value at time Ca_t which corresponds to the time of the last update in Calcium concentration which is performed each time a Node spikes.
Return 0.0 if not overridden
virtual double nest::Node::get_synaptic_elements(Name) const
Get the number of synaptic element for the current Node at Ca_t which corresponds to the time of the last spike.
Return 0.0 if not overridden
virtual int nest::Node::get_synaptic_elements_vacant(Name) const
Get the number of vacant synaptic element for the current Node Return 0 if not overridden.
Referenced by nest::SPManager::get_synaptic_elements.
virtual int nest::Node::get_synaptic_elements_connected(Name) const
Get the number of connected synaptic element for the current Node Return 0 if not overridden.
virtual std::map< Name, double > nest::Node::get_synaptic_elements() const
Get the number of all synaptic elements for the current Node at time t Return an empty map if not overridden.
virtual void nest::Node::update_synaptic_elements(double)
Triggers the update of all SynapticElements stored in the synaptic_element_map_.
It also updates the calcium concentration. t double time when the update is being performed
Referenced by nest::SimulationManager::update_.
virtual void nest::Node::decay_synaptic_elements_vacant()
Is used to reduce the number of synaptic elements in the node through time.
This amount is defined by tau_vacant.
Referenced by nest::SimulationManager::update_.
virtual void nest::Node::connect_synaptic_element(Name, int)
Is used to update the number of connected synaptic elements (SynapticElement::z_connected_) when a synapse is formed or deleted.
type Name, name of the synaptic element to connect n int number of new connections of the given type
double nest::Node::get_K_value(double t)
return the Kminus value at t (in ms).
UnexpectedEvent
double nest::Node::get_LTD_value(double t)
void nest::Node::get_K_values(double t, double &Kminus, double &nearest_neighbor_Kminus, double &Kminus_triplet)
write the Kminus, nearest_neighbor_Kminus, and Kminus_triplet values at t (in ms) to the provided locations.
UnexpectedEvent
void nest::Node::get_history(double t1, double t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike history for (t1,t2].
UnexpectedEvent
void nest::Node::get_LTP_history(double t1, double t2, std::deque< histentry_extended >::iterator *start, std::deque< histentry_extended >::iterator *finish)
void nest::Node::get_urbanczik_history(double t1, double t2, std::deque< histentry_extended >::iterator *start, std::deque< histentry_extended >::iterator *finish, int)
double nest::Node::get_C_m(int comp)
double nest::Node::get_g_L(int comp)
double nest::Node::get_tau_L(int comp)
double nest::Node::get_tau_s(int comp)
double nest::Node::get_tau_syn_ex(int comp)
double nest::Node::get_tau_syn_in(int comp)
void nest::Node::event_hook(DSSpikeEvent &)
Modify Event object parameters during event delivery.
Some Nodes want to perform a function on an event for each of their targets. An example is the poisson_generator which needs to draw a random number for each target. The DSSpikeEvent, DirectSendingSpikeEvent, calls sender->event_hook(thread, *this) in its operator() function instead of calling target->handle(). The default implementation of Node::event_hook() just calls target->handle(DSSpikeEvent&). Any reimplementation must also execute this call. Otherwise the event will not be delivered. If needed, target->handle(DSSpikeEvent) may be called more than once.
References numerics::e.
Referenced by nest::DSSpikeEvent::operator(), nest::DSCurrentEvent::operator().
void nest::Node::event_hook(DSCurrentEvent &)
References numerics::e.
void nest::Node::set_thread(thread)
Store the number of the thread to which the node is assigned.
The assignment is done after node creation by the Network class. : NodeManager::add_node().
References thread_.
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_.
thread nest::Node::get_thread() const
Retrieve the number of the thread to which the node is assigned.
References thread_.
Referenced by nest::RecordingBackendASCII::disenroll, nest::RecordingBackendMemory::disenroll, nest::RecordingBackendMPI::disenroll, nest::RecordingBackendScreen::disenroll, nest::RecordingBackendSIONlib::disenroll, nest::StimulationBackendMPI::disenroll, nest::RecordingBackendASCII::enroll, nest::RecordingBackendMemory::enroll, nest::RecordingBackendMPI::enroll, nest::RecordingBackendScreen::enroll, nest::RecordingBackendSIONlib::enroll, nest::StimulationBackendMPI::enroll, nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_, nest::RecordingBackendASCII::get_device_status, nest::RecordingBackendMemory::get_device_status, nest::RecordingBackendScreen::get_device_status, nest::weight_recorder::get_status, get_status_base, nest::RecordingBackendASCII::set_value_names, nest::RecordingBackendMemory::set_value_names, nest::RecordingBackendSIONlib::set_value_names, nest::RecordingBackendASCII::write, nest::RecordingBackendMemory::write, nest::RecordingBackendScreen::write, nest::RecordingBackendSIONlib::write.
void nest::Node::set_vp(thread)
Store the number of the virtual process to which the node is assigned.
This is assigned to the node in NodeManager::add_node().
References nest::names::vp, vp_.
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_, nest::ModelManager::get_proxy_node, nest::proxynode::proxynode.
thread nest::Node::get_vp() const
Retrieve the number of the virtual process to which the node is assigned.
References vp_.
Referenced by nest::RecordingBackendASCII::compute_vp_node_id_string_, get_status_base, nest::RecordingBackendSIONlib::write.
void nest::Node::set_model_id(int)
Set the model id.
This method is called by NodeManager::add_node() when a node is created. get_model_id()
References model_id_.
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_, nest::ModelManager::create_proxynode_, nest::proxynode::proxynode.
void nest::Node::set_initialized()
Execute post-initialization actions in node models.
This method is called by NodeManager::add_node() on a node once is fully initialized, i.e. after node ID, nc, model_id, thread, vp is set.
References set_initialized_.
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_.
virtual SignalType nest::Node::sends_signal() const
type of signal this node produces used in check_connection to only connect neurons which send / receive compatible information
References nest::SPIKE.
virtual SignalType nest::Node::receives_signal() const
type of signal this node consumes used in check_connection to only connect neurons which send / receive compatible information
References nest::SPIKE.
DictionaryDatum nest::Node::get_status_base()
Return a dictionary with the node's properties.
get_status_base() first gets a dictionary with the basic information of an element, using get_status_dict_(). It then calls the custom function get_status(DictionaryDatum) with the created status dictionary as argument.
References nest::names::element_type, nest::names::frozen, get_element_type, get_model_id, get_name, get_node_id, get_status, get_status_dict_, get_thread, get_thread_lid, get_vp, nest::names::global_id, is_frozen, nest::NodeManager::is_local_node, is_proxy, nest::kernel, nest::names::local, nest::names::model, nest::names::model_id, nest::KernelManager::node_manager, nest::names::node_uses_wfr, node_uses_wfr, nest::names::thread, nest::names::thread_local_id, nest::names::vp.
void nest::Node::set_status_base(const DictionaryDatum &)
Set status dictionary of a node.
Forwards to set_status() of the derived class.
References numerics::e, nest::names::frozen, frozen_, get_name, get_node_id, set_status.
bool nest::Node::is_model_prototype() const
Returns true if node is model prototype.
References nest::invalid_thread, vp_.
Referenced by nest::weight_recorder::get_status, nest::multimeter::send_test_event, nest::poisson_generator_ps::send_test_event, nest::ppd_sup_generator::send_test_event.
void nest::Node::set_thread_lid(const index)
set thread local index
References thread_lid_.
index nest::Node::get_thread_lid() const
get thread local index
References thread_lid_.
Referenced by get_status_base.
void nest::Node::set_local_device_id(const index lsdid)
Sets the local device id.
Throws an error if used on a non-device node. get_local_device_id
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_.
index nest::Node::get_local_device_id() const
Gets the local device id.
Throws an error if used on a non-device node. set_local_device_id
void nest::Node::init_state_()
Configure state variables depending on runtime information.
Overload this method if the node needs to adapt state variables prior to first simulation to runtime information, e.g., the number of incoming connections.
Referenced by init, nest::spike_train_injector::init_state_.
void nest::Node::init_buffers_()
Configure persistent internal data structures.
Let node configure persistent internal data structures, such as input buffers or ODE solvers, to runtime information prior to first simulation.
Referenced by init.
void nest::Node::set_initialized_()
Referenced by set_initialized.
Model & nest::Node::get_model_() const
References nest::ModelManager::get_node_model, nest::kernel, model_id_, nest::KernelManager::model_manager.
void nest::Node::set_frozen_(bool frozen)
Mark node as frozen.
References nest::names::frozen, frozen_.
Referenced by nest::proxynode::proxynode.
const ConcreteNode & nest::Node::downcast(const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
This function is used to convert generic Node references to specific ones when intializing parameters or state from a prototype.
References nest::names::n.