nest::GridMask
Position< D, int > nest::GridMask< D >::upper_left_
Referenced by nest::GridMask< D >::get_upper_left.
Position< D, int > nest::GridMask< D >::lower_right_
Referenced by nest::GridMask< D >::get_lower_right.
nest::GridMask< D >::GridMask(const DictionaryDatum &d)
Parameters: shape - size in grid coordinates (length 2 for 2D layers or length 3 for 3D layers)
References nest::names::d, nest::names::shape.
Referenced by nest::GridMask< D >::clone.
bool nest::GridMask< D >::inside(const std::vector< double > &) const override
true if point is inside mask.
void nest::GridMask< D >::set_anchor(const Position< D, int > &)
References nest::names::anchor.
Referenced by nest::NestModule::create_mask.
DictionaryDatum nest::GridMask< D >::get_dict() const override
a dictionary with the definition for this mask.
References nest::names::d, nest::names::shape.
GridMask< D >* nest::GridMask< D >::clone() const
References nest::GridMask< D >::GridMask.
AbstractMask* nest::GridMask< D >::intersect_mask(const AbstractMask &) const override
Create the intersection of this mask with another.
Masks must have the same dimension a new dynamically allocated mask.
AbstractMask* nest::GridMask< D >::union_mask(const AbstractMask &) const override
Create the union of this mask with another.
Masks must have the same dimension. a new dynamically allocated mask.
AbstractMask* nest::GridMask< D >::minus_mask(const AbstractMask &) const override
Create the difference of this mask and another.
Masks must have the same dimension. a new dynamically allocated mask.
Position< D, int > nest::GridMask< D >::get_upper_left() const
References nest::GridMask< D >::upper_left_.
Referenced by nest::MaskedLayer< D >::check_mask_.
Position< D, int > nest::GridMask< D >::get_lower_right() const
References nest::GridMask< D >::lower_right_.
Referenced by nest::MaskedLayer< D >::check_mask_.
Name nest::GridMask< 2 >::get_name()
References nest::names::grid.
Name nest::GridMask< 3 >::get_name()
References nest::names::grid3d.
static Name nest::GridMask< D >::get_name()
the name of this mask type.