nest::IOManager
std::string nest::IOManager::data_path_
Path for all files written by devices.
Referenced by get_data_path, get_status, set_data_path_prefix_.
std::string nest::IOManager::data_prefix_
Prefix for all files written by devices.
Referenced by get_status, set_data_path_prefix_.
bool nest::IOManager::overwrite_files_
If true, overwrite existing data files.
Referenced by get_status, initialize, set_status.
std::map< Name, RecordingBackend* > nest::IOManager::recording_backends_
A mapping from names to registered recording backends.
Referenced by change_number_of_threads, check_recording_backend_device_status, cleanup, enroll_recorder, finalize, get_recording_backend_device_defaults, get_recording_backend_device_status, get_recording_backend_status, get_status, initialize, is_valid_recording_backend, post_run_hook, post_step_hook, pre_run_hook, prepare, register_recording_backend, set_recording_backend_status, set_recording_value_names, write, ~IOManager.
std::map< Name, StimulationBackend* > nest::IOManager::stimulation_backends_
A mapping from names to registered stimulation backends.
Referenced by change_number_of_threads, cleanup, finalize, get_status, initialize, is_valid_stimulation_backend, post_run_hook, pre_run_hook, prepare, register_stimulation_backend, ~IOManager.
nest::IOManager::IOManager()
nest::IOManager::~IOManager() override
References recording_backends_, stimulation_backends_.
void nest::IOManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References nest::names::data_path, nest::names::data_prefix, overwrite_files_, recording_backends_, set_data_path_prefix_, stimulation_backends_.
void nest::IOManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
References recording_backends_, stimulation_backends_.
void nest::IOManager::change_number_of_threads() override
Change the number of threads.
Many data structures within the different managers depend on the number of threads. This function is called on each manager upon a change of that number and allows the manager to re-allocate data structures accordingly.
References recording_backends_, stimulation_backends_.
void nest::IOManager::set_status(const DictionaryDatum &) override
References nest::names::d, nest::names::overwrite_files, overwrite_files_, set_data_path_prefix_.
void nest::IOManager::get_status(DictionaryDatum &) override
References nest::names::data_path, data_path_, nest::names::data_prefix, data_prefix_, nest::names::overwrite_files, overwrite_files_, nest::names::recording_backends, recording_backends_, nest::names::stimulation_backends, stimulation_backends_.
void nest::IOManager::set_recording_backend_status(std::string, const DictionaryDatum &)
References nest::names::d, recording_backends_.
Referenced by nest::set_model_defaults.
DictionaryDatum nest::IOManager::get_recording_backend_status(std::string)
References nest::names::element_type, recording_backends_.
Referenced by nest::get_model_defaults.
const std::string & nest::IOManager::get_data_prefix() const
The prefix for files written by devices.
The prefix must not contain any part of a path. get_data_dir(), overwrite_files()
Referenced by nest::RecordingBackendSIONlib::build_filename_, nest::RecordingBackendASCII::DeviceData::compute_filename_, nest::RecordingBackendMPI::get_port, nest::StimulationBackendMPI::get_port.
const std::string & nest::IOManager::get_data_path() const
The path for files written by devices.
It may be the empty string (use current directory). get_data_prefix(), overwrite_files()
References data_path_.
Referenced by nest::RecordingBackendSIONlib::build_filename_, nest::RecordingBackendASCII::DeviceData::compute_filename_, nest::RecordingBackendMPI::get_port, nest::StimulationBackendMPI::get_port.
bool nest::IOManager::overwrite_files() const
Indicate if existing data files should be overwritten.
true if existing data files should be overwritten by devices. Default: false.
void nest::IOManager::post_run_hook()
Clean up in all registered recording backends after a single call to run by calling the backends' post_run_hook() functions.
References recording_backends_, stimulation_backends_.
Referenced by nest::SimulationManager::run.
void nest::IOManager::pre_run_hook()
References recording_backends_, stimulation_backends_.
Referenced by nest::SimulationManager::run.
void nest::IOManager::post_step_hook()
Clean up in all registered recording backends after a single simulation step by calling the backends' post_step_hook() functions.
References recording_backends_.
Referenced by nest::SimulationManager::update_.
void nest::IOManager::cleanup() override
Finalize all registered recording backends after a call to SimulationManager::simulate() or SimulationManager::cleanup() by calling the backends' finalize() functions.
References recording_backends_, stimulation_backends_.
void nest::IOManager::prepare() override
References recording_backends_, stimulation_backends_.
void nest::IOManager::register_recording_backend(Name)
References recording_backends_.
void nest::IOManager::register_stimulation_backend(const Name)
References stimulation_backends_.
bool nest::IOManager::is_valid_recording_backend(const Name) const
References recording_backends_.
bool nest::IOManager::is_valid_stimulation_backend(const Name) const
References stimulation_backends_.
void nest::IOManager::write(const Name backend_name, const RecordingDevice &device, const Event &event, const std::vector< double > &double_values, const std::vector< long > &long_values)
Send device data to a given recording backend.
This function is called from a RecordingDevice device when it wants to write data to a given recording backend, identified by its backend_name. The function takes an Event event from which some fundamental data is taken and additionally vectors of double_values and long_values that have to be written. The data vectors may be empty, if no additional data has to be written. backend_name the name of the RecordingBackend to write to device a reference to the RecordingDevice that wants to write event the Event to be written double_values a vector of doubles to be written long_values a vector of longs to be written
References recording_backends_.
Referenced by nest::RecordingDevice::write.
void nest::IOManager::enroll_recorder(const Name, const RecordingDevice &, const DictionaryDatum &)
References nest::names::params, recording_backends_.
Referenced by nest::RecordingDevice::set_initialized_, nest::RecordingDevice::set_status.
void nest::IOManager::enroll_stimulator(const Name, StimulationDevice &, const DictionaryDatum &)
References nest::names::params.
Referenced by nest::StimulationDevice::set_initialized_, nest::StimulationDevice::set_status.
void nest::IOManager::set_recording_value_names(const Name backend_name, const RecordingDevice &device, const std::vector< Name > &double_value_names, const std::vector< Name > &long_value_names)
References recording_backends_.
Referenced by nest::RecordingDevice::pre_run_hook.
void nest::IOManager::check_recording_backend_device_status(const Name, const DictionaryDatum &)
References nest::names::params, recording_backends_.
Referenced by nest::RecordingDevice::set_status.
void nest::IOManager::get_recording_backend_device_defaults(const Name, DictionaryDatum &)
References nest::names::params, recording_backends_.
Referenced by nest::RecordingDevice::get_status.
void nest::IOManager::get_recording_backend_device_status(const Name, const RecordingDevice &, DictionaryDatum &)
References nest::names::d, recording_backends_.
Referenced by nest::RecordingDevice::get_status.
void nest::IOManager::set_data_path_prefix_(const DictionaryDatum &)
References nest::names::data_path, data_path_, nest::names::data_prefix, data_prefix_, LOG, nest::M_ERROR.
Referenced by initialize, set_status.