nest::ConnectionManager
ConnectionType
friend class SimulationManager
Stopwatch nest::ConnectionManager::sw_construction_connect
Referenced by nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute.
std::vector< std::vector< ConnectorBase* > > nest::ConnectionManager::connections_
A structure to hold the Connector objects which in turn hold the connection information.
Corresponds to a three dimensional structure: threads|synapses|connections
Referenced by get_num_connections_, get_target_node_id, send, set_source_has_more_targets.
SourceTable nest::ConnectionManager::source_table_
A structure to hold the node IDs of presynaptic neurons during postsynaptic connection creation, before the connection information has been transferred to the presynaptic side.
Internally arranged in a 3d structure: threads|synapses|node IDs
Referenced by clean_source_table, clear_compressed_spike_data_map, clear_source_table, get_next_target_data, get_source_node_id, is_source_table_cleared, no_targets_to_process, reject_last_target_data, reset_source_table_entry_point, restore_source_table_entry_point, restructure_connection_tables, save_source_table_entry_point.
std::vector< std::vector< std::vector< SpikeData > > > nest::ConnectionManager::compressed_spike_data_
A structure to hold "unpacked" spikes on the postsynaptic side if spike compression is enabled.
Internally arranged in a 3d structure: synapses|sources|spike data
Referenced by get_compressed_spike_data.
std::vector< std::vector< std::vector< size_t > > > nest::ConnectionManager::secondary_recv_buffer_pos_
Stores absolute position in receive buffer of secondary events.
structure: threads|synapses|position
Referenced by get_secondary_recv_buffer_position.
std::map< index, size_t > nest::ConnectionManager::buffer_pos_of_source_node_id_syn_id_
TargetTable nest::ConnectionManager::target_table_
A structure to hold the information about targets for each neuron on the presynaptic side.
Internally arranged in a 3d structure: threads|localnodes|targets
Referenced by add_target, get_remote_targets_of_local_node, get_secondary_send_buffer_positions, prepare_target_table, restructure_connection_tables.
TargetTableDevices nest::ConnectionManager::target_table_devices_
Referenced by get_device_connected, resize_target_table_devices_to_number_of_neurons, resize_target_table_devices_to_number_of_synapse_types, send_from_device, send_to_devices.
std::vector< DelayChecker > nest::ConnectionManager::delay_checkers_
std::vector< std::vector< size_t > > nest::ConnectionManager::num_connections_
A structure to count the number of synapses of a specific type.
Arranged in a 2d structure: threads|synapsetypes.
DictionaryDatum nest::ConnectionManager::connruledict_
Dictionary for connection rules.
Referenced by register_conn_builder, valid_connection_rule.
std::vector< GenericConnBuilderFactory* > nest::ConnectionManager::connbuilder_factories_
ConnBuilder factories, indexed by connruledict_ elements.
Referenced by register_conn_builder.
delay nest::ConnectionManager::min_delay_
Value of the smallest delay in the network.
Referenced by get_min_delay.
delay nest::ConnectionManager::max_delay_
Value of the largest delay in the network in steps.
Referenced by get_max_delay.
bool nest::ConnectionManager::keep_source_table_
Whether to keep source table after connection setup is complete.
Referenced by clean_source_table, clear_source_table, get_keep_source_table.
bool nest::ConnectionManager::connections_have_changed_
True if new connections have been created since startup or last call to simulate.
Referenced by connections_have_changed.
bool nest::ConnectionManager::get_connections_has_been_called_
true if GetConnections has been called.
bool nest::ConnectionManager::sort_connections_by_source_
Whether to sort connections by source node ID.
Referenced by get_sort_connections_by_source.
bool nest::ConnectionManager::use_compressed_spikes_
Whether to use spike compression; if a neuron has targets on multiple threads of a process, this switch makes sure that only a single packet is sent to the process instead of one packet per target thread; requires sort_connections_by_source_ = true; for more details see the discussion and sketch in https://github.com/nest/nest-simulator/pull/1338.
Referenced by use_compressed_spikes.
bool nest::ConnectionManager::has_primary_connections_
Whether primary connections (spikes) exist.
Referenced by has_primary_connections.
PerThreadBoolIndicator nest::ConnectionManager::check_primary_connections_
Check for primary connections (spikes) on each thread.
bool nest::ConnectionManager::secondary_connections_exist_
Whether secondary connections (e.g., gap junctions) exist.
Referenced by secondary_connections_exist.
PerThreadBoolIndicator nest::ConnectionManager::check_secondary_connections_
Check for secondary connections (e.g., gap junctions) on each thread.
double nest::ConnectionManager::stdp_eps_
Maximum distance between (double) spike times in STDP that is still considered 0.
See issue #894
Referenced by get_stdp_eps.
nest::ConnectionManager::ConnectionManager()
nest::ConnectionManager::~ConnectionManager() override
void nest::ConnectionManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::vp_manager.
void nest::ConnectionManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
void nest::ConnectionManager::change_number_of_threads() override
Change the number of threads.
Many data structures within the different managers depend on the number of threads. This function is called on each manager upon a change of that number and allows the manager to re-allocate data structures accordingly.
void nest::ConnectionManager::set_status(const DictionaryDatum &) override
References nest::names::keep_source_table, nest::kernel, nest::names::max_delay, nest::names::min_delay, nest::names::sort_connections_by_source, nest::names::use_compressed_spikes.
void nest::ConnectionManager::get_status(DictionaryDatum &) override
References nest::names::connection_rules, nest::names::keep_source_table, nest::names::max_delay, nest::names::min_delay, nest::names::num_connections, nest::names::sort_connections_by_source, nest::names::time_construction_connect, nest::names::use_compressed_spikes.
bool nest::ConnectionManager::valid_connection_rule(std::string)
References connruledict_.
void nest::ConnectionManager::compute_target_data_buffer_size()
References nest::MPIManager::communicate, nest::MPIManager::get_num_processes, nest::VPManager::get_num_threads, nest::MPIManager::get_rank, nest::kernel, nest::KernelManager::mpi_manager, nest::MPIManager::set_buffer_size_target_data, nest::KernelManager::vp_manager.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::compute_compressed_secondary_recv_buffer_positions(const thread tid)
References nest::MPIManager::get_process_id_of_node_id, nest::MPIManager::get_recv_displacement_secondary_events_in_int, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::collect_compressed_spike_data(const thread tid)
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::clear_compressed_spike_data_map(const thread tid)
References nest::SourceTable::clear_compressed_spike_data_map, source_table_.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::register_conn_builder(const std::string &name)
Add a connectivity rule, i.e.
the respective ConnBuilderFactory.
References connbuilder_factories_, connruledict_.
Referenced by nest::NestModule::init.
nest::ConnBuilder * nest::ConnectionManager::get_conn_builder(const std::string &name, NodeCollectionPTR sources, NodeCollectionPTR targets, const DictionaryDatum &conn_spec, const std::vector< DictionaryDatum > &syn_specs)
Referenced by nest::SPManager::disconnect.
void nest::ConnectionManager::connect(NodeCollectionPTR, NodeCollectionPTR, const DictionaryDatum &, const std::vector< DictionaryDatum > &)
Create connections.
References ALL_ENTRIES_ACCESSED, nest::ConnBuilder::connect, nest::names::rule.
Referenced by nest::connect, nest::ConnectionCreator::connect_to_target_, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_, nest::ConnBuilder::single_connect_.
void nest::ConnectionManager::connect(TokenArray, TokenArray, const DictionaryDatum &)
References nest::NodeManager::get_node_or_proxy, nest::ModelManager::get_synapse_model_id, getValue< std::string >, nest::kernel, nest::names::model, nest::KernelManager::model_manager, nest::KernelManager::node_manager.
void nest::ConnectionManager::connect(const index snode_id, Node *target, thread target_thread, const synindex syn_id, const DictionaryDatum &params, const double delay=numerics::nan, const double weight=numerics::nan)
Connect two nodes.
The source node is defined by its global ID. The target node is defined by the node. The connection is established on the thread/process that owns the target node. The parameters delay and weight have the default value numerics::nan. numerics::nan is a special value, which describes double values that are not a number. If delay or weight is omitted in a connect call, numerics::nan indicates this and weight/delay are set only, if they are valid. snode_id node ID of the sending Node. target Pointer to target Node. target_thread Thread that hosts the target node. syn_id The synapse model to use. params Parameter dictionary to configure the synapse. delay Delay of the connection (in ms). weight Weight of the connection.
References nest::ModelManager::assert_valid_syn_id, nest::NodeManager::get_node_or_proxy, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::node_manager.
bool nest::ConnectionManager::connect(const index snode_id, const index target, const DictionaryDatum &params, const synindex syn_id)
Connect two nodes.
The source and target nodes are defined by their global ID. The connection is established on the thread/process that owns the target node. snode_id node ID of the sending Node. target node ID of the target Node. params Parameter dictionary to configure the synapse. syn_id The synapse model to use.
References nest::ModelManager::assert_valid_syn_id, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::node_manager, nest::KernelManager::vp_manager.
void nest::ConnectionManager::connect_arrays(long *sources, long *targets, double *weights, double *delays, std::vector< std::string > &p_keys, double *p_values, size_t n, std::string syn_model)
References ALL_ENTRIES_ACCESSED, nest::connect, nest::ModelManager::get_connector_defaults, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_num_threads, nest::ModelManager::get_synapse_model_id, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::model_manager, numerics::nan, nest::KernelManager::node_manager, Name::toString, nest::KernelManager::vp_manager.
Referenced by nest::connect_arrays.
nest::index nest::ConnectionManager::find_connection(const thread tid, const synindex syn_id, const index snode_id, const index tnode_id)
void nest::ConnectionManager::disconnect(const thread tid, const synindex syn_id, const index snode_id, const index tnode_id)
References nest::invalid_synindex.
Referenced by nest::SPManager::delete_synapse, nest::SPManager::disconnect.
nest::ConnectionManager::ConnectionType nest::ConnectionManager::connection_required(Node *&source, Node *&target, thread tid)
Check whether a connection between the given source and target nodes can be established on the given thread with id tid.
The type of connection as ConnectionType if the connection should be made, ConnectionType::NO_CONNECTION otherwise.
References nest::NodeManager::get_node_or_proxy, nest::VPManager::is_local_vp, nest::kernel, nest::VPManager::node_id_to_vp, nest::KernelManager::node_manager, nest::KernelManager::vp_manager, nest::VPManager::vp_to_thread.
DictionaryDatum nest::ConnectionManager::get_synapse_status(const index source_node_id, const index target_node_id, const thread tid, const synindex syn_id, const index lcid) const
References nest::ModelManager::assert_valid_syn_id, nest::NodeManager::get_node_or_proxy, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::node_manager, nest::names::port, nest::names::source, nest::names::synapse_id, nest::names::synapse_model, nest::names::target_thread.
Referenced by nest::Layer< D >::dump_connections, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::get_connection_status.
void nest::ConnectionManager::set_synapse_status(const index source_node_id, const index target_node_id, const thread tid, const synindex syn_id, const index lcid, const DictionaryDatum &dict)
References nest::ModelManager::assert_valid_syn_id, nest::ModelManager::get_connection_model, nest::NodeManager::get_node_or_proxy, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::node_manager.
Referenced by nest::NestModule::SetStatus_aaFunction::execute, nest::set_connection_status.
ArrayDatum nest::ConnectionManager::get_connections(const DictionaryDatum &params)
Return connections between pairs of neurons.
The params dictionary can have the following entries: 'source' a token array with node IDs of source neurons. 'target' a token array with node IDs of target neuron. If either of these does not exist, all neuron are used for the respective entry. 'synapse_model' name of the synapse model, or all synapse models are searched. 'synapse_label' label (long) of the synapse, or all synapses are searched. The function then iterates all entries in source and collects the connection IDs to all neurons in target.
References Token::empty, nest::get_connections, nest::ModelManager::get_num_connection_models, nest::ModelManager::get_synapse_model_id, nest::VPManager::get_thread_id, getValue< std::string >, nest::kernel, Name::lookup, nest::KernelManager::model_manager, nest::KernelManager::simulation_manager, nest::names::source, nest::names::synapse_label, nest::names::synapse_model, nest::names::target, nest::UNLABELED_CONNECTION, nest::SimulationManager::update_connection_infrastructure, nest::KernelManager::vp_manager.
Referenced by nest::Layer< D >::dump_connections, nest::get_connections.
void nest::ConnectionManager::get_connections(std::deque< ConnectionID > &connectome, NodeCollectionPTR source, NodeCollectionPTR target, synindex syn_id, long synapse_label) const
References extend_connectome, nest::ConnectorBase::get_connection, nest::ConnectorBase::get_connection_with_specified_targets, nest::VPManager::get_thread_id, nest::kernel, nest::ConnectorBase::size, nest::KernelManager::vp_manager.
size_t nest::ConnectionManager::get_num_connections() const
Returns the number of connections in the network.
Referenced by nest::ModelManager::get_connector_defaults.
size_t nest::ConnectionManager::get_num_connections(const synindex syn_id) const
Returns the number of connections of this synapse type.
void nest::ConnectionManager::get_sources(const std::vector< index > &targets, const index syn_id, std::vector< std::vector< index > > &sources)
References nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::SPManager::delete_synapses_from_post.
void nest::ConnectionManager::get_targets(const std::vector< index > &sources, const index syn_id, const std::string &post_synaptic_element, std::vector< std::vector< index > > &targets)
References nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::SPManager::delete_synapses_from_pre.
const std::vector< Target > & nest::ConnectionManager::get_remote_targets_of_local_node(const thread tid, const index lid) const
References nest::TargetTable::get_targets, target_table_.
Referenced by nest::EventDeliveryManager::send_off_grid_remote, nest::EventDeliveryManager::send_remote.
index nest::ConnectionManager::get_target_node_id(const thread tid, const synindex syn_id, const index lcid) const
References connections_.
bool nest::ConnectionManager::get_device_connected(thread tid, index lcid) const
References nest::TargetTableDevices::is_device_connected, target_table_devices_.
Referenced by nest::StimulationBackendMPI::prepare.
void nest::ConnectionManager::trigger_update_weight(const long vt_node_id, const std::vector< spikecounter > &dopa_spikes, const double t_trig)
Triggered by volume transmitter in update.
Triggeres updates for all connectors of dopamine synapses that are registered with the volume transmitter with node_id vt_node_id.
References nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::volume_transmitter::update.
delay nest::ConnectionManager::get_min_delay() const
Return minimal connection delay, which is precomputed by update_delay_extrema_().
References min_delay_.
Referenced by nest::SimulationManager::advance_time_, nest::DelayChecker::assert_two_valid_delays_steps, nest::DelayChecker::assert_valid_delay_ms, nest::correlomatrix_detector::handle, nest::correlospinmatrix_detector::handle, nest::rate_neuron_ipn< TNonlinearities >::init_buffers_, nest::rate_neuron_opn< TNonlinearities >::init_buffers_, nest::rate_transformer_node< TNonlinearities >::init_buffers_, nest::EventDeliveryManager::init_moduli, nest::SimulationManager::prepare, nest::RingBuffer::resize, nest::MultRBuffer::resize, nest::ListRingBuffer::resize, nest::MultiChannelInputBuffer< num_channels >::resize, nest::step_rate_generator::update, nest::SimulationManager::update_, nest::rate_neuron_ipn< TNonlinearities >::update_, nest::rate_neuron_opn< TNonlinearities >::update_, nest::rate_transformer_node< TNonlinearities >::update_, nest::EventDeliveryManager::update_moduli.
delay nest::ConnectionManager::get_max_delay() const
Return maximal connection delay, which is precomputed by update_delay_extrema_().
References max_delay_.
Referenced by nest::DelayChecker::assert_two_valid_delays_steps, nest::DelayChecker::assert_valid_delay_ms, nest::ClopathArchivingNode::init_clopath_buffers, nest::EventDeliveryManager::init_moduli, nest::RingBuffer::resize, nest::MultRBuffer::resize, nest::ListRingBuffer::resize, nest::MultiChannelInputBuffer< num_channels >::resize, nest::EventDeliveryManager::update_moduli.
bool nest::ConnectionManager::get_user_set_delay_extrema() const
void nest::ConnectionManager::send(const thread tid, const synindex syn_id, const index lcid, const std::vector< ConnectorModel * > &cm, Event &e)
References connections_.
Referenced by nest::EventDeliveryManager::deliver_events_.
void nest::ConnectionManager::send_to_devices(const thread tid, const index source_node_id, Event &e)
Send event e to all device targets of source source_node_id.
References nest::kernel, nest::TargetTableDevices::send_to_device, target_table_devices_.
Referenced by nest::EventDeliveryManager::send, nest::EventDeliveryManager::send_secondary.
void nest::ConnectionManager::send_to_devices(const thread tid, const index source_node_id, SecondaryEvent &e)
References nest::kernel, nest::TargetTableDevices::send_to_device, target_table_devices_.
void nest::ConnectionManager::send_from_device(const thread tid, const index ldid, Event &e)
Send event e to all targets of source device ldid (local device id)
References nest::kernel, nest::TargetTableDevices::send_from_device, target_table_devices_.
Referenced by nest::EventDeliveryManager::send_local_.
void nest::ConnectionManager::send_local(thread t, Node &source, Event &e)
Send event e to all targets of node source on thread t.
void nest::ConnectionManager::calibrate(const TimeConverter &)
Resize the structures for the Connector objects if necessary.
This function should be called after number of threads, min_delay, max_delay, and time representation have been changed in the scheduler. The TimeConverter is used to convert times from the old to the new representation. It is also forwarding the calibration request to all ConnectorModel objects.
References nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::SimulationManager::set_status.
nest::DelayChecker & nest::ConnectionManager::get_delay_checker()
Returns the delay checker for the current thread.
References nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection, nest::GenericConnectorModel< ConnectionT >::set_status, nest::cont_delay_synapse< targetidentifierT >::set_status, nest::Connection< targetidentifierT >::set_status, nest::GenericConnectorModel< ConnectionT >::used_default_delay.
void nest::ConnectionManager::clean_source_table(const thread tid)
Removes processed entries from source table.
References nest::SourceTable::clean, keep_source_table_, source_table_.
Referenced by nest::EventDeliveryManager::gather_target_data.
void nest::ConnectionManager::clear_source_table(const thread tid)
Clears all entries in source table.
References nest::SourceTable::clear, keep_source_table_, source_table_.
Referenced by nest::EventDeliveryManager::gather_target_data.
bool nest::ConnectionManager::get_keep_source_table() const
Returns true if source table is kept after building network.
References keep_source_table_.
bool nest::ConnectionManager::is_source_table_cleared() const
Returns true if source table was cleared.
References nest::SourceTable::is_cleared, source_table_.
void nest::ConnectionManager::prepare_target_table(const thread tid)
References nest::TargetTable::prepare, target_table_.
Referenced by nest::EventDeliveryManager::gather_target_data.
void nest::ConnectionManager::resize_target_table_devices_to_number_of_neurons()
References nest::TargetTableDevices::resize_to_number_of_neurons, target_table_devices_.
Referenced by nest::NodeManager::add_node.
void nest::ConnectionManager::resize_target_table_devices_to_number_of_synapse_types()
References nest::TargetTableDevices::resize_to_number_of_synapse_types, target_table_devices_.
Referenced by nest::NodeManager::add_node.
bool nest::ConnectionManager::get_next_target_data(const thread tid, const thread rank_start, const thread rank_end, thread &target_rank, TargetData &next_target_data)
References nest::SourceTable::get_next_target_data, source_table_.
Referenced by nest::EventDeliveryManager::collocate_target_data_buffers_.
void nest::ConnectionManager::reject_last_target_data(const thread tid)
References nest::SourceTable::reject_last_target_data, source_table_.
Referenced by nest::EventDeliveryManager::collocate_target_data_buffers_.
void nest::ConnectionManager::save_source_table_entry_point(const thread tid)
References nest::SourceTable::save_entry_point, source_table_.
Referenced by nest::EventDeliveryManager::collocate_target_data_buffers_, nest::EventDeliveryManager::gather_target_data.
void nest::ConnectionManager::reset_source_table_entry_point(const thread tid)
References nest::SourceTable::reset_entry_point, source_table_.
Referenced by nest::EventDeliveryManager::gather_target_data.
void nest::ConnectionManager::restore_source_table_entry_point(const thread tid)
References nest::SourceTable::restore_entry_point, source_table_.
Referenced by nest::EventDeliveryManager::gather_target_data.
void nest::ConnectionManager::add_target(const thread tid, const thread target_rank, const TargetData &target_data)
References nest::TargetTable::add_target, target_table_.
Referenced by nest::EventDeliveryManager::distribute_target_data_buffers_.
bool nest::ConnectionManager::get_sort_connections_by_source() const
Return sort_connections_by_source_, which indicates whether connections_ and source_table_ should be sorted according to source node ID.
References sort_connections_by_source_.
bool nest::ConnectionManager::use_compressed_spikes() const
References use_compressed_spikes_.
Referenced by nest::EventDeliveryManager::deliver_events_.
void nest::ConnectionManager::sort_connections(const thread tid)
Sorts connections in the presynaptic infrastructure by increasing source node ID.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::remove_disabled_connections(const thread tid)
Removes disabled connections (of structural plasticity)
bool nest::ConnectionManager::connections_have_changed() const
Returns true if connection information needs to be communicated.
False otherwise.
References connections_have_changed_.
void nest::ConnectionManager::set_connections_have_changed()
Sets flag indicating whether connection information needs to be communicated to true.
References nest::kernel, LOG, nest::M_WARNING.
Referenced by nest::connect_layers, nest::SPManager::disconnect, nest::SPManager::update_structural_plasticity.
void nest::ConnectionManager::unset_connections_have_changed()
Sets flag indicating whether connection information needs to be communicated to false.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::restructure_connection_tables(const thread tid)
Deletes TargetTable and resets processed flags of SourceTable.
This function must be called if connections are created after connections have been communicated previously. It basically restores the connection infrastructure to a state where all information only exists on the postsynaptic side.
References nest::TargetTable::clear, nest::SourceTable::is_cleared, nest::SourceTable::reset_processed_flags, source_table_, target_table_.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::set_source_has_more_targets(const thread tid, const synindex syn_id, const index lcid, const bool more_targets)
References connections_.
Referenced by nest::SourceTable::get_next_target_data.
void nest::ConnectionManager::no_targets_to_process(const thread tid)
References nest::SourceTable::no_targets_to_process, source_table_.
Referenced by nest::EventDeliveryManager::collocate_target_data_buffers_.
const std::vector< size_t > & nest::ConnectionManager::get_secondary_send_buffer_positions(const thread tid, const index lid, const synindex syn_id) const
References nest::TargetTable::get_secondary_send_buffer_positions, target_table_.
Referenced by nest::EventDeliveryManager::send_secondary.
size_t nest::ConnectionManager::get_secondary_recv_buffer_position(const thread tid, const synindex syn_id, const index lcid) const
Returns read position in MPI receive buffer for secondary connections.
References secondary_recv_buffer_pos_.
Referenced by nest::SourceTable::populate_target_data_fields_.
bool nest::ConnectionManager::deliver_secondary_events(const thread tid, const bool called_from_wfr_update, std::vector< unsigned int > &recv_buffer)
References nest::ModelManager::get_connection_models, nest::MPIManager::get_done_marker_position_in_secondary_events_recv_buffer, nest::MPIManager::get_num_processes, nest::ModelManager::get_secondary_event_prototype, nest::SimulationManager::get_slice_origin, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::mpi_manager, nest::Event::set_stamp, nest::KernelManager::simulation_manager, nest::SecondaryEvent::size.
Referenced by nest::EventDeliveryManager::deliver_secondary_events.
void nest::ConnectionManager::compress_secondary_send_buffer_pos(const thread tid)
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::resize_connections()
References nest::VPManager::assert_single_threaded, nest::ModelManager::get_num_connection_models, nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::vp_manager.
Referenced by nest::ModelManager::copy_connection_model_, nest::ModelManager::register_connection_model_.
void nest::ConnectionManager::sync_has_primary_connections()
References nest::MPIManager::any_true, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::ConnectionManager::check_secondary_connections_exist()
References nest::MPIManager::any_true, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by nest::SimulationManager::update_connection_infrastructure.
bool nest::ConnectionManager::has_primary_connections() const
References has_primary_connections_.
bool nest::ConnectionManager::secondary_connections_exist() const
References secondary_connections_exist_.
index nest::ConnectionManager::get_source_node_id(const thread tid, const synindex syn_id, const index lcid)
References nest::SourceTable::get_node_id, source_table_.
Referenced by nest::Event::retrieve_sender_node_id_from_source_table.
double nest::ConnectionManager::get_stdp_eps() const
References stdp_eps_.
Referenced by nest::ArchivingNode::get_history.
void nest::ConnectionManager::set_stdp_eps(const double stdp_eps)
References nest::Time::get_resolution, LOG, nest::M_INFO.
Referenced by nest::NestModule::SetStdpEps_dFunction::execute.
const std::vector< SpikeData > & nest::ConnectionManager::get_compressed_spike_data(const synindex syn_id, const index idx)
References compressed_spike_data_.
Referenced by nest::EventDeliveryManager::deliver_events_.
size_t nest::ConnectionManager::get_num_target_data(const thread tid) const
size_t nest::ConnectionManager::get_num_connections_(const thread tid, const synindex syn_id) const
References connections_.
void nest::ConnectionManager::get_source_node_ids_(const thread tid, const synindex syn_id, const index tnode_id, std::vector< index > &sources)
void nest::ConnectionManager::split_to_neuron_device_vectors_(const thread tid, NodeCollectionPTR nodecollection, std::vector< index > &neuron_node_ids, std::vector< index > &device_node_ids) const
Splits a TokenArray of node IDs to two vectors containing node IDs of neurons and node IDs of devices.
References nest::NodeManager::get_node_or_proxy, nest::kernel, nest::KernelManager::node_manager.
void nest::ConnectionManager::update_delay_extrema_()
Update delay extrema to current values.
Static since it only operates in static variables. This allows it to be called from const-method get_status() as well.
References nest::MPIManager::communicate, nest::MPIManager::get_rank, nest::Time::get_resolution, nest::Time::get_steps, nest::kernel, nest::KernelManager::mpi_manager, nest::Time::pos_inf.
Referenced by nest::SimulationManager::prepare.
const nest::Time nest::ConnectionManager::get_min_delay_time_() const
This method queries and finds the minimum delay of all local connections.
References nest::Time::pos_inf.
const nest::Time nest::ConnectionManager::get_max_delay_time_() const
This method queries and finds the maximum delay of all local connections.
References nest::Time::get_resolution.
void nest::ConnectionManager::delete_connections_()
Deletes all connections.
void nest::ConnectionManager::connect_(Node &source, Node &target, const index s_node_id, const thread tid, const synindex syn_id, const DictionaryDatum &params, const double delay=numerics::nan, const double weight=numerics::nan)
connect_ is used to establish a connection between a sender and receiving node which both have proxies.
The parameters delay and weight have the default value numerics::nan. numerics::nan is a special value, which describes double values that are not a number. If delay or weight is omitted in an connect call, numerics::nan indicates this and weight/delay are set only, if they are valid. source A reference to the sending Node. target A reference to the receiving Node. s_node_id The node ID of the sending Node. tid The thread of the target node. syn_id The synapse model to use. params The parameters for the connection. delay The delay of the connection (optional). weight The weight of the connection (optional).
References nest::ConnectorModel::add_connection, nest::ModelManager::connector_requires_clopath_archiving, nest::ModelManager::connector_requires_urbanczik_archiving, nest::ModelManager::get_connection_model, nest::ConnectorModel::is_primary, nest::kernel, nest::KernelManager::model_manager.
void nest::ConnectionManager::connect_to_device_(Node &source, Node &target, const index s_node_id, const thread tid, const synindex syn_id, const DictionaryDatum &params, const double delay=NAN, const double weight=NAN)
connect_to_device_ is used to establish a connection between a sender and receiving node if the sender has proxies, and the receiver does not.
The parameters delay and weight have the default value NAN. NAN is a special value in cmath, which describes double values that are not a number. If delay or weight is omitted in an connect call, NAN indicates this and weight/delay are set only, if they are valid. source A reference to the sending Node. target A reference to the receiving Node. s_node_id The node ID of the sending Node. tid The thread of the target node. syn_id The synapse model to use. params The parameters for the connection. delay The delay of the connection (optional). weight The weight of the connection (optional).
void nest::ConnectionManager::connect_from_device_(Node &source, Node &target, const thread tid, const synindex syn_id, const DictionaryDatum &params, const double delay=NAN, const double weight=NAN)
connect_from_device_ is used to establish a connection between a sender and receiving node if the sender does not have proxies.
The parameters delay and weight have the default value NAN. NAN is a special value in cmath, which describes double values that are not a number. If delay or weight is omitted in an connect call, NAN indicates this and weight/delay are set only, if they are valid. source A reference to the sending Node. target A reference to the receiving Node. s_node_id The node ID of the sending Node. tid The thread of the target node. syn_id The synapse model to use. params The parameters for the connection. delay The delay of the connection (optional). weight The weight of the connection (optional).
void nest::ConnectionManager::increase_connection_count(const thread tid, const synindex syn_id)
Increases the connection count.
References nest::MAX_LCID.