nest::Connection
constexpr ConnectionModelProperties nest::Connection< targetidentifierT >::properties
targetidentifierT nest::Connection< targetidentifierT >::target_
Referenced by nest::Connection< targetidentifierT >::get_rport, nest::Connection< targetidentifierT >::get_target.
SynIdDelay nest::Connection< targetidentifierT >::syn_id_delay_
syn_id (9 bit), delay (21 bit) in timesteps of this connection and more_targets and disabled flags (each 1 bit)
Referenced by nest::Connection< targetidentifierT >::disable, nest::Connection< targetidentifierT >::get_delay, nest::Connection< targetidentifierT >::get_delay_steps, nest::Connection< targetidentifierT >::get_syn_id, nest::Connection< targetidentifierT >::is_disabled, nest::Connection< targetidentifierT >::set_delay, nest::Connection< targetidentifierT >::set_delay_steps, nest::Connection< targetidentifierT >::set_source_has_more_targets, nest::Connection< targetidentifierT >::set_syn_id, nest::Connection< targetidentifierT >::source_has_more_targets.
nest::Connection< targetidentifierT >::Connection()
nest::Connection< targetidentifierT >::Connection(const Connection< targetidentifierT > &rhs)=default
Connection& nest::Connection< targetidentifierT >::operator=(const Connection< targetidentifierT > &rhs)=default
SecondaryEvent * nest::Connection< targetidentifierT >::get_secondary_event()
Get a pointer to an instance of a SecondaryEvent if this connection supports secondary events.
To prevent erronous calls of this function on primary connections, the base class implementation below just contains assert(false).
void nest::Connection< targetidentifierT >::get_status(DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::d, nest::names::delay.
void nest::Connection< targetidentifierT >::set_status(const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
Target and Rport cannot be changed after a connection has been created.
References nest::DelayChecker::assert_valid_delay_ms, nest::KernelManager::connection_manager, nest::names::d, nest::names::delay, nest::ConnectionManager::get_delay_checker, nest::kernel.
void nest::Connection< targetidentifierT >::check_synapse_params(const DictionaryDatum &d) const
Check syn_spec dictionary for parameters that are not allowed with the given connection.
Will issue warning or throw error if an illegal parameter is found. The method does nothing if no illegal parameter is found. Classes requiring checks need to override the function with their own implementation, as this base class implementation does not do anything.
void nest::Connection< targetidentifierT >::calibrate(const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
References nest::TimeConverter::from_old_steps, nest::Time::get_steps.
double nest::Connection< targetidentifierT >::get_delay() const
Return the delay of the connection in ms.
References nest::SynIdDelay::get_delay_ms, nest::Connection< targetidentifierT >::syn_id_delay_.
long nest::Connection< targetidentifierT >::get_delay_steps() const
Return the delay of the connection in steps.
References nest::SynIdDelay::delay, nest::Connection< targetidentifierT >::syn_id_delay_.
void nest::Connection< targetidentifierT >::set_delay(const double delay)
Set the delay of the connection.
References nest::SynIdDelay::set_delay_ms, nest::Connection< targetidentifierT >::syn_id_delay_.
void nest::Connection< targetidentifierT >::set_delay_steps(const long delay)
Set the delay of the connection in steps.
References nest::SynIdDelay::delay, nest::Connection< targetidentifierT >::syn_id_delay_.
void nest::Connection< targetidentifierT >::set_syn_id(synindex syn_id)
Set the synapse id of the connection.
References nest::SynIdDelay::syn_id, nest::Connection< targetidentifierT >::syn_id_delay_.
synindex nest::Connection< targetidentifierT >::get_syn_id() const
Get the synapse id of the connection.
References nest::SynIdDelay::syn_id, nest::Connection< targetidentifierT >::syn_id_delay_.
long nest::Connection< targetidentifierT >::get_label() const
References nest::UNLABELED_CONNECTION.
void nest::Connection< targetidentifierT >::trigger_update_weight(const thread, const std::vector< spikecounter > &, const double, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node* nest::Connection< targetidentifierT >::get_target(const thread tid) const
References nest::Connection< targetidentifierT >::target_.
rport nest::Connection< targetidentifierT >::get_rport() const
References nest::Connection< targetidentifierT >::target_.
void nest::Connection< targetidentifierT >::set_source_has_more_targets(const bool more_targets)
Sets a flag in the connection to signal that the following connection has the same source.
source_has_more_targets
References nest::SynIdDelay::set_source_has_more_targets, nest::Connection< targetidentifierT >::syn_id_delay_.
bool nest::Connection< targetidentifierT >::source_has_more_targets() const
Returns a flag denoting whether the connection has source subsequent targets.
set_source_has_more_targets
References nest::SynIdDelay::source_has_more_targets, nest::Connection< targetidentifierT >::syn_id_delay_.
void nest::Connection< targetidentifierT >::disable()
Disables the connection.
is_disabled
References nest::SynIdDelay::disable, nest::Connection< targetidentifierT >::syn_id_delay_.
bool nest::Connection< targetidentifierT >::is_disabled() const
Returns a flag denoting if the connection is disabled.
disable
References nest::SynIdDelay::is_disabled, nest::Connection< targetidentifierT >::syn_id_delay_.
void nest::Connection< targetidentifierT >::check_connection_(Node &dummy_target, Node &source, Node &target, const rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
s The source node r The target node receptor The ID of the requested receptor type the last spike produced by the presynaptic neuron (for STDP and maturing connections)
References nest::names::receptor_type, nest::names::source, nest::names::target.
Referenced by nest::bernoulli_synapse< targetidentifierT >::check_connection, nest::clopath_synapse< targetidentifierT >::check_connection, nest::cont_delay_synapse< targetidentifierT >::check_connection, nest::ht_synapse< targetidentifierT >::check_connection, nest::jonke_synapse< targetidentifierT >::check_connection, nest::quantal_stp_synapse< targetidentifierT >::check_connection, nest::static_synapse< targetidentifierT >::check_connection, nest::static_synapse_hom_w< targetidentifierT >::check_connection, nest::stdp_nn_pre_centered_synapse< targetidentifierT >::check_connection, nest::stdp_nn_restr_synapse< targetidentifierT >::check_connection, nest::stdp_nn_symm_synapse< targetidentifierT >::check_connection, nest::stdp_pl_synapse_hom< targetidentifierT >::check_connection, nest::stdp_synapse< targetidentifierT >::check_connection, nest::stdp_facetshw_synapse_hom< targetidentifierT >::check_connection, nest::stdp_synapse_hom< targetidentifierT >::check_connection, nest::stdp_triplet_synapse< targetidentifierT >::check_connection, nest::tsodyks2_synapse< targetidentifierT >::check_connection, nest::tsodyks_synapse< targetidentifierT >::check_connection, nest::tsodyks_synapse_hom< targetidentifierT >::check_connection, nest::urbanczik_synapse< targetidentifierT >::check_connection, nest::vogels_sprekeler_synapse< targetidentifierT >::check_connection, nest::stdp_dopamine_synapse< targetidentifierT >::check_connection.