nest::CommonPropertiesHomW
double nest::CommonPropertiesHomW::weight_
Referenced by get_status, get_weight, set_status.
nest::CommonPropertiesHomW::CommonPropertiesHomW()
Default constructor.
Sets all property values to defaults.
void nest::CommonPropertiesHomW::get_status(DictionaryDatum &d) const
Get all properties and put them into a dictionary.
References nest::names::d, nest::CommonSynapseProperties::get_status, nest::names::weight, weight_.
Referenced by nest::TsodyksHomCommonProperties::get_status.
double nest::CommonPropertiesHomW::get_weight() const
References weight_.
Referenced by nest::static_synapse_hom_w< targetidentifierT >::send, nest::tsodyks_synapse_hom< targetidentifierT >::send.
void nest::CommonPropertiesHomW::set_status(const DictionaryDatum &d, ConnectorModel &cm)
Set properties from the values given in dictionary.
References nest::names::d, nest::CommonSynapseProperties::set_status, nest::names::weight, weight_.
Referenced by nest::TsodyksHomCommonProperties::set_status.