nest::EventDeliveryManager
bool nest::EventDeliveryManager::off_grid_spiking_
indicates whether spikes are not constrained to the grid
Referenced by gather_spike_data, gather_spike_data_, get_off_grid_communication, get_status, initialize, set_off_grid_communication, set_status.
std::vector< delay > nest::EventDeliveryManager::moduli_
Table of pre-computed modulos.
This table is used to map time steps, given as offset from now, to ring-buffer bins. There are min_delay+max_delay bins in a ring buffer, and the moduli_ array is rotated by min_delay elements after each slice is completed. RingBuffer
Referenced by get_modulo, init_moduli, update_moduli.
std::vector< delay > nest::EventDeliveryManager::slice_moduli_
Table of pre-computed slice-based modulos.
This table is used to map time steps, give as offset from now, to slice-based ring-buffer bins. There are ceil(max_delay/min_delay) bins in a slice-based ring buffer, one per slice within max_delay. Since max_delay may not be a multiple of min_delay, we cannot simply rotate the table content after each slice, but have to recompute the table anew. SliceRingBuffer
Referenced by get_slice_modulo, init_moduli, update_moduli.
std::vector< std::vector< std::vector< std::vector< Target > > > > nest::EventDeliveryManager::emitted_spikes_register_
Register for node IDs of neurons that spiked.
This is a 4-dim structure. While spikes are written to the buffer they are immediately sorted by the thread that will later move the spikes to the MPI buffers. First dim: write threads (from node to register) Second dim: read threads (from register to MPI buffer) Third dim: lag Fourth dim: Target (will be converted in SpikeData)
Referenced by clean_spike_register_, finalize, gather_spike_data_, initialize, reset_spike_register_, resize_spike_register_, send_remote.
std::vector< std::vector< std::vector< std::vector< OffGridTarget > > > > nest::EventDeliveryManager::off_grid_emitted_spike_register_
Register for node IDs of precise neurons that spiked.
This is a 4-dim structure. While spikes are written to the buffer they are immediately sorted by the thread that will later move the spikes to the MPI buffers. First dim: write threads (from node to register) Second dim: read threads (from register to MPI buffer) Third dim: lag Fourth dim: OffGridTarget (will be converted in OffGridSpikeData)
Referenced by clean_spike_register_, finalize, gather_spike_data_, initialize, reset_spike_register_, resize_spike_register_, send_off_grid_remote.
std::vector< unsigned int > nest::EventDeliveryManager::send_buffer_secondary_events_
Buffer to collect the secondary events after serialization.
Referenced by configure_secondary_buffers, finalize, gather_secondary_events, send_secondary, write_done_marker_secondary_events_.
std::vector< unsigned int > nest::EventDeliveryManager::recv_buffer_secondary_events_
Referenced by configure_secondary_buffers, deliver_secondary_events, finalize, gather_secondary_events.
std::vector< unsigned long > nest::EventDeliveryManager::local_spike_counter_
Number of generated spike events (both off- and on-grid) during the last call to simulate.
Referenced by get_status, initialize, reset_counters, send.
std::vector< SpikeData > nest::EventDeliveryManager::send_buffer_spike_data_
Referenced by configure_spike_data_buffers, finalize, gather_spike_data, resize_send_recv_buffers_spike_data_.
std::vector< SpikeData > nest::EventDeliveryManager::recv_buffer_spike_data_
Referenced by finalize, gather_spike_data, resize_send_recv_buffers_spike_data_.
std::vector< OffGridSpikeData > nest::EventDeliveryManager::send_buffer_off_grid_spike_data_
Referenced by configure_spike_data_buffers, finalize, gather_spike_data, resize_send_recv_buffers_spike_data_.
std::vector< OffGridSpikeData > nest::EventDeliveryManager::recv_buffer_off_grid_spike_data_
Referenced by finalize, gather_spike_data, resize_send_recv_buffers_spike_data_.
std::vector< TargetData > nest::EventDeliveryManager::send_buffer_target_data_
Referenced by collocate_target_data_buffers_, gather_target_data, resize_send_recv_buffers_target_data.
std::vector< TargetData > nest::EventDeliveryManager::recv_buffer_target_data_
whether size of MPI buffer for communication of connections was changed
Referenced by gather_target_data, resize_send_recv_buffers_target_data.
bool nest::EventDeliveryManager::buffer_size_target_data_has_changed_
whether size of MPI buffer for communication of spikes was changed
Referenced by gather_target_data, initialize.
bool nest::EventDeliveryManager::buffer_size_spike_data_has_changed_
whether size of MPI buffer for communication of spikes can be decreased
Referenced by gather_spike_data_, initialize.
bool nest::EventDeliveryManager::decrease_buffer_size_spike_data_
Referenced by gather_spike_data_, initialize.
PerThreadBoolIndicator nest::EventDeliveryManager::gather_completed_checker_
Referenced by gather_spike_data_, gather_target_data, initialize.
nest::EventDeliveryManager::EventDeliveryManager()
nest::EventDeliveryManager::~EventDeliveryManager() override
void nest::EventDeliveryManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References buffer_size_spike_data_has_changed_, buffer_size_target_data_has_changed_, decrease_buffer_size_spike_data_, emitted_spikes_register_, gather_completed_checker_, nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, init_moduli, nest::PerThreadBoolIndicator::initialize, nest::kernel, local_spike_counter_, off_grid_emitted_spike_register_, off_grid_spiking_, reset_counters, reset_timers_for_dynamics, reset_timers_for_preparation, nest::KernelManager::vp_manager.
Referenced by change_number_of_threads.
void nest::EventDeliveryManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
References emitted_spikes_register_, off_grid_emitted_spike_register_, recv_buffer_off_grid_spike_data_, recv_buffer_secondary_events_, recv_buffer_spike_data_, send_buffer_off_grid_spike_data_, send_buffer_secondary_events_, send_buffer_spike_data_, boost::tuples::swap.
Referenced by change_number_of_threads.
void nest::EventDeliveryManager::change_number_of_threads() override
Change the number of threads.
Many data structures within the different managers depend on the number of threads. This function is called on each manager upon a change of that number and allows the manager to re-allocate data structures accordingly.
References finalize, initialize.
void nest::EventDeliveryManager::set_status(const DictionaryDatum &) override
References nest::names::off_grid_spiking, off_grid_spiking_.
void nest::EventDeliveryManager::get_status(DictionaryDatum &) override
References nest::names::local_spike_counter, local_spike_counter_, nest::names::off_grid_spiking, off_grid_spiking_.
void nest::EventDeliveryManager::send(Node &source, EventT &e, const long lag=0)
Standard routine for sending events.
This method decides if the event has to be delivered locally or globally. It exists to keep a clean and unitary interface for the event sending mechanism. Only specialization for SpikeEvent does remote sending. Specialized for DSSpikeEvent to avoid that these events are sent to remote processes. send_local()
References numerics::e, send_local_, nest::names::source.
Referenced by nest::iaf_psc_exp_ps::emit_instant_spike_, nest::iaf_psc_exp_ps_lossless::emit_instant_spike_, nest::iaf_psc_alpha_ps::emit_instant_spike_, nest::iaf_psc_delta_ps::emit_instant_spike_, nest::iaf_psc_exp_ps::emit_spike_, nest::iaf_psc_exp_ps_lossless::emit_spike_, nest::iaf_psc_delta_ps::emit_spike_, nest::iaf_psc_alpha_ps::emit_spike_, nest::iaf_chs_2007::update, nest::iaf_psc_exp::update, nest::glif_psc::update, nest::ac_generator::update, nest::amat2_psc_exp::update, nest::binary_neuron< TGainfunction >::update, nest::cm_default::update, nest::dc_generator::update, nest::gamma_sup_generator::update, nest::gif_psc_exp::update, nest::gif_psc_exp_multisynapse::update, nest::iaf_psc_alpha::update, nest::iaf_psc_alpha_multisynapse::update, nest::iaf_psc_delta::update, nest::iaf_psc_exp_htum::update, nest::iaf_psc_exp_multisynapse::update, nest::inhomogeneous_poisson_generator::update, nest::izhikevich::update, nest::mat2_psc_exp::update, nest::mip_generator::update, nest::multimeter::update, nest::noise_generator::update, nest::parrot_neuron::update, nest::parrot_neuron_ps::update, nest::poisson_generator::update, nest::poisson_generator_ps::update, nest::pp_psc_delta::update, nest::ppd_sup_generator::update, nest::pulsepacket_generator::update, nest::sinusoidal_poisson_generator::update, nest::spike_dilutor::update, nest::spike_generator::update, nest::spike_train_injector::update, nest::step_current_generator::update.
void nest::EventDeliveryManager::send_secondary(Node &source, SecondaryEvent &e)
Send a secondary event remote.
References nest::KernelManager::connection_manager, numerics::e, nest::ConnectionManager::get_secondary_send_buffer_positions, nest::VPManager::get_thread_id, nest::kernel, nest::VPManager::node_id_to_lid, nest::names::positions, send_buffer_secondary_events_, send_local_, nest::ConnectionManager::send_to_devices, nest::names::source, nest::KernelManager::vp_manager.
Referenced by nest::step_rate_generator::update, nest::rate_neuron_ipn< TNonlinearities >::update_, nest::rate_neuron_opn< TNonlinearities >::update_, nest::rate_transformer_node< TNonlinearities >::update_.
void nest::EventDeliveryManager::send_local(thread t, Node &source, Event &e)
Send event e to all targets of node source on thread t.
void nest::EventDeliveryManager::send_remote(thread tid, SpikeEvent &, const long lag=0)
Add node ID of event sender to the spike_register.
An event sent through this method will remain in the queue until the network time has advanced by min_delay_ steps. After this period the buffers are collocated and sent to the partner machines. Old documentation from network.h: Place an event in the global event queue. Add event to the queue to be delivered when it is due. At the delivery time, the target list of the sender is iterated and the event is delivered to all targets. The event is guaranteed to arrive at the receiver when all elements are updated and the system is in a synchronised (single threaded) state. send_to_targets()
References nest::KernelManager::connection_manager, numerics::e, emitted_spikes_register_, nest::VPManager::get_num_assigned_ranks_per_thread, nest::ConnectionManager::get_remote_targets_of_local_node, nest::kernel, nest::VPManager::node_id_to_lid, nest::names::targets, nest::KernelManager::vp_manager.
Referenced by send.
void nest::EventDeliveryManager::send_off_grid_remote(thread tid, SpikeEvent &e, const long lag=0)
Add node ID of event sender to the spike_register.
Store event offset with node ID. An event sent through this method will remain in the queue until the network time has advanced by min_delay_ steps. After this period the buffers are collocated and sent to the partner machines. Old documentation from network.h: Place an event in the global event queue. Add event to the queue to be delivered when it is due. At the delivery time, the target list of the sender is iterated and the event is delivered to all targets. The event is guaranteed to arrive at the receiver when all elements are updated and the system is in a synchronised (single threaded) state. send_to_targets()
References nest::KernelManager::connection_manager, numerics::e, nest::VPManager::get_num_assigned_ranks_per_thread, nest::ConnectionManager::get_remote_targets_of_local_node, nest::kernel, nest::VPManager::node_id_to_lid, off_grid_emitted_spike_register_, nest::names::targets, nest::KernelManager::vp_manager.
Referenced by send.
void nest::EventDeliveryManager::send_to_node(Event &e)
Send event e directly to its target node.
This should be used only where necessary, e.g. if a node wants to reply to a *RequestEvent immediately.
References numerics::e.
bool nest::EventDeliveryManager::get_off_grid_communication() const
return current communication style.
A result of true means off_grid, false means on_grid communication.
References off_grid_spiking_.
void nest::EventDeliveryManager::set_off_grid_communication(bool off_grid_spiking)
set communication style to off_grid (true) or on_grid
References nest::names::off_grid_spiking, off_grid_spiking_.
Referenced by nest::NodeManager::add_node, nest::spike_train_injector::pre_run_hook.
size_t nest::EventDeliveryManager::write_toggle() const
Return 0 for even, 1 for odd time slices.
This is useful for buffers that need to be written alternatingly by time slice. The value is given by get_slice_() % 2. read_toggle
References nest::SimulationManager::get_slice, nest::kernel, nest::KernelManager::simulation_manager.
Referenced by read_toggle.
size_t nest::EventDeliveryManager::read_toggle() const
Return 1 - write_toggle().
This is useful for buffers that need to be read alternatingly by slice. The value is given by 1-write_toggle(). write_toggle
References write_toggle.
delay nest::EventDeliveryManager::get_modulo(delay d)
Return (T+d) mod max_delay.
References nest::names::d, moduli_.
Referenced by nest::RingBuffer::get_index_, nest::MultRBuffer::get_index_, nest::ListRingBuffer::get_index_, nest::iaf_psc_alpha::handle, nest::iaf_psc_exp::handle, nest::iaf_psc_exp::update, nest::iaf_psc_alpha::update.
delay nest::EventDeliveryManager::get_slice_modulo(delay d)
Index to slice-based buffer.
Return ((T+d)/min_delay) % ceil(max_delay/min_delay).
References nest::names::d, slice_moduli_.
Referenced by nest::SliceRingBuffer::add_spike, nest::SliceRingBuffer::discard_events, nest::SliceRingBuffer::prepare_delivery.
void nest::EventDeliveryManager::configure_spike_data_buffers()
Resize spike_register and comm_buffer to correct dimensions.
Resizes also off_grid_*_buffer_. This is done by simulate() when called for the first time. The spike buffers cannot be reconfigured later, whence neither the number of local threads or the min_delay can change after simulate() has been called. ConnectorModel::check_delay() and Network::set_status() ensure this.
References configure_spike_register, nest::kernel, resize_send_recv_buffers_spike_data_, send_buffer_off_grid_spike_data_, send_buffer_spike_data_.
Referenced by nest::SimulationManager::prepare, nest::SimulationManager::set_status.
void nest::EventDeliveryManager::configure_spike_register()
References nest::VPManager::get_num_threads, nest::kernel, reset_spike_register_, resize_spike_register_, nest::KernelManager::vp_manager.
Referenced by configure_spike_data_buffers.
void nest::EventDeliveryManager::resize_send_recv_buffers_target_data()
References nest::kernel, recv_buffer_target_data_, send_buffer_target_data_.
Referenced by gather_target_data, nest::SimulationManager::update_connection_infrastructure.
void nest::EventDeliveryManager::configure_secondary_buffers()
References nest::kernel, recv_buffer_secondary_events_, send_buffer_secondary_events_.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::EventDeliveryManager::gather_spike_data(const thread tid)
Collocates spikes from register to MPI buffers, communicates via MPI and delivers events to targets.
References gather_spike_data_, off_grid_spiking_, recv_buffer_off_grid_spike_data_, recv_buffer_spike_data_, send_buffer_off_grid_spike_data_, send_buffer_spike_data_.
Referenced by nest::SimulationManager::update_.
void nest::EventDeliveryManager::gather_target_data(const thread tid)
Collocates presynaptic connection information, communicates via MPI and creates presynaptic connection infrastructure.
References nest::PerThreadBoolIndicator::all_false, nest::PerThreadBoolIndicator::all_true, nest::PerThreadBoolIndicator::any_false, buffer_size_target_data_has_changed_, nest::ConnectionManager::clean_source_table, nest::ConnectionManager::clear_source_table, collocate_target_data_buffers_, nest::MPIManager::communicate_target_data_Alltoall, nest::KernelManager::connection_manager, distribute_target_data_buffers_, gather_completed_checker_, nest::VPManager::get_assigned_ranks, nest::MPIManager::increase_buffer_size_target_data, nest::kernel, nest::KernelManager::mpi_manager, nest::ConnectionManager::prepare_target_table, recv_buffer_target_data_, nest::ConnectionManager::reset_source_table_entry_point, resize_send_recv_buffers_target_data, nest::ConnectionManager::restore_source_table_entry_point, nest::ConnectionManager::save_source_table_entry_point, send_buffer_target_data_, set_complete_marker_target_data_, nest::KernelManager::vp_manager.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::EventDeliveryManager::gather_secondary_target_data()
Collocates presynaptic connection information for secondary events (MPI buffer offsets), communicates via MPI and create presynaptic connection infrastructure for secondary events.
void nest::EventDeliveryManager::write_done_marker_secondary_events_(const bool done)
References nest::MPIManager::get_done_marker_position_in_secondary_events_send_buffer, nest::MPIManager::get_num_processes, nest::kernel, nest::KernelManager::mpi_manager, send_buffer_secondary_events_.
Referenced by gather_secondary_events.
void nest::EventDeliveryManager::gather_secondary_events(const bool done)
References nest::MPIManager::communicate_secondary_events_Alltoallv, nest::kernel, nest::KernelManager::mpi_manager, recv_buffer_secondary_events_, send_buffer_secondary_events_, write_done_marker_secondary_events_.
Referenced by nest::SimulationManager::update_.
bool nest::EventDeliveryManager::deliver_secondary_events(const thread tid, const bool called_from_wfr_update)
References nest::KernelManager::connection_manager, nest::ConnectionManager::deliver_secondary_events, nest::kernel, recv_buffer_secondary_events_.
Referenced by nest::SimulationManager::update_.
void nest::EventDeliveryManager::update_moduli()
Update table of fixed modulos, including slice-based.
This function is called after all nodes have been updated. We can compute the value of (T+d) mod max_delay without explicit reference to the network clock, because compute_moduli_ is called whenever the network clock advances. The various modulos for all available delays are stored in a lookup-table and this table is rotated once per time slice.
References nest::KernelManager::connection_manager, nest::names::d, nest::SimulationManager::get_clock, nest::ConnectionManager::get_max_delay, nest::ConnectionManager::get_min_delay, nest::Time::get_steps, nest::kernel, nest::names::max_delay, nest::names::min_delay, moduli_, nest::KernelManager::simulation_manager, slice_moduli_.
Referenced by nest::SimulationManager::advance_time_.
void nest::EventDeliveryManager::init_moduli()
Initialize modulo table.
TODO: can probably be private
References nest::KernelManager::connection_manager, nest::names::d, nest::SimulationManager::get_clock, nest::ConnectionManager::get_max_delay, nest::ConnectionManager::get_min_delay, nest::Time::get_steps, nest::kernel, nest::names::max_delay, nest::names::min_delay, moduli_, nest::KernelManager::simulation_manager, slice_moduli_.
Referenced by initialize, nest::SimulationManager::prepare.
void nest::EventDeliveryManager::reset_counters()
Set local spike counter to zero.
References local_spike_counter_.
Referenced by initialize, nest::SimulationManager::run.
void nest::EventDeliveryManager::reset_timers_for_preparation()
Set time measurements for internal profiling to zero (reg.
prep.)
Referenced by initialize.
void nest::EventDeliveryManager::reset_timers_for_dynamics()
Set time measurements for internal profiling to zero (reg.
sim. dyn.)
Referenced by initialize, nest::SimulationManager::prepare.
void nest::EventDeliveryManager::send(Node &source, SpikeEvent &e, const long lag)
References nest::KernelManager::connection_manager, numerics::e, nest::kernel, local_spike_counter_, send_local_, send_off_grid_remote, send_remote, nest::ConnectionManager::send_to_devices, nest::names::source.
void nest::EventDeliveryManager::send(Node &source, DSSpikeEvent &e, const long lag)
References numerics::e, send_local_, nest::names::source.
void nest::EventDeliveryManager::gather_spike_data_(const thread tid, std::vector< SpikeDataT > &send_buffer, std::vector< SpikeDataT > &recv_buffer)
References nest::PerThreadBoolIndicator::all_false, nest::PerThreadBoolIndicator::all_true, nest::PerThreadBoolIndicator::any_false, buffer_size_spike_data_has_changed_, clean_spike_register_, collocate_spike_data_buffers_, nest::MPIManager::communicate_off_grid_spike_data_Alltoall, nest::MPIManager::communicate_spike_data_Alltoall, nest::MPIManager::decrease_buffer_size_spike_data, decrease_buffer_size_spike_data_, deliver_events_, emitted_spikes_register_, gather_completed_checker_, nest::VPManager::get_assigned_ranks, nest::MPIManager::increase_buffer_size_spike_data, nest::kernel, nest::KernelManager::mpi_manager, off_grid_emitted_spike_register_, off_grid_spiking_, reset_spike_register_, resize_send_recv_buffers_spike_data_, set_complete_marker_spike_data_, set_end_and_invalid_markers_, nest::KernelManager::vp_manager.
Referenced by gather_spike_data.
void nest::EventDeliveryManager::resize_send_recv_buffers_spike_data_()
References nest::kernel, recv_buffer_off_grid_spike_data_, recv_buffer_spike_data_, send_buffer_off_grid_spike_data_, send_buffer_spike_data_.
Referenced by configure_spike_data_buffers, gather_spike_data_.
bool nest::EventDeliveryManager::collocate_spike_data_buffers_(const thread tid, const AssignedRanks &assigned_ranks, SendBufferPosition &send_buffer_position, std::vector< std::vector< std::vector< std::vector< TargetT > > > > &spike_register, std::vector< SpikeDataT > &send_buffer)
Moves spikes from on grid and off grid spike registers to correct locations in MPI buffers.
References nest::SendBufferPosition::are_all_chunks_filled, nest::SendBufferPosition::idx, nest::SendBufferPosition::increase, nest::SendBufferPosition::is_chunk_filled, reset_complete_marker_spike_data_.
Referenced by gather_spike_data_.
void nest::EventDeliveryManager::set_end_and_invalid_markers_(const AssignedRanks &assigned_ranks, const SendBufferPosition &send_buffer_position, std::vector< SpikeDataT > &send_buffer)
Marks end of valid regions in MPI buffers.
References nest::SendBufferPosition::begin, nest::AssignedRanks::begin, nest::SendBufferPosition::end, nest::AssignedRanks::end, nest::SendBufferPosition::idx.
Referenced by gather_spike_data_.
void nest::EventDeliveryManager::reset_complete_marker_spike_data_(const AssignedRanks &assigned_ranks, const SendBufferPosition &send_buffer_position, std::vector< SpikeDataT > &send_buffer) const
Resets marker in MPI buffer that signals end of communication across MPI ranks.
References nest::AssignedRanks::begin, nest::SendBufferPosition::end, nest::AssignedRanks::end.
Referenced by collocate_spike_data_buffers_.
void nest::EventDeliveryManager::set_complete_marker_spike_data_(const AssignedRanks &assigned_ranks, const SendBufferPosition &send_buffer_position, std::vector< SpikeDataT > &send_buffer) const
Sets marker in MPI buffer that signals end of communication across MPI ranks.
References nest::AssignedRanks::begin, nest::SendBufferPosition::end, nest::AssignedRanks::end.
Referenced by gather_spike_data_.
bool nest::EventDeliveryManager::deliver_events_(const thread tid, const std::vector< SpikeDataT > &recv_buffer)
Reads spikes from MPI buffers and delivers them to ringbuffer of nodes.
References nest::KernelManager::connection_manager, nest::SimulationManager::get_clock, nest::ConnectionManager::get_compressed_spike_data, nest::ModelManager::get_connection_models, nest::MPIManager::get_num_processes, nest::MPIManager::get_send_recv_count_spike_data_per_rank, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::mpi_manager, nest::ConnectionManager::send, nest::Event::set_offset, nest::Event::set_sender_node_id_info, nest::Event::set_stamp, nest::KernelManager::simulation_manager, nest::Time::step, nest::ConnectionManager::use_compressed_spikes.
Referenced by gather_spike_data_.
void nest::EventDeliveryManager::reset_spike_register_(const thread tid)
Deletes all spikes from spike registers and resets spike counters.
References emitted_spikes_register_, off_grid_emitted_spike_register_.
Referenced by configure_spike_register, gather_spike_data_.
void nest::EventDeliveryManager::resize_spike_register_(const thread tid)
Resizes spike registers according minimal delay so it can accommodate all possible lags.
References emitted_spikes_register_, nest::kernel, off_grid_emitted_spike_register_.
Referenced by configure_spike_register.
void nest::EventDeliveryManager::clean_spike_register_(const thread tid)
Removes spikes that were successfully moved to MPI buffers from spike register, such that they are not considered in (potential) next communication round.
References emitted_spikes_register_, is_marked_for_removal_, off_grid_emitted_spike_register_.
Referenced by gather_spike_data_.
bool nest::EventDeliveryManager::collocate_target_data_buffers_(const thread tid, const AssignedRanks &assigned_ranks, SendBufferPosition &send_buffer_position)
Fills MPI buffer for communication of connection information from presynaptic to postsynaptic side.
Builds TargetData objects from SourceTable and connections information.
References nest::SendBufferPosition::are_all_chunks_filled, nest::SendBufferPosition::begin, nest::AssignedRanks::begin, nest::KernelManager::connection_manager, nest::SendBufferPosition::end, nest::AssignedRanks::end, nest::ConnectionManager::get_next_target_data, nest::SendBufferPosition::idx, nest::SendBufferPosition::increase, nest::SendBufferPosition::is_chunk_filled, nest::kernel, nest::ConnectionManager::no_targets_to_process, nest::ConnectionManager::reject_last_target_data, nest::ConnectionManager::save_source_table_entry_point, send_buffer_target_data_.
Referenced by gather_target_data.
void nest::EventDeliveryManager::set_complete_marker_target_data_(const AssignedRanks &assigned_ranks, const SendBufferPosition &send_buffer_position)
Sets marker in MPI buffer that signals end of communication across MPI ranks.
References nest::AssignedRanks::begin, nest::SendBufferPosition::end, nest::AssignedRanks::end.
Referenced by gather_target_data.
bool nest::EventDeliveryManager::distribute_target_data_buffers_(const thread tid)
Reads TargetData objects from MPI buffers and creates Target objects on TargetTable (presynaptic part of connection infrastructure).
References nest::ConnectionManager::add_target, nest::KernelManager::connection_manager, nest::MPIManager::get_num_processes, nest::MPIManager::get_send_recv_count_target_data_per_rank, nest::TargetData::get_source_tid, nest::TargetData::is_end_marker, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by gather_target_data.
void nest::EventDeliveryManager::send_local_(Node &source, EventT &e, const long lag)
Sends event e to all targets of node source.
Delivers events from devices directly to targets.
References nest::KernelManager::connection_manager, numerics::e, nest::kernel, nest::ConnectionManager::send_from_device, nest::names::source.
Referenced by send, send_secondary.
void nest::EventDeliveryManager::send_local_(Node &source, SecondaryEvent &e, const long lag)
References nest::KernelManager::connection_manager, numerics::e, nest::kernel, nest::ConnectionManager::send_from_device, nest::names::source.
bool nest::EventDeliveryManager::is_marked_for_removal_(const Target &target)
Returns true if spike has been moved to MPI buffer, such that it can be removed by clean_spike_register.
Required static function by std::remove_if.
References nest::names::target.
Referenced by clean_spike_register_.