nest::TargetData
constexpr uint8_t nest::TargetData::NUM_BITS_LID
constexpr uint8_t nest::TargetData::NUM_BITS_MARKER
constexpr uint8_t nest::TargetData::NUM_BITS_IS_PRIMARY
constexpr int nest::TargetData::MAX_LID
Referenced by set_source_lid.
unsigned int nest::TargetData::source_lid_
local id of presynaptic neuron
Referenced by get_source_lid, set_source_lid.
unsigned int nest::TargetData::source_tid_
thread index of presynaptic neuron
Referenced by get_source_tid, set_source_tid.
unsigned int nest::TargetData::marker_
Referenced by is_complete_marker, is_end_marker, is_invalid_marker, reset_marker, set_complete_marker, set_end_marker, set_invalid_marker.
bool nest::TargetData::is_primary_
TargetData has TargetDataFields else SecondaryTargetDataFields.
Referenced by is_primary, set_is_primary.
TargetDataFields nest::TargetData::target_data
Referenced by nest::TargetTable::add_target, nest::SourceTable::populate_target_data_fields_.
SecondaryTargetDataFields nest::TargetData::secondary_data
Referenced by nest::TargetTable::add_target, nest::SourceTable::populate_target_data_fields_.
union nest::TargetData::@3 nest::TargetData::@4
variant fields
void nest::TargetData::reset_marker()
References marker_, nest::TARGET_DATA_ID_DEFAULT.
Referenced by nest::SourceTable::populate_target_data_fields_.
void nest::TargetData::set_complete_marker()
References marker_, nest::TARGET_DATA_ID_COMPLETE.
void nest::TargetData::set_end_marker()
References marker_, nest::TARGET_DATA_ID_END.
void nest::TargetData::set_invalid_marker()
References marker_, nest::TARGET_DATA_ID_INVALID.
bool nest::TargetData::is_complete_marker() const
References marker_, nest::TARGET_DATA_ID_COMPLETE.
bool nest::TargetData::is_end_marker() const
References marker_, nest::TARGET_DATA_ID_END.
Referenced by nest::EventDeliveryManager::distribute_target_data_buffers_.
bool nest::TargetData::is_invalid_marker() const
References marker_, nest::TARGET_DATA_ID_INVALID.
void nest::TargetData::set_source_lid(const index source_lid)
References MAX_LID, source_lid_.
Referenced by nest::SourceTable::populate_target_data_fields_.
void nest::TargetData::set_source_tid(const thread source_tid)
References nest::MAX_TID, source_tid_.
Referenced by nest::SourceTable::populate_target_data_fields_.
index nest::TargetData::get_source_lid() const
References source_lid_.
Referenced by nest::TargetTable::add_target.
thread nest::TargetData::get_source_tid() const
References source_tid_.
Referenced by nest::EventDeliveryManager::distribute_target_data_buffers_.
void nest::TargetData::set_is_primary(const bool is_primary)
References is_primary, is_primary_.
Referenced by nest::SourceTable::populate_target_data_fields_.
bool nest::TargetData::is_primary() const
References is_primary_.
Referenced by nest::TargetTable::add_target, set_is_primary.