nest::ConnectorModel
std::string nest::ConnectorModel::name_
name of the ConnectorModel
Referenced by get_name.
bool nest::ConnectorModel::default_delay_needs_check_
indicates whether the default delay must be checked
bool nest::ConnectorModel::is_primary_
indicates whether this ConnectorModel belongs to a primary connection
Referenced by is_primary.
bool nest::ConnectorModel::has_delay_
indicates whether ConnectorModel has a delay
Referenced by has_delay.
bool nest::ConnectorModel::requires_symmetric_
indicates that ConnectorModel requires symmetric connections
Referenced by requires_symmetric.
bool nest::ConnectorModel::supports_wfr_
indicates whether connection can be used during wfr update
Referenced by supports_wfr.
bool nest::ConnectorModel::requires_clopath_archiving_
indicates that ConnectorModel requires Clopath archiving
Referenced by requires_clopath_archiving.
bool nest::ConnectorModel::requires_urbanczik_archiving_
indicates that ConnectorModel requires Urbanczik archiving
Referenced by requires_urbanczik_archiving.
nest::ConnectorModel::ConnectorModel(const std::string, const bool is_primary, const bool has_delay, const bool requires_symmetric, const bool supports_wfr, const bool requires_clopath_archiving, const bool requires_urbanczik_archiving)
nest::ConnectorModel::ConnectorModel(const ConnectorModel &, const std::string)
virtual nest::ConnectorModel::~ConnectorModel()
virtual void nest::ConnectorModel::add_connection(Node &src, Node &tgt, std::vector< ConnectorBase * > &hetconn, const synindex syn_id, const DictionaryDatum &d, const double delay=NAN, const double weight=NAN)=0
Adds a connection.
src Source node tgt Target node hetconn Connector vector syn_id Synapse id d Parameter dictionary to configure the synapse delay Delay of the connection weight Weight of the connection Delay and weight have the default value NAN, a special value, which describes double values that are not a number. If delay or weight is omitted, NAN indicates this and weight/delay are set only if they are valid.
Referenced by nest::TargetTableDevices::add_connection_from_device, nest::TargetTableDevices::add_connection_to_device, nest::ConnectionManager::connect_.
virtual ConnectorModel * nest::ConnectorModel::clone(std::string, synindex syn_id) const =0
Referenced by nest::ModelManager::copy_connection_model_, nest::ModelManager::register_connection_model_.
virtual void nest::ConnectorModel::calibrate(const TimeConverter &tc)=0
virtual void nest::ConnectorModel::get_status(DictionaryDatum &) const =0
virtual void nest::ConnectorModel::set_status(const DictionaryDatum &)=0
virtual const CommonSynapseProperties & nest::ConnectorModel::get_common_properties() const =0
virtual void nest::ConnectorModel::check_synapse_params(const DictionaryDatum &) const =0
Checks to see if illegal parameters are given in syn_spec.
virtual SecondaryEvent * nest::ConnectorModel::get_event() const =0
Referenced by nest::GenericSecondaryConnectorModel< ConnectionT >::clone, nest::ModelManager::get_secondary_event_prototype.
virtual void nest::ConnectorModel::set_syn_id(synindex syn_id)=0
Referenced by nest::GenericSecondaryConnectorModel< ConnectionT >::clone, nest::GenericConnectorModel< ConnectionT >::clone.
virtual SecondaryEvent * nest::ConnectorModel::create_event() const =0
std::string nest::ConnectorModel::get_name() const
References name_.
Referenced by nest::ModelManager::register_connection_model_.
bool nest::ConnectorModel::is_primary() const
References is_primary_.
Referenced by nest::GenericSecondaryConnectorModel< ConnectionT >::clone, nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources, nest::ConnectionManager::connect_.
bool nest::ConnectorModel::has_delay() const
References has_delay_.
bool nest::ConnectorModel::requires_symmetric() const
References requires_symmetric_.
bool nest::ConnectorModel::requires_clopath_archiving() const
References requires_clopath_archiving_.
bool nest::ConnectorModel::requires_urbanczik_archiving() const
References requires_urbanczik_archiving_.
bool nest::ConnectorModel::supports_wfr() const
References supports_wfr_.