nest::ModelRangeManager
std::vector< modelrange > nest::ModelRangeManager::modelranges_
Referenced by add_range, finalize, get_contiguous_node_id_range, get_model_id.
index nest::ModelRangeManager::first_node_id_
Referenced by add_range, finalize.
index nest::ModelRangeManager::last_node_id_
Referenced by add_range, finalize.
nest::ModelRangeManager::ModelRangeManager()
nest::ModelRangeManager::~ModelRangeManager() override
void nest::ModelRangeManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
void nest::ModelRangeManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
References first_node_id_, last_node_id_, modelranges_.
void nest::ModelRangeManager::set_status(const DictionaryDatum &) override
void nest::ModelRangeManager::get_status(DictionaryDatum &) override
void nest::ModelRangeManager::add_range(index model, index first_node_id, index last_node_id)
Assign a range of node IDs for the given model.
References first_node_id_, last_node_id_, nest::names::model, modelranges_.
Referenced by nest::NodeManager::add_node.
bool nest::ModelRangeManager::is_in_range(index node_id) const
Check whether a node ID is with the range of assigned node IDs.
Referenced by get_contiguous_node_id_range, get_model_id.
index nest::ModelRangeManager::get_model_id(index node_id) const
Get the ID of the model to which this node ID is assigned.
References is_in_range, modelranges_.
Referenced by nest::ModelManager::get_proxy_node.
nest::Model * nest::ModelRangeManager::get_model_of_node_id(index)
Return the Model for a given node ID.
References nest::ModelManager::get_node_model, nest::kernel, nest::KernelManager::model_manager.
const modelrange & nest::ModelRangeManager::get_contiguous_node_id_range(index node_id) const
Return the contiguous range of IDs of nodes assigned to the same model as the node with the given node ID.
References is_in_range, modelranges_.
std::vector< modelrange >::const_iterator nest::ModelRangeManager::begin() const
std::vector< modelrange >::const_iterator nest::ModelRangeManager::end() const