nest::SourceTable
std::vector< std::vector< BlockVector< Source > > > nest::SourceTable::sources_
3D structure storing node IDs of presynaptic neurons.
Referenced by add_source, clear, disable_connection, find_first_source, get_source_node_ids, num_unique_sources, reject_last_target_data, reset_entry_point, reset_processed_flags, save_entry_point.
PerThreadBoolIndicator nest::SourceTable::is_cleared_
Whether the 3D structure has been deleted.
Referenced by clear.
std::vector< SourceTablePosition > nest::SourceTable::current_positions_
Needed during readout of sources_.
Referenced by no_targets_to_process, reject_last_target_data, restore_entry_point, save_entry_point.
std::vector< SourceTablePosition > nest::SourceTable::saved_positions_
Needed during readout of sources_.
Referenced by reset_entry_point, restore_entry_point, save_entry_point.
PerThreadBoolIndicator nest::SourceTable::saved_entry_point_
If we detect an overflow in one of the MPI buffer parts, we save our current position in sources_ to continue at that point in the next communication round, while filling up (possible) remaining parts of the MPI buffer.
Referenced by restore_entry_point, save_entry_point.
std::vector< std::vector< std::map< index, SpikeData > > > nest::SourceTable::compressible_sources_
A structure to temporarily hold information about all process local targets will be addressed by incoming spikes.
Data from this structure is transferred to the compressed_spike_data_ structure of ConnectionManager during construction of the postsynaptic connection infrastructure. Arranged as a two dimensional vector (thread|synapse) with an inner map (source node id -> spike data).
std::vector< std::vector< std::map< index, size_t > > > nest::SourceTable::compressed_spike_data_map_
A structure to temporarily store locations of "unpacked spikes" in the compressed_spike_data_ structure of ConnectionManager.
Data from this structure is transferred to the presynaptic side during construction of the presynaptic connection infrastructure. Arranged as a two dimensional vector (thread|synapse) with an inner map (source node id -> index).
Referenced by clear_compressed_spike_data_map.
const size_t nest::SourceTable::min_deleted_elements_
Minimal number of sources that need to be deleted per synapse type and thread before a reallocation of the respective vector is performed.
Balances number of reallocations and memory usage. SourceTable::clean()
bool nest::SourceTable::source_should_be_processed_(const thread rank_start, const thread rank_end, const Source &source) const
Returns whether this Source object should be considered when constructing MPI buffers for communicating connections.
Returns false if i) this entry was already processed, or ii) this entry is disabled (e.g., by structural plastcity) or iii) the reading thread is not responsible for the particular part of the MPI buffer where this entry would be written.
References nest::MPIManager::get_process_id_of_node_id, nest::kernel, nest::KernelManager::mpi_manager.
bool nest::SourceTable::next_entry_has_same_source_(const SourceTablePosition &current_position, const Source &current_source) const
Returns true if the following entry in the SourceTable has the same source gid.
References nest::Source::get_node_id, nest::SourceTablePosition::is_invalid, nest::SourceTablePosition::lcid, nest::SourceTablePosition::syn_id, nest::SourceTablePosition::tid.
bool nest::SourceTable::previous_entry_has_same_source_(const SourceTablePosition &current_position, const Source &current_source) const
Returns true if the previous entry in the SourceTable has the same source gid.
References nest::Source::get_node_id, nest::SourceTablePosition::is_invalid, nest::SourceTablePosition::lcid, nest::SourceTablePosition::syn_id, nest::SourceTablePosition::tid.
bool nest::SourceTable::populate_target_data_fields_(const SourceTablePosition &current_position, const Source &current_source, const thread source_rank, TargetData &next_target_data) const
Fills the fields of a TargetData during construction of * presynaptic connection infrastructure.
References nest::KernelManager::connection_manager, nest::Source::get_node_id, nest::MPIManager::get_recv_displacement_secondary_events_in_int, nest::ConnectionManager::get_secondary_recv_buffer_position, nest::Source::is_primary, nest::kernel, nest::SourceTablePosition::lcid, nest::KernelManager::mpi_manager, nest::TargetData::reset_marker, nest::TargetData::secondary_data, nest::TargetData::set_is_primary, nest::TargetDataFields::set_lcid, nest::SecondaryTargetDataFields::set_recv_buffer_pos, nest::TargetData::set_source_lid, nest::TargetData::set_source_tid, nest::TargetDataFields::set_syn_id, nest::SecondaryTargetDataFields::set_syn_id, nest::TargetDataFields::set_tid, nest::SourceTablePosition::syn_id, nest::TargetData::target_data, nest::SourceTablePosition::tid.
nest::SourceTable::SourceTable()
nest::SourceTable::~SourceTable()
void nest::SourceTable::initialize()
Initialize data structure.
References nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::vp_manager.
void nest::SourceTable::finalize()
Delete data structures.
void nest::SourceTable::add_source(const thread tid, const synindex syn_id, const index node_id, const bool is_primary)
Adds a source to sources_.
References sources_.
void nest::SourceTable::clear(const thread tid)
Clears sources_.
References is_cleared_, sources_.
Referenced by nest::ConnectionManager::clear_source_table.
bool nest::SourceTable::is_cleared() const
Returns true if sources_ has been cleared.
Referenced by nest::ConnectionManager::is_source_table_cleared, nest::ConnectionManager::restructure_connection_tables.
bool nest::SourceTable::get_next_target_data(const thread tid, const thread rank_start, const thread rank_end, thread &source_rank, TargetData &next_target_data)
Returns the next target data, according to the current_positions_.
References nest::KernelManager::connection_manager, nest::SourceTablePosition::decrease, nest::Source::get_node_id, nest::MPIManager::get_process_id_of_node_id, nest::SourceTablePosition::is_invalid, nest::kernel, nest::SourceTablePosition::lcid, nest::KernelManager::mpi_manager, nest::SourceTablePosition::seek_to_next_valid_index, nest::Source::set_processed, nest::ConnectionManager::set_source_has_more_targets, nest::SourceTablePosition::syn_id, nest::SourceTablePosition::tid.
Referenced by nest::ConnectionManager::get_next_target_data.
void nest::SourceTable::reject_last_target_data(const thread tid)
Rejects the last target data, and resets the current_positions_ accordingly.
References current_positions_, sources_.
Referenced by nest::ConnectionManager::reject_last_target_data.
void nest::SourceTable::save_entry_point(const thread tid)
Stores current_positions_ in saved_positions_.
References current_positions_, saved_entry_point_, saved_positions_, sources_.
Referenced by nest::ConnectionManager::save_source_table_entry_point.
void nest::SourceTable::restore_entry_point(const thread tid)
Restores current_positions_ from saved_positions_.
References current_positions_, saved_entry_point_, saved_positions_.
Referenced by nest::ConnectionManager::restore_source_table_entry_point.
void nest::SourceTable::reset_entry_point(const thread tid)
Resets saved_positions_ to end of sources_.
References saved_positions_, sources_.
Referenced by nest::ConnectionManager::reset_source_table_entry_point.
nest::index nest::SourceTable::get_node_id(const thread tid, const synindex syn_id, const index lcid) const
Returns the node ID of the source at tid|syn_id|lcid.
References nest::kernel.
Referenced by nest::ConnectionManager::get_source_node_id, get_source_node_ids.
std::vector< BlockVector< nest::Source > > & nest::SourceTable::get_thread_local_sources(const thread tid)
Returns a reference to all sources local on thread; necessary for sorting.
nest::SourceTablePosition nest::SourceTable::find_maximal_position() const
Determines maximal saved_positions_ after which it is safe to delete sources during clean().
References nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
void nest::SourceTable::reset_processed_flags(const thread tid)
Resets all processed flags.
Needed for restructuring connection tables, e.g., during structural plasticity update.
References sources_.
Referenced by nest::ConnectionManager::restructure_connection_tables.
void nest::SourceTable::clean(const thread tid)
Removes all entries marked as processed.
References BlockVector< value_type_ >::begin, BlockVector< value_type_ >::clear, BlockVector< value_type_ >::end, BlockVector< value_type_ >::erase, nest::SourceTablePosition::lcid, BlockVector< value_type_ >::size, nest::SourceTablePosition::syn_id, nest::SourceTablePosition::tid.
Referenced by nest::ConnectionManager::clean_source_table.
void nest::SourceTable::no_targets_to_process(const thread tid)
Sets current_positions_ for this thread to minimal values so that these are not considered in find_maximal_position().
References current_positions_.
Referenced by nest::ConnectionManager::no_targets_to_process.
void nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources(const thread tid, std::map< index, size_t > &buffer_pos_of_source_node_id_syn_id_)
Computes MPI buffer positions for unique combination of source node ID and synapse type across all threads for all secondary connections.
References nest::ModelManager::get_connection_model, nest::MPIManager::get_process_id_of_node_id, nest::ModelManager::get_secondary_event_prototype, nest::ConnectorModel::is_primary, nest::kernel, nest::KernelManager::model_manager, nest::KernelManager::mpi_manager, nest::MPIManager::set_recv_counts_secondary_events_in_int_per_rank, nest::SecondaryEvent::size.
index nest::SourceTable::find_first_source(const thread tid, const synindex syn_id, const index snode_id) const
Finds the first entry in sources_ at the given thread id and synapse type that is equal to snode_id.
References sources_.
void nest::SourceTable::disable_connection(const thread tid, const synindex syn_id, const index lcid)
Marks entry in sources_ at given position as disabled.
References sources_.
nest::index nest::SourceTable::remove_disabled_sources(const thread tid, const synindex syn_id)
Removes all entries from sources_ that are marked as disabled.
References BlockVector< value_type_ >::begin, BlockVector< value_type_ >::end, BlockVector< value_type_ >::erase, BlockVector< value_type_ >::size.
void nest::SourceTable::get_source_node_ids(const thread tid, const synindex syn_id, const std::vector< index > &source_lcids, std::vector< index > &sources)
Returns node IDs for entries in sources_ for the given thread id, synapse type and local connections ids.
References get_node_id, sources_.
size_t nest::SourceTable::num_unique_sources(const thread tid, const synindex syn_id) const
Returns the number of unique node IDs for given thread id and synapse type in sources_.
This number corresponds to the number of targets that need to be communicated during construction of the presynaptic connection infrastructure.
References sources_.
void nest::SourceTable::resize_sources(const thread tid)
Resizes sources_ according to total number of threads and synapse types.
References nest::kernel.
index nest::SourceTable::pack_source_node_id_and_syn_id(const index source_node_id, const synindex syn_id) const
Encodes combination of node ID and synapse types as single long number.
References nest::invalid_synindex.
void nest::SourceTable::resize_compressible_sources()
References nest::ModelManager::get_num_connection_models, nest::kernel, nest::KernelManager::model_manager.
void nest::SourceTable::collect_compressible_sources(const thread tid)
void nest::SourceTable::fill_compressed_spike_data(std::vector< std::vector< std::vector< SpikeData > > > &compressed_spike_data)
References nest::ModelManager::get_num_connection_models, nest::kernel, nest::KernelManager::model_manager.
void nest::SourceTable::clear_compressed_spike_data_map(const thread tid)
References compressed_spike_data_map_.
Referenced by nest::ConnectionManager::clear_compressed_spike_data_map.