nest::glif_psc
friend class nest::RecordablesMap< glif_psc >
friend class nest::UniversalDataLogger< glif_psc >
Parameters_ nest::glif_psc::P_
Referenced by get_status, get_threshold_, get_V_m_, set_status.
State_ nest::glif_psc::S_
Referenced by get_ASCurrents_sum_, get_I_, get_I_syn_, get_status, get_threshold_, get_threshold_spike_, get_threshold_voltage_, get_V_m_, set_status.
Variables_ nest::glif_psc::V_
Buffers_ nest::glif_psc::B_
nest::RecordablesMap< nest::glif_psc > nest::glif_psc::recordablesMap_
Mapping of recordables names to access functions.
Referenced by get_status, glif_psc.
nest::glif_psc::glif_psc()
References recordablesMap_.
nest::glif_psc::glif_psc(const glif_psc &)
nest::port nest::glif_psc::send_test_event(nest::Node &, nest::port, nest::synindex, bool) override
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws IllegalConnection. This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node. If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
References numerics::e, nest::names::receptor_type, nest::names::target.
void nest::glif_psc::handle(nest::SpikeEvent &) override
Handle incoming spike events.
Default implementation of event handlers just throws an UnexpectedEvent exception. thrd Id of the calling thread. e Event object. This handler has to be implemented if a Node should accept spike events. class SpikeEvent class UnexpectedEvent UnexpectedEvent This is the default event to throw.
References numerics::e, nest::kernel.
void nest::glif_psc::handle(nest::CurrentEvent &) override
Handler for current events.
handle(thread, SpikeEvent&) UnexpectedEvent
References numerics::e, nest::kernel.
void nest::glif_psc::handle(nest::DataLoggingRequest &) override
Handler for universal data logging request.
handle(SpikeEvent&) UnexpectedEvent
References numerics::e.
nest::port nest::glif_psc::handles_test_event(nest::SpikeEvent &, nest::port) override
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event(). handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle. See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3. The semantics of all other handles_test_event() functions is identical. IllegalConnection
References nest::names::receptor_type.
nest::port nest::glif_psc::handles_test_event(nest::CurrentEvent &, nest::port) override
References nest::names::receptor_type.
nest::port nest::glif_psc::handles_test_event(nest::DataLoggingRequest &, nest::port) override
References nest::names::receptor_type.
void nest::glif_psc::get_status(DictionaryDatum &) const override
Export properties of the node by setting entries in the status dictionary.
d Dictionary.
References nest::names::d, nest::glif_psc::Parameters_::get, nest::glif_psc::State_::get, nest::ArchivingNode::get_status, P_, nest::names::recordables, recordablesMap_, S_.
void nest::glif_psc::set_status(const DictionaryDatum &) override
Change properties of the node according to the entries in the dictionary.
d Dictionary with named parameter settings.
References nest::names::d, P_, S_, nest::glif_psc::State_::set, nest::glif_psc::Parameters_::set, nest::ArchivingNode::set_status.
void nest::glif_psc::init_buffers_() override
Reset internal buffers of neuron.
void nest::glif_psc::pre_run_hook() override
Initialize auxiliary quantities, leave parameters and state untouched.
References nest::names::a, numerics::e, IAFPropagatorAlpha::evaluate, nest::Time::get_ms, nest::Time::get_resolution, nest::Time::get_steps, nest::names::h.
void nest::glif_psc::update(nest::Time const &, const long, const long) override
Take neuron through given time interval.
References nest::names::a, nest::names::beta, nest::KernelManager::event_delivery_manager, nest::kernel, nest::names::origin, nest::EventDeliveryManager::send.
double nest::glif_psc::get_V_m_() const
References nest::glif_psc::Parameters_::E_L_, P_, S_, nest::glif_psc::State_::U_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::glif_psc::get_ASCurrents_sum_() const
References nest::glif_psc::State_::ASCurrents_sum_, S_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::glif_psc::get_I_() const
References nest::glif_psc::State_::I_, S_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::glif_psc::get_I_syn_() const
References nest::glif_psc::State_::I_syn_, S_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::glif_psc::get_threshold_() const
References nest::glif_psc::Parameters_::E_L_, P_, S_, nest::glif_psc::State_::threshold_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::glif_psc::get_threshold_spike_() const
References S_, nest::glif_psc::State_::threshold_spike_.
Referenced by nest::RecordablesMap< HostNode >::create.
double nest::glif_psc::get_threshold_voltage_() const
References S_, nest::glif_psc::State_::threshold_voltage_.
Referenced by nest::RecordablesMap< HostNode >::create.