nest::static_synapse
typedef CommonSynapseProperties nest::static_synapse< targetidentifierT >::CommonPropertiesType
typedef Connection< targetidentifierT > nest::static_synapse< targetidentifierT >::ConnectionBase
double nest::static_synapse< targetidentifierT >::weight_
Referenced by nest::static_synapse< targetidentifierT >::send, nest::static_synapse< targetidentifierT >::set_weight.
constexpr ConnectionModelProperties nest::static_synapse< targetidentifierT >::properties
nest::static_synapse< targetidentifierT >::static_synapse()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
nest::static_synapse< targetidentifierT >::static_synapse(const static_synapse &rhs)=default
Copy constructor from a property object.
Needs to be defined properly in order for GenericConnector to work.
static_synapse& nest::static_synapse< targetidentifierT >::operator=(const static_synapse &rhs)=default
void nest::static_synapse< targetidentifierT >::check_connection(Node &s, Node &t, rport receptor_type, const CommonPropertiesType &)
References nest::Connection< targetidentifierT >::check_connection_, nest::names::receptor_type.
void nest::static_synapse< targetidentifierT >::send(Event &e, const thread tid, const CommonSynapseProperties &)
References numerics::e, nest::static_synapse< targetidentifierT >::get_delay_steps, nest::static_synapse< targetidentifierT >::get_rport, nest::static_synapse< targetidentifierT >::get_target, nest::static_synapse< targetidentifierT >::weight_.
void nest::static_synapse< targetidentifierT >::get_status(DictionaryDatum &d) const
References nest::names::d, nest::names::size_of, nest::names::weight.
void nest::static_synapse< targetidentifierT >::set_status(const DictionaryDatum &d, ConnectorModel &cm)
References nest::names::d, nest::names::weight.
void nest::static_synapse< targetidentifierT >::set_weight(double w)
References nest::names::w, nest::static_synapse< targetidentifierT >::weight_.
long nest::Connection< targetidentifierT >::get_delay_steps() const
Return the delay of the connection in steps.
Referenced by nest::static_synapse< targetidentifierT >::send.
rport nest::Connection< targetidentifierT >::get_rport() const
Referenced by nest::static_synapse< targetidentifierT >::send.
Node* nest::Connection< targetidentifierT >::get_target(const thread tid) const
Referenced by nest::static_synapse< targetidentifierT >::send.