SLIFunction
SLIFunction::SLIFunction()
virtual void SLIFunction::execute(SLIInterpreter *) const =0
Referenced by Datum::execute, FunctionDatum::execute.
virtual SLIFunction::~SLIFunction()
virtual void SLIFunction::backtrace(SLIInterpreter *, int) const
Show stack backtrace information on error.
This function tries to extract and display useful information from the execution stack if an error occurs. This function should be implemented for all functions which store administrative information on the execution stack. Examples are: loops and procedure iterations. backtrace() is only called, if the interpreter flag show_backtrace is set.
Referenced by FunctionDatum::backtrace.