nest::Stopwatch
@0
typedef size_t nest::Stopwatch::timestamp_t
typedef size_t nest::Stopwatch::timeunit_t
timestamp_t nest::Stopwatch::_beg
timestamp_t nest::Stopwatch::_end
size_t nest::Stopwatch::_prev_elapsed
bool nest::Stopwatch::_running
bool nest::Stopwatch::correct_timeunit(timeunit_t t)
References DAYS, HOURS, MICROSEC, MILLISEC, MINUTES, SECONDS.
nest::Stopwatch::Stopwatch()
Creates a stopwatch that is not running.
References reset.
void nest::Stopwatch::start()
Starts or resumes the stopwatch, if it is not running already.
Referenced by nest::NodeManager::add_node, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute.
void nest::Stopwatch::stop()
Stops the stopwatch, if it is not stopped already.
Referenced by nest::NodeManager::add_node, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute.
bool nest::Stopwatch::isRunning() const
Returns, whether the stopwatch is running.
double nest::Stopwatch::elapsed(timeunit_t timeunit=SECONDS) const
Returns the time elapsed between the start and stop of the stopwatch.
If it is running, it returns the time from start until now. If the stopwatch is run previously, the previous runtime is added. If you want only the last measurement, you have to reset the timer, before stating the measurement. Does not change the running state.
Referenced by nest::NodeManager::get_status.
nest::Stopwatch::timestamp_t nest::Stopwatch::elapsed_timestamp() const
Returns the time elapsed between the start and stop of the stopwatch.
If it is running, it returns the time from start until now. If the stopwatch is run previously, the previous runtime is added. If you want only the last measurement, you have to reset the timer, before stating the measurement. Does not change the running state. In contrast to Stopwatch::elapsed(), only the timestamp is returned, that is the number if microseconds as an integer.
void nest::Stopwatch::reset()
Resets the stopwatch.
Referenced by nest::NodeManager::initialize, Stopwatch.
void nest::Stopwatch::print(const char *msg="", timeunit_t timeunit=SECONDS, std::ostream &os=std::cout) const
This method prints out the currently elapsed time.
std::ostream & operator<<(std::ostream &os, const Stopwatch &stopwatch)
Convenient method for writing time in seconds to some ostream.
nest::Stopwatch::timestamp_t nest::Stopwatch::get_timestamp()
Returns current time in microseconds since EPOCH.
References SECONDS.