nest::ArchivingNode
size_t nest::ArchivingNode::n_incoming_
Referenced by register_stdp_connection.
double nest::ArchivingNode::Kminus_
double nest::ArchivingNode::Kminus_triplet_
double nest::ArchivingNode::tau_minus_
double nest::ArchivingNode::tau_minus_inv_
double nest::ArchivingNode::tau_minus_triplet_
double nest::ArchivingNode::tau_minus_triplet_inv_
double nest::ArchivingNode::max_delay_
Referenced by register_stdp_connection.
double nest::ArchivingNode::trace_
double nest::ArchivingNode::last_spike_
Referenced by get_spiketime_ms.
std::deque< histentry > nest::ArchivingNode::history_
Referenced by register_stdp_connection.
nest::ArchivingNode::ArchivingNode()
Constructor.
Copy Constructor.
nest::ArchivingNode::ArchivingNode(const ArchivingNode &)
double nest::ArchivingNode::get_K_value(double t) override
return the Kminus (synaptic trace) value at t (in ms).
When the trace is requested at the exact same time that the neuron emits a spike, the trace value as it was just before the spike is returned.
References nest::kernel.
void nest::ArchivingNode::get_K_values(double t, double &Kminus, double &nearest_neighbor_Kminus, double &Kminus_triplet) override
write the Kminus (eligibility trace for STDP), nearest_neighbour_Kminus (eligibility trace for nearest-neighbour STDP: like Kminus, but increased to 1, rather than by 1, on a spike occurrence), and Kminus_triplet values at t (in ms) to the provided locations.
UnexpectedEvent
References nest::kernel.
Referenced by get_K_values.
void nest::ArchivingNode::get_K_values(double t, double &Kminus, double &Kminus_triplet)
The legacy version of the function, kept for compatibility after changing the function signature in PR #865.
UnexpectedEvent
References get_K_values.
double nest::ArchivingNode::get_K_triplet_value(const std::deque< histentry >::iterator &iter)
return the triplet Kminus value for the associated iterator.
void nest::ArchivingNode::get_history(double t1, double t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish) override
return the spike times (in steps) of spikes which occurred in the range (t1,t2].
References nest::KernelManager::connection_manager, nest::ConnectionManager::get_stdp_eps, nest::kernel, nest::names::start.
void nest::ArchivingNode::register_stdp_connection(double t_first_read, double delay) override
Register a new incoming STDP connection.
t_first_read: The newly registered synapse will read the history entries with t > t_first_read.
References history_, nest::kernel, nest::names::max, max_delay_, n_incoming_.
void nest::ArchivingNode::get_status(DictionaryDatum &d) const override
Export properties of the node by setting entries in the status dictionary.
d Dictionary.
References nest::names::archiver_length, nest::names::d, nest::StructuralPlasticityNode::get_status, nest::names::post_trace, nest::names::t_spike, nest::names::tau_minus, nest::names::tau_minus_triplet.
Referenced by nest::amat2_psc_exp::get_status, nest::binary_neuron< TGainfunction >::get_status, nest::cm_default::get_status, nest::gif_psc_exp::get_status, nest::gif_psc_exp_multisynapse::get_status, nest::glif_psc::get_status, nest::iaf_chs_2007::get_status, nest::iaf_psc_alpha::get_status, nest::iaf_psc_alpha_multisynapse::get_status, nest::iaf_psc_alpha_ps::get_status, nest::iaf_psc_delta::get_status, nest::iaf_psc_delta_ps::get_status, nest::iaf_psc_exp::get_status, nest::iaf_psc_exp_htum::get_status, nest::iaf_psc_exp_multisynapse::get_status, nest::iaf_psc_exp_ps::get_status, nest::iaf_psc_exp_ps_lossless::get_status, nest::izhikevich::get_status, nest::mat2_psc_exp::get_status, nest::parrot_neuron::get_status, nest::parrot_neuron_ps::get_status, nest::pp_psc_delta::get_status, nest::rate_neuron_ipn< TNonlinearities >::get_status, nest::rate_neuron_opn< TNonlinearities >::get_status, nest::rate_transformer_node< TNonlinearities >::get_status, nest::ClopathArchivingNode::get_status, nest::UrbanczikArchivingNode< urbanczik_parameters >::get_status.
void nest::ArchivingNode::set_status(const DictionaryDatum &d) override
Change properties of the node according to the entries in the dictionary.
d Dictionary with named parameter settings.
References nest::names::clear, nest::names::d, nest::StructuralPlasticityNode::set_status, nest::names::tau_minus, nest::names::tau_minus_triplet.
Referenced by nest::amat2_psc_exp::set_status, nest::binary_neuron< TGainfunction >::set_status, nest::cm_default::set_status, nest::gif_psc_exp::set_status, nest::gif_psc_exp_multisynapse::set_status, nest::glif_psc::set_status, nest::iaf_chs_2007::set_status, nest::iaf_psc_alpha::set_status, nest::iaf_psc_alpha_multisynapse::set_status, nest::iaf_psc_alpha_ps::set_status, nest::iaf_psc_delta::set_status, nest::iaf_psc_delta_ps::set_status, nest::iaf_psc_exp::set_status, nest::iaf_psc_exp_htum::set_status, nest::iaf_psc_exp_multisynapse::set_status, nest::iaf_psc_exp_ps::set_status, nest::iaf_psc_exp_ps_lossless::set_status, nest::izhikevich::set_status, nest::mat2_psc_exp::set_status, nest::parrot_neuron::set_status, nest::parrot_neuron_ps::set_status, nest::pp_psc_delta::set_status, nest::rate_neuron_ipn< TNonlinearities >::set_status, nest::rate_neuron_opn< TNonlinearities >::set_status, nest::rate_transformer_node< TNonlinearities >::set_status, nest::ClopathArchivingNode::set_status, nest::UrbanczikArchivingNode< urbanczik_parameters >::set_status.
void nest::ArchivingNode::set_spiketime(Time const &t_sp, double offset=0.0)
record spike history
References nest::Time::get_ms, nest::kernel, nest::names::offset, nest::StructuralPlasticityNode::set_spiketime.
Referenced by nest::iaf_psc_alpha::update, nest::iaf_psc_alpha_multisynapse::update, nest::iaf_psc_exp_multisynapse::update, nest::parrot_neuron::update, nest::parrot_neuron_ps::update.
double nest::ArchivingNode::get_spiketime_ms() const
References last_spike_.
void nest::ArchivingNode::clear_history()
clear spike history
Referenced by nest::amat2_psc_exp::init_buffers_, nest::binary_neuron< TGainfunction >::init_buffers_, nest::gif_psc_exp::init_buffers_, nest::gif_psc_exp_multisynapse::init_buffers_, nest::iaf_chs_2007::init_buffers_, nest::iaf_psc_alpha::init_buffers_, nest::iaf_psc_alpha_multisynapse::init_buffers_, nest::iaf_psc_alpha_ps::init_buffers_, nest::iaf_psc_delta::init_buffers_, nest::iaf_psc_delta_ps::init_buffers_, nest::iaf_psc_exp::init_buffers_, nest::iaf_psc_exp_htum::init_buffers_, nest::iaf_psc_exp_multisynapse::init_buffers_, nest::iaf_psc_exp_ps::init_buffers_, nest::izhikevich::init_buffers_, nest::mat2_psc_exp::init_buffers_, nest::parrot_neuron::init_buffers_, nest::parrot_neuron_ps::init_buffers_, nest::pp_psc_delta::init_buffers_, nest::rate_neuron_ipn< TNonlinearities >::init_buffers_, nest::rate_neuron_opn< TNonlinearities >::init_buffers_, nest::rate_transformer_node< TNonlinearities >::init_buffers_.