nest::Source
uint64_t nest::Source::node_id_
node ID of source
Referenced by disable, get_node_id, is_disabled, set_node_id.
bool nest::Source::processed_
whether this target has already been moved to the MPI buffer
Referenced by is_processed, set_processed.
bool nest::Source::primary_
Referenced by is_primary, set_primary.
nest::Source::Source()
nest::Source::Source(const uint64_t node_id, const bool primary)
References nest::MAX_NODE_ID.
void nest::Source::set_node_id(const uint64_t node_id)
Sets node_id_ to the specified value.
References nest::MAX_NODE_ID, node_id_.
uint64_t nest::Source::get_node_id() const
Returns this Source's node ID.
References node_id_.
Referenced by nest::SourceTable::get_next_target_data, nest::SourceTable::next_entry_has_same_source_, nest::SourceTable::populate_target_data_fields_, nest::SourceTable::previous_entry_has_same_source_.
void nest::Source::set_processed(const bool processed)
References processed_.
Referenced by nest::SourceTable::get_next_target_data.
bool nest::Source::is_processed() const
References processed_.
void nest::Source::set_primary(const bool primary)
Sets whether Source is primary.
References primary_.
bool nest::Source::is_primary() const
Returns whether Source is primary.
References primary_.
Referenced by nest::SourceTable::populate_target_data_fields_.
void nest::Source::disable()
Disables Source.
References nest::DISABLED_NODE_ID, node_id_.
bool nest::Source::is_disabled() const
Returns whether Source is disabled.
References nest::DISABLED_NODE_ID, node_id_.
bool operator<(const Source &lhs, const Source &rhs)
bool operator>(const Source &lhs, const Source &rhs)
bool operator==(const Source &lhs, const Source &rhs)