nest::ModelManager
std::vector< Model* > nest::ModelManager::builtin_node_models_
List of clean built-in node models.
Referenced by finalize, initialize, register_node_model_, ~ModelManager.
std::vector< Model* > nest::ModelManager::node_models_
List of usable node models.
This list is cleared and repopulated upon application startup and calls to ResetKernel. It contains copies of the built-in models, models registered from extension modules, and models created by calls to CopyModel(). The elements of this list also keep the user-modified defaults.
Referenced by calibrate, clear_node_models_, copy_node_model_, get_node_model, get_node_model_id, initialize, memory_info, register_node_model_.
std::vector< ConnectorModel* > nest::ModelManager::builtin_connection_models_
List of built-in clean connection models.
Referenced by initialize, register_connection_model_, ~ModelManager.
std::vector< std::vector< ConnectorModel* > > nest::ModelManager::connection_models_
The list of usable connection models.
The first dimension keeps one entry per thread, the second dimension has the actual models. This list is cleared and repopulated upon application startup and calls to ResetKernel. The inner list contains copies of the built-in models, models registered from extension modules, and models created by calls to CopyModel(). The elements of the list also keep the user-modified defaults.
Referenced by assert_valid_syn_id, calibrate, clear_connection_models_, connector_requires_clopath_archiving, connector_requires_symmetric, connector_requires_urbanczik_archiving, copy_connection_model_, get_connection_model, get_connection_models, get_connector_defaults, get_num_connection_models, initialize, register_connection_model_, set_synapse_defaults_.
DictionaryDatum nest::ModelManager::modeldict_
Dictionary of all node models.
Referenced by clear_node_models_, copy_model, copy_node_model_, get_status, initialize, register_node_model, register_node_model_, set_model_defaults.
DictionaryDatum nest::ModelManager::synapsedict_
Dictionary of all synapse models.
Referenced by copy_connection_model_, copy_model, get_status, get_synapse_model_id, initialize, register_connection_model_, set_model_defaults.
Model* nest::ModelManager::proxynode_model_
Referenced by clear_node_models_, create_proxynode_, initialize.
std::vector< std::vector< Node* > > nest::ModelManager::proxy_nodes_
Placeholders for remote nodes, one per thread.
Referenced by clear_node_models_, copy_node_model_, get_proxy_node, initialize, register_node_model_.
bool nest::ModelManager::model_defaults_modified_
True if any model defaults have been modified.
Referenced by are_model_defaults_modified, clear_node_models_, set_node_defaults_, set_synapse_defaults_.
nest::ModelManager::ModelManager()
nest::ModelManager::~ModelManager() override
References builtin_connection_models_, builtin_node_models_, clear_connection_models_, clear_node_models_.
void nest::ModelManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References builtin_connection_models_, builtin_node_models_, connection_models_, create_proxynode_, nest::VPManager::get_thread_id, nest::kernel, modeldict_, node_models_, proxy_nodes_, proxynode_model_, nest::Model::set_threads, nest::Model::set_type_id, synapsedict_, nest::KernelManager::vp_manager.
Referenced by change_number_of_threads.
void nest::ModelManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
References builtin_node_models_, clear_connection_models_, clear_node_models_.
Referenced by change_number_of_threads.
void nest::ModelManager::change_number_of_threads() override
Change the number of threads.
Many data structures within the different managers depend on the number of threads. This function is called on each manager upon a change of that number and allows the manager to re-allocate data structures accordingly.
References finalize, initialize.
void nest::ModelManager::set_status(const DictionaryDatum &) override
void nest::ModelManager::get_status(DictionaryDatum &) override
References nest::names::max_num_syn_models, nest::MAX_SYN_ID, modeldict_, nest::names::node_models, nest::names::synapse_models, synapsedict_.
void nest::ModelManager::calibrate(const TimeConverter &)
Resize the structures for the Connector objects if necessary.
Functor to compare Models by their name. This function should be called after number of threads, min_delay, max_delay, and time representation have been changed in the scheduler. The TimeConverter is used to convert times from the old to the new representation. It is also forwarding the calibration request to all ConnectorModel objects.
References connection_models_, nest::kernel, node_models_.
Referenced by nest::SimulationManager::set_status.
Node * nest::ModelManager::get_proxy_node(thread tid, index node_id)
Return a proxynode configured for thread tid and the given node_id.
References nest::ModelRangeManager::get_model_id, nest::kernel, nest::KernelManager::modelrange_manager, proxy_nodes_, nest::Node::set_node_id_, nest::Node::set_vp.
Referenced by nest::NodeManager::get_mpi_local_node_or_device_head, nest::NodeManager::get_node_or_proxy.
ConnectorModel & nest::ModelManager::get_connection_model(synindex syn_id, thread t=0)
Return pointer to protoype for given synapse id.
UnknownSynapseType Todo: make the return type const, after the increment of num_connections and the min_ and max_delay setting in ConnectorBase was moved out to the ConnectionManager
References assert_valid_syn_id, connection_models_.
Referenced by nest::TargetTableDevices::add_connection_from_device, nest::TargetTableDevices::add_connection_to_device, nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources, nest::ConnectionManager::connect_, copy_connection_model_, get_secondary_event_prototype, nest::ConnBuilder::set_synapse_model_, nest::ConnectionManager::set_synapse_status.
const std::vector< ConnectorModel * > & nest::ModelManager::get_connection_models(thread tid)
References connection_models_.
Referenced by nest::EventDeliveryManager::deliver_events_, nest::ConnectionManager::deliver_secondary_events.
index nest::ModelManager::register_node_model(const Name &name, std::string deprecation_info=std::string())
Register a node-model prototype.
This function must be called exactly once for each model class to make it known in the simulator. The natural place for a call to this function is in a *module.cpp file. name of the new node model. deprecation_info If non-empty string, deprecation warning will be issued for model with this info to user. ID of the new model object. register_prototype_connection
References modeldict_, register_node_model_, Name::toString.
Referenced by nest::ModelsModule::init.
index nest::ModelManager::copy_model(Name old_name, Name new_name, DictionaryDatum params)
Copy an existing model and register it as a new model.
This function allows users to create their own, cloned models. old_name name of existing model. new_name name of new model. params default parameters of new model. model ID of new Model object. copy_node_model_, copy_connection_model_
References copy_connection_model_, copy_node_model_, Token::empty, modeldict_, set_node_defaults_, set_synapse_defaults_, synapsedict_.
Referenced by nest::copy_model, nest::NestModule::CopyModel_l_l_DFunction::execute.
bool nest::ModelManager::set_model_defaults(Name name, DictionaryDatum params)
Set the default parameters of a model.
name of model. params default parameters to be set. true if the operation succeeded, else false set_node_defaults_, set_synapse_defaults_
References Token::empty, modeldict_, set_node_defaults_, set_synapse_defaults_, synapsedict_.
void nest::ModelManager::register_connection_model(const std::string &name, const RegisterConnectionModelFlags flags=default_connection_model_flags)
Register a synape model with a custom Connector model and without any common properties.
"hpc synapses" use TargetIdentifierIndex for ConnectionT and store the target neuron in form of a 2 Byte index instead of an 8 Byte pointer. This limits the number of thread local neurons to 65,536. No support for different receptor types. Otherwise identical to non-hpc version. When called, this function should be specialised by a class template, e.g. bernoulli_synapse< targetidentifierT > name The name under which the ConnectorModel will be registered.
References nest::enumFlagSet, nest::HAS_DELAY, nest::IS_PRIMARY, register_connection_model_, nest::REGISTER_HPC, nest::REGISTER_LBL, nest::REQUIRES_CLOPATH_ARCHIVING, nest::REQUIRES_SYMMETRIC, nest::REQUIRES_URBANCZIK_ARCHIVING, nest::SUPPORTS_WFR.
Referenced by nest::register_connection_model.
void nest::ModelManager::register_secondary_connection_model(const std::string &name, const RegisterConnectionModelFlags flags=default_secondary_connection_model_flags)
Register a synape with default Connector and without any common properties.
References nest::enumFlagSet, nest::HAS_DELAY, register_connection_model_, nest::REQUIRES_SYMMETRIC, nest::SUPPORTS_WFR.
Referenced by nest::register_secondary_connection_model.
index nest::ModelManager::get_node_model_id(const Name) const
The model ID for a Model with a given name UnknownModelName if the model is not available
References node_models_.
Referenced by nest::create, nest::AbstractLayer::create_layer, nest::get_model_defaults.
Model * nest::ModelManager::get_node_model(index) const
The Model registered with the given model ID
References node_models_.
Referenced by nest::NodeManager::add_node, compare_model_by_id_, copy_node_model_, nest::Node::get_model_, nest::get_model_defaults, nest::ModelRangeManager::get_model_of_node_id, nest::Node::get_name, nest::proxynode::get_status, nest::NodeCollectionPrimitive::NodeCollectionPrimitive, nest::NodeManager::print, nest::NodeCollectionComposite::print_me, nest::NodeCollectionPrimitive::print_primitive, nest::proxynode::send_test_event, nest::proxynode::sends_secondary_event, nest::proxynode::sends_signal, set_node_defaults_.
index nest::ModelManager::get_synapse_model_id(std::string model_name)
The numeric ID of a given synapse model UnknownSynapseType if the model is not available
References Token::empty, synapsedict_.
Referenced by nest::ConnBuilder::ConnBuilder, nest::ConnectionManager::connect, nest::ConnectionManager::connect_arrays, nest::ConnectionCreator::ConnectionCreator, nest::ConnectionCreator::extract_params_, nest::ConnectionManager::get_connections, nest::get_model_defaults, nest::GenericConnectorModel< ConnectionT >::get_status, nest::ConnBuilder::set_synapse_model_.
DictionaryDatum nest::ModelManager::get_connector_defaults(synindex syn_id) const
References assert_valid_syn_id, nest::KernelManager::connection_manager, connection_models_, nest::names::element_type, nest::ConnectionManager::get_num_connections, nest::kernel, nest::names::num_connections.
Referenced by nest::ConnBuilder::ConnBuilder, nest::ConnectionManager::connect_arrays, nest::ConnectionCreator::ConnectionCreator, nest::ConnectionCreator::extract_params_, nest::get_model_defaults, nest::ConnBuilder::set_default_weight_or_delay_, nest::SPBuilder::update_delay.
bool nest::ModelManager::connector_requires_symmetric(const synindex syn_id) const
Checks, whether synapse type requires symmetric connections.
References assert_valid_syn_id, connection_models_.
bool nest::ModelManager::connector_requires_clopath_archiving(const synindex syn_id) const
Checks, whether synapse type requires Clopath archiving.
References assert_valid_syn_id, connection_models_.
Referenced by nest::ConnectionManager::connect_.
bool nest::ModelManager::connector_requires_urbanczik_archiving(const synindex syn_id) const
Checks, whether synapse type requires Urbanczik archiving.
References assert_valid_syn_id, connection_models_.
Referenced by nest::ConnectionManager::connect_.
void nest::ModelManager::set_connector_defaults(synindex syn_id, const DictionaryDatum &d)
void nest::ModelManager::assert_valid_syn_id(synindex syn_id, thread t=0) const
Asserts validity of synapse index, otherwise throws exception.
UnknownSynapseType
References connection_models_.
Referenced by nest::ConnectionManager::connect, connector_requires_clopath_archiving, connector_requires_symmetric, connector_requires_urbanczik_archiving, get_connection_model, get_connector_defaults, get_secondary_event_prototype, nest::ConnectionManager::get_synapse_status, set_synapse_defaults_, nest::ConnectionManager::set_synapse_status.
bool nest::ModelManager::are_model_defaults_modified() const
References model_defaults_modified_.
size_t nest::ModelManager::get_num_connection_models() const
References connection_models_, nest::invalid_synindex.
Referenced by nest::SourceTable::fill_compressed_spike_data, nest::ConnectionManager::get_connections, nest::SourceTable::resize_compressible_sources, nest::ConnectionManager::resize_connections.
void nest::ModelManager::memory_info() const
Print out the memory information for each node model.
References compare_model_by_id_, nest::mod, node_models_.
Referenced by nest::NestModule::MemoryInfoFunction::execute.
SecondaryEvent & nest::ModelManager::get_secondary_event_prototype(const synindex syn_id, const thread tid)
References assert_valid_syn_id, get_connection_model, nest::ConnectorModel::get_event.
Referenced by nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources, nest::ConnectionManager::deliver_secondary_events.
void nest::ModelManager::clear_node_models_()
References model_defaults_modified_, modeldict_, node_models_, proxy_nodes_, proxynode_model_.
Referenced by finalize, ~ModelManager.
void nest::ModelManager::clear_connection_models_()
References connection_models_.
Referenced by finalize, ~ModelManager.
index nest::ModelManager::register_node_model_(Model *model)
References builtin_node_models_, create_proxynode_, nest::VPManager::get_thread_id, nest::kernel, modeldict_, node_models_, proxy_nodes_, nest::Model::set_model_id, nest::KernelManager::vp_manager.
Referenced by register_node_model.
synindex nest::ModelManager::register_connection_model_(ConnectorModel *)
References builtin_connection_models_, nest::ConnectorModel::clone, nest::KernelManager::connection_manager, connection_models_, nest::ConnectorModel::get_name, nest::kernel, nest::ConnectionManager::resize_connections, synapsedict_.
Referenced by register_connection_model, register_secondary_connection_model.
index nest::ModelManager::copy_node_model_(index old_id, Name new_name)
Copy an existing node model and register it as a new model.
old_id ID of existing model. new_name name of new model. model ID of new Model object. copy_model(), copy_connection_model_()
References nest::Model::clone, create_proxynode_, nest::Model::deprecation_warning, get_node_model, nest::VPManager::get_thread_id, nest::kernel, modeldict_, node_models_, proxy_nodes_, nest::Model::set_model_id, Name::toString, nest::KernelManager::vp_manager.
Referenced by copy_model.
index nest::ModelManager::copy_connection_model_(index old_id, Name new_name)
Copy an existing synapse model and register it as a new model.
old_id ID of existing model. new_name name of new model. model ID of new Model object. copy_model(), copy_node_model_()
References nest::ConnectorModel::clone, nest::KernelManager::connection_manager, connection_models_, get_connection_model, nest::invalid_synindex, nest::kernel, LOG, nest::M_ERROR, nest::MAX_SYN_ID, nest::ConnectionManager::resize_connections, synapsedict_, Name::toString.
Referenced by copy_model.
void nest::ModelManager::set_node_defaults_(index model_id, const DictionaryDatum &params)
Set the default parameters of a model.
model_id of model. params default parameters to be set. set_model_defaults, set_synapse_defaults_
References ALL_ENTRIES_ACCESSED, get_node_model, model_defaults_modified_, nest::Model::set_status.
Referenced by copy_model, set_model_defaults.
void nest::ModelManager::set_synapse_defaults_(index model_id, const DictionaryDatum &params)
Set the default parameters of a model.
name of model. params default parameters to be set. set_model_defaults, set_node_defaults_
References ALL_ENTRIES_ACCESSED, assert_valid_syn_id, connection_models_, nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, nest::kernel, model_defaults_modified_, nest::KernelManager::vp_manager.
Referenced by copy_model, set_model_defaults.
Node * nest::ModelManager::create_proxynode_(thread t, int model_id)
References nest::Model::create, proxynode_model_, nest::Node::set_model_id.
Referenced by copy_node_model_, initialize, register_node_model_.
bool nest::ModelManager::compare_model_by_id_(const int a, const int b)
Compares model ids for sorting in memory_info.
References nest::Model::get_name, get_node_model, nest::kernel, nest::KernelManager::model_manager.
Referenced by memory_info.