Scanner
ScanStates
Codes
std::istream* Scanner::in
Referenced by GetSource, operator(), source.
CharCode Scanner::code
Referenced by operator(), Scanner.
unsigned long Scanner::line
Current line number.
Referenced by clear_context, get_line, operator(), print_error, source.
unsigned long Scanner::col
Current column in line.
Referenced by clear_context, get_col, operator(), print_error, source.
std::string Scanner::context
Current context.
Referenced by clear_context, operator(), print_error, source.
std::string Scanner::old_context
Referenced by clear_context, operator(), print_error, source.
enum ScanStates Scanner::trans[lastscanstate][lastcode][lastscanstate][lastcode]
Referenced by operator(), Scanner.
const unsigned char Scanner::space
Referenced by Scanner.
const unsigned char Scanner::tab
Referenced by Scanner.
const unsigned char Scanner::endoln
Referenced by operator(), Scanner.
const unsigned char Scanner::cr
Referenced by Scanner.
const unsigned char Scanner::endof
Referenced by operator(), Scanner.
SymbolDatum Scanner::BeginArraySymbol
Referenced by Parser::operator(), operator().
SymbolDatum Scanner::EndArraySymbol
Referenced by Parser::operator(), operator().
SymbolDatum Scanner::BeginProcedureSymbol
Referenced by Parser::operator(), operator().
SymbolDatum Scanner::EndProcedureSymbol
Referenced by Parser::operator(), operator().
SymbolDatum Scanner::EndSymbol
Referenced by IparsestdinFunction::execute, ParsestdinFunction::execute, IparseFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, Parser::operator(), operator().
int Scanner::digval(unsigned char c) const
Referenced by operator().
Scanner::Scanner(std::istream *)
Initialise scanner with a stream.
Scanner (implemented as a DFA)
References aheadalphst, aheadfracst, aheadintst, aheadlitst, aheadsgst, alpha, alphast, asterisk, asteriskst, backslash, backslashcst, backslashst, ccommentst, closebrace, closebracest, closebracket, closebracketst, closeparenth, closeparst, code, cparenthcst, cr, decpdgtst, decpfirstst, decpoint, decpointst, digit, dotalphast, endof, endoln, eof, eofst, eoln, error, expdigst, expntl, expntlst, fracdgtst, CharCode::Group, intdgtst, intexpst, invalid, lastcode, lastscanstate, literalst, minus, minusst, mnexpst, newline, newlinest, null, nullst, oparenthcst, openbrace, openbracest, openbracket, openbracketst, openparenth, openparst, percent, percentst, plexpst, plus, plusst, CharCode::Range, sgalphast, slash, slashst, space, start, startstringst, stringst, tab, tabulator, tabulatorst, trans, whitespace.
void Scanner::source(std::istream *)
Set new input stream.
References col, context, in, line, old_context.
Referenced by Parser::readSymbol, Parser::readToken.
std::istream * Scanner::GetSource()
Return input stream.
References in.
bool Scanner::operator()(Token &)
Scan input until the next Token.
References aheadalphst, aheadfracst, aheadintst, aheadlitst, aheadsgst, alphast, backslashcst, BeginArraySymbol, BeginProcedureSymbol, Token::clear, closebracest, closebracketst, closeparst, code, col, context, cparenthcst, decpdgtst, decpointst, digval, dotalphast, end, EndArraySymbol, endof, endoln, EndProcedureSymbol, EndSymbol, eofst, error, expdigst, expntlst, fracdgtst, in, intdgtst, intexpst, line, literalst, minusst, mnexpst, Token::move, newlinest, old_context, oparenthcst, openbracest, openbracketst, openparst, plusst, print_error, sgalphast, start, stringst, tabulatorst, trans.
void Scanner::print_error(const char *)
Issue an error message.
References col, context, line, old_context.
Referenced by Parser::operator(), operator().
unsigned long Scanner::get_line() const
Return current line number in input stream.
References line.
unsigned long Scanner::get_col() const
Return position in current line in input stream.
References col.
void Scanner::clear_context()
References col, context, line, old_context.
Referenced by Parser::clear_context.