nest::NodeCollectionComposite
friend class nc_const_iterator
std::vector< NodeCollectionPrimitive > nest::NodeCollectionComposite::parts_
Vector of primitives.
Referenced by nest::nc_const_iterator::composite_update_indices_, contains, end, find, get_metadata, has_proxies, nest::nc_const_iterator::nc_const_iterator, NodeCollectionComposite, nest::nc_const_iterator::operator*, operator+, operator==, operator[], print_me, set_metadata.
size_t nest::NodeCollectionComposite::size_
Total number of node IDs.
Referenced by NodeCollectionComposite, operator==, size.
size_t nest::NodeCollectionComposite::step_
Step length, set when slicing.
Referenced by begin, contains, end, find, local_begin, MPI_local_begin, NodeCollectionComposite, operator+, operator[], print_me, step.
size_t nest::NodeCollectionComposite::start_part_
Primitive to start at, set when slicing.
Referenced by begin, contains, find, local_begin, MPI_local_begin, NodeCollectionComposite, operator[].
size_t nest::NodeCollectionComposite::start_offset_
Element to start at, set when slicing.
Referenced by begin, contains, find, local_begin, MPI_local_begin, NodeCollectionComposite, operator[].
size_t nest::NodeCollectionComposite::end_part_
Primitive or one past the primitive to end at, set when slicing.
Referenced by nest::nc_const_iterator::composite_update_indices_, contains, end, find, NodeCollectionComposite, nest::nc_const_iterator::operator*, operator+, operator[], print_me.
size_t nest::NodeCollectionComposite::end_offset_
One past the element to end at, set when slicing.
Referenced by nest::nc_const_iterator::composite_update_indices_, contains, end, find, NodeCollectionComposite, nest::nc_const_iterator::operator*, operator+, operator[], print_me.
void nest::NodeCollectionComposite::merge_parts(std::vector< NodeCollectionPrimitive > &parts) const
Goes through the vector of primitives, merging as much as possible.
parts Vector of primitives to be merged.
Referenced by operator+.
nest::NodeCollectionComposite::NodeCollectionComposite(const NodeCollectionPrimitive &, size_t, size_t, size_t)
Create a composite from a primitive, with boundaries and step length.
primitive Primitive to be converted start Offset in the primitive to begin at. end Offset in the primitive, one past the node to end at. step Length to step in the primitive.
References parts_.
nest::NodeCollectionComposite::NodeCollectionComposite(const NodeCollectionComposite &)
Composite copy constructor.
comp Composite to be copied.
nest::NodeCollectionComposite::NodeCollectionComposite(const NodeCollectionComposite &, size_t, size_t, size_t)
Creates a new composite from another, with boundaries and step length.
This constructor is used only when slicing. composite Composite to slice. start Index in the composite to begin at. end Index in the composite one past the node to end at. step Length to step in the composite.
References begin, end, end_offset_, end_part_, nest::nc_const_iterator::get_current_part_offset, size, size_, start_offset_, start_part_, step_.
nest::NodeCollectionComposite::NodeCollectionComposite(const std::vector< NodeCollectionPrimitive > &)
Create a composite from a vector of primitives.
parts Vector of primitives.
References parts_, nest::primitiveSort, size_.
void nest::NodeCollectionComposite::print_me(std::ostream &) const override
Print out the contents of the NodeCollection in a pretty and informative way.
References begin, end, end_offset_, end_part_, nest::Model::get_name, nest::ModelManager::get_node_model, nest::kernel, nest::NodeIDTriple::model_id, nest::KernelManager::model_manager, nest::NodeIDTriple::node_id, parts_, step_.
index nest::NodeCollectionComposite::operator[](const size_t) const override
Get the node ID in the specified index in the NodeCollection.
idx Index in the NodeCollection a node ID
References begin, end_offset_, end_part_, parts_, start_offset_, start_part_, step_.
NodeCollectionPTR nest::NodeCollectionComposite::operator+(NodeCollectionPTR rhs) const override
Addition operator.
Joins this composite with another NodeCollection. The resulting NodeCollection is sorted and merged, and converted to a primitive if possible. rhs NodeCollection to add to this composite a NodeCollection pointer to either a primitive or a composite.
References begin, contains, end, end_offset_, end_part_, get_metadata, merge_parts, parts_, nest::primitiveSort, size, step_, nest::NodeCollection::valid.
NodeCollectionPTR nest::NodeCollectionComposite::operator+(const NodeCollectionPrimitive &rhs) const
References nest::NodeCollectionPrimitive::get_metadata, get_metadata, merge_parts, parts_, nest::primitiveSort.
bool nest::NodeCollectionComposite::operator==(const NodeCollectionPTR rhs) const override
References parts_, size_.
NodeCollectionComposite::const_iterator nest::NodeCollectionComposite::begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection
References start_offset_, start_part_, step_.
Referenced by contains, find, NodeCollectionComposite, operator+, operator[], print_me, to_array.
NodeCollectionComposite::const_iterator nest::NodeCollectionComposite::local_begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection, in a parallel context.
References end, nest::nc_const_iterator::get_current_part_offset, nest::VPManager::get_num_virtual_processes, nest::kernel, nest::VPManager::node_id_to_vp, start_offset_, start_part_, step_, nest::VPManager::thread_to_vp, nest::KernelManager::vp_manager.
NodeCollectionComposite::const_iterator nest::NodeCollectionComposite::MPI_local_begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection, in an MPI-parallel context.
References end, nest::nc_const_iterator::get_current_part_offset, nest::MPIManager::get_num_processes, nest::MPIManager::get_process_id_of_vp, nest::MPIManager::get_rank, nest::kernel, nest::KernelManager::mpi_manager, start_offset_, start_part_, step_.
NodeCollectionComposite::const_iterator nest::NodeCollectionComposite::end(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const override
Method to get an iterator representing the end of the NodeCollection.
offset Index of element NC that iterator points to an iterator representing the end of the NodeCollection, taking offset into account
References end_offset_, end_part_, parts_, step_.
Referenced by nest::nc_const_iterator::composite_update_indices_, find, local_begin, MPI_local_begin, NodeCollectionComposite, operator+, print_me, slice, to_array.
ArrayDatum nest::NodeCollectionComposite::to_array() const override
Returns an ArrayDatum filled with node IDs from the composite.
References begin, end, size.
size_t nest::NodeCollectionComposite::size() const override
Returns total number of node IDs in the composite.
References size_.
Referenced by contains, find, NodeCollectionComposite, operator+, slice, to_array.
size_t nest::NodeCollectionComposite::step() const override
Returns the step between node IDs in the composite.
References step_.
Referenced by slice.
bool nest::NodeCollectionComposite::contains(index node_id) const override
Check if the NodeCollection contains a specified node ID.
node_id node ID to see if exists in the NodeCollection true if the NodeCollection contains the node ID, false otherwise
References begin, end_offset_, end_part_, parts_, size, start_offset_, start_part_, step_.
Referenced by operator+.
NodeCollectionPTR nest::NodeCollectionComposite::slice(size_t start, size_t end, size_t step=1) const override
Slices the NodeCollection to the boundaries, with an optional step parameter.
Note that the boundaries being specified are inclusive. start Index of the NodeCollection to start at end One past the index of the NodeCollection to stop at step Number of places between node IDs to skip. Defaults to 1 a NodeCollection pointer to the new, sliced NodeCollection.
References end, size, step, nest::NodeCollection::valid.
void nest::NodeCollectionComposite::set_metadata(NodeCollectionMetadataPTR) override
Sets the metadata of the NodeCollection.
meta A Metadata pointer
References parts_.
NodeCollectionMetadataPTR nest::NodeCollectionComposite::get_metadata() const override
Gets the metadata of the NodeCollection.
A Metadata pointer
References parts_.
Referenced by operator+.
bool nest::NodeCollectionComposite::is_range() const override
bool nest::NodeCollectionComposite::empty() const override
Checks if the NodeCollection has no elements.
true if the NodeCollection is empty, false otherwise
long nest::NodeCollectionComposite::find(const index) const override
Returns index of node with given node ID in NodeCollection.
Index of node with given node ID; -1 if node not in NodeCollection.
References begin, end, end_offset_, end_part_, parts_, size, start_offset_, start_part_, step_.
bool nest::NodeCollectionComposite::has_proxies() const override
Returns whether the NodeCollection contains any nodes with proxies or not.
true if any nodes in the NodeCollection has proxies, false otherwise.
References parts_.