SLIException
std::string SLIException::what_
Referenced by what.
SLIException::SLIException(char const *const what)
SLIException::SLIException(const std::string &what)
SLIException::~SLIException() override
const char * SLIException::what() const override
Returns the SLI error name, used by raiseerror.
Return name of the exception as C-style string. Use this name to translate the exception to a SLI error. For example: catch(IllegalOperation&e) { i->error("SetStatus","NodesmustbeaNodeCollectionorSynapseCollection."); i->raiseerror(e.what()); return; } The catch clause must be terminated with a return statement, if raiseerror was called.
References what_.
Referenced by SLIInterpreter::raiseerror.
virtual std::string SLIException::message() const =0
Returns a diagnostic message or empty string.
Referenced by SLIInterpreter::raiseerror, WrappedThreadException::WrappedThreadException.