SLIgraphics::ReadPGMFunction
std::istream * SLIgraphics::ReadPGMFunction::openPGMFile(StringDatum *) const
opens the file
Referenced by execute.
void SLIgraphics::ReadPGMFunction::readMagicNumber(std::istream *, char[2]) const
reads the magic number into string magic
Referenced by execute.
void SLIgraphics::ReadPGMFunction::initRead(std::istream *, int &, int &, int &) const
reads width, height, maxval
Referenced by execute.
void SLIgraphics::ReadPGMFunction::readImage(std::istream *, char[2], std::vector< long > &, int, int, int) const
reads the image
Referenced by execute.
void SLIgraphics::ReadPGMFunction::execute(SLIInterpreter *) const override
@BeginDocumentation Name:readPGM - read in grey-level image in PGM Format.
Synopsis:string readPGM -> int int int arraytype fname readPGM -> width height maxval [grayvals] Description:this function reads an image file in the PGM format and returns the width, height, maximum gray value and the image itself (as a linear array). On Unix systems, man pgm should give you a description of the PGM (Portable GrayMap) image format. Parameters:fname - name of file to be read [grayvals] - one-dim. array containing the pixel gray values, starting from the upper left corner of the image, continuing rowwise (normal englissh reading order). maxval - the maximum gray value width - width of image in pixels (no. of columns) height - height of image (no. of rows) Examples:(FancyImage.pgm) readPGM -> 16 24 255 [grayvals] This reads the image FancyImage.pgm, and tells you that it has 16 columns, 24 rows, and a maximum gray value of 255. The pixel gray values are stored in the array. Author:Schmuker, Gewaltig FirstVersion:9.1.2003 SeeAlso:writePGM
References SLIInterpreter::ArgumentTypeError, SLIInterpreter::BadIOError, Token::datum, SLIInterpreter::EStack, initRead, TokenStack::load, SLIInterpreter::M_ERROR, SLIInterpreter::message, openPGMFile, SLIInterpreter::OStack, TokenStack::pop, TokenStack::push, SLIInterpreter::raiseerror, readImage, readMagicNumber, SLIInterpreter::StackUnderflowError, TokenStack::top.