TokenArrayObj
Token* TokenArrayObj::p
Referenced by allocate, assign, assign_move, begin, capacity, clear, erase, get, index_is_valid, info, insert, insert_move, operator=, operator==, operator[], reduce, replace_move, size, TokenArrayObj, valid, ~TokenArrayObj.
Token* TokenArrayObj::begin_of_free_storage
Referenced by allocate, append_move, assign, assign_move, clear, end, erase, index_is_valid, info, insert, insert_move, operator=, pop_back, push_back, push_back_by_pointer, push_back_by_ref, push_back_move, reduce, replace_move, size, TokenArrayObj, valid.
Token* TokenArrayObj::end_of_free_storage
Referenced by allocate, append_move, capacity, clear, info, insert_move, operator=, valid.
unsigned int TokenArrayObj::alloc_block_size
Referenced by allocate, clear, info, push_back, push_back_by_pointer, push_back_by_ref, push_back_move, reserve, resize, shrink.
unsigned int TokenArrayObj::refs_
Referenced by add_reference, references, remove_reference.
size_t TokenArrayObj::allocations
Referenced by getallocations.
void TokenArrayObj::allocate(size_t, size_t, size_t, const Token &=Token())
References alloc_block_size, begin_of_free_storage, end_of_free_storage, p, size.
Referenced by reserve, resize, shrink.
TokenArrayObj::TokenArrayObj()
TokenArrayObj::TokenArrayObj(size_t, const Token &=Token(), size_t=0)
References resize.
TokenArrayObj::TokenArrayObj(const TokenArrayObj &)
References begin_of_free_storage, p, resize.
TokenArrayObj::~TokenArrayObj()
References p.
Token * TokenArrayObj::begin() const
References p.
Referenced by TokenArray::assign_move, TokenArray::begin, TokenStack::clear, TokenArray::erase, operator=, operator==, reduce, TokenArray::rotate.
Token * TokenArrayObj::end() const
References begin_of_free_storage.
Referenced by assign, assign_move, TokenStack::clear, TokenArray::end, erase, operator=, operator==, TokenStack::pick, TokenStack::pop, TokenStack::pop_move, reduce, replace_move, TokenStack::roll, TokenStack::swap, TokenStack::top.
size_t TokenArrayObj::size() const
References begin_of_free_storage, p.
Referenced by allocate, append_move, empty, erase, insert, insert_move, TokenStack::load, operator==, push_back, push_back_by_pointer, push_back_by_ref, push_back_move, reduce, replace_move, reserve, reserve_token, resize, shrink, TokenArray::size.
size_t TokenArrayObj::capacity() const
References end_of_free_storage, p.
Referenced by TokenArray::capacity, operator=, push_back, push_back_by_pointer, push_back_by_ref, push_back_move, reserve, reserve_token, shrink, TokenStack::size.
Token & TokenArrayObj::operator[](size_t i)
References p.
const Token & TokenArrayObj::operator[](size_t i) const
References p.
const Token & TokenArrayObj::get(long i) const
References p.
Referenced by TokenArray::get.
bool TokenArrayObj::index_is_valid(long i) const
References begin_of_free_storage, p.
Referenced by TokenArray::index_is_valid.
void TokenArrayObj::rotate(Token *, Token *, Token *)
Referenced by TokenStack::roll, TokenArray::rotate.
bool TokenArrayObj::shrink()
References alloc_block_size, allocate, capacity, size.
Referenced by TokenArray::shrink.
bool TokenArrayObj::reserve(size_t)
References alloc_block_size, allocate, capacity, size.
Referenced by append_move, assign, assign_move, insert, insert_move, push_back, push_back_by_pointer, push_back_by_ref, push_back_move, replace_move, TokenArray::reserve, reserve_token.
unsigned int TokenArrayObj::references()
References refs_.
Referenced by TokenArray::clone, TokenArray::detach, TokenArray::references.
unsigned int TokenArrayObj::remove_reference()
References refs_.
Referenced by TokenArray::clone, TokenArray::detach, TokenArray::operator=, TokenArray::~TokenArray.
unsigned int TokenArrayObj::add_reference()
References refs_.
Referenced by TokenArray::TokenArray.
void TokenArrayObj::resize(size_t, size_t, const Token &=Token())
References alloc_block_size, allocate, size.
Referenced by operator=, TokenArray::resize, resize, TokenArrayObj.
void TokenArrayObj::resize(size_t, const Token &=Token())
References alloc_block_size, resize.
void TokenArrayObj::reserve_token(size_t n)
References capacity, reserve, size.
void TokenArrayObj::push_back(const Token &t)
References alloc_block_size, begin_of_free_storage, capacity, reserve, size.
Referenced by TokenStack::push, TokenArray::push_back.
void TokenArrayObj::push_back_move(Token &t)
References alloc_block_size, begin_of_free_storage, capacity, reserve, size.
Referenced by TokenArray::push_back, TokenArray::push_back_dont_clone, TokenArray::push_back_move, TokenStack::push_move.
void TokenArrayObj::push_back_by_ref(const Token &t)
Push back a reference.
This function expects that enough space on the stack has been reserved and that the token points to a valid datum object.
References alloc_block_size, begin_of_free_storage, capacity, reserve, size.
Referenced by TokenStack::push_by_ref.
void TokenArrayObj::push_back_by_pointer(Datum *rhs)
Push back a datum pointer.
This function assumes that enough space on the stack has been reserved. This function expects a valid datum pointer and increases the reference count of the datum.
References alloc_block_size, begin_of_free_storage, capacity, reserve, size.
Referenced by TokenStack::push_by_pointer.
void TokenArrayObj::assign_move(Token *tp, Token &t)
Referenced by TokenArray::assign_move.
void TokenArrayObj::pop_back()
References begin_of_free_storage, clear.
Referenced by TokenStack::pop, TokenArray::pop_back, TokenStack::pop_move.
void TokenArrayObj::erase(size_t, size_t)
References erase, p, size.
Referenced by TokenStack::clear, erase, TokenArray::erase, TokenStack::pop.
void TokenArrayObj::erase(Token *, Token *)
References begin_of_free_storage, end, Datum::removeReference.
void TokenArrayObj::erase(Token *tp)
References erase.
void TokenArrayObj::reduce(Token *, Token *)
References begin, begin_of_free_storage, end, p.
Referenced by TokenArray::reduce, reduce.
void TokenArrayObj::reduce(size_t, size_t)
References p, reduce, size.
void TokenArrayObj::insert(size_t, size_t=1, const Token &=Token())
References begin_of_free_storage, p, reserve, size.
Referenced by insert.
void TokenArrayObj::insert(size_t i, const Token &t)
References insert.
void TokenArrayObj::insert_move(size_t, TokenArrayObj &)
References begin_of_free_storage, end_of_free_storage, p, reserve, size.
Referenced by TokenArray::insert_move.
void TokenArrayObj::insert_move(size_t, Token &)
References begin_of_free_storage, end_of_free_storage, p, Token::p, reserve, size.
void TokenArrayObj::assign_move(TokenArrayObj &, size_t, size_t)
References begin_of_free_storage, end, p, reserve.
void TokenArrayObj::assign(const TokenArrayObj &, size_t, size_t)
References begin_of_free_storage, end, p, reserve.
Referenced by TokenArray::assign_move.
void TokenArrayObj::replace_move(size_t, size_t, TokenArrayObj &)
References begin_of_free_storage, end, p, Datum::removeReference, reserve, size.
Referenced by TokenArray::replace_move.
void TokenArrayObj::append_move(TokenArrayObj &)
References begin_of_free_storage, end_of_free_storage, reserve, size.
Referenced by TokenArray::append_move.
void TokenArrayObj::clear()
References alloc_block_size, begin_of_free_storage, end_of_free_storage, p.
Referenced by pop_back.
const TokenArrayObj & TokenArrayObj::operator=(const TokenArrayObj &)
References begin, begin_of_free_storage, capacity, end, end_of_free_storage, p, resize.
bool TokenArrayObj::operator==(const TokenArrayObj &) const
References begin, end, p, size.
bool TokenArrayObj::empty() const
References size.
void TokenArrayObj::info(std::ostream &) const
References alloc_block_size, begin_of_free_storage, end_of_free_storage, p.
bool TokenArrayObj::valid() const
References begin_of_free_storage, end_of_free_storage, p.
Referenced by TokenArray::valid.
static size_t TokenArrayObj::getallocations()
References allocations.
Referenced by Allocations_aFunction::execute.