nest::Model
std::string nest::Model::name_
Name of the Model.
This name will be used to identify all Nodes which are created by this model object.
Referenced by get_name.
index nest::Model::type_id_
Identifier of the model C++ type.
For pristine models, the type_id equals the model_id. For copied models, the type_id equals the type_id of the base model. This number is needed to automatically save and restore copied models.
Referenced by get_status, get_type_id, set_type_id.
std::vector< std::vector< Node* > > nest::Model::memory_
Memory for all nodes sorted by threads.
Referenced by clear, create, get_status, mem_available, mem_capacity, reserve_additional, set_threads_.
nest::Model::Model(const std::string &name)
nest::Model::Model(const Model &m)
virtual nest::Model::~Model()
virtual Model* nest::Model::clone(const std::string &) const =0
Create clone with new name.
Referenced by nest::ModelManager::copy_node_model_.
void nest::Model::set_threads()
Set number of threads based on number set in network.
As long as no nodes of the model have been allocated, the number of threads may be changed. Requires that network pointer in NestModule is initialized.
References nest::kernel, set_threads_.
Referenced by nest::GenericModel< ElementT >::GenericModel, nest::ModelManager::initialize.
Node * nest::Model::create(thread t)
Allocate new Node and return its pointer.
create() is not const, because it is allowed to modify the Model object for 'administrative' purposes.
References create_, memory_, nest::names::n.
Referenced by nest::ModelManager::create_proxynode_.
void nest::Model::clear()
Deletes all nodes which belong to this model.
References memory_, set_threads_.
void nest::Model::reserve_additional(thread t, size_t n)
Reserve space for n additional Nodes.
References memory_, nest::names::n.
std::string nest::Model::get_name() const
Return name of the Model.
This function returns the name of the Model as C++ string. The name is defined by the constructor. The result is identical to the value of Node::get_name(); Model::Model() Node::get_name()
References name_.
Referenced by nest::ModelManager::compare_model_by_id_, nest::Node::get_name, get_status, set_status.
size_t nest::Model::mem_available()
Return the available memory.
The result is given in number of elements, not in bytes. Note that this function reports a sum over all threads.
References memory_.
size_t nest::Model::mem_capacity()
Return the memory capacity.
The result is given in number of elements, not in bytes. Note that this function reports a sum over all threads.
References memory_.
virtual bool nest::Model::has_proxies()=0
virtual bool nest::Model::one_node_per_process()=0
virtual bool nest::Model::is_off_grid()=0
virtual void nest::Model::calibrate_time(const TimeConverter &tc)=0
void nest::Model::set_status(DictionaryDatum)
Change properties of the prototype node according to the entries in the dictionary.
d Dictionary with named parameter settings.
References nest::names::d, numerics::e, get_name, set_status_.
Referenced by nest::ModelManager::set_node_defaults_.
DictionaryDatum nest::Model::get_status()
Export properties of the prototype node by setting entries in the status dictionary.
d Dictionary.
References nest::names::available, nest::names::capacity, nest::names::d, get_name, get_status_, nest::names::instantiations, nest::kernel, memory_, nest::names::model, nest::names::type_id, type_id_.
Referenced by nest::get_model_defaults.
virtual port nest::Model::send_test_event(Node &, rport, synindex, bool)=0
virtual void nest::Model::sends_secondary_event(GapJunctionEvent &ge)=0
Referenced by nest::proxynode::sends_secondary_event.
virtual void nest::Model::sends_secondary_event(InstantaneousRateConnectionEvent &re)=0
virtual void nest::Model::sends_secondary_event(DiffusionConnectionEvent &de)=0
virtual void nest::Model::sends_secondary_event(DelayedRateConnectionEvent &re)=0
virtual SignalType nest::Model::sends_signal() const =0
Check what type of signal this model is sending.
Required so that proxynode can formward this call to model that in turn delegates the call to the underlying prototype.
Referenced by nest::proxynode::sends_signal.
virtual size_t nest::Model::get_element_size() const =0
Return the size of the prototype.
virtual Node const& nest::Model::get_prototype() const =0
Return const reference to the prototype.
virtual void nest::Model::set_model_id(int)=0
Set the model id on the prototype.
Referenced by nest::ModelManager::copy_node_model_, nest::ModelManager::register_node_model_.
virtual int nest::Model::get_model_id()=0
Get the model id from the prototype.
virtual void nest::Model::deprecation_warning(const std::string &)=0
Issue deprecation warning on first call if model is deprecated.
calling function
Referenced by nest::ModelManager::copy_node_model_.
void nest::Model::set_type_id(index id)
Set the model id on the prototype.
References type_id_.
Referenced by nest::GenericModel< ElementT >::GenericModel, nest::ModelManager::initialize.
index nest::Model::get_type_id() const
References type_id_.
Referenced by nest::GenericModel< ElementT >::GenericModel.
virtual void nest::Model::set_status_(DictionaryDatum)=0
Referenced by set_status.
virtual DictionaryDatum nest::Model::get_status_()=0
Referenced by get_status.
void nest::Model::set_threads_(thread t)
Set the number of threads.
set_threads()
References memory_.
Referenced by clear, set_threads.
virtual Node* nest::Model::create_()=0
Create a new object.
Referenced by create.