nest::RandomManager
std::map< std::string, BaseRandomGeneratorFactory* > nest::RandomManager::rng_types_
Available RNG types.
std::string nest::RandomManager::current_rng_type_
Name of currently used RNG type.
std::uint32_t nest::RandomManager::base_seed_
Base seed used when RNGs were last created.
RngPtr nest::RandomManager::rank_synced_rng_
Random number generator synchronized across ranks.
std::vector< RngPtr > nest::RandomManager::vp_synced_rngs_
Random number generators synchronized across VPs.
std::vector< RngPtr > nest::RandomManager::vp_specific_rngs_
Random number generators specific to VPs.
const std::string nest::RandomManager::DEFAULT_RNG_TYPE_
RNG type used by default.
const std::uint32_t nest::RandomManager::DEFAULT_BASE_SEED_
Base seed used by default.
const std::uint32_t nest::RandomManager::RANK_SYNCED_SEEDER_
Rank-synchronized seed-sequence initializer component.
const std::uint32_t nest::RandomManager::THREAD_SYNCED_SEEDER_
Thread-synchronized seed-sequence initializer component.
const std::uint32_t nest::RandomManager::THREAD_SPECIFIC_SEEDER_
Thread-specific seed-sequence initializer component.
nest::RandomManager::RandomManager()
nest::RandomManager::~RandomManager() override
void nest::RandomManager::initialize() override
Register available RNG types, set default RNG type and create RNGs.
void nest::RandomManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
void nest::RandomManager::change_number_of_threads() override
Change the number of threads.
Many data structures within the different managers depend on the number of threads. This function is called on each manager upon a change of that number and allows the manager to re-allocate data structures accordingly.
void nest::RandomManager::set_status(const DictionaryDatum &) override
References nest::names::local_num_threads, nest::names::rng_seed, nest::names::rng_type.
void nest::RandomManager::get_status(DictionaryDatum &) override
References nest::names::rng_seed, nest::names::rng_type, nest::names::rng_types.
RngPtr nest::RandomManager::get_rank_synced_rng() const
Get rank-synchronized random number generator.
The rank-synchronized generator provides identical random number sequences on all MPI ranks. It may be used only by the master thread on each rank and must be used in lock-step across all ranks. Synchronization is checked by MPI exchange at certain points during a simulation.
Referenced by nest::get_rank_synced_rng.
RngPtr nest::RandomManager::get_vp_synced_rng(thread tid) const
Get VP-synchronized random number generator.
The kernel maintains one instance of a synchronized random number generator for each thread (and thus, across ranks, for each VP). The purpose of these synchronized generators is to provide identical random number sequences on each VP while VPs execute in parallel. All VPs (ie all threads on all ranks) must use the generators in lock-step to maintain synchrony. Synchronization is checked by MPI exchange at certain points during a simulation. tid ID of thread requesting generator
Referenced by nest::get_vp_synced_rng.
RngPtr nest::RandomManager::get_vp_specific_rng(thread tid) const
Get VP-specific random number generator.
Each VP (thread) can use this RNG freely and will receive an independent random number sequence.
Referenced by nest::get_vp_specific_rng.
void nest::RandomManager::check_rng_synchrony() const
Confirm that rank- and thread-synchronized RNGs are in sync.
KernelException if RNGs are out of sync.
References nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::SimulationManager::run.
void nest::RandomManager::register_rng_type(std::string name)
Register new random number generator type with manager.
This allows NEST modules to add new RNG types. RNG_TYPE Class fulfilling requirements of C++ RNG.
void nest::RandomManager::reset_rngs_()
Replace current RNGs with newly seeded generators.
The new generators will be of type current_rng_type_ and will be seeded using base_seed_.
References nest::VPManager::get_thread_id, nest::VPManager::get_vp, nest::kernel, nest::KernelManager::vp_manager.