SLIInterpreter
const int SLIInterpreter::M_ALL
Predefined error level for turning on the display of all messages; for use with verbosity(int).
Referenced by SLIStartup::SLIStartup.
const int SLIInterpreter::M_DEBUG
Predefined error level for debugging messages.
Referenced by Processes::ForkFunction::execute, SLIStartup::init, message, SLIStartup::SLIStartup.
const int SLIInterpreter::M_STATUS
Predefined error level for status messages.
Referenced by message, SLIStartup::SLIStartup.
const int SLIInterpreter::M_INFO
Predefined error level for informational messages.
Referenced by backtrace_off, backtrace_on, Get_a_aFunction::execute, message, SLIStartup::SLIStartup, toggle_stack_display.
const int SLIInterpreter::M_DEPRECATED
Predefined error level for deprecation warnings.
Referenced by FunctionDatum::execute, message, SLIStartup::SLIStartup.
const int SLIInterpreter::M_PROGRESS
Predefined error level for progress messages.
Referenced by message.
const int SLIInterpreter::M_WARNING
Predefined error level for warning messages.
Referenced by message, SLIStartup::SLIStartup.
const int SLIInterpreter::M_ERROR
Predefined error level for error messages.
Referenced by addmodule, FilesystemModule::CopyFileFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, StartFunction::execute, RaiseerrorFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, Get_a_aFunction::execute, Join_sFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, AddtotrieFunction::execute, message, print_error, SLIStartup::SLIStartup.
const int SLIInterpreter::M_FATAL
Predefined error level for failure messages.
Referenced by execute_, execute_debug_, SLIStartup::init, message, SLIStartup::SLIStartup, terminate.
const int SLIInterpreter::M_QUIET
An error level above all others.
Use to turn off messages completely.
Referenced by SLIStartup::SLIStartup.
std::list< SLIModule* > SLIInterpreter::modules
Referenced by addmodule, ~SLIInterpreter.
bool SLIInterpreter::debug_mode_
True, if SLI level debugging is enabled.
Referenced by debug_commandline, debug_mode_off, debug_mode_on, get_debug_mode, step_mode.
bool SLIInterpreter::show_stack_
Show stack in debug mode.
Referenced by debug_commandline, toggle_stack_display.
bool SLIInterpreter::show_backtrace_
Show stack-backtrace on error.
Referenced by backtrace_off, backtrace_on, debug_commandline, show_backtrace.
bool SLIInterpreter::catch_errors_
Enter debugger on error.
Referenced by catch_errors, catch_errors_off, catch_errors_on, debug_commandline.
bool SLIInterpreter::opt_tailrecursion_
Optimize tailing recursion.
Referenced by backtrace_off, backtrace_on, debug_commandline, optimize_tailrecursion, optimize_tailrecursion_off, optimize_tailrecursion_on.
int SLIInterpreter::call_depth_
Current depth of procedure calls.
Referenced by debug_commandline, dec_call_depth, get_call_depth, inc_call_depth, set_call_depth, step_mode.
int SLIInterpreter::max_call_depth_
Depth until which procedure calls are debugged.
Referenced by debug_commandline, get_max_call_depth, set_max_call_depth, step_mode.
unsigned long SLIInterpreter::cycle_count
Referenced by cycles, execute_, execute_debug_.
bool SLIInterpreter::cycle_guard
Referenced by removecycleguard, setcycleguard.
unsigned long SLIInterpreter::cycle_restriction
Referenced by setcycleguard.
int SLIInterpreter::verbositylevel
Referenced by message, verbosity.
unsigned long SLIInterpreter::code_accessed
Referenced by ProceduretypeFunction::execute, CodeAccessedFunction::execute.
unsigned long SLIInterpreter::code_executed
Referenced by IiterateFunction::execute, CodeExecutedFunction::execute.
Dictionary* SLIInterpreter::statusdict
Referenced by execute_, execute_debug_, SLIStartup::init, initdictionaries, terminate.
Dictionary* SLIInterpreter::errordict
Referenced by execute_, execute_debug_, initdictionaries, print_error, raiseagain, raiseerror, raisesignal, SLIInterpreter.
DictionaryStack* SLIInterpreter::DStack
Referenced by basedef, basedef_move, baseknown, baselookup, createcommand, createconstant, createdouble, def, def_move, OOSupportModule::CallMemberFunction::execute, DictputFunction::execute, DictbeginFunction::execute, DictendFunction::execute, DicttopinfoFunction::execute, WhoFunction::execute, DictstackFunction::execute, CurrentdictFunction::execute, CountdictstackFunction::execute, CleardictstackFunction::execute, CleardictFunction::execute, UndefFunction::execute, RestoredstackFunction::execute, initdictionaries, known, lookup, lookup2, raiseerror, undef, ~SLIInterpreter.
Parser* SLIInterpreter::parse
Referenced by IparsestdinFunction::execute, ParsestdinFunction::execute, IparseFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, SLIInterpreter, ~SLIInterpreter.
Name SLIInterpreter::ilookup_name
Referenced by CurrentnameFunction::execute, Ilookup, initbuiltins.
Name SLIInterpreter::ipop_name
Referenced by SwitchFunction::execute, SwitchdefaultFunction::execute, initbuiltins.
Name SLIInterpreter::isetcallback_name
Referenced by CallbacktypeFunction::execute, initbuiltins.
Name SLIInterpreter::iiterate_name
Referenced by Iiterate, initbuiltins.
Name SLIInterpreter::iloop_name
Referenced by LoopFunction::execute, initbuiltins.
Name SLIInterpreter::irepeat_name
Referenced by RepeatFunction::execute, initbuiltins.
Name SLIInterpreter::ifor_name
Referenced by ForFunction::execute, initbuiltins.
Name SLIInterpreter::iforallarray_name
Referenced by Forall_aFunction::execute, initbuiltins.
Name SLIInterpreter::iforallindexedarray_name
Referenced by Forallindexed_aFunction::execute, initbuiltins.
Name SLIInterpreter::iforallindexedstring_name
Referenced by Forallindexed_sFunction::execute, initbuiltins.
Name SLIInterpreter::iforallstring_name
Referenced by Forall_sFunction::execute, initbuiltins.
Name SLIInterpreter::pi_name
Referenced by initbuiltins.
Name SLIInterpreter::e_name
Referenced by initbuiltins.
Name SLIInterpreter::iparse_name
Referenced by debug_commandline, XIstreamtypeFunction::execute, XIfstreamtypeFunction::execute, SLIStartup::init.
Name SLIInterpreter::stop_name
Referenced by debug_commandline, raiseagain, raiseerror.
Name SLIInterpreter::end_name
Referenced by OOSupportModule::CallMemberFunction::execute, init_slidict.
Name SLIInterpreter::null_name
Name SLIInterpreter::true_name
Referenced by FilesystemModule::CompareFilesFunction::execute, CaseFunction::execute, Empty_aFunction::execute, Shrink_aFunction::execute, Empty_sFunction::execute, Search_sFunction::execute, Search_aFunction::execute, RegexpModule::RegcompFunction::execute, SLIStartup::GetenvFunction::execute, execute_, execute_debug_, init_slicontrol, raiseagain, raiseerror.
Name SLIInterpreter::false_name
Referenced by FilesystemModule::CompareFilesFunction::execute, CaseFunction::execute, Empty_aFunction::execute, Shrink_aFunction::execute, Empty_sFunction::execute, Search_sFunction::execute, Search_aFunction::execute, RegexpModule::RegcompFunction::execute, SLIStartup::GetenvFunction::execute, init_slicontrol, raiseerror, SLIInterpreter.
Name SLIInterpreter::mark_name
Referenced by debug_commandline, SLIArrayModule::MapFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, LoopFunction::execute, ExitFunction::execute, RepeatFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CounttomarkFunction::execute, RepeatanyFunction::execute, DictconstructFunction::execute, init_slicontrol.
Name SLIInterpreter::istopped_name
Referenced by StoppedFunction::execute, StopFunction::execute, init_slicontrol.
Name SLIInterpreter::systemdict_name
Referenced by initdictionaries.
Name SLIInterpreter::userdict_name
Referenced by initdictionaries.
Name SLIInterpreter::errordict_name
Referenced by Processes::init, initdictionaries, Processes::systemerror.
Name SLIInterpreter::quitbyerror_name
Referenced by execute_, execute_debug_, SLIInterpreter.
Name SLIInterpreter::newerror_name
Referenced by init_slicontrol, raiseagain, raiseerror.
Name SLIInterpreter::errorname_name
Referenced by print_error, raiseerror.
Name SLIInterpreter::commandname_name
Referenced by raiseagain, raiseerror.
Name SLIInterpreter::signo_name
Referenced by raisesignal.
Name SLIInterpreter::recordstacks_name
Referenced by init_slicontrol, raiseerror.
Name SLIInterpreter::estack_name
Referenced by raiseerror.
Name SLIInterpreter::ostack_name
Referenced by raiseerror.
Name SLIInterpreter::dstack_name
Referenced by raiseerror.
Name SLIInterpreter::commandstring_name
Referenced by addlinkedusermodule, addmodule, initexternals, neststartup.
Name SLIInterpreter::interpreter_name
Referenced by getcurrentname.
Name SLIInterpreter::ArgumentTypeError
Referenced by eq_execute, PrintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Put_iv_i_iFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, LoopFunction::execute, LoadFunction::execute, LookupFunction::execute, CaseFunction::execute, Get_a_aFunction::execute, Join_sFunction::execute, DictbeginFunction::execute, DictconstructFunction::execute, RestoredstackFunction::execute, SLIgraphics::ReadPGMFunction::execute, Mod_iiFunction::execute, Inv_dFunction::execute, TrieFunction::execute, AddtotrieFunction::execute.
Name SLIInterpreter::StackUnderflowError
Referenced by eq_execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, LoopFunction::execute, LookupFunction::execute, DebugFunction::execute, DictbeginFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, Mod_iiFunction::execute, Inv_dFunction::execute, PopFunction::execute, NpopFunction::execute, DupFunction::execute, ExchFunction::execute, IndexFunction::execute, RollFunction::execute, RolluFunction::execute, RolldFunction::execute, OverFunction::execute, CopyFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, TrieFunction::execute, AddtotrieFunction::execute, TypeFunction::execute.
Name SLIInterpreter::UndefinedNameError
Referenced by LoadFunction::execute.
Name SLIInterpreter::WriteProtectedError
Name SLIInterpreter::DivisionByZeroError
Referenced by SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArangeFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute.
Name SLIInterpreter::RangeCheckError
Referenced by SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, RollFunction::execute.
Name SLIInterpreter::PositiveIntegerExpectedError
Referenced by Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute.
Name SLIInterpreter::BadIOError
Referenced by StrFunction::execute, FilesystemModule::FileNamesFunction::execute, FilesystemModule::DirectoryFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute.
Name SLIInterpreter::StringStreamExpectedError
Referenced by StrFunction::execute.
Name SLIInterpreter::CycleGuardError
Name SLIInterpreter::SystemSignal
Name SLIInterpreter::BadErrorHandler
Referenced by raiseagain, raiseerror.
Name SLIInterpreter::KernelError
Name SLIInterpreter::InternalKernelError
Token SLIInterpreter::execbarrier_token
Token SLIInterpreter::ct
Referenced by CallbacktypeFunction::execute, IsetcallbackFunction::execute.
TokenStack SLIInterpreter::OStack
Referenced by assert_stack_load, debug_commandline, eq_execute, execute, nest::NestModule::Disconnect_aFunction::execute, OstrstreamFunction::execute, StrFunction::execute, nest::NestModule::GetStatus_gFunction::execute, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::NestModule::GetMetadata_gFunction::execute, nest::NestModule::GetKernelStatus_Function::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::SetStatus_CDFunction::execute, nest::NestModule::SetKernelStatus_DFunction::execute, nest::NestModule::Cva_CFunction::execute, nest::NestModule::SetStatus_aaFunction::execute, nest::NestModule::SetDefaults_l_DFunction::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::CopyModel_l_l_DFunction::execute, nest::NestModule::GetConnections_DFunction::execute, nest::NestModule::SimulateFunction::execute, nest::NestModule::RunFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::PrintNodesToStreamFunction::execute, nest::NestModule::RankFunction::execute, nest::NestModule::NumProcessesFunction::execute, nest::NestModule::SetFakeNumProcesses_iFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::ProcessorNameFunction::execute, nest::NestModule::Cvdict_CFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::Cvnodecollection_iaFunction::execute, nest::NestModule::Cvnodecollection_ivFunction::execute, nest::NestModule::Cva_gFunction::execute, nest::NestModule::Size_gFunction::execute, nest::NestModule::ValidQ_gFunction::execute, nest::NestModule::Join_g_gFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::eq_gFunction::execute, nest::NestModule::BeginIterator_gFunction::execute, nest::NestModule::EndIterator_gFunction::execute, nest::NestModule::GetNodeID_qFunction::execute, nest::NestModule::GetNodeIDModelID_qFunction::execute, nest::NestModule::Next_qFunction::execute, nest::NestModule::Eq_q_qFunction::execute, nest::NestModule::Lt_q_qFunction::execute, nest::NestModule::Get_g_iFunction::execute, nest::NestModule::Take_g_aFunction::execute, nest::NestModule::SetStdpEps_dFunction::execute, nest::NestModule::Mul_P_PFunction::execute, nest::NestModule::Div_P_PFunction::execute, nest::NestModule::Add_P_PFunction::execute, nest::NestModule::Sub_P_PFunction::execute, nest::NestModule::Compare_P_P_DFunction::execute, nest::NestModule::Conditional_P_P_PFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Exp_PFunction::execute, nest::NestModule::Sin_PFunction::execute, nest::NestModule::Cos_PFunction::execute, nest::NestModule::Pow_P_dFunction::execute, nest::NestModule::Dimension2d_P_PFunction::execute, nest::NestModule::Dimension3d_P_P_PFunction::execute, nest::NestModule::CreateParameter_DFunction::execute, nest::NestModule::GetValue_PFunction::execute, nest::NestModule::IsSpatial_PFunction::execute, nest::NestModule::Apply_P_DFunction::execute, nest::NestModule::Apply_P_gFunction::execute, nest::NestModule::CreateLayer_D_DFunction::execute, nest::NestModule::GetPosition_gFunction::execute, nest::NestModule::Displacement_g_gFunction::execute, nest::NestModule::Displacement_a_gFunction::execute, nest::NestModule::Distance_g_gFunction::execute, nest::NestModule::Distance_a_gFunction::execute, nest::NestModule::Distance_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute, nest::NestModule::CreateMask_DFunction::execute, nest::NestModule::GetLayerStatus_gFunction::execute, nest::NestModule::Inside_a_MFunction::execute, nest::NestModule::And_M_MFunction::execute, nest::NestModule::Or_M_MFunction::execute, nest::NestModule::Sub_M_MFunction::execute, nest::NestModule::DumpLayerNodes_os_gFunction::execute, nest::NestModule::DumpLayerConnections_os_g_g_lFunction::execute, nest::NestModule::Cvdict_MFunction::execute, nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, FilesystemModule::FileNamesFunction::execute, FilesystemModule::DirectoryFunction::execute, FilesystemModule::TmpNamFunction::execute, FilesystemModule::CompareFilesFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::ForkFunction::execute, Processes::Sysexec_aFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::PipeFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::AvailableFunction::execute, Processes::GetPIDFunction::execute, Processes::GetPPIDFunction::execute, Processes::GetPGRPFunction::execute, Processes::MkfifoFunction::execute, Processes::SetNonblockFunction::execute, Processes::CtermidFunction::execute, Processes::Isatty_isFunction::execute, Processes::Isatty_osFunction::execute, MathLinkPutStringFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IClearFunction::execute, OClearFunction::execute, IFailFunction::execute, OGoodFunction::execute, Cvx_fFunction::execute, IEofFunction::execute, OEofFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, DatatypeFunction::execute, LitproceduretypeFunction::execute, TrietypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::ReverseFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::FlattenFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::TransposeFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::ValidFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Put_iv_i_iFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, SLIArrayModule::Iforall_ivFunction::execute, SLIArrayModule::Iforall_dvFunction::execute, IiterateFunction::execute, IloopFunction::execute, IrepeatFunction::execute, IforFunction::execute, IforallarrayFunction::execute, IforallindexedarrayFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, OStackdumpFunction::execute, LoopFunction::execute, IfFunction::execute, IfelseFunction::execute, RepeatFunction::execute, StoppedFunction::execute, StopFunction::execute, CurrentnameFunction::execute, DefFunction::execute, SetFunction::execute, LoadFunction::execute, LookupFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, RaiseerrorFunction::execute, PrinterrorFunction::execute, CyclesFunction::execute, CodeAccessedFunction::execute, CodeExecutedFunction::execute, ExecFunction::execute, TypeinfoFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CaseFunction::execute, CounttomarkFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, TimeFunction::execute, Sleep_dFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, SetGuardFunction::execute, MessageFunction::execute, SetVerbosityFunction::execute, VerbosityFunction::execute, DebugFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Allocations_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Append_aFunction::execute, Append_pFunction::execute, Append_sFunction::execute, Prepend_aFunction::execute, Prepend_pFunction::execute, Prepend_sFunction::execute, Join_sFunction::execute, Join_aFunction::execute, Join_pFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Length_sFunction::execute, Length_aFunction::execute, Length_pFunction::execute, Length_lpFunction::execute, Capacity_aFunction::execute, Size_aFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Empty_aFunction::execute, References_aFunction::execute, Shrink_aFunction::execute, Capacity_sFunction::execute, Size_sFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Empty_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Cvx_aFunction::execute, Cvlit_nFunction::execute, Cvlit_pFunction::execute, Cvlp_pFunction::execute, Cvn_sFunction::execute, Cvn_lFunction::execute, Cvi_sFunction::execute, Cvd_sFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, Search_sFunction::execute, Search_aFunction::execute, RepeatanyFunction::execute, DictFunction::execute, DictputFunction::execute, DictgetFunction::execute, DictbeginFunction::execute, DictinfoFunction::execute, DicttopinfoFunction::execute, WhoFunction::execute, DictconstructFunction::execute, DictstackFunction::execute, CurrentdictFunction::execute, CountdictstackFunction::execute, Length_dFunction::execute, Empty_DFunction::execute, CleardictFunction::execute, ClonedictFunction::execute, UndefFunction::execute, KnownFunction::execute, Cva_dFunction::execute, KeysFunction::execute, ValuesFunction::execute, RestoredstackFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, Add_diFunction::execute, Add_iiFunction::execute, Add_idFunction::execute, Add_ddFunction::execute, Sub_diFunction::execute, Sub_iiFunction::execute, Sub_idFunction::execute, Sub_ddFunction::execute, Mul_diFunction::execute, Mul_iiFunction::execute, Mul_idFunction::execute, Mul_ddFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute, Sin_dFunction::execute, Asin_dFunction::execute, Cos_dFunction::execute, Acos_dFunction::execute, Exp_dFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqr_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, Modf_dFunction::execute, Frexp_dFunction::execute, Ldexp_diFunction::execute, Dexp_iFunction::execute, Abs_iFunction::execute, Abs_dFunction::execute, Neg_iFunction::execute, Neg_dFunction::execute, Inv_dFunction::execute, EqFunction::execute, NeqFunction::execute, AndFunction::execute, OrFunction::execute, And_iiFunction::execute, Or_iiFunction::execute, XorFunction::execute, Not_bFunction::execute, Not_iFunction::execute, Geq_iiFunction::execute, Geq_idFunction::execute, Geq_diFunction::execute, Geq_ddFunction::execute, Leq_iiFunction::execute, Leq_idFunction::execute, Leq_diFunction::execute, Leq_ddFunction::execute, Gt_iiFunction::execute, Gt_ddFunction::execute, Gt_idFunction::execute, Gt_diFunction::execute, Gt_ssFunction::execute, Lt_iiFunction::execute, Lt_ddFunction::execute, Lt_idFunction::execute, Lt_diFunction::execute, Lt_ssFunction::execute, IntegerFunction::execute, DoubleFunction::execute, UnitStep_iFunction::execute, UnitStep_dFunction::execute, UnitStep_iaFunction::execute, UnitStep_daFunction::execute, Round_dFunction::execute, Floor_dFunction::execute, Ceil_dFunction::execute, Max_i_iFunction::execute, Max_i_dFunction::execute, Max_d_iFunction::execute, Max_d_dFunction::execute, Min_i_iFunction::execute, Min_i_dFunction::execute, Min_d_iFunction::execute, Min_d_dFunction::execute, RegexpModule::RegcompFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute, PopFunction::execute, NpopFunction::execute, DupFunction::execute, ExchFunction::execute, IndexFunction::execute, RollFunction::execute, RolluFunction::execute, RolldFunction::execute, RotFunction::execute, OverFunction::execute, CountFunction::execute, CopyFunction::execute, ClearFunction::execute, ExecstackFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, OperandstackFunction::execute, SLIStartup::GetenvFunction::execute, TrieFunction::execute, TrieInfoFunction::execute, AddtotrieFunction::execute, Cva_tFunction::execute, Cvt_aFunction::execute, TypeFunction::execute, ToUppercase_sFunction::execute, ToLowercase_sFunction::execute, execute_, execute_debug_, raiseagain, raiseerror, ~SLIInterpreter.
TokenStack SLIInterpreter::EStack
Referenced by SLIArrayModule::IMapFunction::backtrace, SLIArrayModule::IMap_ivFunction::backtrace, SLIArrayModule::IMap_dvFunction::backtrace, SLIArrayModule::IMapThreadFunction::backtrace, SLIArrayModule::IMapIndexedFunction::backtrace, SLIArrayModule::Iforall_ivFunction::backtrace, SLIArrayModule::Iforall_dvFunction::backtrace, IiterateFunction::backtrace, IloopFunction::backtrace, IrepeatFunction::backtrace, IforFunction::backtrace, IforallarrayFunction::backtrace, IforallindexedarrayFunction::backtrace, IforallindexedstringFunction::backtrace, IforallstringFunction::backtrace, debug_commandline, eq_execute, execute, nest::NestModule::Disconnect_aFunction::execute, OstrstreamFunction::execute, StrFunction::execute, nest::NestModule::GetStatus_gFunction::execute, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::NestModule::GetMetadata_gFunction::execute, nest::NestModule::GetKernelStatus_Function::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::SetStatus_CDFunction::execute, nest::NestModule::SetKernelStatus_DFunction::execute, nest::NestModule::Cva_CFunction::execute, nest::NestModule::SetStatus_aaFunction::execute, nest::NestModule::SetDefaults_l_DFunction::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::CopyModel_l_l_DFunction::execute, nest::NestModule::GetConnections_DFunction::execute, nest::NestModule::SimulateFunction::execute, nest::NestModule::PrepareFunction::execute, nest::NestModule::RunFunction::execute, nest::NestModule::CleanupFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::ResetKernelFunction::execute, nest::NestModule::MemoryInfoFunction::execute, nest::NestModule::PrintNodesFunction::execute, nest::NestModule::PrintNodesToStreamFunction::execute, nest::NestModule::RankFunction::execute, nest::NestModule::NumProcessesFunction::execute, nest::NestModule::SetFakeNumProcesses_iFunction::execute, nest::NestModule::SyncProcessesFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::ProcessorNameFunction::execute, nest::NestModule::Cvdict_CFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::Cvnodecollection_iaFunction::execute, nest::NestModule::Cvnodecollection_ivFunction::execute, nest::NestModule::Cva_gFunction::execute, nest::NestModule::Size_gFunction::execute, nest::NestModule::ValidQ_gFunction::execute, nest::NestModule::Join_g_gFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::eq_gFunction::execute, nest::NestModule::BeginIterator_gFunction::execute, nest::NestModule::EndIterator_gFunction::execute, nest::NestModule::GetNodeID_qFunction::execute, nest::NestModule::GetNodeIDModelID_qFunction::execute, nest::NestModule::Next_qFunction::execute, nest::NestModule::Eq_q_qFunction::execute, nest::NestModule::Lt_q_qFunction::execute, nest::NestModule::Get_g_iFunction::execute, nest::NestModule::Take_g_aFunction::execute, nest::NestModule::EnableStructuralPlasticity_Function::execute, nest::NestModule::DisableStructuralPlasticity_Function::execute, nest::NestModule::SetStdpEps_dFunction::execute, nest::NestModule::Mul_P_PFunction::execute, nest::NestModule::Div_P_PFunction::execute, nest::NestModule::Add_P_PFunction::execute, nest::NestModule::Sub_P_PFunction::execute, nest::NestModule::Compare_P_P_DFunction::execute, nest::NestModule::Conditional_P_P_PFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Exp_PFunction::execute, nest::NestModule::Sin_PFunction::execute, nest::NestModule::Cos_PFunction::execute, nest::NestModule::Pow_P_dFunction::execute, nest::NestModule::Dimension2d_P_PFunction::execute, nest::NestModule::Dimension3d_P_P_PFunction::execute, nest::NestModule::CreateParameter_DFunction::execute, nest::NestModule::GetValue_PFunction::execute, nest::NestModule::IsSpatial_PFunction::execute, nest::NestModule::Apply_P_DFunction::execute, nest::NestModule::Apply_P_gFunction::execute, nest::NestModule::CreateLayer_D_DFunction::execute, nest::NestModule::GetPosition_gFunction::execute, nest::NestModule::Displacement_g_gFunction::execute, nest::NestModule::Displacement_a_gFunction::execute, nest::NestModule::Distance_g_gFunction::execute, nest::NestModule::Distance_a_gFunction::execute, nest::NestModule::Distance_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute, nest::NestModule::CreateMask_DFunction::execute, nest::NestModule::GetLayerStatus_gFunction::execute, nest::NestModule::Inside_a_MFunction::execute, nest::NestModule::And_M_MFunction::execute, nest::NestModule::Or_M_MFunction::execute, nest::NestModule::Sub_M_MFunction::execute, nest::NestModule::DumpLayerNodes_os_gFunction::execute, nest::NestModule::DumpLayerConnections_os_g_g_lFunction::execute, nest::NestModule::Cvdict_MFunction::execute, nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, FilesystemModule::FileNamesFunction::execute, FilesystemModule::DirectoryFunction::execute, FilesystemModule::TmpNamFunction::execute, FilesystemModule::CompareFilesFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::ForkFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::PipeFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::AvailableFunction::execute, Processes::GetPIDFunction::execute, Processes::GetPPIDFunction::execute, Processes::GetPGRPFunction::execute, Processes::MkfifoFunction::execute, Processes::SetNonblockFunction::execute, Processes::CtermidFunction::execute, Processes::Isatty_isFunction::execute, Processes::Isatty_osFunction::execute, MathLinkPutStringFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IClearFunction::execute, OClearFunction::execute, IFailFunction::execute, OGoodFunction::execute, Cvx_fFunction::execute, IEofFunction::execute, OEofFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, DatatypeFunction::execute, NametypeFunction::execute, ProceduretypeFunction::execute, LitproceduretypeFunction::execute, FunctiontypeFunction::execute, CallbacktypeFunction::execute, XIstreamtypeFunction::execute, XIfstreamtypeFunction::execute, TrietypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::ReverseFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::FlattenFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::TransposeFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::ValidFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Put_iv_i_iFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, SLIArrayModule::Iforall_ivFunction::execute, SLIArrayModule::Iforall_dvFunction::execute, IlookupFunction::execute, IsetcallbackFunction::execute, IiterateFunction::execute, IloopFunction::execute, IrepeatFunction::execute, IforFunction::execute, IforallarrayFunction::execute, IforallindexedarrayFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, Backtrace_onFunction::execute, Backtrace_offFunction::execute, OStackdumpFunction::execute, EStackdumpFunction::execute, LoopFunction::execute, ExitFunction::execute, QuitFunction::execute, IfFunction::execute, IfelseFunction::execute, RepeatFunction::execute, CloseinputFunction::execute, StoppedFunction::execute, StopFunction::execute, CurrentnameFunction::execute, IparsestdinFunction::execute, StartFunction::execute, ParsestdinFunction::execute, IparseFunction::execute, DefFunction::execute, SetFunction::execute, LoadFunction::execute, LookupFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, RaiseerrorFunction::execute, PrinterrorFunction::execute, RaiseagainFunction::execute, CyclesFunction::execute, CodeAccessedFunction::execute, CodeExecutedFunction::execute, ExecFunction::execute, TypeinfoFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CaseFunction::execute, CounttomarkFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, TimeFunction::execute, Sleep_dFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, SetGuardFunction::execute, RemoveGuardFunction::execute, MessageFunction::execute, SetVerbosityFunction::execute, VerbosityFunction::execute, NoopFunction::execute, DebugOnFunction::execute, DebugOffFunction::execute, DebugFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Allocations_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Append_aFunction::execute, Append_pFunction::execute, Append_sFunction::execute, Prepend_aFunction::execute, Prepend_pFunction::execute, Prepend_sFunction::execute, Join_sFunction::execute, Join_aFunction::execute, Join_pFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Length_sFunction::execute, Length_aFunction::execute, Length_pFunction::execute, Length_lpFunction::execute, Capacity_aFunction::execute, Size_aFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Empty_aFunction::execute, References_aFunction::execute, Shrink_aFunction::execute, Capacity_sFunction::execute, Size_sFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Empty_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Cvx_aFunction::execute, Cvlit_nFunction::execute, Cvlit_pFunction::execute, Cvlp_pFunction::execute, Cvn_sFunction::execute, Cvn_lFunction::execute, Cvi_sFunction::execute, Cvd_sFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, Search_sFunction::execute, Search_aFunction::execute, IrepeatanyFunction::execute, RepeatanyFunction::execute, DictFunction::execute, DictputFunction::execute, DictgetFunction::execute, DictbeginFunction::execute, DictendFunction::execute, DictinfoFunction::execute, DicttopinfoFunction::execute, WhoFunction::execute, DictconstructFunction::execute, DictstackFunction::execute, CurrentdictFunction::execute, CountdictstackFunction::execute, CleardictstackFunction::execute, Length_dFunction::execute, Empty_DFunction::execute, CleardictFunction::execute, ClonedictFunction::execute, UndefFunction::execute, KnownFunction::execute, Cva_dFunction::execute, KeysFunction::execute, ValuesFunction::execute, RestoredstackFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, Add_diFunction::execute, Add_iiFunction::execute, Add_idFunction::execute, Add_ddFunction::execute, Sub_diFunction::execute, Sub_iiFunction::execute, Sub_idFunction::execute, Sub_ddFunction::execute, Mul_diFunction::execute, Mul_iiFunction::execute, Mul_idFunction::execute, Mul_ddFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute, Sin_dFunction::execute, Asin_dFunction::execute, Cos_dFunction::execute, Acos_dFunction::execute, Exp_dFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqr_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, Modf_dFunction::execute, Frexp_dFunction::execute, Ldexp_diFunction::execute, Dexp_iFunction::execute, Abs_iFunction::execute, Abs_dFunction::execute, Neg_iFunction::execute, Neg_dFunction::execute, Inv_dFunction::execute, EqFunction::execute, NeqFunction::execute, AndFunction::execute, OrFunction::execute, And_iiFunction::execute, Or_iiFunction::execute, XorFunction::execute, Not_bFunction::execute, Not_iFunction::execute, Geq_iiFunction::execute, Geq_idFunction::execute, Geq_diFunction::execute, Geq_ddFunction::execute, Leq_iiFunction::execute, Leq_idFunction::execute, Leq_diFunction::execute, Leq_ddFunction::execute, Gt_iiFunction::execute, Gt_ddFunction::execute, Gt_idFunction::execute, Gt_diFunction::execute, Gt_ssFunction::execute, Lt_iiFunction::execute, Lt_ddFunction::execute, Lt_idFunction::execute, Lt_diFunction::execute, Lt_ssFunction::execute, IntegerFunction::execute, DoubleFunction::execute, UnitStep_iFunction::execute, UnitStep_dFunction::execute, UnitStep_iaFunction::execute, UnitStep_daFunction::execute, Round_dFunction::execute, Floor_dFunction::execute, Ceil_dFunction::execute, Max_i_iFunction::execute, Max_i_dFunction::execute, Max_d_iFunction::execute, Max_d_dFunction::execute, Min_i_iFunction::execute, Min_i_dFunction::execute, Min_d_iFunction::execute, Min_d_dFunction::execute, RegexpModule::RegcompFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute, PopFunction::execute, NpopFunction::execute, DupFunction::execute, ExchFunction::execute, IndexFunction::execute, RollFunction::execute, RolluFunction::execute, RolldFunction::execute, RotFunction::execute, OverFunction::execute, CountFunction::execute, CopyFunction::execute, ClearFunction::execute, ExecstackFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, OperandstackFunction::execute, SLIStartup::GetenvFunction::execute, TrieFunction::execute, TrieInfoFunction::execute, AddtotrieFunction::execute, Cva_tFunction::execute, Cvt_aFunction::execute, TypeFunction::execute, ToUppercase_sFunction::execute, ToLowercase_sFunction::execute, execute_, execute_debug_, getcurrentname, SLIStartup::init, raiseagain, raiseerror, stack_backtrace, startup, ~SLIInterpreter.
SLIType SLIInterpreter::Integertype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Doubletype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Stringtype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Nametype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Booltype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Literaltype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Arraytype
Referenced by inittypes, Parser::operator(), ~SLIInterpreter.
SLIType SLIInterpreter::Proceduretype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Litproceduretype
Referenced by inittypes, Parser::operator(), ~SLIInterpreter.
SLIType SLIInterpreter::Dictionarytype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Symboltype
Referenced by inittypes, Parser::operator(), ~SLIInterpreter.
SLIType SLIInterpreter::Functiontype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Trietype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Callbacktype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Istreamtype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::XIstreamtype
Referenced by CloseinputFunction::execute, inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::Ostreamtype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::IntVectortype
Referenced by inittypes, ~SLIInterpreter.
SLIType SLIInterpreter::DoubleVectortype
Referenced by inittypes, ~SLIInterpreter.
DatatypeFunction SLIInterpreter::datatypefunction
Referenced by nest::NestModule::init, RegexpModule::init, inittypes.
NametypeFunction SLIInterpreter::nametypefunction
Referenced by inittypes.
ProceduretypeFunction SLIInterpreter::proceduretypefunction
Referenced by inittypes.
LitproceduretypeFunction SLIInterpreter::litproceduretypefunction
Referenced by inittypes.
FunctiontypeFunction SLIInterpreter::functiontypefunction
Referenced by inittypes.
TrietypeFunction SLIInterpreter::trietypefunction
Referenced by inittypes.
CallbacktypeFunction SLIInterpreter::callbacktypefunction
Referenced by inittypes.
XIstreamtypeFunction SLIInterpreter::xistreamtypefunction
Referenced by inittypes.
const IlookupFunction SLIInterpreter::ilookupfunction
Referenced by Ilookup, initbuiltins.
const IsetcallbackFunction SLIInterpreter::isetcallbackfunction
Referenced by initbuiltins.
const IiterateFunction SLIInterpreter::iiteratefunction
Referenced by Iiterate, initbuiltins.
const IloopFunction SLIInterpreter::iloopfunction
Referenced by initbuiltins.
const IrepeatFunction SLIInterpreter::irepeatfunction
Referenced by initbuiltins.
const IforFunction SLIInterpreter::iforfunction
Referenced by initbuiltins.
const IforallarrayFunction SLIInterpreter::iforallarrayfunction
Referenced by initbuiltins.
const IforallindexedarrayFunction SLIInterpreter::iforallindexedarrayfunction
Referenced by initbuiltins.
const IforallindexedstringFunction SLIInterpreter::iforallindexedstringfunction
Referenced by initbuiltins.
const IforallstringFunction SLIInterpreter::iforallstringfunction
Referenced by initbuiltins.
const char *const SLIInterpreter::M_ALL_NAME
Referenced by message.
const char *const SLIInterpreter::M_DEBUG_NAME
Referenced by message.
const char *const SLIInterpreter::M_STATUS_NAME
Referenced by message.
const char *const SLIInterpreter::M_INFO_NAME
Referenced by message.
const char *const SLIInterpreter::M_PROGRESS_NAME
Referenced by message.
const char *const SLIInterpreter::M_DEPRECATED_NAME
Referenced by message.
const char *const SLIInterpreter::M_WARNING_NAME
Referenced by message.
const char *const SLIInterpreter::M_ERROR_NAME
Referenced by message.
const char *const SLIInterpreter::M_FATAL_NAME
Referenced by message.
const char *const SLIInterpreter::M_QUIET_NAME
void SLIInterpreter::inittypes()
References Arraytype, Booltype, Callbacktype, callbacktypefunction, datatypefunction, Dictionarytype, Doubletype, DoubleVectortype, Functiontype, functiontypefunction, Integertype, IntVectortype, Istreamtype, Literaltype, Litproceduretype, litproceduretypefunction, Nametype, nametypefunction, Ostreamtype, Proceduretype, proceduretypefunction, SLIType::setdefaultaction, SLIType::settypename, Stringtype, Symboltype, Trietype, trietypefunction, XIstreamtype, xistreamtypefunction.
Referenced by SLIInterpreter.
void SLIInterpreter::initdictionaries()
References def, DStack, errordict, errordict_name, DictionaryStack::push, DictionaryStack::set_basedict, statusdict, systemdict_name, userdict_name.
Referenced by SLIInterpreter.
void SLIInterpreter::initbuiltins()
References createcommand, createdouble, numerics::e, e_name, ifor_name, iforallarray_name, iforallarrayfunction, iforallindexedarray_name, iforallindexedarrayfunction, iforallindexedstring_name, iforallindexedstringfunction, iforallstring_name, iforallstringfunction, iforfunction, iiterate_name, iiteratefunction, ilookup_name, ilookupfunction, iloop_name, iloopfunction, ipop_name, irepeat_name, irepeatfunction, isetcallback_name, isetcallbackfunction, numerics::pi, pi_name.
Referenced by SLIInterpreter.
void SLIInterpreter::initexternals()
References commandstring_name, def_move, init_sli_io, init_slicontrol, init_slidata, init_slidict, init_slimath, init_slistack, init_slistring, init_slitypecheck.
Referenced by SLIInterpreter.
SLIInterpreter::SLIInterpreter()
@BeginDocumentation Name: Pi - Value of the constant Pi= 3.1415... Synopsis: Pi -> double Description: Pi yields an approximation with a precision of 12 digits.
Author: Diesmann, Hehl FirstVersion: 10.6.99 References: SeeAlso: E, sin, cos @BeginDocumentation Name: E - Value of the Euler constant E=2.718... Synopsis: E -> double Description: E is the result of the builtin function std::exp(1). The precision of this value is therefore system-dependent. Author: Diesmann, Hehl FirstVersion: 10.6.99 SeeAlso: exp @BeginDocumentation Name: errordict - pushes error dictionary on operand stack Synopsis: errordict -> dict Description: Pushes the dictionary object errordict on the operand stack. errordict is not an operator; it is a name in systemdict associated with the dictionary object. The flag newerror helps to distinguish between interrupts caused by call of stop and interrupts raised by raiseerror. The name command contains the name of the command which caused the most recent error. The flag recordstacks decides whether the state of the interpreter is saved on error. If reckordstacks is true, the following state objects are saved Operand stack -> ostack Dictionary stack -> dstack Execution stack -> estack Parameters: none Examples: errordict info -> shows errordict Remarks: commented 1.4.1999, Diesmann SeeAlso: raiseerror, raiseagain, info References: The Red Book 2nd. ed. p. 408
References baselookup, errordict, false_name, initbuiltins, initdictionaries, initexternals, inittypes, Dictionary::insert, parse, quitbyerror_name.
SLIInterpreter::~SLIInterpreter()
References Arraytype, Booltype, Callbacktype, TokenStack::clear, SLIType::deletetypename, Dictionarytype, Doubletype, DoubleVectortype, DStack, EStack, Functiontype, Integertype, IntVectortype, Istreamtype, Literaltype, Litproceduretype, modules, Nametype, OStack, Ostreamtype, parse, DictionaryStack::pop, Proceduretype, Stringtype, Symboltype, Trietype, XIstreamtype.
int SLIInterpreter::startup()
Initialise the interpreter by reading in the startup files.
References EStack, execute_, TokenStack::load.
Referenced by execute, neststartup.
int SLIInterpreter::execute(const std::string &)
Execute the supplied command string.
References EStack, execute_, OStack, TokenStack::push, startup.
Referenced by main.
int SLIInterpreter::execute(const Token &)
Execute the supplied token.
References EStack, execute_, TokenStack::push, startup.
int SLIInterpreter::execute(int v=0)
Start the interpreter and run the startup code.
References EStack, execute_, execute_debug_, TokenStack::push, startup.
int SLIInterpreter::execute_(size_t exitlevel=0)
Run the interpreter with a prepared execution stack.
The function returns, if the execution stack has reached the given level.
References baselookup, cycle_count, TokenStack::dump, errordict, EStack, Datum::execute, getValue< long >, Dictionary::insert, Dictionary::known, TokenStack::load, M_FATAL, message, OStack, quitbyerror_name, raiseerror, statusdict, terminate, TokenStack::top, true_name.
Referenced by execute, startup.
int SLIInterpreter::execute_debug_(size_t exitlevel=0)
References baselookup, cycle_count, TokenStack::dump, errordict, EStack, Datum::execute, getValue< long >, Dictionary::insert, Dictionary::known, TokenStack::load, M_FATAL, message, OStack, quitbyerror_name, raiseerror, statusdict, terminate, TokenStack::top, true_name.
Referenced by execute.
void SLIInterpreter::createdouble(Name const &, double)
References DictionaryStack::def_move, DStack.
Referenced by initbuiltins.
void SLIInterpreter::createcommand(Name const &, SLIFunction const *, std::string deprecation_info=std::string())
Define a function in the current dictionary.
This function defines a SLI function in the current dictionary. Note that you may also pass a string as the first argument, as there is an implicit type conversion operator from string to Name. Use the Name when a name object for this function already exists.
References DictionaryStack::def_move, DStack, DictionaryStack::known, Name::toString.
Referenced by nest::NestModule::init, FilesystemModule::init, OOSupportModule::init, Processes::init, SLIArrayModule::init, SLIgraphics::init, RegexpModule::init, SLIStartup::init, SpecialFunctionsModule::init, init_sli_io, init_slicontrol, init_slidata, init_slidict, init_slimath, init_slistack, init_slistring, init_slitypecheck, initbuiltins.
void SLIInterpreter::createconstant(Name const &, const Token &)
Define a constant in the current dictionary.
This function defines a SLI constant in the current dictionary. Note that you may also pass a string as the first argument, as there is an implicit type conversion operator from string to Name. Use the Name when a name object for this function already exists.
References DictionaryStack::def_move, DStack.
const Token & SLIInterpreter::lookup(const Name &n) const
Lookup a name searching all dictionaries on the stack.
The first occurrence is reported. If the Name is not found, VoidToken is returned.
References DStack, DictionaryStack::lookup.
Referenced by LoadFunction::execute, LookupFunction::execute.
const Token & SLIInterpreter::lookup2(const Name &n) const
Lookup a name searching all dictionaries on the stack.
The first occurrence is reported. If the Name is not found, an UndefinedName exceptiopn is thrown.
References DStack, DictionaryStack::lookup2.
Referenced by NametypeFunction::execute.
const Token & SLIInterpreter::baselookup(const Name &n) const
Lookup a name searching only the bottom level dictionary.
If the Name is not found, VoidToken is returned.
References DictionaryStack::baselookup, DStack.
Referenced by Dictionary::add_dict, addlinkedusermodule, addmodule, debug_commandline, FilesystemModule::CompareFilesFunction::execute, OOSupportModule::CallMemberFunction::execute, CallbacktypeFunction::execute, XIstreamtypeFunction::execute, XIfstreamtypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, LoopFunction::execute, ExitFunction::execute, RepeatFunction::execute, CloseinputFunction::execute, CurrentnameFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CaseFunction::execute, CounttomarkFunction::execute, Empty_aFunction::execute, Shrink_aFunction::execute, Empty_sFunction::execute, Search_sFunction::execute, Search_aFunction::execute, RepeatanyFunction::execute, DictconstructFunction::execute, RegexpModule::RegcompFunction::execute, SLIStartup::GetenvFunction::execute, execute_, execute_debug_, nest::NestModule::init, Processes::init, SLIStartup::init, neststartup, raiseagain, raiseerror, Dictionary::remove_dict, SLIInterpreter, Processes::systemerror.
bool SLIInterpreter::known(const Name &n) const
Test for a name searching all dictionaries on the stack.
References DStack, DictionaryStack::known.
bool SLIInterpreter::baseknown(const Name &n) const
Test for a name in the bottom level dictionary.
References DictionaryStack::baseknown, DStack.
void SLIInterpreter::def(Name const &, Token const &)
Bind a Token to a Name.
The token is copied. This can be an expensive operation for large objects. Also, if the token is popped off one of the stacks after calling def, it is more reasonable to use SLIInterpreter::def_move.
References DictionaryStack::def, DStack.
Referenced by Processes::init, RegexpModule::init, SLIStartup::init, init_slicontrol, initdictionaries.
void SLIInterpreter::undef(Name const &)
Unbind a previously bound Token from a Name.
Throws UnknownName Exception.
References DStack, DictionaryStack::undef.
void SLIInterpreter::basedef(const Name &n, const Token &t)
Bind a Token to a Name in the bottom level dictionary.
The Token is copied.
References DictionaryStack::basedef, DStack.
void SLIInterpreter::def_move(Name const &, Token &)
Bind a Token to a Name.
like def, however, the Datum object is moved from the token into the dictionary, thus, no memory allocation or copying is needed.
References DictionaryStack::def_move, DStack.
Referenced by DefFunction::execute, SetFunction::execute, init_sli_io, initexternals.
void SLIInterpreter::basedef_move(const Name &n, Token &t)
Bind a Token to a Name in the bottom level dictionary.
The Token is moved.
References DictionaryStack::basedef_move, DStack.
void SLIInterpreter::setcycleguard(Index)
References cycle_guard, cycle_restriction, cycles.
Referenced by SetGuardFunction::execute.
void SLIInterpreter::removecycleguard()
References cycle_guard.
Referenced by RemoveGuardFunction::execute.
void SLIInterpreter::inc_call_depth()
Increment call depth level.
The value of call_depth_ is used to control the step mode. Step mode is disabled for call_depth_ >= max_call_depth_. This gives the user the opportunity to skip over nested calls during debugging.
References call_depth_.
Referenced by ProceduretypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, LoopFunction::execute, RepeatFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute.
void SLIInterpreter::dec_call_depth()
Decrement call depth level.
The value of call_depth_ is used to control the step mode. Step mode is disabled for call_depth_ >= max_call_depth_. This gives the user the opportunity to skip over nested calls during debugging.
References call_depth_.
Referenced by SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::Iforall_ivFunction::execute, SLIArrayModule::Iforall_dvFunction::execute, IiterateFunction::execute, IrepeatFunction::execute, IforFunction::execute, IforallarrayFunction::execute, IforallindexedarrayFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, ExitFunction::execute.
void SLIInterpreter::set_call_depth(int depth)
Set call depth level to a specific value.
The value of call_depth_ is used to control the step mode. Step mode is disabled for call_depth_ >= max_call_depth_. This gives the user the opportunity to skip over nested calls during debugging.
References call_depth_.
int SLIInterpreter::get_call_depth() const
Return current call depth level.
The value of call_depth_ is used to control the step mode. Step mode is disabled for call_depth_ >= max_call_depth_. This gives the user the opportunity to skip over nested calls during debugging.
References call_depth_.
Referenced by DebugOnFunction::execute.
void SLIInterpreter::set_max_call_depth(int d)
Set maximal call depth level to a specific value.
The value of call_depth_ is used to control the step mode. Step mode is disabled for call_depth_ >= max_call_depth_. This gives the user the opportunity to skip over nested calls during debugging.
References max_call_depth_.
Referenced by DebugOnFunction::execute.
int SLIInterpreter::get_max_call_depth() const
Return value of maximal call depth level.
The value of call_depth_ is used to control the step mode. Step mode is disabled for call_depth_ >= max_call_depth_. This gives the user the opportunity to skip over nested calls during debugging.
References max_call_depth_.
bool SLIInterpreter::step_mode() const
Returns true, if step mode is active.
The step mode is active in debug mode if call_depth_ < max_call_depth_
References call_depth_, debug_mode_, max_call_depth_.
Referenced by FunctiontypeFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, IfFunction::execute, IfelseFunction::execute.
bool SLIInterpreter::get_debug_mode() const
Returns true, if debug mode is turned on.
References debug_mode_.
Referenced by CloseinputFunction::execute, StopFunction::execute.
void SLIInterpreter::debug_mode_on()
Turn debug mode on.
References debug_mode_.
Referenced by CloseinputFunction::execute, StopFunction::execute, DebugOnFunction::execute, SLIStartup::init.
void SLIInterpreter::debug_mode_off()
Turn debug mode off.
References debug_mode_.
Referenced by debug_commandline, Processes::ForkFunction::execute, DebugOffFunction::execute.
void SLIInterpreter::toggle_stack_display()
Switch stack display on or off in debug mode.
References M_INFO, message, show_stack_.
void SLIInterpreter::debug_options() const
Show Debug options.
Referenced by debug_commandline, DebugOnFunction::execute.
char SLIInterpreter::debug_commandline(Token &)
Prompt user for commands during debug mode.
In this function, the user can enter simple commands to debug code executed by the interpreter.
References baselookup, call_depth_, catch_errors_, debug_mode_, debug_mode_off, debug_options, TokenStack::dump, EStack, iparse_name, TokenStack::load, mark_name, max_call_depth_, opt_tailrecursion_, OStack, Token::pprint, TokenStack::push, show_backtrace_, show_stack_, stack_backtrace, stop_name.
Referenced by SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, CloseinputFunction::execute, StopFunction::execute.
bool SLIInterpreter::optimize_tailrecursion() const
Returns true, if tailing recursion optimization is done.
References opt_tailrecursion_.
void SLIInterpreter::optimize_tailrecursion_on()
Enable tail-recursion optimization.
Tail-recursion can be optimizes in such a way that the execution stack is not growing with each recursion level. This optimization may improve performance for applications which heavily rely on deep recusions. However, during debugging, tail-recursion optimization removes important information from the execution stack.
References opt_tailrecursion_.
void SLIInterpreter::optimize_tailrecursion_off()
Disable tail-recursion optimization.
Tail-recursion can be optimizes in such a way that the execution stack is not growing with each recursion level. This optimization may improve performance for applications which heavily rely on deep recusions. However, during debugging, tail-recursion optimization removes important information from the execution stack.
References opt_tailrecursion_.
bool SLIInterpreter::show_backtrace() const
True, if a stack backtrace should be shown on error.
Whenever an error or stop is raised, the execution stack is unrolled up to the nearest stopped context. In this process it is possible to display a stack backtrace which allows the user to diagnose the origin and possible cause of the error. For applications which handle themselfs, this backtrace may be disturbing. So it is possible to switch this behavior on and off.
References show_backtrace_.
Referenced by CloseinputFunction::execute, StopFunction::execute.
void SLIInterpreter::backtrace_on()
Switch stack backtrace on.
Whenever an error or stop is raised, the execution stack is unrolled up to the nearest stopped context. In this process it is possible to display a stack backtrace which allows the user to diagnose the origin and possible cause of the error. For applications which handle themselfs, this backtrace may be disturbing. So it is possible to switch this behavior on and off.
References M_INFO, message, opt_tailrecursion_, show_backtrace_.
Referenced by Backtrace_onFunction::execute, SLIStartup::init.
void SLIInterpreter::backtrace_off()
Switch stack backtrace off.
Whenever an error or stop is raised, the execution stack is unrolled up to the nearest stopped context. In this process it is possible to display a stack backtrace which allows the user to diagnose the origin and possible cause of the error. For applications which handle themselfs, this backtrace may be disturbing. So it is possible to switch this behavior on and off.
References M_INFO, message, opt_tailrecursion_, show_backtrace_.
Referenced by Backtrace_offFunction::execute.
bool SLIInterpreter::catch_errors() const
References catch_errors_.
Referenced by CloseinputFunction::execute, StopFunction::execute.
void SLIInterpreter::catch_errors_on()
References catch_errors_.
void SLIInterpreter::catch_errors_off()
References catch_errors_.
void SLIInterpreter::stack_backtrace(int n)
List the execution stack from level n-1 downwards to level 0.
If you want the entire stack to be displayed, call the function as stack_backtrace(EStack.load());
References FunctionDatum::backtrace, Token::datum, EStack, TokenStack::load, TokenStack::pick, TrieDatum::print, AggregateDatum< C, slt >::print.
Referenced by debug_commandline, CloseinputFunction::execute, StopFunction::execute.
void SLIInterpreter::raiseerror(const char *err)
Cause the SLI interpreter to raise an error.
This function is used by classes derived from SLIFunction to raise an error. raiseerror() is an interface to the SLI interpreter's error handling mechanism (see The Red Book for details). If an error is raised, the following actions are performed: the value of errordict /newerror is set to true the value of errordict /command is set to the name of the command which raised the error If the value of errordict /recorstack is true, the state of the interpreter is saved: the operand stack is copied to errordict /ostack the execution stack is copied to errordict /estack the dictionary stack is copied to errordict /dstack the dictionary stack is cleared. stop is called. Stop then tries to find an enclosing stopped context and calls the associated function. This mechanism is explained in detail in The PostScript Reference Manual. If the user did not establish any stopped context, the default stopped context for the SLI interpreter will be executed, which includes display of an error message and stopping program execution. Please note that before raiserror() is called, the state of the operand and execution stack shall be restored to their initial state. err The argument is the name of the error, specified as a string. The name of the currently active function will be used as the function name. raiseerror(Name), raiseerror(Name,Name), raiseagain()
References raiseerror.
Referenced by eq_execute, StrFunction::execute, FilesystemModule::FileNamesFunction::execute, FilesystemModule::DirectoryFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::ForkFunction::execute, Processes::Sysexec_aFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::PipeFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::GetPIDFunction::execute, Processes::GetPPIDFunction::execute, Processes::GetPGRPFunction::execute, Processes::MkfifoFunction::execute, Processes::SetNonblockFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Array2IntVectorFunction::execute, SLIArrayModule::Array2DoubleVectorFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Put_iv_i_iFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, LoopFunction::execute, ExitFunction::execute, IparseFunction::execute, LoadFunction::execute, LookupFunction::execute, RaiseerrorFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CaseFunction::execute, CounttomarkFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, DebugFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Join_sFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, DictbeginFunction::execute, DictendFunction::execute, DictconstructFunction::execute, RestoredstackFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, Inv_dFunction::execute, PopFunction::execute, NpopFunction::execute, DupFunction::execute, ExchFunction::execute, IndexFunction::execute, RollFunction::execute, RolluFunction::execute, RolldFunction::execute, OverFunction::execute, CopyFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, TrieFunction::execute, AddtotrieFunction::execute, TypeFunction::execute, SpecialFunctionsModule::GammaIncFunction::execute, SpecialFunctionsModule::LambertW0Function::execute, SpecialFunctionsModule::LambertWm1Function::execute, SpecialFunctionsModule::ErfFunction::execute, SpecialFunctionsModule::ErfcFunction::execute, SpecialFunctionsModule::GaussDiskConvFunction::execute, execute_, execute_debug_, raiseagain, raiseerror, raisesignal.
void SLIInterpreter::raiseerror(Name err)
Cause the SLI interpreter to raise an error.
This function is used by classes derived from SLIFunction to raise an error. raiseerror() is an interface to the SLI interpreter's error handling mechanism (see The Red Book for details). If an error is raised, the following actions are performed: the value of errordict /newerror is set to true the value of errordict /command is set to the name of the command which raised the error If the value of errordict /recorstack is true, the state of the interpreter is saved: the operand stack is copied to errordict /ostack the execution stack is copied to errordict /estack the dictionary stack is copied to errordict /dstack the dictionary stack is cleared. stop is called. Stop then tries to find an enclosing stopped context and calls the associated function. This mechanism is explained in detail in The PostScript Reference Manual. If the user did not establish any stopped context, the default stopped context for the SLI interpreter will be executed, which includes display of an error message and stopping program execution. Please note that before raiserror() is called, the state of the operand and execution stack shall be restored to their initial state. err The argument is the name of the error. For conveniency, there is also a variant of this function that takes a string as the argument. raiseerror(const char*), raiseerror(Name,Name), raiseagain()
References EStack, getcurrentname, TokenStack::pop, raiseerror.
void SLIInterpreter::raiseerror(std::exception &err)
Handle exceptions thrown by any execute().
This raiseerror is the first step in handling C++ exceptions thrown by an execute() call. In particular, the name of the calling function is recorded; the command is popped from the execution stack; the error message is extracted from those exceptions that are derived from SLIException. handling is forwarded to raiserror(Name, Name).
References errordict, EStack, getcurrentname, Dictionary::insert, SLIException::message, raiseerror, TokenStack::top, SLIException::what.
void SLIInterpreter::raiseerror(Name cmd, Name err)
Cause the SLI interpreter to raise an error.
This function is used by classes derived from SLIFunction to raise an error. raiseerror() is an interface to the SLI interpreter's error handling mechanism (see The Red Book for details). If an error is raised, the following actions are performed: the value of errordict /newerror is set to true the value of errordict /command is set to the name of the command which raised the error If the value of errordict /recorstack is true, the state of the interpreter is saved: the operand stack is copied to errordict /ostack the execution stack is copied to errordict /estack the dictionary stack is copied to errordict /dstack the dictionary stack is cleared. stop is called. Stop then tries to find an enclosing stopped context and calls the associated function. This mechanism is explained in detail in The PostScript Reference Manual. If the user did not establish any stopped context, the default stopped context for the SLI interpreter will be executed, which includes display of an error message and stopping program execution. Please note that before raiserror() is called, the state of the operand and execution stack shall be restored to their initial state. cmd The first argument is the name of the calling function. err The second argument is the name of the error. raiseerror(const char*), raiseerror(Name), raiseagain()
References BadErrorHandler, baselookup, commandname_name, DStack, dstack_name, errordict, errorname_name, EStack, estack_name, false_name, Dictionary::insert, Dictionary::insert_move, Dictionary::lookup, newerror_name, OStack, ostack_name, TokenStack::push, raiseerror, recordstacks_name, stop_name, TokenStack::toArray, DictionaryStack::toArray, true_name.
void SLIInterpreter::print_error(Token cmd)
Print a description of a raised error.
The errordict members errorname, command and message together with the function input parameters decides the nature of the output message. The function use the message() function to print the error. Replaces the SLI :print_error function. cmd The name of the function that raised the error. raiseerror(const char*), raiseerror(Name), raiseerror(Name,Name)
References Token::datum, errordict, errorname_name, TrieDatum::get, Datum::gettypename, TypeTrie::info, Dictionary::known, Dictionary::lookup, M_ERROR, message.
Referenced by PrinterrorFunction::execute.
void SLIInterpreter::raiseagain()
Re-raise the last error.
raiseagain re-raises a previously raised error. This is useful if an error handler cannot cope with a particular error (e.g. a signal) and wants to pass it to an upper level handler. Thus, nestet error handlers are possible. raiseerror(const char*), raiseerror(Name), raiseerror(Name,Name)
References BadErrorHandler, baselookup, commandname_name, Token::empty, errordict, EStack, Dictionary::insert, Dictionary::known, Dictionary::lookup, newerror_name, OStack, TokenStack::push, TokenStack::push_move, raiseerror, stop_name, true_name.
Referenced by RaiseagainFunction::execute.
void SLIInterpreter::raisesignal(int)
TO BE DOCUMENTED.
TodoDocument this function.
References errordict, getcurrentname, Dictionary::insert, raiseerror, signo_name.
void SLIInterpreter::verbosity(int)
Set the verbosity level of the SLI messaging mechanism.
Only messages having an error level that is equal to or greater than this level will be displayed by the interpreter. verbosity(void), message(), debug(), status(), info(), warning(), error(), fatal()
References verbositylevel.
Referenced by SetVerbosityFunction::execute, VerbosityFunction::execute, SLIStartup::init.
int SLIInterpreter::verbosity() const
Retrieve the current verbosity level of the SLI messaging mechanism.
Only messages having an error level that is equal to or greater than this level will be displayed by the interpreter. You may use any positive integer here. For conveniency, there exist five predifined error levels: SLIInterpreter::M_ALL=0, display all messages SLIInterpreter::M_DEBUG=5, display debugging messages and above SLIInterpreter::M_STATUS=7, display status messages and above SLIInterpreter::M_INFO=10, display information messages and above SLIInterpreter::M_PROGRESS=15, display test-related messages and above SLIInterpreter::M_DEPRECATED=18, display deprecation warnings and above SLIInterpreter::M_WARNING=20, display warning messages and above SLIInterpreter::M_ERROR=30, display error messages and above SLIInterpreter::M_FATAL=40, display failure messages and above SLIInterpreter::M_QUIET=100, suppress all messages Thus, by calling verbosity(SLIInterpreter::M_WARNING) you indicate that you are interested in seeing error messages and more important messages only. verbosity(void), message(), debug(), status(), info(), warning(), error(), fatal()
References verbositylevel.
void SLIInterpreter::message(int level, const char from[], const char text[], const char errorname[]="") const
Display a message.
level The error level that shall be associated with the message. You may use any positive integer here. For convenience, there exist five predefined error levels: (SLIInterpreter::M_ALL=0, for use with verbosity(int) only, see there), SLIInterpreter::M_DEBUG=5, a debugging message SLIInterpreter::M_STATUS=7, a status message SLIInterpreter::M_INFO=10, an informational message SLIInterpreter::M_PROGRESS=15, a test-related message SLIInterpreter::M_DEPRECATED=18, a deprecation warning SLIInterpreter::M_WARNING=20, a warning message SLIInterpreter::M_ERROR=30, an error message SLIInterpreter::M_FATAL=40, a failure message. (SLIInterpreter::M_QUIET=100, for use with verbosity(int) only, see there), from A string specifying the name of the function that sends the message. test A string specifying the message text. The message will ony be displayed if the current verbosity level is greater than or equal to the specified level. If two or more messages are issued after each other, that have the same from and level argument, the messages will be grouped together in the output. verbosity(void), verbosity(int)
References M_ALL_NAME, M_DEBUG, M_DEBUG_NAME, M_DEPRECATED, M_DEPRECATED_NAME, M_ERROR, M_ERROR_NAME, M_FATAL, M_FATAL_NAME, M_INFO, M_INFO_NAME, M_PROGRESS, M_PROGRESS_NAME, M_STATUS, M_STATUS_NAME, M_WARNING, M_WARNING_NAME, message, verbositylevel.
Referenced by addmodule, backtrace_off, backtrace_on, Processes::ForkFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, CloseinputFunction::execute, StopFunction::execute, StartFunction::execute, RaiseerrorFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, MessageFunction::execute, Get_a_aFunction::execute, Join_sFunction::execute, DictconstructFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, AddtotrieFunction::execute, FunctionDatum::execute, execute_, execute_debug_, SLIStartup::init, SLIModule::install, message, print_error, sli_logging, terminate, toggle_stack_display.
void SLIInterpreter::message(std::ostream &out, const char levelname[], const char from[], const char text[], const char errorname[]="") const
Function used by the message(int, const char*, const char*) function.
Prints a message to the specified output stream. out output stream levelname name associated with input level
void SLIInterpreter::terminate(int returnvalue=-1)
References getValue< long >, Dictionary::known, M_FATAL, message, statusdict.
Referenced by execute_, execute_debug_.
Name SLIInterpreter::getcurrentname() const
References Token::datum, EStack, FunctionDatum::getname, TrieDatum::getname, interpreter_name, TokenStack::top.
Referenced by LoadFunction::execute, SwitchFunction::execute, SwitchdefaultFunction::execute, CaseFunction::execute, CounttomarkFunction::execute, raiseerror, raisesignal.
unsigned long SLIInterpreter::cycles() const
References cycle_count.
Referenced by CyclesFunction::execute, setcycleguard.
void SLIInterpreter::addmodule()
References SLIModule::install, modules.
Referenced by addmodule, main, neststartup.
void SLIInterpreter::addmodule(SLIModule *)
References baselookup, SLIModule::commandstring, commandstring_name, Token::datum, SLIModule::install, M_ERROR, message, modules, SLIModule::name.
void SLIInterpreter::addlinkedusermodule(SLIModule *)
References baselookup, SLIModule::commandstring, commandstring_name, Token::datum, SLIModule::install.
FunctionDatum * SLIInterpreter::Ilookup() const
References ilookup_name, ilookupfunction.
FunctionDatum * SLIInterpreter::Iiterate() const
References iiterate_name, iiteratefunction.
Referenced by ProceduretypeFunction::execute.
void SLIInterpreter::assert_stack_load(size_t n)
Throw StackUnderflow exception if too few elements on stack.
n Minimum number of elements required on stack. StackUnderflow if fewer that n elements on stack.
References TokenStack::load, OStack.
Referenced by nest::NestModule::Disconnect_aFunction::execute, StrFunction::execute, nest::NestModule::GetStatus_gFunction::execute, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::NestModule::GetMetadata_gFunction::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::SetStatus_CDFunction::execute, nest::NestModule::SetKernelStatus_DFunction::execute, nest::NestModule::SetStatus_aaFunction::execute, nest::NestModule::SetDefaults_l_DFunction::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::CopyModel_l_l_DFunction::execute, nest::NestModule::GetConnections_DFunction::execute, nest::NestModule::SimulateFunction::execute, nest::NestModule::RunFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::SetFakeNumProcesses_iFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::Cvdict_CFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::Cvnodecollection_iaFunction::execute, nest::NestModule::Cvnodecollection_ivFunction::execute, nest::NestModule::Cva_gFunction::execute, nest::NestModule::Size_gFunction::execute, nest::NestModule::ValidQ_gFunction::execute, nest::NestModule::Join_g_gFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::eq_gFunction::execute, nest::NestModule::BeginIterator_gFunction::execute, nest::NestModule::EndIterator_gFunction::execute, nest::NestModule::GetNodeID_qFunction::execute, nest::NestModule::GetNodeIDModelID_qFunction::execute, nest::NestModule::Next_qFunction::execute, nest::NestModule::Eq_q_qFunction::execute, nest::NestModule::Lt_q_qFunction::execute, nest::NestModule::Get_g_iFunction::execute, nest::NestModule::Take_g_aFunction::execute, nest::NestModule::SetStdpEps_dFunction::execute, nest::NestModule::Mul_P_PFunction::execute, nest::NestModule::Div_P_PFunction::execute, nest::NestModule::Add_P_PFunction::execute, nest::NestModule::Sub_P_PFunction::execute, nest::NestModule::Compare_P_P_DFunction::execute, nest::NestModule::Conditional_P_P_PFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Exp_PFunction::execute, nest::NestModule::Sin_PFunction::execute, nest::NestModule::Cos_PFunction::execute, nest::NestModule::Pow_P_dFunction::execute, nest::NestModule::Dimension2d_P_PFunction::execute, nest::NestModule::Dimension3d_P_P_PFunction::execute, nest::NestModule::CreateParameter_DFunction::execute, nest::NestModule::GetValue_PFunction::execute, nest::NestModule::IsSpatial_PFunction::execute, nest::NestModule::Apply_P_DFunction::execute, nest::NestModule::Apply_P_gFunction::execute, nest::NestModule::CreateLayer_D_DFunction::execute, nest::NestModule::GetPosition_gFunction::execute, nest::NestModule::Displacement_g_gFunction::execute, nest::NestModule::Displacement_a_gFunction::execute, nest::NestModule::Distance_g_gFunction::execute, nest::NestModule::Distance_a_gFunction::execute, nest::NestModule::Distance_aFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute, nest::NestModule::CreateMask_DFunction::execute, nest::NestModule::GetLayerStatus_gFunction::execute, nest::NestModule::Inside_a_MFunction::execute, nest::NestModule::And_M_MFunction::execute, nest::NestModule::Or_M_MFunction::execute, nest::NestModule::Sub_M_MFunction::execute, nest::NestModule::DumpLayerNodes_os_gFunction::execute, nest::NestModule::DumpLayerConnections_os_g_g_lFunction::execute, nest::NestModule::Cvdict_MFunction::execute, nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, FilesystemModule::CompareFilesFunction::execute, MathLinkPutStringFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IClearFunction::execute, OClearFunction::execute, IFailFunction::execute, OGoodFunction::execute, Cvx_fFunction::execute, IEofFunction::execute, OEofFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ReverseFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, LoadFunction::execute, PrinterrorFunction::execute, TypeinfoFunction::execute, Sleep_dFunction::execute, Token_isFunction::execute, SetGuardFunction::execute, RepeatanyFunction::execute, CleardictFunction::execute, ClonedictFunction::execute, RestoredstackFunction::execute, SLIStartup::GetenvFunction::execute, ToUppercase_sFunction::execute, ToLowercase_sFunction::execute.