nest::NodeCollection
using nest::NodeCollection::const_iterator = nc_const_iterator
friend class nc_const_iterator
unsigned long nest::NodeCollection::fingerprint_
Unique identity of the kernel that created the NodeCollection.
nest::NodeCollection::NodeCollection()
Initializer gets current fingerprint from the kernel.
virtual nest::NodeCollection::~NodeCollection()=default
bool nest::NodeCollection::valid() const
Check to see if the fingerprint of the NodeCollection matches that of the kernel.
true if the fingerprint matches that of the kernel, false otherwise
virtual void nest::NodeCollection::print_me(std::ostream &) const =0
Print out the contents of the NodeCollection in a pretty and informative way.
virtual index nest::NodeCollection::operator[](size_t) const =0
Get the node ID in the specified index in the NodeCollection.
idx Index in the NodeCollection a node ID
virtual NodeCollectionPTR nest::NodeCollection::operator+(NodeCollectionPTR) const =0
Join two NodeCollections.
May return a primitive or composite, depending on the input. rhs NodeCollection pointer to the NodeCollection to be added a NodeCollection pointer
virtual bool nest::NodeCollection::operator==(NodeCollectionPTR) const =0
bool nest::NodeCollection::operator!=(NodeCollectionPTR) const
Check if two NodeCollections are equal.
rhs NodeCollection pointer to the NodeCollection to be checked against true if they are equal, false otherwise
virtual const_iterator nest::NodeCollection::begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const =0
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection
virtual const_iterator nest::NodeCollection::local_begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const =0
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection, in a parallel context.
virtual const_iterator nest::NodeCollection::MPI_local_begin(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const =0
Method to get an iterator representing the beginning of the NodeCollection.
an iterator representing the beginning of the NodeCollection, in an MPI-parallel context.
virtual const_iterator nest::NodeCollection::end(NodeCollectionPTR=NodeCollectionPTR(nullptr)) const =0
Method to get an iterator representing the end of the NodeCollection.
offset Index of element NC that iterator points to an iterator representing the end of the NodeCollection, taking offset into account
virtual ArrayDatum nest::NodeCollection::to_array() const =0
Method that creates an ArrayDatum filled with node IDs from the NodeCollection.
an ArrayDatum containing node IDs
virtual size_t nest::NodeCollection::size() const =0
Get the size of the NodeCollection.
number of node IDs in the NodeCollection
virtual size_t nest::NodeCollection::step() const =0
Get the step of the NodeCollection.
step between node IDs in the NodeCollection
virtual bool nest::NodeCollection::contains(const index node_id) const =0
Check if the NodeCollection contains a specified node ID.
node_id node ID to see if exists in the NodeCollection true if the NodeCollection contains the node ID, false otherwise
virtual NodeCollectionPTR nest::NodeCollection::slice(size_t start, size_t end, size_t step) const =0
Slices the NodeCollection to the boundaries, with an optional step parameter.
Note that the boundaries being specified are inclusive. start Index of the NodeCollection to start at end One past the index of the NodeCollection to stop at step Number of places between node IDs to skip. Defaults to 1 a NodeCollection pointer to the new, sliced NodeCollection.
void nest::NodeCollection::set_metadata(NodeCollectionMetadataPTR)=0
Sets the metadata of the NodeCollection.
meta A Metadata pointer
virtual NodeCollectionMetadataPTR nest::NodeCollection::get_metadata() const =0
Gets the metadata of the NodeCollection.
A Metadata pointer
virtual bool nest::NodeCollection::is_range() const =0
virtual bool nest::NodeCollection::empty() const =0
Checks if the NodeCollection has no elements.
true if the NodeCollection is empty, false otherwise
virtual long nest::NodeCollection::find(const index) const =0
Returns index of node with given node ID in NodeCollection.
Index of node with given node ID; -1 if node not in NodeCollection.
virtual bool nest::NodeCollection::has_proxies() const =0
Returns whether the NodeCollection contains any nodes with proxies or not.
true if any nodes in the NodeCollection has proxies, false otherwise.
static NodeCollectionPTR nest::NodeCollection::create(const IntVectorDatum &node_ids)
Create a NodeCollection from a vector of node IDs.
Results in a primitive if the node IDs are homogeneous and contiguous, or a composite otherwise. node_ids Vector of node IDs from which to create the NodeCollection a NodeCollection pointer to the created NodeCollection
Referenced by nest::Layer< D >::dump_connections, nest::NestModule::Cvnodecollection_iaFunction::execute, nest::NestModule::Cvnodecollection_ivFunction::execute, nest::NodeManager::get_nodes, nest::node_collection_array_index, nest::weight_recorder::Parameters_::set.
static NodeCollectionPTR nest::NodeCollection::create(const TokenArray &node_ids)
Create a NodeCollection from an array of node IDs.
Results in a primitive if the node IDs are homogeneous and contiguous, or a composite otherwise. node_ids Array of node IDs from which to create the NodeCollection a NodeCollection pointer to the created NodeCollection
static NodeCollectionPTR nest::NodeCollection::create(const index node_id)
Create a NodeCollection from a single node ID.
Results in a primitive. node_id Node ID from which to create the NodeCollection a NodeCollection pointer to the created NodeCollection
static NodeCollectionPTR nest::NodeCollection::create(const std::vector< index > &node_ids)
Create a NodeCollection from an array of node IDs.
Results in a primitive if the node IDs are homogeneous and contiguous, or a composite otherwise. node_ids Array of node IDs from which to create the NodeCollection a NodeCollection pointer to the created NodeCollection
static NodeCollectionPTR nest::NodeCollection::create_()
static NodeCollectionPTR nest::NodeCollection::create_(const std::vector< index > &)