nest::CommonSynapseProperties
NodeCollectionDatum nest::CommonSynapseProperties::weight_recorder_
Referenced by get_status, get_weight_recorder, set_status.
long nest::CommonSynapseProperties::wr_node_id_
Referenced by get_wr_node_id, set_status.
nest::CommonSynapseProperties::CommonSynapseProperties()
Standard constructor.
Default implementation of an empty CommonSynapseProperties object. Sets all common properties to default values.
nest::CommonSynapseProperties::~CommonSynapseProperties()
Destructor.
void nest::CommonSynapseProperties::get_status(DictionaryDatum &d) const
Get all properties and put them into a dictionary.
References nest::names::d, nest::names::weight_recorder, weight_recorder_.
Referenced by nest::JonkeCommonProperties::get_status, nest::STDPDopaCommonProperties::get_status, nest::STDPPLHomCommonProperties::get_status, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::get_status, nest::STDPHomCommonProperties::get_status, nest::CommonPropertiesHomW::get_status.
void nest::CommonSynapseProperties::set_status(const DictionaryDatum &d, ConnectorModel &cm)
Set properties from the values given in dictionary.
References nest::names::d, nest::names::weight_recorder, weight_recorder_, wr_node_id_.
Referenced by nest::JonkeCommonProperties::set_status, nest::STDPDopaCommonProperties::set_status, nest::STDPPLHomCommonProperties::set_status, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::set_status, nest::STDPHomCommonProperties::set_status, nest::CommonPropertiesHomW::set_status.
void nest::CommonSynapseProperties::calibrate(const TimeConverter &)
Calibrate all time objects, which might be contained in this object.
Node * nest::CommonSynapseProperties::get_node()
get reference to registering node
long nest::CommonSynapseProperties::get_vt_node_id() const
get node ID of volume transmitter
index nest::CommonSynapseProperties::get_wr_node_id() const
get node ID of weight_recorder
References wr_node_id_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.
NodeCollectionDatum nest::CommonSynapseProperties::get_weight_recorder() const
get weight_recorder
References weight_recorder_.
Referenced by nest::Connector< ConnectionT >::send_weight_event.