bv_iterator
using bv_iterator< value_type_, ref_, ptr_ >::iter_ = bv_iterator< value_type_, cv_value_type_&, cv_value_type_* >
using bv_iterator< value_type_, ref_, ptr_ >::iterator = iter_< value_type_ >
using bv_iterator< value_type_, ref_, ptr_ >::const_iterator = iter_< const value_type_ >
using bv_iterator< value_type_, ref_, ptr_ >::iterator_category = std::random_access_iterator_tag
using bv_iterator< value_type_, ref_, ptr_ >::value_type = value_type_
using bv_iterator< value_type_, ref_, ptr_ >::pointer = ptr_
using bv_iterator< value_type_, ref_, ptr_ >::reference = ref_
using bv_iterator< value_type_, ref_, ptr_ >::difference_type = typename BlockVector< value_type >::difference_type
friend class BlockVector< value_type_ >
friend class bv_iterator
const BlockVector< value_type_ >* bv_iterator< value_type_, ref_, ptr_ >::block_vector_
BlockVector to which this iterator points.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::const_cast_, BlockVector< value_type_ >::erase, bv_iterator< value_type_, ref_, ptr_ >::operator++, bv_iterator< value_type_, ref_, ptr_ >::operator--, bv_iterator< value_type_, ref_, ptr_ >::operator=.
std::vector<std::vector<value_type_>>::const_iterator bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_
Iterator for the current block in the blockmap.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::const_cast_, bv_iterator< value_type_, ref_, ptr_ >::operator!=, bv_iterator< value_type_, ref_, ptr_ >::operator++, bv_iterator< value_type_, ref_, ptr_ >::operator-, bv_iterator< value_type_, ref_, ptr_ >::operator--, bv_iterator< value_type_, ref_, ptr_ >::operator<, bv_iterator< value_type_, ref_, ptr_ >::operator=, bv_iterator< value_type_, ref_, ptr_ >::operator==, bv_iterator< value_type_, ref_, ptr_ >::operator>.
std::vector<value_type_>::const_iterator bv_iterator< value_type_, ref_, ptr_ >::block_it_
Iterator pointing to the current element in the current block.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::const_cast_, bv_iterator< value_type_, ref_, ptr_ >::operator!=, bv_iterator< value_type_, ref_, ptr_ >::operator++, bv_iterator< value_type_, ref_, ptr_ >::operator-, bv_iterator< value_type_, ref_, ptr_ >::operator--, bv_iterator< value_type_, ref_, ptr_ >::operator<, bv_iterator< value_type_, ref_, ptr_ >::operator=, bv_iterator< value_type_, ref_, ptr_ >::operator==, bv_iterator< value_type_, ref_, ptr_ >::operator>.
std::vector<value_type_>::const_iterator bv_iterator< value_type_, ref_, ptr_ >::current_block_end_
Iterator pointing to the end of the current block.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::const_cast_, bv_iterator< value_type_, ref_, ptr_ >::operator++, bv_iterator< value_type_, ref_, ptr_ >::operator--, bv_iterator< value_type_, ref_, ptr_ >::operator=.
bv_iterator< value_type_, ref_, ptr_ >::bv_iterator()
bv_iterator< value_type_, ref_, ptr_ >::bv_iterator(const BlockVector< value_type_ > &)
Creates an iterator pointing to the first element in a BlockVector.
block_vector BlockVector to which the iterator will point to.
bv_iterator< value_type_, ref_, ptr_ >::bv_iterator(const iterator &)
Iterator copy constructor.
other Iterator to be copied.
bv_iterator< value_type_, ref_, ptr_ >::bv_iterator(const BlockVector< value_type_ > *, const typename std::vector< std::vector< value_type_ > >::const_iterator, const typename std::vector< value_type_ >::const_iterator, const typename std::vector< value_type_ >::const_iterator)
Creates an iterator with specified parameters.
block_vector BlockVector to point to. block_index Index of current block. block_it Iterator pointing to current element in the current block. current_block_end Iterator pointing to the end of the current block.
bv_iterator< value_type_, ref_, ptr_ > & bv_iterator< value_type_, ref_, ptr_ >::operator++()
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_, bv_iterator< value_type_, ref_, ptr_ >::current_block_end_.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::operator+=.
bv_iterator< value_type_, ref_, ptr_ > & bv_iterator< value_type_, ref_, ptr_ >::operator--()
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_, bv_iterator< value_type_, ref_, ptr_ >::current_block_end_.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::operator-=.
bv_iterator< value_type_, ref_, ptr_ > & bv_iterator< value_type_, ref_, ptr_ >::operator+=(difference_type)
References bv_iterator< value_type_, ref_, ptr_ >::operator++, bv_iterator< value_type_, ref_, ptr_ >::operator-=.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::operator-=.
bv_iterator< value_type_, ref_, ptr_ > & bv_iterator< value_type_, ref_, ptr_ >::operator-=(difference_type)
References bv_iterator< value_type_, ref_, ptr_ >::operator+=, bv_iterator< value_type_, ref_, ptr_ >::operator--.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::operator+=.
bv_iterator< value_type_, ref_, ptr_ > bv_iterator< value_type_, ref_, ptr_ >::operator+(difference_type) const
bv_iterator< value_type_, ref_, ptr_ > bv_iterator< value_type_, ref_, ptr_ >::operator-(difference_type) const
bv_iterator< value_type_, ref_, ptr_ > bv_iterator< value_type_, ref_, ptr_ >::operator++(int)
bv_iterator< value_type_, ref_, ptr_ > bv_iterator< value_type_, ref_, ptr_ >::operator--(int)
bv_iterator< value_type_, ref_, ptr_ >::reference bv_iterator< value_type_, ref_, ptr_ >::operator*() const
bv_iterator< value_type_, ref_, ptr_ >::pointer bv_iterator< value_type_, ref_, ptr_ >::operator->() const
bv_iterator< value_type_, ref_, ptr_ >::difference_type bv_iterator< value_type_, ref_, ptr_ >::operator-(const iterator &) const
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_, max_block_size.
bv_iterator< value_type_, ref_, ptr_ >::difference_type bv_iterator< value_type_, ref_, ptr_ >::operator-(const const_iterator &) const
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_, max_block_size.
bv_iterator< value_type_, ref_, ptr_ >::iterator & bv_iterator< value_type_, ref_, ptr_ >::operator=(const iterator &)
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_, bv_iterator< value_type_, ref_, ptr_ >::current_block_end_.
bv_iterator< value_type_, ref_, ptr_ >::reference bv_iterator< value_type_, ref_, ptr_ >::operator[](difference_type n) const
bool bv_iterator< value_type_, ref_, ptr_ >::operator==(const bv_iterator &) const
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_.
bool bv_iterator< value_type_, ref_, ptr_ >::operator!=(const bv_iterator &) const
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_.
bool bv_iterator< value_type_, ref_, ptr_ >::operator<(const bv_iterator &) const
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::operator<=.
bool bv_iterator< value_type_, ref_, ptr_ >::operator>(const bv_iterator &) const
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::operator>=.
bool bv_iterator< value_type_, ref_, ptr_ >::operator<=(const bv_iterator &) const
References bv_iterator< value_type_, ref_, ptr_ >::operator<, operator==.
bool bv_iterator< value_type_, ref_, ptr_ >::operator>=(const bv_iterator &) const
References operator==, bv_iterator< value_type_, ref_, ptr_ >::operator>.
bv_iterator< value_type_, ref_, ptr_ >::iterator bv_iterator< value_type_, ref_, ptr_ >::const_cast_() const
Converts the iterator to a non-const iterator.
References bv_iterator< value_type_, ref_, ptr_ >::block_it_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_, bv_iterator< value_type_, ref_, ptr_ >::block_vector_it_, bv_iterator< value_type_, ref_, ptr_ >::current_block_end_.
Referenced by BlockVector< value_type_ >::erase.