nest::SimulationManager
Time nest::SimulationManager::clock_
SimulationManager clock, updated once per slice.
Referenced by get_clock, get_slice_origin, get_time.
delay nest::SimulationManager::slice_
current update slice
Referenced by get_slice.
delay nest::SimulationManager::to_do_
number of pending steps
Referenced by run_end_time, run_start_time.
delay nest::SimulationManager::to_do_total_
number of requested steps in current simulation
Referenced by run_duration, run_start_time.
delay nest::SimulationManager::from_step_
update clock_+from_step<=T<clock_+to_step_
Referenced by get_from_step, get_time.
delay nest::SimulationManager::to_step_
update clock_+from_step<=T<clock_+to_step_
Referenced by get_to_step.
timeval nest::SimulationManager::t_slice_begin_
Wall-clock time at the begin of a time slice.
timeval nest::SimulationManager::t_slice_end_
Wall-clock time at the end of time slice.
long nest::SimulationManager::t_real_
Accumulated wall-clock time spent simulating (in us)
bool nest::SimulationManager::prepared_
Indicates whether the SimulationManager is in a prepared state.
Referenced by has_been_prepared.
bool nest::SimulationManager::simulating_
true if simulation in progress
Referenced by get_time, run_end_time, run_start_time.
bool nest::SimulationManager::simulated_
indicates whether the SimulationManager has already been simulated for sometime
Referenced by has_been_simulated.
bool nest::SimulationManager::inconsistent_state_
true after exception during update_ simulation must not be resumed
bool nest::SimulationManager::print_time_
Indicates whether time should be printed during simulations (or not)
bool nest::SimulationManager::use_wfr_
Indicates wheter waveform relaxation is used.
Referenced by use_wfr.
double nest::SimulationManager::wfr_comm_interval_
Desired waveform relaxation communication interval (in ms)
Referenced by get_wfr_comm_interval.
double nest::SimulationManager::wfr_tol_
Convergence tolerance of waveform relaxation method.
Referenced by get_wfr_tol.
long nest::SimulationManager::wfr_max_iterations_
maximal number of iterations used for waveform relaxation
size_t nest::SimulationManager::wfr_interpolation_order_
interpolation order for waveform relaxation method
Referenced by get_wfr_interpolation_order.
double nest::SimulationManager::update_time_limit_
throw exception if single update cycle takes longer than update_time_limit_ (seconds, default inf)
double nest::SimulationManager::min_update_time_
shortest update time seen so far (seconds)
double nest::SimulationManager::max_update_time_
longest update time seen so far (seconds)
Stopwatch nest::SimulationManager::sw_simulate_
Stopwatch nest::SimulationManager::sw_communicate_prepare_
nest::SimulationManager::SimulationManager()
void nest::SimulationManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References nest::Time::reset_resolution, nest::Time::reset_to_defaults.
void nest::SimulationManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
void nest::SimulationManager::set_status(const DictionaryDatum &) override
References nest::names::biological_time, nest::ConnectionManager::calibrate, nest::ModelManager::calibrate, nest::EventDeliveryManager::configure_spike_data_buffers, nest::KernelManager::connection_manager, nest::KernelManager::event_delivery_manager, nest::Time::get_ms, nest::Time::get_ms_per_tic, nest::Time::get_resolution, nest::Time::get_tics_per_ms, is_integer, nest::kernel, LOG, nest::M_ERROR, nest::M_INFO, nest::M_WARNING, nest::KernelManager::model_manager, nest::names::print_time, nest::names::resolution, nest::Time::set_resolution, nest::names::tics_per_ms, nest::TimeZero, nest::names::update_time_limit, nest::names::use_wfr, nest::names::wfr_comm_interval, nest::names::wfr_interpolation_order, nest::names::wfr_max_iterations, nest::names::wfr_tol.
void nest::SimulationManager::get_status(DictionaryDatum &) override
References nest::names::biological_time, nest::Time::get_ms_per_tic, nest::Time::get_resolution, nest::Time::get_tics_per_ms, nest::Time::get_tics_per_step, nest::Time::max, nest::names::max_update_time, nest::Time::min, nest::names::min_update_time, nest::names::ms_per_tic, nest::names::prepared, nest::names::print_time, nest::names::resolution, nest::names::T_max, nest::names::T_min, nest::names::tics_per_ms, nest::names::tics_per_step, nest::names::time_communicate_prepare, nest::names::time_simulate, nest::names::to_do, nest::names::update_time_limit, nest::names::use_wfr, nest::names::wfr_comm_interval, nest::names::wfr_interpolation_order, nest::names::wfr_max_iterations, nest::names::wfr_tol.
void nest::SimulationManager::assert_valid_simtime(Time const &)
check for errors in time before run
KernelException if illegal time passed
References nest::Time::get_resolution, nest::Time::is_finite, LOG, nest::M_ERROR, nest::Time::max.
void nest::SimulationManager::prepare() override
Initialize simulation for a set of run calls.
Must be called before a sequence of runs, and again after cleanup.
References nest::NodeManager::check_wfr_use, nest::EventDeliveryManager::configure_spike_data_buffers, nest::KernelManager::connection_manager, nest::NodeManager::ensure_valid_thread_local_ids, nest::MUSICManager::enter_runtime, nest::KernelManager::event_delivery_manager, nest::ConnectionManager::get_min_delay, nest::Time::get_ms, nest::Time::get_resolution, nest::VPManager::get_thread_id, nest::EventDeliveryManager::init_moduli, nest::kernel, LOG, nest::M_ERROR, nest::KernelManager::music_manager, nest::KernelManager::node_manager, nest::NodeManager::prepare_nodes, nest::EventDeliveryManager::reset_timers_for_dynamics, nest::ConnectionManager::update_delay_extrema_, nest::KernelManager::vp_manager.
void nest::SimulationManager::run(Time const &)
Run a simulation for another Time.
Can be repeated ad infinitum with calls to get_status(), but any changes to the network are undefined, leading serious risk of incorrect results.
References nest::RandomManager::check_rng_synchrony, nest::KernelManager::event_delivery_manager, nest::Time::get_steps, nest::KernelManager::io_manager, nest::kernel, LOG, nest::M_ERROR, nest::M_WARNING, nest::IOManager::post_run_hook, nest::IOManager::pre_run_hook, nest::KernelManager::random_manager, nest::EventDeliveryManager::reset_counters.
Referenced by nest::run.
void nest::SimulationManager::cleanup() override
Closes a set of runs, doing finalizations such as file closures.
After cleanup() is called, no more run()s can be called before another prepare() call.
References nest::NodeManager::finalize_nodes, nest::kernel, LOG, nest::M_ERROR, nest::KernelManager::node_manager.
bool nest::SimulationManager::use_wfr() const
Returns true if waveform relaxation is used.
References use_wfr_.
double nest::SimulationManager::get_wfr_comm_interval() const
Get the desired communication interval for the waveform relaxation.
References wfr_comm_interval_.
Referenced by nest::GenericConnectorModel< ConnectionT >::used_default_delay.
double nest::SimulationManager::get_wfr_tol() const
Get the convergence tolerance of the waveform relaxation method.
References wfr_tol_.
Referenced by nest::rate_neuron_ipn< TNonlinearities >::update_, nest::rate_neuron_opn< TNonlinearities >::update_, nest::rate_transformer_node< TNonlinearities >::update_.
size_t nest::SimulationManager::get_wfr_interpolation_order() const
Get the interpolation order of the waveform relaxation method.
References wfr_interpolation_order_.
Time const & nest::SimulationManager::get_slice_origin() const
Get the time at the beginning of the current time slice.
References clock_.
Referenced by nest::ConnectionManager::deliver_secondary_events, nest::iaf_psc_alpha_ps::handle, nest::iaf_psc_exp_ps::handle, nest::iaf_psc_exp_ps_lossless::handle, nest::parrot_neuron_ps::handle.
nest::Time const nest::SimulationManager::get_previous_slice_origin() const
Get the time at the beginning of the previous time slice.
References nest::kernel.
Time const nest::SimulationManager::get_time() const
Precise time of simulation.
The precise time of the simulation is defined only while the simulation is not in progress.
References clock_, from_step_, simulating_.
Referenced by nest::RecordingBackendSIONlib::close_files_, nest::RecordingBackendSIONlib::open_files_, nest::ac_generator::pre_run_hook, nest::noise_generator::pre_run_hook, nest::pulsepacket_generator::pre_run_hook, nest::sinusoidal_poisson_generator::pre_run_hook, run_end_time, run_start_time.
bool nest::SimulationManager::has_been_simulated() const
Return true, if the SimulationManager has already been simulated for some time.
This does NOT indicate that simulate has been called (i.e. if Simulate is called with 0 as argument, the flag is still set to false.)
References simulated_.
bool nest::SimulationManager::has_been_prepared() const
Return true, if the SimulationManager has been prepared for simulation.
This is the case from the time when the Prepare function is called until the simulation context is left by a call to Cleanup.
References prepared_.
size_t nest::SimulationManager::get_slice() const
Get slice number.
Increased by one for each slice. Can be used to choose alternating buffers.
References slice_.
Referenced by nest::EventDeliveryManager::write_toggle.
Time const & nest::SimulationManager::get_clock() const
Return current simulation time.
References clock_.
Referenced by nest::EventDeliveryManager::deliver_events_, nest::EventDeliveryManager::init_moduli, nest::EventDeliveryManager::update_moduli.
Time nest::SimulationManager::run_duration() const
Get the simulation duration in the current call to run().
References nest::Time::get_resolution, to_do_total_.
Time nest::SimulationManager::run_start_time() const
Get the start time of the current call to run().
References nest::Time::get_resolution, get_time, simulating_, to_do_, to_do_total_.
Time nest::SimulationManager::run_end_time() const
Get the simulation's time at the end of the current call to run().
References nest::Time::get_resolution, get_time, simulating_, to_do_.
delay nest::SimulationManager::get_from_step() const
Return start of current time slice, in steps.
References from_step_.
delay nest::SimulationManager::get_to_step() const
Return end of current time slice, in steps.
References to_step_.
void nest::SimulationManager::update_connection_infrastructure(const thread tid)
Sorts source table and connections and create new target table.
References nest::ConnectionManager::check_secondary_connections_exist, nest::ConnectionManager::clear_compressed_spike_data_map, nest::ConnectionManager::collect_compressed_spike_data, nest::MPIManager::communicate_recv_counts_secondary_events, nest::ConnectionManager::compress_secondary_send_buffer_pos, nest::ConnectionManager::compute_compressed_secondary_recv_buffer_positions, nest::ConnectionManager::compute_target_data_buffer_size, nest::EventDeliveryManager::configure_secondary_buffers, nest::KernelManager::connection_manager, nest::KernelManager::event_delivery_manager, nest::EventDeliveryManager::gather_target_data, nest::kernel, nest::KernelManager::mpi_manager, nest::KernelManager::node_manager, nest::EventDeliveryManager::resize_send_recv_buffers_target_data, nest::ConnectionManager::restructure_connection_tables, nest::NodeManager::set_have_nodes_changed, nest::ConnectionManager::sort_connections, nest::ConnectionManager::sync_has_primary_connections, nest::ConnectionManager::unset_connections_have_changed.
Referenced by nest::SPManager::disconnect, nest::ConnectionManager::get_connections.
void nest::SimulationManager::reset_timers_for_preparation()
Set time measurements for internal profiling to zero (reg.
prep.)
void nest::SimulationManager::reset_timers_for_dynamics()
Set time measurements for internal profiling to zero (reg.
sim. dyn.)
void nest::SimulationManager::call_update_()
actually run simulation, aka wrap update_
References nest::Time::get_ms, nest::NodeManager::get_num_active_nodes, nest::MPIManager::get_num_processes, nest::VPManager::get_num_threads, nest::Time::get_resolution, nest::kernel, LOG, nest::M_INFO, nest::KernelManager::mpi_manager, nest::KernelManager::node_manager, nest::MPIManager::synchronize, nest::KernelManager::vp_manager.
void nest::SimulationManager::update_()
References nest::MUSICManager::advance_music_time, nest::SparseNodeArray::begin, nest::KernelManager::connection_manager, nest::Node::decay_synaptic_elements_vacant, nest::EventDeliveryManager::deliver_secondary_events, nest::SparseNodeArray::end, nest::KernelManager::event_delivery_manager, nest::EventDeliveryManager::gather_secondary_events, nest::EventDeliveryManager::gather_spike_data, nest::NodeManager::get_local_nodes, nest::ConnectionManager::get_min_delay, nest::Time::get_ms, nest::VPManager::get_num_threads, nest::Time::get_resolution, nest::VPManager::get_thread_id, nest::NodeManager::get_wfr_nodes_on_thread, nest::KernelManager::io_manager, nest::kernel, LOG, nest::M_ERROR, nest::M_WARNING, nest::KernelManager::music_manager, nest::KernelManager::node_manager, nest::IOManager::post_step_hook, nest::KernelManager::sp_manager, nest::SPManager::update_structural_plasticity, nest::Node::update_synaptic_elements, nest::KernelManager::vp_manager.
bool nest::SimulationManager::wfr_update_(Node *)
actually perform simulation
void nest::SimulationManager::advance_time_()
Update time to next time step.
References nest::KernelManager::connection_manager, nest::KernelManager::event_delivery_manager, nest::ConnectionManager::get_min_delay, nest::kernel, nest::EventDeliveryManager::update_moduli.
void nest::SimulationManager::print_progress_()
TODO: Remove, replace by logging!
References nest::Time::get_ms, nest::Time::get_resolution.