BoolDatum
sli::pool BoolDatum::memory
const char * BoolDatum::true_string
Referenced by BoolDatum, print.
const char * BoolDatum::false_string
Referenced by print.
Datum * BoolDatum::clone() const override
Virtual copy constructor.
Use this function to lazily copy a datum.
References BoolDatum.
BoolDatum::BoolDatum()
Referenced by clone.
BoolDatum::BoolDatum(const BoolDatum &)=default
BoolDatum & BoolDatum::operator=(const BoolDatum &)=default
BoolDatum::BoolDatum(bool val)
BoolDatum::BoolDatum(const Name &)
References GenericDatum< bool, &SLIInterpreter::Booltype >::d, true_string.
BoolDatum::operator bool() const
References GenericDatum< bool, &SLIInterpreter::Booltype >::d.
BoolDatum::operator Name() const
BoolDatum::operator std::string() const
void BoolDatum::input_form(std::ostream &) const override
References print.
void BoolDatum::print(std::ostream &) const override
References GenericDatum< bool, &SLIInterpreter::Booltype >::d, false_string, true_string.
Referenced by input_form, pprint.
void BoolDatum::pprint(std::ostream &) const override
References print.
void * BoolDatum::operator new(size_t size)
void BoolDatum::operator delete(void *p, size_t size)