nest::Target
using nest::Target::bits_for_processed_flag = StaticAssert< NUM_BITS_PROCESSED_FLAG == 1U >::success
using nest::Target::position_of_processed_flag = StaticAssert< BITPOS_PROCESSED_FLAG == 63U >::success
uint64_t nest::Target::remote_target_id_
Referenced by get_lcid, get_rank, get_status, get_syn_id, get_tid, operator=, set_lcid, set_rank, set_status, set_syn_id, set_tid.
constexpr uint8_t nest::Target::BITPOS_LCID
Referenced by get_lcid, set_lcid.
constexpr uint8_t nest::Target::BITPOS_RANK
Referenced by get_rank, set_rank.
constexpr uint8_t nest::Target::BITPOS_TID
Referenced by get_tid, set_tid.
constexpr uint8_t nest::Target::BITPOS_SYN_ID
Referenced by get_syn_id, set_syn_id.
constexpr uint8_t nest::Target::BITPOS_PROCESSED_FLAG
Referenced by get_status.
constexpr uint64_t nest::Target::MASK_LCID
Referenced by get_lcid.
constexpr uint64_t nest::Target::MASK_RANK
Referenced by get_rank.
constexpr uint64_t nest::Target::MASK_TID
Referenced by get_tid.
constexpr uint64_t nest::Target::MASK_SYN_ID
Referenced by get_syn_id.
constexpr uint64_t nest::Target::MASK_PROCESSED_FLAG
Referenced by get_status, set_status.
nest::Target::Target()
nest::Target::Target(const Target &target)
References set_status, nest::TARGET_ID_UNPROCESSED.
nest::Target::Target(const thread tid, const thread rank, const synindex syn_id, const index lcid)
References nest::MAX_LCID, nest::MAX_RANK, nest::MAX_SYN_ID, nest::MAX_TID, set_lcid, set_rank, set_status, set_syn_id, set_tid, nest::TARGET_ID_UNPROCESSED.
Target & nest::Target::operator=(const Target &)
References remote_target_id_, set_status, nest::TARGET_ID_UNPROCESSED.
void nest::Target::set_lcid(const index lcid)
Set local connection id.
References BITPOS_LCID, nest::MAX_LCID, remote_target_id_.
Referenced by Target.
index nest::Target::get_lcid() const
Return local connection id.
References BITPOS_LCID, MASK_LCID, remote_target_id_.
void nest::Target::set_rank(const thread rank)
Set rank.
References BITPOS_RANK, nest::MAX_RANK, remote_target_id_.
Referenced by Target.
thread nest::Target::get_rank() const
Return rank.
References BITPOS_RANK, MASK_RANK, remote_target_id_.
void nest::Target::set_tid(const thread tid)
Set thread id.
References BITPOS_TID, nest::MAX_TID, remote_target_id_.
Referenced by Target.
thread nest::Target::get_tid() const
Return thread id.
References BITPOS_TID, MASK_TID, remote_target_id_.
void nest::Target::set_syn_id(const synindex syn_id)
Set the synapse-type id.
References BITPOS_SYN_ID, nest::MAX_SYN_ID, remote_target_id_.
Referenced by Target.
synindex nest::Target::get_syn_id() const
Return synapse-type id.
References BITPOS_SYN_ID, MASK_SYN_ID, remote_target_id_.
void nest::Target::set_status(enum_status_target_id status)
Set the status of the target identifier: processed or unprocessed.
References MASK_PROCESSED_FLAG, remote_target_id_, nest::TARGET_ID_PROCESSED, nest::TARGET_ID_UNPROCESSED.
Referenced by mark_for_removal, operator=, Target.
enum_status_target_id nest::Target::get_status() const
Get the status of the target identifier: processed or unprocessed.
References BITPOS_PROCESSED_FLAG, MASK_PROCESSED_FLAG, remote_target_id_, nest::TARGET_ID_PROCESSED, nest::TARGET_ID_UNPROCESSED.
Referenced by is_processed.
bool nest::Target::is_processed() const
Return the status od the target identifier: processed or unprocessed.
References get_status, nest::TARGET_ID_PROCESSED.
double nest::Target::get_offset() const
Return offset.
void nest::Target::mark_for_removal()
Set the status of the target identifier to processed.
References set_status, nest::TARGET_ID_PROCESSED.