nest::CurrentEvent
double nest::CurrentEvent::c_
Referenced by get_current, set_current.
void nest::CurrentEvent::operator()() override
Deliver the event to receiver.
This operator calls the handler for the specific event type at the receiver.
References nest::Node::handle, nest::Event::receiver_.
CurrentEvent * nest::CurrentEvent::clone() const override
Virtual copy constructor.
void nest::CurrentEvent::set_current(double)
References nest::names::c, c_.
Referenced by nest::ac_generator::update, nest::dc_generator::update, nest::step_current_generator::update.
double nest::CurrentEvent::get_current() const
References c_.