BlockVector
using BlockVector< value_type_ >::value_type = value_type_
using BlockVector< value_type_ >::difference_type = typename std::vector< value_type >::difference_type
using BlockVector< value_type_ >::const_reference = const value_type&
using BlockVector< value_type_ >::const_pointer = const value_type*
using BlockVector< value_type_ >::iterator = bv_iterator< value_type_, value_type_&, value_type_* >
using BlockVector< value_type_ >::const_iterator = bv_iterator< value_type_, const value_type_&, const value_type_* >
using BlockVector< value_type_ >::reverse_iterator = std::reverse_iterator< iterator >
using BlockVector< value_type_ >::const_reverse_iterator = std::reverse_iterator< const_iterator >
using BlockVector< value_type_ >::size_type = size_t
friend class bv_iterator
std::vector< std::vector< value_type_ > > BlockVector< value_type_ >::blockmap_
Vector holding blocks containing data.
Referenced by BlockVector< value_type_ >::BlockVector.
iterator BlockVector< value_type_ >::finish_
Iterator pointing to one past the last element.
Referenced by BlockVector< value_type_ >::BlockVector.
BlockVector< value_type_ >::BlockVector()
Creates an empty BlockVector.
BlockVector< value_type_ >::BlockVector(size_t)
Creates a BlockVector containing a number of elements.
n Number of elements.
References BlockVector< value_type_ >::begin, BlockVector< value_type_ >::blockmap_, BlockVector< value_type_ >::finish_, max_block_size, nest::names::n.
BlockVector< value_type_ >::BlockVector(const BlockVector< value_type_ > &)
BlockVector copy constructor.
other BlockVector to copy.
BlockVector< value_type_ >::~BlockVector()
value_type_ & BlockVector< value_type_ >::operator[](const size_t pos)
Subscript access to the data contained in the BlockVector.
pos The index of the element for which data should be accessed. Read/write reference to data. Note that data access with this operator is unchecked.
References block_size_shift, max_block_size_sub_1.
const value_type_ & BlockVector< value_type_ >::operator[](const size_t pos) const
Subscript access to the data contained in the BlockVector.
pos The index of the element for which data should be accessed. Read-only (constant) reference to data. Note that data access with this operator is unchecked.
References block_size_shift, max_block_size_sub_1.
BlockVector< value_type_ >::iterator BlockVector< value_type_ >::begin()
Returns a read/write iterator that points to the first element in the BlockVector.
Iteration is done in ordinary element order.
Referenced by BlockVector< value_type_ >::BlockVector, nest::SourceTable::clean, nest::Connector< ConnectionT >::remove_disabled_connections, nest::SourceTable::remove_disabled_sources, nest::sort.
BlockVector< value_type_ >::const_iterator BlockVector< value_type_ >::begin() const
Returns a read-only (constant) iterator that points to the first element in the BlockVector.
Iteration is done in ordinary element order.
BlockVector< value_type_ >::iterator BlockVector< value_type_ >::end()
Returns a read/write iterator that points one past the last element in the BlockVector.
Iteration is done in ordinary element order.
Referenced by nest::SourceTable::clean, nest::Connector< ConnectionT >::remove_disabled_connections, nest::SourceTable::remove_disabled_sources, nest::sort.
BlockVector< value_type_ >::const_iterator BlockVector< value_type_ >::end() const
Returns a read-only (constant) iterator that points one past the last element in the BlockVector.
Iteration is done in ordinary element order.
void BlockVector< value_type_ >::push_back(const value_type_ &value)
Add data to the end of the BlockVector.
value Data to be added. Assigns given data to the element at the end of the BlockVector.
References max_block_size.
Referenced by nest::Connector< ConnectionT >::get_connection, nest::Connector< ConnectionT >::get_connection_with_specified_targets, nest::Connector< ConnectionT >::get_source_lcids, nest::Connector< ConnectionT >::push_back.
void BlockVector< value_type_ >::clear()
Erases all the elements.
References max_block_size.
Referenced by nest::SourceTable::clean, nest::Connector< ConnectionT >::~Connector.
size_t BlockVector< value_type_ >::size() const
Returns the number of elements in the BlockVector.
References max_block_size.
Referenced by nest::SourceTable::clean, nest::Connector< ConnectionT >::get_all_connections, nest::Connector< ConnectionT >::get_source_lcids, nest::Connector< ConnectionT >::get_synapse_status, nest::quicksort3way, nest::SourceTable::remove_disabled_sources, nest::Connector< ConnectionT >::send_to_all, nest::Connector< ConnectionT >::set_synapse_status, nest::Connector< ConnectionT >::size, nest::sort, nest::Connector< ConnectionT >::trigger_update_weight.
BlockVector< value_type_ >::iterator BlockVector< value_type_ >::erase(const_iterator, const_iterator)
Remove a range of elements.
first Iterator pointing to the first element to be erased. last Iterator pointing one past the last element to be erased. An iterator pointing to the element pointed to by last prior to erasing (or end()). This function will erase the elements in the range [first, last) and shorten the BlockVector accordingly.
References bv_iterator< value_type_, ref_, ptr_ >::block_vector_, nest::names::clear, bv_iterator< value_type_, ref_, ptr_ >::const_cast_, max_block_size.
Referenced by nest::SourceTable::clean, nest::Connector< ConnectionT >::remove_disabled_connections, nest::SourceTable::remove_disabled_sources.
void BlockVector< value_type_ >::print_blocks() const
Writes the contents of the BlockVector, separated into blocks, to cerr.
int BlockVector< value_type_ >::get_max_block_size() const
Returns the block-size.
References max_block_size.
BlockVector< value_type_ >::size_type BlockVector< value_type_ >::max_size() const
Returns the size() of the largest possible BlockVector.
BlockVector< value_type_ >::reverse_iterator BlockVector< value_type_ >::rbegin()
Returns a read/write reverse iterator that points to the last element in the BlockVector.
Iteration is done in reverse element order.
BlockVector< value_type_ >::reverse_iterator BlockVector< value_type_ >::rbegin() const
Returns a read-only (constant) reverse iterator that points to the last element in the BlockVector.
Iteration is done in reverse element order.
BlockVector< value_type_ >::reverse_iterator BlockVector< value_type_ >::rend()
Returns a read/write reverse iterator that points to one before the first element in the BlockVector.
Iteration is done in reverse element order.
BlockVector< value_type_ >::reverse_iterator BlockVector< value_type_ >::rend() const
Returns a read-only (constant) reverse iterator that points to one before the first element in the BlockVector.
Iteration is done in reverse element order.