nest::DelayChecker
Time nest::DelayChecker::min_delay_
Minimal delay of all created synapses.
Referenced by DelayChecker, get_min_delay.
Time nest::DelayChecker::max_delay_
Maximal delay of all created synapses.
Referenced by DelayChecker, get_max_delay.
bool nest::DelayChecker::user_set_delay_extrema_
Flag indicating if the user set the delay extrema.
Referenced by get_user_set_delay_extrema.
bool nest::DelayChecker::freeze_delay_update_
Referenced by enable_delay_update, freeze_delay_update.
nest::DelayChecker::DelayChecker()
nest::DelayChecker::DelayChecker(const DelayChecker &)
References nest::Time::calibrate, max_delay_, min_delay_.
const Time & nest::DelayChecker::get_min_delay() const
References min_delay_.
const Time & nest::DelayChecker::get_max_delay() const
References max_delay_.
void nest::DelayChecker::freeze_delay_update()
This method freezes the min/ max delay update in SetDefaults of connections method.
This is used, when the delay of default connections in the ConnectorModel is set: we do not know, whether new connections with this delay will ever be created.
References freeze_delay_update_.
Referenced by nest::GenericConnectorModel< ConnectionT >::set_status.
void nest::DelayChecker::enable_delay_update()
This method enables the min/ max delay update in SetDefaults of connections method.
This is used, when the delay of default connections in the ConnectorModel is set: we do not know, whether new connections with this delay will ever be created.
References freeze_delay_update_.
Referenced by nest::GenericConnectorModel< ConnectionT >::set_status.
void nest::DelayChecker::assert_valid_delay_ms(double)
Raise exception if delay value in milliseconds is invalid.
Not const, since it may update delay extrema as a side-effect.
References nest::KernelManager::connection_manager, nest::Time::delay_ms_to_steps, nest::Time::delay_steps_to_ms, nest::ConnectionManager::get_max_delay, nest::ConnectionManager::get_min_delay, nest::Time::get_resolution, nest::kernel.
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection, nest::cont_delay_synapse< targetidentifierT >::set_status, nest::Connection< targetidentifierT >::set_status, nest::GenericConnectorModel< ConnectionT >::used_default_delay.
void nest::DelayChecker::assert_two_valid_delays_steps(delay, delay)
Raise exception if either of the two delays in steps is invalid.
Setting continuous delays requires testing d and d+1. This function implements this more efficiently than two calls to assert_valid_delay(). This test accepts the delays in steps, as this makes more sense when working with continuous delays. Not const, since it may update delay extrema as a side-effect.
References nest::KernelManager::connection_manager, nest::Time::delay_steps_to_ms, nest::ConnectionManager::get_max_delay, nest::ConnectionManager::get_min_delay, nest::Time::get_resolution, nest::kernel, nest::names::max, nest::names::min.
Referenced by nest::cont_delay_synapse< targetidentifierT >::set_status.
bool nest::DelayChecker::get_user_set_delay_extrema() const
References user_set_delay_extrema_.
void nest::DelayChecker::calibrate(const TimeConverter &)
References nest::TimeConverter::from_old_tics, nest::Time::get_ms, nest::Time::neg_inf, nest::Time::pos_inf, set_min_max_delay_.
void nest::DelayChecker::get_status(DictionaryDatum &) const
References nest::names::max_delay, nest::names::min_delay.
void nest::DelayChecker::set_status(const DictionaryDatum &)
References nest::names::d, nest::kernel, nest::names::max_delay, nest::names::min_delay, set_min_max_delay_.
void nest::DelayChecker::set_min_max_delay_(const double, const double)
References nest::Time::get_ms, nest::Time::get_resolution, nest::Time::get_steps, LOG, nest::M_INFO.
Referenced by calibrate, set_status.