nest::iaf_psc_delta_ps
friend class RecordablesMap< iaf_psc_delta_ps >
friend class UniversalDataLogger< iaf_psc_delta_ps >
Parameters_ nest::iaf_psc_delta_ps::P_
Referenced by get_status, get_V_m_, pre_run_hook, set_status, update.
State_ nest::iaf_psc_delta_ps::S_
Referenced by get_status, get_V_m_, set_status, update.
Variables_ nest::iaf_psc_delta_ps::V_
Referenced by pre_run_hook, update.
Buffers_ nest::iaf_psc_delta_ps::B_
Referenced by handle, handles_test_event, pre_run_hook, update.
void nest::iaf_psc_delta_ps::init_buffers_() override
Configure persistent internal data structures.
Let node configure persistent internal data structures, such as input buffers or ODE solvers, to runtime information prior to first simulation.
References nest::ArchivingNode::clear_history.
void nest::iaf_psc_delta_ps::pre_run_hook() override
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
References B_, nest::iaf_psc_delta_ps::Parameters_::c_m_, nest::iaf_psc_delta_ps::Variables_::exp_t_, numerics::expm1, nest::iaf_psc_delta_ps::Variables_::expm1_t_, nest::Time::get_ms, nest::Time::get_resolution, nest::Time::get_steps, nest::iaf_psc_delta_ps::Variables_::h_ms_, nest::iaf_psc_delta_ps::Buffers_::logger_, P_, nest::iaf_psc_delta_ps::Variables_::R_, nest::iaf_psc_delta_ps::Variables_::refractory_steps_, nest::iaf_psc_delta_ps::Parameters_::t_ref_, nest::iaf_psc_delta_ps::Parameters_::tau_m_, V_.
void nest::iaf_psc_delta_ps::update(Time const &, const long, const long) override
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to. Time network time at beginning of time slice. long initial step inside time slice long post-final step inside time slice
References nest::SliceRingBuffer::add_refractory, B_, nest::iaf_psc_delta_ps::Buffers_::currents_, emit_instant_spike_, emit_spike_, nest::iaf_psc_delta_ps::Buffers_::events_, nest::iaf_psc_delta_ps::Variables_::expm1_t_, nest::SliceRingBuffer::get_next_spike, nest::RingBuffer::get_value, nest::iaf_psc_delta_ps::Variables_::h_ms_, nest::iaf_psc_delta_ps::State_::I_, nest::iaf_psc_delta_ps::Parameters_::I_e_, nest::iaf_psc_delta_ps::State_::is_refractory_, nest::kernel, nest::iaf_psc_delta_ps::State_::last_spike_offset_, nest::iaf_psc_delta_ps::State_::last_spike_step_, nest::iaf_psc_delta_ps::Buffers_::logger_, P_, nest::SliceRingBuffer::prepare_delivery, propagate_, nest::iaf_psc_delta_ps::Variables_::R_, nest::iaf_psc_delta_ps::Variables_::refr_spikes_buffer_, nest::iaf_psc_delta_ps::Variables_::refractory_steps_, S_, nest::iaf_psc_delta_ps::Parameters_::t_ref_, nest::iaf_psc_delta_ps::Parameters_::tau_m_, nest::iaf_psc_delta_ps::State_::U_, nest::iaf_psc_delta_ps::Parameters_::U_min_, nest::iaf_psc_delta_ps::Parameters_::U_th_, V_, nest::iaf_psc_delta_ps::State_::with_refr_input_.
void nest::iaf_psc_delta_ps::emit_spike_(Time const &origin, const long lag, const double offset_U)
Calculate the precise spike time, emit the spike and reset the neuron.
origin Time stamp at beginning of slice lag Time step within slice offset_U Time offset for U value, i.e. for time when threshold crossing was detected
References nest::KernelManager::event_delivery_manager, nest::kernel, nest::EventDeliveryManager::send, nest::Event::set_offset.
Referenced by update.
void nest::iaf_psc_delta_ps::emit_instant_spike_(Time const &origin, const long lag, const double spike_offset)
Instantaneously emit a spike at the precise time defined by origin, lag and spike_offset and reset the neuron.
origin Time stamp at beginning of slice lag Time step within slice spike_offset Time offset for spike
References nest::KernelManager::event_delivery_manager, nest::kernel, nest::EventDeliveryManager::send, nest::Event::set_offset.
Referenced by update.
void nest::iaf_psc_delta_ps::propagate_(const double dt)
Propagate neuron state.
Propagate the neuron's state by dt. dt Interval over which to propagate
References numerics::expm1.
Referenced by update.
double nest::iaf_psc_delta_ps::get_V_m_() const
Read out the real membrane potential.
References nest::iaf_psc_delta_ps::Parameters_::E_L_, P_, S_, nest::iaf_psc_delta_ps::State_::U_.
Referenced by nest::RecordablesMap< HostNode >::create.
RecordablesMap< iaf_psc_delta_ps > nest::iaf_psc_delta_ps::recordablesMap_
Mapping of recordables names to access functions.
Referenced by get_status, handles_test_event, iaf_psc_delta_ps.
nest::iaf_psc_delta_ps::iaf_psc_delta_ps()
Basic constructor.
This constructor should only be used by GenericModel to create model prototype instances.
References recordablesMap_.
nest::iaf_psc_delta_ps::iaf_psc_delta_ps(const iaf_psc_delta_ps &)
Copy constructor.
GenericModel::create_() uses the copy constructor to clone actual model instances from the prototype instance. The copy constructor MUST NOT be used to create nodes based on nodes that have been placed in the network.
port nest::iaf_psc_delta_ps::send_test_event(Node &, rport, synindex, bool) override
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws IllegalConnection. This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node. If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
port nest::iaf_psc_delta_ps::handles_test_event(SpikeEvent &, rport) override
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event(). handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle. See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3. The semantics of all other handles_test_event() functions is identical. IllegalConnection
References nest::Node::get_name.
port nest::iaf_psc_delta_ps::handles_test_event(CurrentEvent &, rport) override
References nest::Node::get_name.
port nest::iaf_psc_delta_ps::handles_test_event(DataLoggingRequest &, rport) override
References B_, nest::Node::get_name, nest::iaf_psc_delta_ps::Buffers_::logger_, recordablesMap_.
void nest::iaf_psc_delta_ps::handle(SpikeEvent &) override
Handle incoming spike events.
Default implementation of event handlers just throws an UnexpectedEvent exception. thrd Id of the calling thread. e Event object. This handler has to be implemented if a Node should accept spike events. class SpikeEvent class UnexpectedEvent UnexpectedEvent This is the default event to throw.
References nest::SliceRingBuffer::add_spike, B_, nest::iaf_psc_delta_ps::Buffers_::events_, nest::kernel.
void nest::iaf_psc_delta_ps::handle(CurrentEvent &) override
Handler for current events.
handle(thread, SpikeEvent&) UnexpectedEvent
References nest::RingBuffer::add_value, B_, nest::iaf_psc_delta_ps::Buffers_::currents_, nest::kernel.
void nest::iaf_psc_delta_ps::handle(DataLoggingRequest &) override
Handler for universal data logging request.
handle(SpikeEvent&) UnexpectedEvent
bool nest::iaf_psc_delta_ps::is_off_grid() const override
Returns true if the node sends/receives off-grid events.
This is used to discriminate between different types of nodes when adding new nodes to the network.
void nest::iaf_psc_delta_ps::get_status(DictionaryDatum &) const override
Export properties of the node by setting entries in the status dictionary.
d Dictionary.
References nest::iaf_psc_delta_ps::Parameters_::get, nest::iaf_psc_delta_ps::State_::get, nest::ArchivingNode::get_status, P_, nest::names::recordables, recordablesMap_, S_.
void nest::iaf_psc_delta_ps::set_status(const DictionaryDatum &) override
Change properties of the node according to the entries in the dictionary.
d Dictionary with named parameter settings.
References P_, S_, nest::iaf_psc_delta_ps::State_::set, nest::iaf_psc_delta_ps::Parameters_::set, nest::ArchivingNode::set_status.
void nest::Node::handle(SpikeEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(WeightRecorderEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(RateEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DataLoggingRequest &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DataLoggingReply &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(CurrentEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(ConductanceEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DoubleDataEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(GapJunctionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(InstantaneousRateConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DiffusionConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DelayedRateConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
port nest::Node::handles_test_event(SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event(). handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle. See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3. The semantics of all other handles_test_event() functions is identical. IllegalConnection
port nest::Node::handles_test_event(WeightRecorderEvent &, rport receptor_type)
port nest::Node::handles_test_event(RateEvent &, rport receptor_type)
port nest::Node::handles_test_event(DataLoggingRequest &, rport receptor_type)
port nest::Node::handles_test_event(CurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(ConductanceEvent &, rport receptor_type)
port nest::Node::handles_test_event(DoubleDataEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSSpikeEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSCurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(GapJunctionEvent &, rport receptor_type)
port nest::Node::handles_test_event(InstantaneousRateConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DiffusionConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DelayedRateConnectionEvent &, rport receptor_type)