nest::SparseNodeArray
typedef BlockVector<SparseNodeArray::NodeEntry>::const_iterator nest::SparseNodeArray::const_iterator
Iterator inherited from BlockVector.
BlockVector< NodeEntry > nest::SparseNodeArray::nodes_
stores local node information
Referenced by begin.
index nest::SparseNodeArray::global_max_node_id_
globally largest node ID
index nest::SparseNodeArray::local_min_node_id_
smallest local node ID
index nest::SparseNodeArray::local_max_node_id_
largest local node ID
double nest::SparseNodeArray::left_scale_
scale factor for left side of array
double nest::SparseNodeArray::right_scale_
scale factor for right side of array
index nest::SparseNodeArray::split_node_id_
Globally smallest node ID in right side of array.
Is updated by set_max_node_id() Is global_max_node_id_ + 1 as long as right side is empty.
size_t nest::SparseNodeArray::split_idx_
Array index of first element in right side of array.
bool nest::SparseNodeArray::have_split_
Mark whether split has happened during network construction.
False as long as only one kind of neuron has been added.
bool nest::SparseNodeArray::left_side_has_proxies_
Proxy status of nodes on left side of array.
nest::SparseNodeArray::SparseNodeArray()
Create empty sparse node array.
size_t nest::SparseNodeArray::size() const
Return size of container.
This is the number of local nodes. get_max_node_id()
void nest::SparseNodeArray::clear()
Clear the array.
void nest::SparseNodeArray::add_local_node(Node &)
Add single local node.
References nest::Node::get_node_id, nest::VPManager::get_num_virtual_processes, nest::Node::has_proxies, nest::kernel, nest::KernelManager::vp_manager.
void nest::SparseNodeArray::set_max_node_id(index)
Set max node ID to maximum in network.
This also sets split_node_id_ to max node ID + 1 as long as we have not split. Must be called by any method adding nodes to the network at end of each batch of nodes added.
nest::index nest::SparseNodeArray::get_max_node_id() const
Globally largest node ID.
nest::Node * nest::SparseNodeArray::get_node_by_node_id(index) const
Return pointer to node or nullptr if node is not local.
The caller is responsible for providing proper proxy-node pointers for non-local nodes.
nest::Node * nest::SparseNodeArray::get_node_by_index(size_t) const
Lookup node based on index into container.
Required for target lookup by HPC synapses.
nest::SparseNodeArray::const_iterator nest::SparseNodeArray::begin() const
Constant iterators for safe iteration of SparseNodeArray.
References nodes_.
Referenced by nest::OneToOneBuilder::connect_, nest::AllToAllBuilder::connect_, nest::FixedInDegreeBuilder::connect_, nest::BernoulliBuilder::connect_, nest::SPManager::get_synaptic_elements, nest::SimulationManager::update_.
nest::SparseNodeArray::const_iterator nest::SparseNodeArray::end() const
Referenced by nest::OneToOneBuilder::connect_, nest::AllToAllBuilder::connect_, nest::FixedInDegreeBuilder::connect_, nest::BernoulliBuilder::connect_, nest::SPManager::get_synaptic_elements, nest::SimulationManager::update_.
bool nest::SparseNodeArray::is_consistent_() const