TrieDatum
sli::pool TrieDatum::memory
Referenced by operator delete, operator new.
Name TrieDatum::name
Referenced by getname, print.
TypeTrie TrieDatum::tree
Referenced by equals, get, info, insert, insert_move, lookup.
Datum * TrieDatum::clone() const override
Virtual copy constructor.
Use this function to lazily copy a datum.
Datum * TrieDatum::get_ptr() override
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
The prefix const indicates that the pointer should be trated as const because changes affect all other references as well.
References Datum::addReference.
TrieDatum::TrieDatum(TrieDatum const &fd)
References Datum::set_executable.
TrieDatum::TrieDatum(Name const &n)
References Datum::set_executable.
TrieDatum::TrieDatum(Name const &n, const TokenArray &ta)
References Datum::set_executable.
void TrieDatum::print(std::ostream &o) const override
References name.
Referenced by pprint, SLIInterpreter::stack_backtrace.
void TrieDatum::pprint(std::ostream &o) const override
References print.
Referenced by info.
void TrieDatum::info(std::ostream &out) const override
References TypeTrie::info, pprint, tree.
bool TrieDatum::equals(Datum const *) const override
References tree.
const Name & TrieDatum::getname() const
References name.
Referenced by AddtotrieFunction::execute, Cva_tFunction::execute, SLIInterpreter::getcurrentname.
void TrieDatum::insert(const TypeArray &a, const Token &t)
References TypeTrie::insert, tree.
void TrieDatum::insert_move(const TypeArray &a, Token &t)
References TypeTrie::insert_move, tree.
Referenced by AddtotrieFunction::execute.
const Token & TrieDatum::lookup(const TokenStack &s) const
References TypeTrie::lookup, tree.
Referenced by TrietypeFunction::execute.
TypeTrie & TrieDatum::get()
References tree.
Referenced by TrieInfoFunction::execute, Cva_tFunction::execute, SLIInterpreter::print_error.
static void * TrieDatum::operator new(size_t size)
References sli::pool::alloc, memory, sli::pool::size_of.
static void TrieDatum::operator delete(void *p, size_t size)
References sli::pool::free, memory, sli::pool::size_of.