nest::PerThreadBoolIndicator
std::vector< BoolIndicatorUInt64 > nest::PerThreadBoolIndicator::per_thread_status_
Referenced by all_false, all_true, any_false, any_true, initialize, operator[].
nest::PerThreadBoolIndicator::PerThreadBoolIndicator()
BoolIndicatorUInt64 & nest::PerThreadBoolIndicator::operator[](const thread tid)
References per_thread_status_.
void nest::PerThreadBoolIndicator::initialize(const thread num_threads, const bool status)
Resize to the given number of threads and set all elements to false.
References nest::VPManager::assert_single_threaded, per_thread_status_.
Referenced by nest::EventDeliveryManager::initialize.
bool nest::PerThreadBoolIndicator::all_false() const
Waits for all threads and returns whether all elements are false.
References per_thread_status_.
Referenced by nest::EventDeliveryManager::gather_spike_data_, nest::EventDeliveryManager::gather_target_data.
bool nest::PerThreadBoolIndicator::all_true() const
Waits for all threads and returns whether all elements are true.
References per_thread_status_.
Referenced by nest::EventDeliveryManager::gather_spike_data_, nest::EventDeliveryManager::gather_target_data.
bool nest::PerThreadBoolIndicator::any_false() const
Waits for all threads and returns whether any elements are false.
References per_thread_status_.
Referenced by nest::EventDeliveryManager::gather_spike_data_, nest::EventDeliveryManager::gather_target_data.
bool nest::PerThreadBoolIndicator::any_true() const
Waits for all threads and returns whether any elements are true.
References per_thread_status_.