nest::CompTree
Compartment nest::CompTree::root_
Referenced by get_root.
std::vector< long > nest::CompTree::compartment_indices_
std::vector< Compartment* > nest::CompTree::compartments_
Referenced by CompTree.
std::vector< Compartment* > nest::CompTree::leafs_
Referenced by CompTree.
long nest::CompTree::size_
Referenced by get_size.
void nest::CompTree::solve_matrix_downsweep(Compartment *compartment_ptr, std::vector< Compartment * >::iterator leaf_it)
References nest::Compartment::children, nest::Compartment::gather_input, nest::Compartment::io, nest::Compartment::n_passed, nest::Compartment::parent.
void nest::CompTree::solve_matrix_upsweep(Compartment *compartment, double vv)
References nest::Compartment::calc_v, nest::Compartment::children.
void nest::CompTree::set_parents()
For each compartments, sets its pointer towards its parent compartment.
References nest::Compartment::p_index, nest::Compartment::parent.
void nest::CompTree::set_compartments()
Creates a vector of compartment pointers, organized in the order in which they were added by add_compartment()
void nest::CompTree::set_leafs()
Creates a vector of compartment pointers of compartments that are also leafs of the tree.
nest::CompTree::CompTree()
References compartments_, leafs_.
nest::CompTree::~CompTree()
void nest::CompTree::add_compartment(const long parent_index)
Add a compartment to the tree structure via the python interface root should have -1 as parent index.
Add root compartment first. Assumes parent of compartment is already added
void nest::CompTree::add_compartment(const long parent_index, const DictionaryDatum &compartment_params)
void nest::CompTree::add_compartment(Compartment *compartment, const long parent_index)
References nest::Compartment::children, nest::Compartment::comp_index.
void nest::CompTree::pre_run_hook()
Initialize state variables.
void nest::CompTree::init_pointers()
Initialize all tree structure pointers.
void nest::CompTree::set_syn_buffers(std::vector< RingBuffer > &syn_buffers)
Initializes pointers for the spike buffers for all synapse receptors.
std::map< Name, double * > nest::CompTree::get_recordables()
Returns a map of variable names and pointers to the recordables.
References nest::names::recordables.
nest::Compartment * nest::CompTree::get_compartment(const long compartment_index) const
Get the compartment corresponding to the provided index in the tree.
This function gets the compartments by a recursive search through the tree. The overloaded functions looks only in the subtree of the provided compartment, and also has the option to throw an error if no compartment corresponding to compartment_index is found in the tree
Referenced by nest::cm_default::get_status, nest::cm_default::handles_test_event.
nest::Compartment * nest::CompTree::get_compartment(const long compartment_index, Compartment *compartment, const long raise_flag) const
References nest::Compartment::children, nest::Compartment::comp_index.
nest::Compartment * nest::CompTree::get_compartment_opt(const long compartment_indx) const
Get the compartment corresponding to the provided index in the tree.
Optimized trough the use of a pointer vector containing all compartments. Calling this function before CompTree::init_pointers() is called will result in a segmentation fault
Compartment* nest::CompTree::get_root() const
References root_.
Referenced by nest::cm_default::handles_test_event.
long nest::CompTree::get_size() const
References size_.
Referenced by nest::cm_default::get_status, nest::cm_default::handles_test_event.
std::vector< double > nest::CompTree::get_voltage() const
Returns vector of voltage values, indices correspond to compartments in compartments_
double nest::CompTree::get_compartment_voltage(const long compartment_index)
Return voltage of single compartment voltage, indicated by the compartment_index.
void nest::CompTree::construct_matrix(const long lag)
Construct the matrix equation to be solved to advance the model one timestep.
void nest::CompTree::solve_matrix()
Solve matrix with O(n) algorithm.
void nest::CompTree::print_tree() const
Print the tree graph.
References nest::Compartment::ca, nest::Compartment::comp_index, nest::Compartment::el, nest::Compartment::gc, nest::Compartment::gl, nest::Compartment::parent.