nest::Ntree
typedef Position< D > nest::Ntree< D, T, max_capacity, max_depth >::key_type
typedef T nest::Ntree< D, T, max_capacity, max_depth >::mapped_type
typedef std::pair< Position< D >, T > nest::Ntree< D, T, max_capacity, max_depth >::value_type
typedef value_type& nest::Ntree< D, T, max_capacity, max_depth >::reference
typedef const value_type& nest::Ntree< D, T, max_capacity, max_depth >::const_reference
const int nest::Ntree< D, T, max_capacity, max_depth >::N
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::iterator::next_leaf_, nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::next_leaf_, nest::Ntree< D, T, max_capacity, max_depth >::split_.
Position< D > nest::Ntree< D, T, max_capacity, max_depth >::lower_left_
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::masked_iterator, nest::Ntree< D, T, max_capacity, max_depth >::split_, nest::Ntree< D, T, max_capacity, max_depth >::subquad_.
Position< D > nest::Ntree< D, T, max_capacity, max_depth >::extent_
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::masked_iterator, nest::Ntree< D, T, max_capacity, max_depth >::split_, nest::Ntree< D, T, max_capacity, max_depth >::subquad_.
bool nest::Ntree< D, T, max_capacity, max_depth >::leaf_
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::is_leaf, nest::Ntree< D, T, max_capacity, max_depth >::iterator::iterator, nest::Ntree< D, T, max_capacity, max_depth >::split_.
std::vector< value_type > nest::Ntree< D, T, max_capacity, max_depth >::nodes_
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::iterator::iterator, nest::Ntree< D, T, max_capacity, max_depth >::iterator::operator*, nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::operator*, nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::operator++, nest::Ntree< D, T, max_capacity, max_depth >::iterator::operator->, nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::operator->, nest::Ntree< D, T, max_capacity, max_depth >::split_.
Ntree* nest::Ntree< D, T, max_capacity, max_depth >::parent_
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::iterator::iterator.
int nest::Ntree< D, T, max_capacity, max_depth >::my_subquad_
This Ntree's subquad number within parent.
int nest::Ntree< D, T, max_capacity, max_depth >::my_depth_
This Ntree's depth in the tree.
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert.
Ntree* nest::Ntree< D, T, max_capacity, max_depth >::children_[N][N]
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::iterator::iterator, nest::Ntree< D, T, max_capacity, max_depth >::split_.
std::bitset< D > nest::Ntree< D, T, max_capacity, max_depth >::periodic_
periodic b.c.
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::masked_iterator.
friend class iterator
friend class masked_iterator
nest::Ntree< D, T, max_capacity, max_depth >::Ntree(const Position< D > &lower_left, const Position< D > &extent, std::bitset< D > periodic=0, Ntree *parent=0, int subquad=0)
Create a Ntree that covers the region defined by the two input positions.
lower_left Lower left corner of ntree. extent Size (width,height) of ntree.
nest::Ntree< D, T, max_capacity, max_depth >::~Ntree()
Delete Ntree recursively.
Ntree< D, T, max_capacity, max_depth >::iterator nest::Ntree< D, T, max_capacity, max_depth >::insert(Position< D > pos, const T &node)
Traverse quadtree structure from current ntree.
Inserts node in correct leaf in quadtree. iterator pointing to inserted node.
References nest::Ntree< D, T, max_capacity, max_depth >::children_, nest::Ntree< D, T, max_capacity, max_depth >::extent_, nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::leaf_, nest::Ntree< D, T, max_capacity, max_depth >::lower_left_, nest::Ntree< D, T, max_capacity, max_depth >::my_depth_, nest::Ntree< D, T, max_capacity, max_depth >::nodes_, nest::Ntree< D, T, max_capacity, max_depth >::periodic_, nest::Ntree< D, T, max_capacity, max_depth >::split_, nest::Ntree< D, T, max_capacity, max_depth >::subquad_.
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::split_.
iterator nest::Ntree< D, T, max_capacity, max_depth >::insert(const value_type &val)
std::multimap like insert method
iterator nest::Ntree< D, T, max_capacity, max_depth >::insert(iterator, const value_type &val)
STL container compatible insert method (the first argument is ignored)
std::vector< std::pair< Position< D >, T > > nest::Ntree< D, T, max_capacity, max_depth >::get_nodes()
member nodes in ntree and their position.
References nest::Ntree< D, T, max_capacity, max_depth >::append_nodes_.
std::vector< std::pair< Position< D >, T > > nest::Ntree< D, T, max_capacity, max_depth >::get_nodes(const Mask< D > &mask, const Position< D > &anchor)
Applies a Mask to this ntree.
mask mask to apply. anchor position to center mask in. member nodes in ntree inside mask.
References nest::Ntree< D, T, max_capacity, max_depth >::append_nodes_.
iterator nest::Ntree< D, T, max_capacity, max_depth >::begin()
This function returns a node iterator which will traverse the subtree below this Ntree.
iterator for nodes in quadtree.
iterator nest::Ntree< D, T, max_capacity, max_depth >::end()
Referenced by nest::FreeLayer< D >::insert_global_positions_ntree_, nest::GridLayer< D >::insert_global_positions_ntree_.
masked_iterator nest::Ntree< D, T, max_capacity, max_depth >::masked_begin(const Mask< D > &mask, const Position< D > &anchor)
This function returns a masked node iterator which will traverse the subtree below this Ntree, skipping nodes outside the mask.
iterator for nodes in quadtree.
masked_iterator nest::Ntree< D, T, max_capacity, max_depth >::masked_end()
bool nest::Ntree< D, T, max_capacity, max_depth >::is_leaf() const
true if ntree is a leaf.
References nest::Ntree< D, T, max_capacity, max_depth >::leaf_.
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::iterator::iterator.
void nest::Ntree< D, T, max_capacity, max_depth >::split_()
Change a leaf ntree to a regular ntree with four children regions.
References nest::Ntree< D, T, max_capacity, max_depth >::children_, nest::Ntree< D, T, max_capacity, max_depth >::extent_, nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::leaf_, nest::Ntree< D, T, max_capacity, max_depth >::lower_left_, nest::Ntree< D, T, max_capacity, max_depth >::N, nest::Ntree< D, T, max_capacity, max_depth >::nodes_, nest::Ntree< D, T, max_capacity, max_depth >::subquad_.
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert.
void nest::Ntree< D, T, max_capacity, max_depth >::append_nodes_(std::vector< value_type > &)
Append this ntree's nodes to the vector.
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::get_nodes.
void nest::Ntree< D, T, max_capacity, max_depth >::append_nodes_(std::vector< value_type > &, const Mask< D > &, const Position< D > &)
Append this ntree's nodes inside the mask to the vector.
int nest::Ntree< D, T, max_capacity, max_depth >::subquad_(const Position< D > &)
the subquad number for this position
References nest::Ntree< D, T, max_capacity, max_depth >::extent_, nest::Ntree< D, T, max_capacity, max_depth >::lower_left_.
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::insert, nest::Ntree< D, T, max_capacity, max_depth >::split_.