nest::NestModule
using nest::NestModule::ParameterFactory = GenericFactory< Parameter >
using nest::NestModule::ParameterCreatorFunction = GenericFactory< Parameter >::CreatorFunction
using nest::NestModule::MaskFactory = GenericFactory< AbstractMask >
using nest::NestModule::MaskCreatorFunction = GenericFactory< AbstractMask >::CreatorFunction
SLIType nest::NestModule::ConnectionType
Referenced by init, ~NestModule.
SLIType nest::NestModule::MaskType
Referenced by init.
SLIType nest::NestModule::NodeCollectionType
Referenced by init, ~NestModule.
SLIType nest::NestModule::NodeCollectionIteratorType
Referenced by init, ~NestModule.
SLIType nest::NestModule::ParameterType
Referenced by init, ~NestModule.
nest::NestModule::GetStatus_gFunction nest::NestModule::getstatus_gfunction
Referenced by init.
nest::NestModule::GetStatus_iFunction nest::NestModule::getstatus_ifunction
Referenced by init.
nest::NestModule::GetStatus_CFunction nest::NestModule::getstatus_Cfunction
Referenced by init.
nest::NestModule::GetStatus_aFunction nest::NestModule::getstatus_afunction
Referenced by init.
nest::NestModule::GetMetadata_gFunction nest::NestModule::getmetadata_gfunction
Referenced by init.
nest::NestModule::GetKernelStatus_Function nest::NestModule::getkernelstatus_function
Referenced by init.
nest::NestModule::SetStatus_idFunction nest::NestModule::setstatus_idfunction
Referenced by init.
nest::NestModule::SetStatus_CDFunction nest::NestModule::setstatus_CDfunction
Referenced by init.
nest::NestModule::SetKernelStatus_DFunction nest::NestModule::setkernelstatus_Dfunction
Referenced by init.
nest::NestModule::Cva_CFunction nest::NestModule::cva_cfunction
Referenced by init.
nest::NestModule::SetStatus_aaFunction nest::NestModule::setstatus_aafunction
Referenced by init.
nest::NestModule::SetDefaults_l_DFunction nest::NestModule::setdefaults_l_Dfunction
Referenced by init.
nest::NestModule::GetDefaults_lFunction nest::NestModule::getdefaults_lfunction
Referenced by init.
nest::NestModule::CopyModel_l_l_DFunction nest::NestModule::copymodel_l_l_Dfunction
Referenced by init.
nest::NestModule::GetConnections_DFunction nest::NestModule::getconnections_Dfunction
Referenced by init.
nest::NestModule::SimulateFunction nest::NestModule::simulatefunction
Referenced by init.
nest::NestModule::PrepareFunction nest::NestModule::preparefunction
Referenced by init.
nest::NestModule::RunFunction nest::NestModule::runfunction
Referenced by init.
nest::NestModule::CleanupFunction nest::NestModule::cleanupfunction
Referenced by init.
nest::NestModule::Create_l_iFunction nest::NestModule::create_l_ifunction
Referenced by init.
nest::NestModule::GetNodes_D_b nest::NestModule::getnodes_D_bfunction
Referenced by init.
nest::NestModule::Disconnect_g_g_D_DFunction nest::NestModule::disconnect_g_g_D_Dfunction
Referenced by init.
nest::NestModule::Disconnect_aFunction nest::NestModule::disconnect_afunction
Referenced by init.
nest::NestModule::Connect_g_g_D_DFunction nest::NestModule::connect_g_g_D_Dfunction
Referenced by init.
nest::NestModule::Connect_g_g_D_aFunction nest::NestModule::connect_g_g_D_afunction
Referenced by init.
nest::NestModule::ResetKernelFunction nest::NestModule::resetkernelfunction
Referenced by init.
nest::NestModule::MemoryInfoFunction nest::NestModule::memoryinfofunction
Referenced by init.
nest::NestModule::PrintNodesFunction nest::NestModule::printnodesfunction
Referenced by init.
nest::NestModule::PrintNodesToStreamFunction nest::NestModule::printnodestostreamfunction
Referenced by init.
nest::NestModule::RankFunction nest::NestModule::rankfunction
Referenced by init.
nest::NestModule::NumProcessesFunction nest::NestModule::numprocessesfunction
Referenced by init.
nest::NestModule::SetFakeNumProcesses_iFunction nest::NestModule::setfakenumprocesses_ifunction
Referenced by init.
nest::NestModule::SyncProcessesFunction nest::NestModule::syncprocessesfunction
Referenced by init.
nest::NestModule::TimeCommunication_i_i_bFunction nest::NestModule::timecommunication_i_i_bfunction
Referenced by init.
nest::NestModule::TimeCommunicationv_i_iFunction nest::NestModule::timecommunicationv_i_ifunction
Referenced by init.
nest::NestModule::TimeCommunicationAlltoall_i_iFunction nest::NestModule::timecommunicationalltoall_i_ifunction
Referenced by init.
nest::NestModule::TimeCommunicationAlltoallv_i_iFunction nest::NestModule::timecommunicationalltoallv_i_ifunction
Referenced by init.
nest::NestModule::ProcessorNameFunction nest::NestModule::processornamefunction
Referenced by init.
nest::NestModule::Cvdict_CFunction nest::NestModule::cvdict_Cfunction
Referenced by init.
nest::NestModule::Cvnodecollection_i_iFunction nest::NestModule::cvnodecollection_i_ifunction
Referenced by init.
nest::NestModule::Cvnodecollection_iaFunction nest::NestModule::cvnodecollection_iafunction
Referenced by init.
nest::NestModule::Cvnodecollection_ivFunction nest::NestModule::cvnodecollection_ivfunction
Referenced by init.
nest::NestModule::Cva_gFunction nest::NestModule::cva_gfunction
Referenced by init.
nest::NestModule::Size_gFunction nest::NestModule::size_gfunction
Referenced by init.
nest::NestModule::ValidQ_gFunction nest::NestModule::validq_gfunction
Referenced by init.
nest::NestModule::Join_g_gFunction nest::NestModule::join_g_gfunction
Referenced by init.
nest::NestModule::MemberQ_g_iFunction nest::NestModule::memberq_g_ifunction
Referenced by init.
nest::NestModule::Find_g_iFunction nest::NestModule::find_g_ifunction
Referenced by init.
nest::NestModule::eq_gFunction nest::NestModule::eq_gfunction
Referenced by init.
nest::NestModule::BeginIterator_gFunction nest::NestModule::beginiterator_gfunction
Referenced by init.
nest::NestModule::EndIterator_gFunction nest::NestModule::enditerator_gfunction
Referenced by init.
nest::NestModule::GetNodeID_qFunction nest::NestModule::getnodeid_qfunction
Referenced by init.
nest::NestModule::GetNodeIDModelID_qFunction nest::NestModule::getnodeidmodelid_qfunction
Referenced by init.
nest::NestModule::Next_qFunction nest::NestModule::next_qfunction
Referenced by init.
nest::NestModule::Eq_q_qFunction nest::NestModule::eq_q_qfunction
Referenced by init.
nest::NestModule::Lt_q_qFunction nest::NestModule::lt_q_qfunction
Referenced by init.
nest::NestModule::Get_g_iFunction nest::NestModule::get_g_ifunction
Referenced by init.
nest::NestModule::Take_g_aFunction nest::NestModule::take_g_afunction
Referenced by init.
nest::NestModule::EnableStructuralPlasticity_Function nest::NestModule::enablestructuralplasticity_function
Referenced by init.
nest::NestModule::DisableStructuralPlasticity_Function nest::NestModule::disablestructuralplasticity_function
Referenced by init.
nest::NestModule::SetStdpEps_dFunction nest::NestModule::setstdpeps_dfunction
Referenced by init.
nest::NestModule::Mul_P_PFunction nest::NestModule::mul_P_Pfunction
Referenced by init.
nest::NestModule::Div_P_PFunction nest::NestModule::div_P_Pfunction
Referenced by init.
nest::NestModule::Add_P_PFunction nest::NestModule::add_P_Pfunction
Referenced by init.
nest::NestModule::Sub_P_PFunction nest::NestModule::sub_P_Pfunction
Referenced by init.
nest::NestModule::Compare_P_P_DFunction nest::NestModule::compare_P_P_Dfunction
Referenced by init.
nest::NestModule::Conditional_P_P_PFunction nest::NestModule::conditional_P_P_Pfunction
Referenced by init.
nest::NestModule::Min_P_dFunction nest::NestModule::min_P_dfunction
Referenced by init.
nest::NestModule::Max_P_dFunction nest::NestModule::max_P_dfunction
Referenced by init.
nest::NestModule::Redraw_P_d_dFunction nest::NestModule::redraw_P_d_dfunction
Referenced by init.
nest::NestModule::Exp_PFunction nest::NestModule::exp_Pfunction
Referenced by init.
nest::NestModule::Sin_PFunction nest::NestModule::sin_Pfunction
Referenced by init.
nest::NestModule::Cos_PFunction nest::NestModule::cos_Pfunction
Referenced by init.
nest::NestModule::Pow_P_dFunction nest::NestModule::pow_P_dfunction
Referenced by init.
nest::NestModule::Dimension2d_P_PFunction nest::NestModule::dimension2d_P_Pfunction
Referenced by init.
nest::NestModule::Dimension3d_P_P_PFunction nest::NestModule::dimension3d_P_P_Pfunction
Referenced by init.
nest::NestModule::CreateParameter_DFunction nest::NestModule::createparameter_Dfunction
Referenced by init.
nest::NestModule::GetValue_PFunction nest::NestModule::getvalue_Pfunction
Referenced by init.
nest::NestModule::IsSpatial_PFunction nest::NestModule::isspatial_Pfunction
Referenced by init.
nest::NestModule::Apply_P_DFunction nest::NestModule::apply_P_Dfunction
Referenced by init.
nest::NestModule::Apply_P_gFunction nest::NestModule::apply_P_gfunction
Referenced by init.
nest::NestModule::CreateLayer_D_DFunction nest::NestModule::createlayer_D_Dfunction
Referenced by init.
nest::NestModule::GetPosition_gFunction nest::NestModule::getposition_gfunction
Referenced by init.
nest::NestModule::Displacement_g_gFunction nest::NestModule::displacement_g_gfunction
Referenced by init.
nest::NestModule::Displacement_a_gFunction nest::NestModule::displacement_a_gfunction
Referenced by init.
nest::NestModule::Distance_g_gFunction nest::NestModule::distance_g_gfunction
Referenced by init.
nest::NestModule::Distance_a_gFunction nest::NestModule::distance_a_gfunction
Referenced by init.
nest::NestModule::Distance_aFunction nest::NestModule::distance_afunction
Referenced by init.
nest::NestModule::ConnectLayers_g_g_DFunction nest::NestModule::connectlayers_g_g_Dfunction
Referenced by init.
nest::NestModule::CreateMask_DFunction nest::NestModule::createmask_Dfunction
Referenced by init.
nest::NestModule::GetLayerStatus_gFunction nest::NestModule::getlayerstatus_gfunction
Referenced by init.
nest::NestModule::Inside_a_MFunction nest::NestModule::inside_a_Mfunction
Referenced by init.
nest::NestModule::And_M_MFunction nest::NestModule::and_M_Mfunction
Referenced by init.
nest::NestModule::Or_M_MFunction nest::NestModule::or_M_Mfunction
Referenced by init.
nest::NestModule::Sub_M_MFunction nest::NestModule::sub_M_Mfunction
Referenced by init.
nest::NestModule::DumpLayerNodes_os_gFunction nest::NestModule::dumplayernodes_os_gfunction
Referenced by init.
nest::NestModule::DumpLayerConnections_os_g_g_lFunction nest::NestModule::dumplayerconnections_os_g_g_lfunction
Referenced by init.
nest::NestModule::Cvdict_MFunction nest::NestModule::cvdict_Mfunction
Referenced by init.
nest::NestModule::SelectNodesByMask_g_a_MFunction nest::NestModule::selectnodesbymask_g_a_Mfunction
Referenced by init.
nest::NestModule::NestModule()
nest::NestModule::~NestModule() override
References ConnectionType, NodeCollectionIteratorType, NodeCollectionType, ParameterType.
void nest::NestModule::init(SLIInterpreter *) override
References add_P_Pfunction, and_M_Mfunction, apply_P_Dfunction, apply_P_gfunction, beginiterator_gfunction, cleanupfunction, compare_P_P_Dfunction, conditional_P_P_Pfunction, connect_g_g_D_afunction, connect_g_g_D_Dfunction, nest::KernelManager::connection_manager, ConnectionType, connectlayers_g_g_Dfunction, copymodel_l_l_Dfunction, cos_Pfunction, nest::create_doughnut, create_l_ifunction, createlayer_D_Dfunction, createmask_Dfunction, createparameter_Dfunction, cva_cfunction, cva_gfunction, cvdict_Cfunction, cvdict_Mfunction, cvnodecollection_i_ifunction, cvnodecollection_iafunction, cvnodecollection_ivfunction, dimension2d_P_Pfunction, dimension3d_P_P_Pfunction, disablestructuralplasticity_function, disconnect_afunction, disconnect_g_g_D_Dfunction, displacement_a_gfunction, displacement_g_gfunction, distance_a_gfunction, distance_afunction, distance_g_gfunction, div_P_Pfunction, dumplayerconnections_os_g_g_lfunction, dumplayernodes_os_gfunction, enablestructuralplasticity_function, enditerator_gfunction, eq_gfunction, eq_q_qfunction, exp_Pfunction, find_g_ifunction, get_g_ifunction, getconnections_Dfunction, getdefaults_lfunction, getkernelstatus_function, getlayerstatus_gfunction, getmetadata_gfunction, getnodeid_qfunction, getnodeidmodelid_qfunction, getnodes_D_bfunction, getposition_gfunction, getstatus_afunction, getstatus_Cfunction, getstatus_gfunction, getstatus_ifunction, getvalue_Pfunction, inside_a_Mfunction, isspatial_Pfunction, join_g_gfunction, nest::kernel, lt_q_qfunction, MaskType, max_P_dfunction, memberq_g_ifunction, memoryinfofunction, min_P_dfunction, mul_P_Pfunction, next_qfunction, NodeCollectionIteratorType, NodeCollectionType, numprocessesfunction, or_M_Mfunction, ParameterType, pow_P_dfunction, preparefunction, printnodesfunction, printnodestostreamfunction, processornamefunction, rankfunction, redraw_P_d_dfunction, nest::ConnectionManager::register_conn_builder, nest::SPManager::register_growth_curve, register_mask, resetkernelfunction, runfunction, selectnodesbymask_g_a_Mfunction, setdefaults_l_Dfunction, setfakenumprocesses_ifunction, setkernelstatus_Dfunction, setstatus_aafunction, setstatus_CDfunction, setstatus_idfunction, setstdpeps_dfunction, simulatefunction, sin_Pfunction, size_gfunction, nest::KernelManager::sp_manager, sub_M_Mfunction, sub_P_Pfunction, syncprocessesfunction, take_g_afunction, timecommunication_i_i_bfunction, timecommunicationalltoall_i_ifunction, timecommunicationalltoallv_i_ifunction, timecommunicationv_i_ifunction, validq_gfunction.
const std::string nest::NestModule::commandstring() const override
const std::string nest::NestModule::name() const override
Referenced by create_mask, create_parameter, nest::NestModule::SetDefaults_l_DFunction::execute, register_mask, register_parameter.
ParameterDatum nest::NestModule::create_parameter(const Token &)
References nest::names::n.
Referenced by nest::ConnectionCreator::ConnectionCreator, nest::create_parameter, nest::ConnectionCreator::extract_params_.
Parameter * nest::NestModule::create_parameter(const Name &name, const DictionaryDatum &d)
References nest::GenericFactory< BaseT >::create, nest::names::d, name, parameter_factory_.
bool nest::NestModule::register_parameter(const Name &name)
References name, parameter_factory_, nest::GenericFactory< BaseT >::register_subtype.
bool nest::NestModule::register_mask()
Register an AbstractMask subclass as a new mask type.
The name will be found using the function T::get_name() true if the new type was successfully registered, or false if a mask type with the same name already exists.
References mask_factory_, nest::GenericFactory< BaseT >::register_subtype.
Referenced by init.
bool nest::NestModule::register_mask(const Name &name, MaskCreatorFunction creator)
Register a new mask type with the given name, with a supplied function to create mask objects of this type.
name name of the new mask type. creator function creating objects of this type. The function will be called with the parameter dictionary as argument and should return a pointer to a new Mask object. true if the new type was successfully registered, or false if a mask type with the same name already exists.
References mask_factory_, name, nest::GenericFactory< BaseT >::register_subtype.
MaskDatum nest::NestModule::create_mask(const Token &t)
Return a Mask object.
t Either an existing MaskDatum, or a Dictionary containing mask parameters. The dictionary should contain a key with the name of the mask type, with a dictionary of parameters as value, and optionally an anchor. Either the MaskDatum given as argument, or a new mask.
References nest::names::anchor, numerics::e, nest::names::mask, nest::GridMask< D >::set_anchor.
Referenced by nest::ConnectionCreator::ConnectionCreator, nest::create_mask.
AbstractMask * nest::NestModule::create_mask(const Name &name, const DictionaryDatum &d)
Create a new Mask object using the mask factory.
name Mask type to create. d Dictionary with parameters specific for this mask type. dynamically allocated new Mask object.
References nest::GenericFactory< BaseT >::create, nest::names::d, mask_factory_, name.
GenericFactory< Parameter > & nest::NestModule::parameter_factory_()
Referenced by create_parameter, register_parameter.
GenericFactory< AbstractMask > & nest::NestModule::mask_factory_()
Referenced by create_mask, register_mask.