nest::VPManager
const bool nest::VPManager::force_singlethreading_
index nest::VPManager::n_threads_
Number of threads per process.
Referenced by get_num_assigned_ranks_per_thread.
nest::VPManager::VPManager()
nest::VPManager::~VPManager() override
void nest::VPManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References set_num_threads.
void nest::VPManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
void nest::VPManager::set_status(const DictionaryDatum &) override
References nest::KernelManager::change_number_of_threads, nest::MPIManager::get_num_processes, nest::kernel, nest::names::local_num_threads, LOG, nest::M_WARNING, nest::KernelManager::mpi_manager, nest::names::total_num_virtual_procs.
void nest::VPManager::get_status(DictionaryDatum &) override
References nest::names::local_num_threads, nest::names::total_num_virtual_procs.
nest::thread nest::VPManager::get_thread_id() const
Gets ID of local thread.
Returns thread ID if OpenMP is installed and zero otherwise.
Referenced by nest::NodeManager::add_devices_, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_, nest::RecordingBackendMPI::cleanup, nest::StimulationBackendMPI::cleanup, nest::RecordingBackendSIONlib::close_files_, nest::ConnectionManager::connect, nest::OneToOneBuilder::connect_, nest::AllToAllBuilder::connect_, nest::FixedInDegreeBuilder::connect_, nest::FixedOutDegreeBuilder::connect_, nest::FixedTotalNumberBuilder::connect_, nest::BernoulliBuilder::connect_, nest::SymmetricBernoulliBuilder::connect_, nest::SPBuilder::connect_, nest::ConnectionManager::connect_arrays, nest::ModelManager::copy_node_model_, nest::SPManager::delete_synapse, nest::NodeManager::destruct_nodes_, nest::SPManager::disconnect, nest::OneToOneBuilder::disconnect_, nest::AllToAllBuilder::disconnect_, nest::NodeManager::finalize_nodes, nest::ConnectionManager::get_connections, nest::ConnectionManager::get_delay_checker, nest::NodeManager::get_nodes, get_vp, nest::SourceTable::initialize, nest::TargetTable::initialize, nest::ConnectionManager::initialize, nest::EventDeliveryManager::initialize, nest::ModelManager::initialize, nest::RecordingBackendSIONlib::open_files_, nest::ConnectionCreator::pairwise_bernoulli_on_source_, nest::ConnectionCreator::pairwise_bernoulli_on_target_, nest::NodeManager::post_run_cleanup, nest::RecordingBackendSIONlib::post_step_hook, nest::RecordingBackendMPI::prepare, nest::SimulationManager::prepare, nest::StimulationBackendMPI::prepare, nest::NodeManager::prepare_nodes, nest::ModelManager::register_node_model_, nest::RandomManager::reset_rngs_, nest::TargetTableDevices::resize_to_number_of_neurons, nest::TargetTableDevices::resize_to_number_of_synapse_types, nest::EventDeliveryManager::send_secondary, nest::STDPDopaCommonProperties::set_status, nest::ModelManager::set_synapse_defaults_, nest::OneToOneBuilder::sp_connect_, nest::AllToAllBuilder::sp_connect_, nest::OneToOneBuilder::sp_disconnect_, nest::AllToAllBuilder::sp_disconnect_, nest::ConnectionManager::trigger_update_weight, nest::SimulationManager::update_, nest::StimulationBackendMPI::update_device, nest::NormalParameter::value, nest::LognormalParameter::value, nest::RecordingBackendMPI::write.
void nest::VPManager::set_num_threads(const thread n_threads)
Set the number of threads by setting the internal variable n_threads_, the corresponding value in the Communicator, and the OpenMP number of threads.
References nest::kernel.
Referenced by initialize.
nest::thread nest::VPManager::get_num_threads() const
Get number of threads.
This function returns the total number of threads per process.
Referenced by nest::NodeManager::add_node, nest::ConnectionManager::calibrate, nest::SimulationManager::call_update_, nest::RandomManager::check_rng_synchrony, nest::ConnectionManager::compute_target_data_buffer_size, nest::EventDeliveryManager::configure_spike_register, nest::ConnBuilder::connect, nest::ConnectionManager::connect_arrays, nest::ConnBuilder::disconnect, nest::SPManager::disconnect, nest::NodeManager::ensure_valid_thread_local_ids, nest::SourceTable::find_maximal_position, nest::NodeManager::get_nodes, get_num_virtual_processes, nest::ConnectionManager::get_sources, nest::SPManager::get_synaptic_elements, nest::ConnectionManager::get_targets, nest::NodeManager::get_thread_siblings, nest::SourceTable::initialize, nest::TargetTable::initialize, nest::TargetTableDevices::initialize, nest::ConnectionManager::initialize, nest::EventDeliveryManager::initialize, nest::RecordingBackendMPI::initialize, nest::StimulationBackendMPI::initialize, nest::ConnectionCreator::pairwise_bernoulli_on_source_, nest::ConnectionCreator::pairwise_bernoulli_on_target_, nest::StimulationBackendMPI::prepare, nest::NodeManager::prepare_nodes, nest::ConnectionManager::resize_connections, nest::NodeManager::set_status, nest::ModelManager::set_synapse_defaults_, nest::ConnBuilder::set_synapse_params, nest::SPBuilder::sp_connect, nest::SimulationManager::update_.
bool nest::VPManager::is_node_id_vp_local(const index node_id) const
Returns true if the given global node exists on this vp.
References get_num_virtual_processes, get_vp.
index nest::VPManager::node_id_to_lid(const index node_id) const
Returns thread local index of a given global node.
References get_num_virtual_processes.
Referenced by nest::TargetTableDevices::add_connection_to_device, nest::TargetTableDevices::get_connections_to_devices_, nest::TargetTableDevices::get_synapse_status_to_device, nest::EventDeliveryManager::send_off_grid_remote, nest::EventDeliveryManager::send_remote, nest::EventDeliveryManager::send_secondary, nest::TargetTableDevices::send_to_device, nest::TargetTableDevices::set_synapse_status_to_device.
index nest::VPManager::lid_to_node_id(const index lid) const
Returns the node ID of a given local index.
References get_num_virtual_processes, get_vp.
Referenced by nest::TargetTableDevices::get_connections_to_device_for_lid_.
thread nest::VPManager::get_vp() const
Returns virtual process index.
References nest::MPIManager::get_num_processes, nest::MPIManager::get_rank, get_thread_id, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by is_node_id_vp_local, lid_to_node_id, nest::RandomManager::reset_rngs_.
thread nest::VPManager::node_id_to_vp(const index node_id) const
Return a thread number for a given global node id.
Each node has a default thread on which it will run. The thread is defined by the relation: t = (node_id div P) mod T, where P is the number of simulation processes and T the number of threads. This may be used by Network::add_node() if the user has not specified anything.
References get_num_virtual_processes.
Referenced by nest::NodeManager::add_neurons_, nest::FixedTotalNumberBuilder::connect_, nest::ConnectionManager::connection_required, nest::NodeManager::get_node_or_proxy, nest::NodeManager::is_local_node_id, nest::NodeCollectionPrimitive::local_begin, nest::NodeCollectionComposite::local_begin, nest::updateValueParam.
thread nest::VPManager::vp_to_thread(const thread vp) const
Convert a given VP ID to the corresponding thread ID.
References nest::MPIManager::get_num_processes, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by nest::ConnectionManager::connection_required, nest::NodeManager::get_mpi_local_node_or_device_head, nest::NodeManager::get_node_or_proxy, nest::updateValueParam, nest::NormalParameter::value, nest::LognormalParameter::value.
thread nest::VPManager::thread_to_vp(const thread tid) const
Convert a given thread ID to the corresponding VP ID.
References nest::MPIManager::get_num_processes, nest::MPIManager::get_rank, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by nest::NodeManager::add_neurons_, nest::RecordingBackendSIONlib::close_files_, nest::FixedTotalNumberBuilder::connect_, nest::NodeCollectionPrimitive::local_begin, nest::NodeCollectionComposite::local_begin, nest::RecordingBackendSIONlib::open_files_, nest::RecordingBackendSIONlib::post_step_hook.
bool nest::VPManager::is_local_vp(const thread tid) const
Return true, if the given VP is on the local machine.
References nest::MPIManager::get_process_id_of_vp, nest::MPIManager::get_rank, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by nest::ConnectionManager::connection_required, nest::NodeManager::is_local_node, nest::NodeManager::is_local_node_id.
thread nest::VPManager::get_num_virtual_processes() const
Returns the number of virtual processes.
References nest::MPIManager::get_num_processes, get_num_threads, nest::kernel, nest::KernelManager::mpi_manager.
Referenced by nest::SparseNodeArray::add_local_node, nest::NodeManager::add_neurons_, nest::RecordingBackendASCII::compute_vp_node_id_string_, nest::FixedTotalNumberBuilder::connect_, is_node_id_vp_local, lid_to_node_id, nest::NodeCollectionPrimitive::local_begin, nest::NodeCollectionComposite::local_begin, node_id_to_lid, node_id_to_vp.
thread nest::VPManager::get_num_assigned_ranks_per_thread() const
Returns the number of processes that are taken care of by a single thread while processing MPI buffers in a multithreaded environment.
References nest::kernel, n_threads_.
Referenced by get_assigned_ranks, get_start_rank_per_thread, nest::EventDeliveryManager::send_off_grid_remote, nest::EventDeliveryManager::send_remote.
thread nest::VPManager::get_start_rank_per_thread(const thread tid) const
References get_num_assigned_ranks_per_thread.
Referenced by get_assigned_ranks.
thread nest::VPManager::get_end_rank_per_thread(const thread rank_start, const thread num_assigned_ranks_per_thread) const
References nest::kernel.
Referenced by get_assigned_ranks.
AssignedRanks nest::VPManager::get_assigned_ranks(const thread tid)
Returns assigned ranks per thread to fill MPI buffers.
Thread tid is responsible for all ranks in [assigned_ranks.begin, assigned_ranks.end), which are in total assigned_ranks.size and at most assigned_ranks.max_size
References nest::AssignedRanks::begin, nest::AssignedRanks::end, get_end_rank_per_thread, get_num_assigned_ranks_per_thread, get_start_rank_per_thread, nest::AssignedRanks::max_size, nest::AssignedRanks::size.
Referenced by nest::EventDeliveryManager::gather_spike_data_, nest::EventDeliveryManager::gather_target_data.
void nest::VPManager::assert_single_threaded()
Fails if NEST is in thread-parallel section.
Referenced by nest::DataSecondaryEvent< DataType, Subclass >::add_syn_id, nest::PerThreadBoolIndicator::initialize, nest::ConnectionManager::resize_connections, nest::DataSecondaryEvent< DataType, Subclass >::set_coeff_length.