nest::Position
friend class Position
std::ostream& operator<<(std::ostream &os, const Position< D, T > &pos)
Output the Position to an ostream.
std::array< T, D > nest::Position< D, T >::x_
nest::Position< D, T >::Position()
Default constructor, initializing all coordinates to zero.
nest::Position< D, T >::Position(const T &, const T &)
2D Constructor.
References nest::names::x, nest::names::y.
nest::Position< D, T >::Position(const T &, const T &, const T &)
3D Constructor.
References nest::names::x, nest::names::y, nest::names::z.
nest::Position< D, T >::Position(const T *const y)
Constructor initializing a Position from an array.
References nest::names::y.
nest::Position< D, T >::Position(const std::vector< T > &y)
Constructor initializing a Position from a std::vector.
References nest::names::y.
nest::Position< D, T >::Position(const Position &other)
Copy constructor.
nest::Position< D, T >::Position(const Position< D, U > &other)
nest::Position< D, T >::Position(Position &&other)
Move constructor.
References nest::names::other.
Position& nest::Position< D, T >::operator=(const Position &other)=default
Assignment constructor.
Position< D, T > & nest::Position< D, T >::operator=(const std::vector< T > &y)
References nest::names::y.
Position& nest::Position< D, T >::operator=(Position &&other)=default
Move assignment constructor.
T & nest::Position< D, T >::operator[](int i)
an element (coordinate) of the Position
const T & nest::Position< D, T >::operator[](int i) const
an element (coordinate) of the Position
Token nest::Position< D, T >::getToken() const
Moves Position variables into an array.
array of positions stored as a token object.
const std::vector< T > nest::Position< D, T >::get_vector() const
Referenced by nest::ConnectionCreator::connect_to_target_, nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_.
void nest::Position< D, T >::get_vector(std::vector< T > &vector) const
Position nest::Position< D, T >::operator+(const Position< D, OT > &other) const
Elementwise addition.
elementwise sum of coordinates.
Position nest::Position< D, T >::operator-(const Position< D, OT > &other) const
Elementwise subtraction.
elementwise difference of coordinates.
Position< D, T > nest::Position< D, T >::operator-() const
Unary minus.
opposite vector.
References nest::names::p.
Position nest::Position< D, T >::operator*(const Position< D, OT > &other) const
Elementwise multiplication.
elementwise product of coordinates.
Position nest::Position< D, T >::operator/(const Position< D, OT > &other) const
Elementwise division.
elementwise quotient of coordinates.
Position< D, T > nest::Position< D, T >::operator+(const T &) const
Elementwise addition with scalar.
position vector with scalar added to all coordinates
References nest::names::a, nest::names::p.
Position< D, T > nest::Position< D, T >::operator-(const T &) const
Elementwise subtraction with scalar.
position vector with scalar subtracted from all coordinates
References nest::names::a, nest::names::p.
Position< D, T > nest::Position< D, T >::operator*(const T &) const
Multiplication with scalar.
position vector multiplied with the scalar.
References nest::names::a, nest::names::p.
Position< D, T > nest::Position< D, T >::operator/(const T &) const
Division with scalar.
position vector divided by the scalar.
References nest::names::a, nest::names::p.
Position& nest::Position< D, T >::operator+=(const Position< D, OT > &)
In-place elementwise addition.
the Position itself after adding the other Position elementwise.
Position& nest::Position< D, T >::operator-=(const Position< D, OT > &)
In-place elementwise subtraction.
the Position itself after subtracting the other Position elementwise.
Position& nest::Position< D, T >::operator*=(const Position< D, OT > &)
In-place elementwise multiplication.
the Position itself after multiplying with the other Position elementwise.
Position& nest::Position< D, T >::operator/=(const Position< D, OT > &)
In-place elementwise division.
the Position itself after dividing by the other Position elementwise.
Position< D, T > & nest::Position< D, T >::operator+=(const T &)
In-place elementwise addition with scalar.
the Position itself after adding the scalar to all coordinates.
References nest::names::a.
Position< D, T > & nest::Position< D, T >::operator-=(const T &)
In-place elementwise subtraction with scalar.
the Position itself after subtracting the scalar from all coordinates.
References nest::names::a.
Position< D, T > & nest::Position< D, T >::operator*=(const T &)
In-place multiplication by scalar.
the Position itself after multiplying with the scalar.
References nest::names::a.
Position< D, T > & nest::Position< D, T >::operator/=(const T &)
In-place elementwise division.
the Position itself after dividing by the scalar.
References nest::names::a.
bool nest::Position< D, T >::operator==(const Position &y) const
true if all coordinates are equal
References nest::names::y.
bool nest::Position< D, T >::operator!=(const Position &y) const
true if not all coordinates are equal
References nest::names::y.
bool nest::Position< D, T >::operator<(const Position &y) const
true if all coordinates are less
References nest::names::y.
bool nest::Position< D, T >::operator>(const Position &y) const
true if all coordinates are greater
References nest::names::y.
bool nest::Position< D, T >::operator<=(const Position &y) const
true if all coordinates are less or equal
References nest::names::y.
bool nest::Position< D, T >::operator>=(const Position &y) const
true if all coordinates are greater or equal
References nest::names::y.
T nest::Position< D, T >::length() const
Length of Position vector.
Euclidian norm of the vector.
nest::Position< D, T >::operator std::string() const
string representation of Position
void nest::Position< D, T >::print(std::ostream &out, char sep=' ') const
Print position to output stream.
Format: Only as many coordinates as dimensions, separated by spaces [default], no trailing space. out output stream sep separator character
Position< D, T > nest::Position< D, T >::operator+(const Position< D, OT > &other) const
References nest::names::other, nest::names::p.
Position< D, T > nest::Position< D, T >::operator-(const Position< D, OT > &other) const
References nest::names::other, nest::names::p.
Position< D, T > nest::Position< D, T >::operator*(const Position< D, OT > &other) const
References nest::names::other, nest::names::p.
Position< D, T > nest::Position< D, T >::operator/(const Position< D, OT > &other) const
References nest::names::other, nest::names::p.
Position< D, T >& nest::Position< D, T >::operator+=(const Position< D, OT > &other)
References nest::names::other.
Position< D, T >& nest::Position< D, T >::operator-=(const Position< D, OT > &other)
References nest::names::other.
Position< D, T >& nest::Position< D, T >::operator*=(const Position< D, OT > &other)
References nest::names::other.
Position< D, T >& nest::Position< D, T >::operator/=(const Position< D, OT > &other)
References nest::names::other.