nest::iaf_psc_alpha_multisynapse
friend class DynamicRecordablesMap< iaf_psc_alpha_multisynapse >
friend class DynamicUniversalDataLogger< iaf_psc_alpha_multisynapse >
friend class DataAccessFunctor< iaf_psc_alpha_multisynapse >
Referenced by get_data_access_functor.
Parameters_ nest::iaf_psc_alpha_multisynapse::P_
Referenced by get_state_element, get_status, handles_test_event, insert_current_recordables, pre_run_hook, set_status, update.
State_ nest::iaf_psc_alpha_multisynapse::S_
Referenced by get_state_element, get_status, pre_run_hook, set_status, update.
Variables_ nest::iaf_psc_alpha_multisynapse::V_
Referenced by pre_run_hook, update.
Buffers_ nest::iaf_psc_alpha_multisynapse::B_
Referenced by handle, handles_test_event, init_buffers_, pre_run_hook, update.
DynamicRecordablesMap< iaf_psc_alpha_multisynapse > nest::iaf_psc_alpha_multisynapse::recordablesMap_
Mapping of recordables names to access functions.
Referenced by get_status, handles_test_event, iaf_psc_alpha_multisynapse, insert_current_recordables, set_status.
nest::iaf_psc_alpha_multisynapse::iaf_psc_alpha_multisynapse()
References recordablesMap_.
nest::iaf_psc_alpha_multisynapse::iaf_psc_alpha_multisynapse(const iaf_psc_alpha_multisynapse &)
References recordablesMap_.
port nest::iaf_psc_alpha_multisynapse::send_test_event(Node &, rport, synindex, bool) override
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws IllegalConnection. This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node. If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
void nest::iaf_psc_alpha_multisynapse::handle(SpikeEvent &) override
Handle incoming spike events.
Default implementation of event handlers just throws an UnexpectedEvent exception. thrd Id of the calling thread. e Event object. This handler has to be implemented if a Node should accept spike events. class SpikeEvent class UnexpectedEvent UnexpectedEvent This is the default event to throw.
References B_, nest::kernel, nest::iaf_psc_alpha_multisynapse::Buffers_::spikes_.
void nest::iaf_psc_alpha_multisynapse::handle(CurrentEvent &) override
Handler for current events.
handle(thread, SpikeEvent&) UnexpectedEvent
References nest::RingBuffer::add_value, B_, nest::iaf_psc_alpha_multisynapse::Buffers_::currents_, nest::kernel.
void nest::iaf_psc_alpha_multisynapse::handle(DataLoggingRequest &) override
Handler for universal data logging request.
handle(SpikeEvent&) UnexpectedEvent
References B_, nest::iaf_psc_alpha_multisynapse::Buffers_::logger_.
port nest::iaf_psc_alpha_multisynapse::handles_test_event(SpikeEvent &, rport) override
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event(). handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle. See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3. The semantics of all other handles_test_event() functions is identical. IllegalConnection
References nest::Node::get_name, nest::iaf_psc_alpha_multisynapse::Parameters_::has_connections_, nest::iaf_psc_alpha_multisynapse::Parameters_::n_receptors_, P_.
port nest::iaf_psc_alpha_multisynapse::handles_test_event(CurrentEvent &, rport) override
References nest::Node::get_name.
port nest::iaf_psc_alpha_multisynapse::handles_test_event(DataLoggingRequest &, rport) override
References B_, nest::Node::get_name, nest::iaf_psc_alpha_multisynapse::Buffers_::logger_, recordablesMap_.
void nest::iaf_psc_alpha_multisynapse::get_status(DictionaryDatum &) const override
Export properties of the node by setting entries in the status dictionary.
d Dictionary.
References nest::iaf_psc_alpha_multisynapse::Parameters_::get, nest::iaf_psc_alpha_multisynapse::State_::get, nest::ArchivingNode::get_status, P_, nest::names::recordables, recordablesMap_, S_.
void nest::iaf_psc_alpha_multisynapse::set_status(const DictionaryDatum &) override
Change properties of the node according to the entries in the dictionary.
d Dictionary with named parameter settings.
References get_data_access_functor, get_i_syn_name, nest::iaf_psc_alpha_multisynapse::State_::I_SYN, nest::iaf_psc_alpha_multisynapse::State_::NUM_STATE_ELEMENTS_PER_RECEPTOR, P_, recordablesMap_, S_, nest::iaf_psc_alpha_multisynapse::State_::set, nest::iaf_psc_alpha_multisynapse::Parameters_::set, nest::ArchivingNode::set_status, nest::iaf_psc_alpha_multisynapse::Parameters_::tau_syn_.
void nest::Node::handle(SpikeEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(WeightRecorderEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(RateEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DataLoggingRequest &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DataLoggingReply &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(CurrentEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(ConductanceEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DoubleDataEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(GapJunctionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(InstantaneousRateConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DiffusionConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
void nest::Node::handle(DelayedRateConnectionEvent &e)
Import sets of overloaded virtual functions.
Technical Issues / Virtual Functions: Overriding, Overloading, and Hiding
port nest::Node::handles_test_event(SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event(). handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle. See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3. The semantics of all other handles_test_event() functions is identical. IllegalConnection
port nest::Node::handles_test_event(WeightRecorderEvent &, rport receptor_type)
port nest::Node::handles_test_event(RateEvent &, rport receptor_type)
port nest::Node::handles_test_event(DataLoggingRequest &, rport receptor_type)
port nest::Node::handles_test_event(CurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(ConductanceEvent &, rport receptor_type)
port nest::Node::handles_test_event(DoubleDataEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSSpikeEvent &, rport receptor_type)
port nest::Node::handles_test_event(DSCurrentEvent &, rport receptor_type)
port nest::Node::handles_test_event(GapJunctionEvent &, rport receptor_type)
port nest::Node::handles_test_event(InstantaneousRateConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DiffusionConnectionEvent &, rport receptor_type)
port nest::Node::handles_test_event(DelayedRateConnectionEvent &, rport receptor_type)
void nest::iaf_psc_alpha_multisynapse::init_buffers_() override
Configure persistent internal data structures.
Let node configure persistent internal data structures, such as input buffers or ODE solvers, to runtime information prior to first simulation.
References B_, nest::RingBuffer::clear, nest::ArchivingNode::clear_history, nest::iaf_psc_alpha_multisynapse::Buffers_::currents_, nest::iaf_psc_alpha_multisynapse::Buffers_::logger_, nest::iaf_psc_alpha_multisynapse::Buffers_::spikes_.
void nest::iaf_psc_alpha_multisynapse::pre_run_hook() override
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
References B_, nest::iaf_psc_alpha_multisynapse::Parameters_::C_, numerics::e, IAFPropagatorAlpha::evaluate, nest::Time::get_ms, nest::Time::get_resolution, nest::Time::get_steps, nest::iaf_psc_alpha_multisynapse::Buffers_::logger_, nest::iaf_psc_alpha_multisynapse::Parameters_::n_receptors_, nest::iaf_psc_alpha_multisynapse::Variables_::P11_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P21_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P22_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P30_, nest::iaf_psc_alpha_multisynapse::Variables_::P31_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P32_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P33_, P_, nest::iaf_psc_alpha_multisynapse::Variables_::PSCInitialValues_, nest::iaf_psc_alpha_multisynapse::Parameters_::refractory_time_, nest::iaf_psc_alpha_multisynapse::Variables_::RefractoryCounts_, S_, nest::iaf_psc_alpha_multisynapse::Buffers_::spikes_, nest::iaf_psc_alpha_multisynapse::Parameters_::Tau_, nest::iaf_psc_alpha_multisynapse::Parameters_::tau_syn_, V_, nest::iaf_psc_alpha_multisynapse::State_::y1_syn_, nest::iaf_psc_alpha_multisynapse::State_::y2_syn_.
void nest::iaf_psc_alpha_multisynapse::update(Time const &, const long, const long) override
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to. Time network time at beginning of time slice. long initial step inside time slice long post-final step inside time slice
References B_, nest::iaf_psc_alpha_multisynapse::State_::current_, nest::iaf_psc_alpha_multisynapse::Buffers_::currents_, nest::KernelManager::event_delivery_manager, nest::RingBuffer::get_value, nest::iaf_psc_alpha_multisynapse::State_::I_const_, nest::iaf_psc_alpha_multisynapse::Parameters_::I_e_, nest::kernel, nest::iaf_psc_alpha_multisynapse::Buffers_::logger_, nest::iaf_psc_alpha_multisynapse::Parameters_::LowerBound_, nest::iaf_psc_alpha_multisynapse::Parameters_::n_receptors_, nest::iaf_psc_alpha_multisynapse::Variables_::P11_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P21_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P22_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P30_, nest::iaf_psc_alpha_multisynapse::Variables_::P31_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P32_syn_, nest::iaf_psc_alpha_multisynapse::Variables_::P33_, P_, nest::iaf_psc_alpha_multisynapse::Variables_::PSCInitialValues_, nest::iaf_psc_alpha_multisynapse::State_::refractory_steps_, nest::iaf_psc_alpha_multisynapse::Variables_::RefractoryCounts_, S_, nest::EventDeliveryManager::send, nest::ArchivingNode::set_spiketime, nest::iaf_psc_alpha_multisynapse::Buffers_::spikes_, nest::iaf_psc_alpha_multisynapse::Parameters_::Theta_, V_, nest::iaf_psc_alpha_multisynapse::State_::V_m_, nest::iaf_psc_alpha_multisynapse::Parameters_::V_reset_, nest::iaf_psc_alpha_multisynapse::State_::y1_syn_, nest::iaf_psc_alpha_multisynapse::State_::y2_syn_.
DataAccessFunctor< iaf_psc_alpha_multisynapse > nest::iaf_psc_alpha_multisynapse::get_data_access_functor(size_t elem)
References DataAccessFunctor< iaf_psc_alpha_multisynapse >.
Referenced by nest::DynamicRecordablesMap< HostNode >::create, insert_current_recordables, set_status.
double nest::iaf_psc_alpha_multisynapse::get_state_element(size_t elem)
References nest::iaf_psc_alpha_multisynapse::State_::current_, nest::iaf_psc_alpha_multisynapse::Parameters_::E_L_, nest::iaf_psc_alpha_multisynapse::State_::I, nest::iaf_psc_alpha_multisynapse::State_::NUMBER_OF_FIXED_STATES_ELEMENTS, P_, S_, nest::iaf_psc_alpha_multisynapse::State_::V_M, nest::iaf_psc_alpha_multisynapse::State_::V_m_, nest::iaf_psc_alpha_multisynapse::State_::y2_syn_.
Name nest::iaf_psc_alpha_multisynapse::get_i_syn_name(size_t elem)
Referenced by insert_current_recordables, set_status.
void nest::iaf_psc_alpha_multisynapse::insert_current_recordables(size_t first=0)
References get_data_access_functor, get_i_syn_name, nest::iaf_psc_alpha_multisynapse::State_::I_SYN, nest::iaf_psc_alpha_multisynapse::State_::NUM_STATE_ELEMENTS_PER_RECEPTOR, P_, recordablesMap_, nest::iaf_psc_alpha_multisynapse::Parameters_::tau_syn_.
Referenced by nest::DynamicRecordablesMap< HostNode >::create.