AggregateDatum
sli::pool ConnectionDatum::memory
Referenced by AggregateDatum< C, slt >::operator delete, AggregateDatum< C, slt >::operator new.
virtual Datum * AggregateDatum< C, slt >::clone() const
Virtual copy constructor.
Use this function to lazily copy a datum.
AggregateDatum< C, slt >::AggregateDatum()
References Datum::unset_executable.
AggregateDatum< C, slt >::AggregateDatum(const AggregateDatum< C, slt > &d)
AggregateDatum< C, slt >::AggregateDatum(const C &c)
virtual AggregateDatum< C, slt >::~AggregateDatum()
bool AggregateDatum< C, slt >::equals(const Datum *dat) const
void AggregateDatum< C, slt >::print(std::ostream &out) const
Referenced by nest::Layer< D >::dump_nodes, AggregateDatum< C, slt >::info, AggregateDatum< C, slt >::input_form, SLIInterpreter::stack_backtrace.
void AggregateDatum< C, slt >::pprint(std::ostream &out) const
void AggregateDatum< C, slt >::list(std::ostream &out, std::string prefix, int length) const
Referenced by SLIArrayModule::IMapFunction::backtrace, SLIArrayModule::IMap_ivFunction::backtrace, SLIArrayModule::IMap_dvFunction::backtrace, SLIArrayModule::IMapThreadFunction::backtrace, SLIArrayModule::IMapIndexedFunction::backtrace, IiterateFunction::backtrace, IloopFunction::backtrace, IrepeatFunction::backtrace, IforFunction::backtrace, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::IMapIndexedFunction::execute.
virtual void AggregateDatum< C, slt >::input_form(std::ostream &out) const
References AggregateDatum< C, slt >::print.
virtual void AggregateDatum< C, slt >::info(std::ostream &out) const
References AggregateDatum< C, slt >::print.
void AggregateDatum< TokenArray,&SLIInterpreter::Arraytype >::pprint(std::ostream &out) const
void AggregateDatum< TokenArray,&SLIInterpreter::Arraytype >::print(std::ostream &out) const
void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::pprint(std::ostream &out) const
void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::list(std::ostream &out, std::string prefix, int line) const
void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::print(std::ostream &out) const
void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::pprint(std::ostream &out) const
void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::list(std::ostream &out, std::string prefix, int line) const
void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::print(std::ostream &out) const
void AggregateDatum< TokenArray,&SLIInterpreter::Arraytype >::print(std::ostream &) const
void AggregateDatum< TokenArray,&SLIInterpreter::Arraytype >::pprint(std::ostream &) const
void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::print(std::ostream &) const
void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::list(std::ostream &, std::string, int) const
void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::pprint(std::ostream &) const
void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::print(std::ostream &) const
void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::pprint(std::ostream &) const
void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::list(std::ostream &, std::string, int) const
void AggregateDatum< std::string,&SLIInterpreter::Stringtype >::pprint(std::ostream &out) const
void AggregateDatum< std::string,&SLIInterpreter::Stringtype >::pprint(std::ostream &out) const
static void * AggregateDatum< C, slt >::operator new(size_t size)
References sli::pool::alloc, AggregateDatum< C, slt >::memory, sli::pool::size_of.
static void AggregateDatum< C, slt >::operator delete(void *p, size_t size)
References sli::pool::free, AggregateDatum< C, slt >::memory, sli::pool::size_of.
sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Arraytype >::memory(sizeof(ArrayDatum), 10240, 1)
sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::memory(sizeof(ProcedureDatum), 10240, 1)
sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::memory(sizeof(AggregateDatum< TokenArray, &SLIInterpreter::Litproceduretype >), 10240, 1)
sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Arraytype >::memory
sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::memory
sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::memory
sli::pool AggregateDatum< Name,&SLIInterpreter::Nametype >::memory(sizeof(NameDatum), 10240, 1)
sli::pool AggregateDatum< Name,&SLIInterpreter::Literaltype >::memory(sizeof(LiteralDatum), 10240, 1)
sli::pool AggregateDatum< Name,&SLIInterpreter::Nametype >::memory
sli::pool AggregateDatum< Name,&SLIInterpreter::Literaltype >::memory
sli::pool AggregateDatum< std::string,&SLIInterpreter::Stringtype >::memory(sizeof(AggregateDatum< std::string, &SLIInterpreter::Stringtype >), 100, 1)
sli::pool AggregateDatum< std::string,&SLIInterpreter::Stringtype >::memory
sli::pool AggregateDatum< Name,&SLIInterpreter::Symboltype >::memory(sizeof(SymbolDatum), 100, 1)
sli::pool AggregateDatum< Name,&SLIInterpreter::Symboltype >::memory