nest::K
double nest::K::n_K_
double nest::K::gbar_K_
Referenced by K.
double nest::K::e_K_
Referenced by K.
double nest::K::q10_
nest::K::K()
nest::K::K(const DictionaryDatum &channel_params)
References e_K_, gbar_K_.
nest::K::~K()
void nest::K::pre_run_hook()
Referenced by nest::CompartmentCurrents::pre_run_hook.
void nest::K::append_recordables(std::map< Name, double * > *recordables, const long compartment_idx)
Referenced by nest::CompartmentCurrents::get_recordables.
std::pair< double, double > nest::K::f_numstep(const double v_comp)
References nest::names::dt, numerics::e, nest::names::g_K, nest::Time::get_ms, nest::Time::get_resolution.
Referenced by nest::CompartmentCurrents::f_numstep.