nest::ConnBuilder
typedef std::map< Name, ConnParameter* > nest::ConnBuilder::ConnParameterMap
NodeCollectionPTR nest::ConnBuilder::sources_
Referenced by ConnBuilder, nest::FixedInDegreeBuilder::FixedInDegreeBuilder, nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder, nest::AllToAllBuilder::is_symmetric, nest::OneToOneBuilder::OneToOneBuilder.
NodeCollectionPTR nest::ConnBuilder::targets_
Referenced by ConnBuilder, nest::FixedOutDegreeBuilder::FixedOutDegreeBuilder, nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder, nest::AllToAllBuilder::is_symmetric, nest::OneToOneBuilder::OneToOneBuilder.
bool nest::ConnBuilder::allow_autapses_
Referenced by ConnBuilder, nest::FixedInDegreeBuilder::FixedInDegreeBuilder, nest::FixedOutDegreeBuilder::FixedOutDegreeBuilder, nest::SymmetricBernoulliBuilder::SymmetricBernoulliBuilder.
bool nest::ConnBuilder::allow_multapses_
Referenced by ConnBuilder, nest::FixedInDegreeBuilder::FixedInDegreeBuilder, nest::FixedOutDegreeBuilder::FixedOutDegreeBuilder, nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder, nest::SymmetricBernoulliBuilder::SymmetricBernoulliBuilder.
bool nest::ConnBuilder::make_symmetric_
Referenced by ConnBuilder, nest::SymmetricBernoulliBuilder::SymmetricBernoulliBuilder.
bool nest::ConnBuilder::creates_symmetric_connections_
Referenced by nest::SymmetricBernoulliBuilder::SymmetricBernoulliBuilder.
std::vector< std::shared_ptr< WrappedThreadException > > nest::ConnBuilder::exceptions_raised_
buffer for exceptions raised in threads
Name nest::ConnBuilder::pre_synaptic_element_name_
Referenced by nest::SPBuilder::get_pre_synaptic_element_name.
Name nest::ConnBuilder::post_synaptic_element_name_
Referenced by nest::SPBuilder::get_post_synaptic_element_name.
bool nest::ConnBuilder::use_pre_synaptic_element_
Referenced by nest::SPBuilder::SPBuilder, use_structural_plasticity_.
bool nest::ConnBuilder::use_post_synaptic_element_
Referenced by nest::SPBuilder::SPBuilder, use_structural_plasticity_.
std::vector< ConnParameter* > nest::ConnBuilder::parameters_requiring_skipping_
pointers to connection parameters specified as arrays
Referenced by register_parameters_requiring_skipping_, skip_conn_parameter_.
std::vector< index > nest::ConnBuilder::synapse_model_id_
Referenced by ConnBuilder, get_default_delay, get_synapse_model, single_disconnect_.
std::vector< std::vector< DictionaryDatum > > nest::ConnBuilder::param_dicts_
dictionaries to pass to connect function, one per thread for every syn_spec
Referenced by ConnBuilder.
std::vector< bool > nest::ConnBuilder::default_weight_and_delay_
indicate that weight and delay should not be set per synapse
Referenced by ConnBuilder.
std::vector< bool > nest::ConnBuilder::default_weight_
indicate that weight should not be set per synapse
Referenced by ConnBuilder.
std::vector< bool > nest::ConnBuilder::default_delay_
indicate that delay should not be set per synapse
Referenced by ConnBuilder, get_default_delay.
std::vector< ConnParameter* > nest::ConnBuilder::weights_
Referenced by ConnBuilder.
std::vector< ConnParameter* > nest::ConnBuilder::delays_
Referenced by ConnBuilder.
std::vector< ConnParameterMap > nest::ConnBuilder::synapse_params_
all other parameters, mapping name to value representation
Referenced by ConnBuilder.
std::set< Name > nest::ConnBuilder::skip_syn_params_
synapse-specific parameters that should be skipped when we set default synapse parameters
Referenced by ConnBuilder.
void nest::ConnBuilder::connect()
Connect sources to targets according to specifications in dictionary.
Now we can connect with or without structural plasticity. To create a connection, call cb.connect(); where conn_spec_dict speficies connection type and its parameters.
References nest::ModelManager::get_connection_model, nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::model_manager, nest::names::params, nest::REQUIRES_SYMMETRIC, nest::names::requires_symmetric, boost::tuples::swap, nest::names::synapse_model, nest::KernelManager::vp_manager.
Referenced by nest::ConnectionManager::connect.
void nest::ConnBuilder::disconnect()
Now we can delete synapses with or without structural plasticity.
References nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
Referenced by nest::SPManager::disconnect.
nest::ConnBuilder::ConnBuilder(NodeCollectionPTR, NodeCollectionPTR, const DictionaryDatum &, const std::vector< DictionaryDatum > &)
parameters: sources, targets, specifications
References nest::names::allow_autapses, allow_autapses_, nest::names::allow_multapses, allow_multapses_, default_delay_, default_weight_, default_weight_and_delay_, nest::names::delay, delays_, nest::ModelManager::get_connector_defaults, nest::ModelManager::get_synapse_model_id, nest::kernel, nest::names::make_symmetric, make_symmetric_, nest::names::max_delay, nest::names::min_delay, nest::KernelManager::model_manager, nest::names::music_channel, nest::names::num_connections, param_dicts_, nest::names::params, reset_delays_, reset_weights_, set_default_weight_or_delay_, set_structural_plasticity_parameters, set_synapse_model_, set_synapse_params, skip_syn_params_, sources_, nest::names::synapse_model, synapse_model_id_, synapse_params_, targets_, nest::names::weight, weights_.
nest::ConnBuilder::~ConnBuilder()
References nest::names::params.
index nest::ConnBuilder::get_synapse_model() const
References synapse_model_id_.
Referenced by nest::SPManager::update_structural_plasticity.
bool nest::ConnBuilder::get_default_delay() const
References default_delay_, synapse_model_id_.
Referenced by nest::SPManager::set_status.
void nest::ConnBuilder::set_pre_synaptic_element_name(const std::string &name)
Referenced by nest::SPManager::disconnect.
void nest::ConnBuilder::set_post_synaptic_element_name(const std::string &name)
Referenced by nest::SPManager::disconnect.
bool nest::ConnBuilder::all_parameters_scalar_() const
References nest::names::params.
Referenced by nest::AllToAllBuilder::is_symmetric.
bool nest::ConnBuilder::change_connected_synaptic_elements(index, index, const int, int)
Updates the number of connected synaptic elements in the target and the source.
Returns 0 if the target is either on another MPI machine or another thread. Returns 1 otherwise. snode_id id of the source tnode_id id of the target tid thread id update amount of connected synaptic elements to update
References nest::NodeManager::get_node_or_proxy, nest::kernel, nest::names::local, nest::KernelManager::node_manager, nest::names::source, nest::names::target, nest::names::target_thread.
virtual bool nest::ConnBuilder::supports_symmetric() const
virtual bool nest::ConnBuilder::is_symmetric() const
virtual bool nest::ConnBuilder::requires_proxies() const
Return true if rule is applicable only to nodes with proxies.
virtual void nest::ConnBuilder::connect_()=0
Implements the actual connection algorithm.
virtual void nest::ConnBuilder::sp_connect_()
virtual void nest::ConnBuilder::disconnect_()
virtual void nest::ConnBuilder::sp_disconnect_()
void nest::ConnBuilder::update_param_dict_(index snode_id, Node &target, thread target_thread, RngPtr rng, index indx)
References nest::kernel, nest::names::target, nest::names::target_thread.
void nest::ConnBuilder::single_connect_(index, Node &, thread, RngPtr)
Create connection between given nodes, fill parameter values.
References nest::ConnectionManager::connect, nest::KernelManager::connection_manager, nest::kernel, numerics::nan, nest::names::target, nest::names::target_thread.
void nest::ConnBuilder::single_disconnect_(index, Node &, thread)
References nest::SPManager::disconnect, nest::kernel, nest::KernelManager::sp_manager, synapse_model_id_, nest::names::target, nest::names::target_thread.
void nest::ConnBuilder::skip_conn_parameter_(thread, size_t n_skip=1)
Moves pointer in parameter array.
Calls value-function of all parameters being instantiations of ArrayDoubleParameter or ArrayIntegerParameter, thus moving the pointer to the next parameter value. The function is called when the target node is not located on the current thread or MPI-process and read of an array.
References parameters_requiring_skipping_, nest::names::target_thread.
bool nest::ConnBuilder::loop_over_targets_() const
Returns true if conventional looping over targets is indicated.
Conventional looping over targets must be used if any connection parameter requires skipping targets are not given as a simple range (lookup otherwise too slow) Conventional looping should be used if the number of targets is smaller than the number of local nodes For background, see Ippen et al (2017). true if conventional looping is to be used
References nest::kernel, nest::KernelManager::node_manager, nest::NodeManager::size.
bool nest::ConnBuilder::use_structural_plasticity_() const
References use_post_synaptic_element_, use_pre_synaptic_element_.
void nest::ConnBuilder::register_parameters_requiring_skipping_(ConnParameter &param)
Collects all array parameters in a vector.
If the inserted parameter is an array it will be added to a vector of ConnParameters. This vector will be exploited in some connection routines to ensuring thread-safety.
References nest::ConnParameter::is_array, parameters_requiring_skipping_.
void nest::ConnBuilder::set_synapse_model_(DictionaryDatum syn_params, size_t indx)
References nest::ModelManager::get_connection_model, nest::ModelManager::get_synapse_model_id, nest::kernel, nest::KernelManager::model_manager, nest::names::synapse_model.
Referenced by ConnBuilder.
void nest::ConnBuilder::set_default_weight_or_delay_(DictionaryDatum syn_params, size_t indx)
References nest::ConnParameter::create, nest::names::delay, nest::ModelManager::get_connector_defaults, nest::kernel, nest::KernelManager::model_manager, nest::names::weight.
Referenced by ConnBuilder.
void nest::ConnBuilder::set_synapse_params(DictionaryDatum syn_defaults, DictionaryDatum syn_params, size_t indx)
References nest::ConnParameter::create, nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::vp_manager.
Referenced by ConnBuilder.
void nest::ConnBuilder::set_structural_plasticity_parameters(std::vector< DictionaryDatum > syn_specs)
References nest::names::post_synaptic_element, nest::names::pre_synaptic_element.
Referenced by ConnBuilder.
void nest::ConnBuilder::reset_weights_()
Reset weight and delay pointers.
Referenced by ConnBuilder.
void nest::ConnBuilder::reset_delays_()
Referenced by ConnBuilder.