nest::nc_const_iterator
friend class NodeCollectionPrimitive
friend class NodeCollectionComposite
NodeCollectionPTR nest::nc_const_iterator::coll_ptr_
holds pointer reference in safe iterators
size_t nest::nc_const_iterator::element_idx_
index into (current) primitive node collection
Referenced by composite_update_indices_, get_current_part_offset, operator!=, operator*, operator++, operator+=, operator<, operator<=, print_me.
size_t nest::nc_const_iterator::part_idx_
index into parts vector of composite collection
Referenced by composite_update_indices_, get_current_part_offset, operator!=, operator*, operator<, operator<=, print_me.
size_t nest::nc_const_iterator::step_
step for skipping due to e.g. slicing
Referenced by operator++, operator+=.
NodeCollectionPrimitive const* const nest::nc_const_iterator::primitive_collection_
Pointer to primitive collection to iterate over.
Zero if iterator is for composite collection.
Referenced by operator*, operator++, print_me.
NodeCollectionComposite const* const nest::nc_const_iterator::composite_collection_
Pointer to composite collection to iterate over.
Zero if iterator is for primitive collection.
Referenced by composite_update_indices_, operator*, operator+=, print_me.
nest::nc_const_iterator::nc_const_iterator(NodeCollectionPTR collection_ptr, const NodeCollectionPrimitive &collection, size_t offset, size_t step=1)
Create safe iterator for NodeCollectionPrimitive.
collection_ptr smart pointer to collection to keep collection alive collection Collection to iterate over offset Index of collection element iterator points to step Step for skipping due to e.g. slicing
References nest::NodeCollectionPrimitive::size.
nest::nc_const_iterator::nc_const_iterator(NodeCollectionPTR collection_ptr, const NodeCollectionComposite &collection, size_t part, size_t offset, size_t step=1)
Create safe iterator for NodeCollectionComposite.
collection_ptr smart pointer to collection to keep collection alive collection Collection to iterate over part Index of part of collection iterator points to offset Index of element in NC part that iterator points to step Step for skipping due to e.g. slicing
References nest::NodeCollectionComposite::parts_.
void nest::nc_const_iterator::composite_update_indices_()
Conditionally update element_idx and part_idx for composite NodeCollections.
References composite_collection_, element_idx_, nest::NodeCollectionComposite::end, nest::NodeCollectionComposite::end_offset_, nest::NodeCollectionComposite::end_part_, part_idx_, nest::NodeCollectionComposite::parts_.
Referenced by operator++, operator+=.
nest::nc_const_iterator::nc_const_iterator(const nc_const_iterator &nci)=default
void nest::nc_const_iterator::get_current_part_offset(size_t &, size_t &)
References element_idx_, part_idx_.
Referenced by nest::NodeCollectionComposite::local_begin, nest::NodeCollectionComposite::MPI_local_begin, nest::NodeCollectionComposite::NodeCollectionComposite.
NodeIDTriple nest::nc_const_iterator::operator*() const
References composite_collection_, element_idx_, nest::NodeCollectionComposite::end_offset_, nest::NodeCollectionComposite::end_part_, nest::NodeCollectionPrimitive::first_, nest::NodeCollectionPrimitive::last_, nest::NodeIDTriple::lid, nest::NodeIDTriple::model_id, nest::NodeCollectionPrimitive::model_id_, nest::NodeIDTriple::node_id, part_idx_, nest::NodeCollectionComposite::parts_, primitive_collection_.
bool nest::nc_const_iterator::operator!=(const nc_const_iterator &rhs) const
References element_idx_, part_idx_.
bool nest::nc_const_iterator::operator<(const nc_const_iterator &rhs) const
References element_idx_, part_idx_.
bool nest::nc_const_iterator::operator<=(const nc_const_iterator &rhs) const
References element_idx_, part_idx_.
nc_const_iterator & nest::nc_const_iterator::operator++()
References composite_update_indices_, element_idx_, primitive_collection_, nest::NodeCollectionPrimitive::size, step_.
nc_const_iterator & nest::nc_const_iterator::operator+=(const size_t)
References composite_collection_, composite_update_indices_, element_idx_, step_.
nc_const_iterator nest::nc_const_iterator::operator+(const size_t) const
void nest::nc_const_iterator::print_me(std::ostream &) const
References composite_collection_, element_idx_, part_idx_, primitive_collection_.