nest::SpikeData
constexpr int nest::SpikeData::MAX_LAG
Referenced by set, nest::OffGridSpikeData::set.
index nest::SpikeData::lcid_
local connection index
Referenced by get_lcid, operator=, set, nest::OffGridSpikeData::set.
unsigned int nest::SpikeData::marker_
status flag
Referenced by is_complete_marker, is_end_marker, is_invalid_marker, operator=, reset_marker, set, nest::OffGridSpikeData::set, set_complete_marker, set_end_marker, set_invalid_marker.
unsigned int nest::SpikeData::lag_
lag in this min-delay interval
Referenced by get_lag, operator=, set, nest::OffGridSpikeData::set.
unsigned int nest::SpikeData::tid_
thread index
Referenced by get_tid, operator=, set, nest::OffGridSpikeData::set.
synindex nest::SpikeData::syn_id_
synapse-type index
Referenced by get_syn_id, operator=, set, nest::OffGridSpikeData::set.
nest::SpikeData::SpikeData()
nest::SpikeData::SpikeData(const SpikeData &rhs)
nest::SpikeData::SpikeData(const thread tid, const synindex syn_id, const index lcid, const unsigned int lag)
SpikeData & nest::SpikeData::operator=(const SpikeData &rhs)
References lag_, lcid_, marker_, nest::SPIKE_DATA_ID_DEFAULT, syn_id_, tid_.
void nest::SpikeData::set(const thread tid, const synindex syn_id, const index lcid, const unsigned int lag, const double offset)
References lag_, lcid_, marker_, MAX_LAG, nest::MAX_LCID, nest::MAX_SYN_ID, nest::MAX_TID, nest::SPIKE_DATA_ID_DEFAULT, syn_id_, tid_.
Referenced by nest::OffGridSpikeData::set, nest::Event::set_sender_node_id_info.
void nest::SpikeData::set(const TargetT &target, const unsigned int lag)
References lag_, lcid_, marker_, MAX_LAG, nest::SPIKE_DATA_ID_DEFAULT, syn_id_, tid_.
index nest::SpikeData::get_lcid() const
Returns local connection ID.
References lcid_.
Referenced by nest::Event::retrieve_sender_node_id_from_source_table.
unsigned int nest::SpikeData::get_lag() const
Returns lag in min-delay interval.
References lag_.
thread nest::SpikeData::get_tid() const
Returns thread index.
References tid_.
Referenced by nest::Event::retrieve_sender_node_id_from_source_table.
synindex nest::SpikeData::get_syn_id() const
Returns synapse-type index.
References syn_id_.
Referenced by nest::Event::retrieve_sender_node_id_from_source_table.
void nest::SpikeData::reset_marker()
Resets the status flag to default value.
References marker_, nest::SPIKE_DATA_ID_DEFAULT.
void nest::SpikeData::set_complete_marker()
Sets the status flag to complete marker.
References marker_, nest::SPIKE_DATA_ID_COMPLETE.
void nest::SpikeData::set_end_marker()
Sets the status flag to end marker.
References marker_, nest::SPIKE_DATA_ID_END.
void nest::SpikeData::set_invalid_marker()
Sets the status flag to invalid marker.
References marker_, nest::SPIKE_DATA_ID_INVALID.
bool nest::SpikeData::is_complete_marker() const
Returns whether the marker is the complete marker.
References marker_, nest::SPIKE_DATA_ID_COMPLETE.
bool nest::SpikeData::is_end_marker() const
Returns whether the marker is the end marker.
References marker_, nest::SPIKE_DATA_ID_END.
bool nest::SpikeData::is_invalid_marker() const
Returns whether the marker is the invalid marker.
References marker_, nest::SPIKE_DATA_ID_INVALID.
double nest::SpikeData::get_offset() const
Returns offset.