nest::NodeManager
std::vector< SparseNodeArray > nest::NodeManager::local_nodes_
The network as sparse array of local nodes.
One entry per thread, which contains only the thread-local nodes.
Referenced by add_devices_, add_music_nodes_, add_neurons_, add_node, destruct_nodes_, ensure_valid_thread_local_ids, finalize_nodes, get_local_nodes, get_mpi_local_node_or_device_head, get_node_or_proxy, get_thread_siblings, initialize, post_run_cleanup, prepare_nodes, set_status, size, thread_lid_to_node.
std::vector< std::vector< Node* > > nest::NodeManager::wfr_nodes_vec_
Nodelists for unfrozen nodes that use the waveform relaxation method.
Referenced by ensure_valid_thread_local_ids, get_wfr_nodes_on_thread.
bool nest::NodeManager::wfr_is_used_
there is at least one node that uses waveform relaxation
Referenced by check_wfr_use, ensure_valid_thread_local_ids, wfr_is_used.
index nest::NodeManager::wfr_network_size_
Network size when wfr_nodes_vec_ was last updated.
Referenced by ensure_valid_thread_local_ids, initialize.
size_t nest::NodeManager::num_active_nodes_
number of nodes created by prepare_nodes
Referenced by get_num_active_nodes, prepare_nodes.
std::vector< index > nest::NodeManager::num_thread_local_devices_
stores number of thread local devices
Referenced by add_devices_, add_music_nodes_, get_num_thread_local_devices, initialize.
bool nest::NodeManager::have_nodes_changed_
true if new nodes have been created since startup or last call to simulate
Referenced by add_node, have_nodes_changed, set_have_nodes_changed.
std::vector< std::shared_ptr< WrappedThreadException > > nest::NodeManager::exceptions_raised_
Store exceptions raised in thread-parallel sections for later handling.
Referenced by add_devices_, add_music_nodes_, add_neurons_, add_node.
Stopwatch nest::NodeManager::sw_construction_create_
Referenced by add_node, get_status, initialize.
nest::NodeManager::NodeManager()
nest::NodeManager::~NodeManager() override
References destruct_nodes_.
void nest::NodeManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References ensure_valid_thread_local_ids, nest::kernel, local_nodes_, num_thread_local_devices_, nest::Stopwatch::reset, sw_construction_create_, wfr_network_size_.
Referenced by change_number_of_threads.
void nest::NodeManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
References destruct_nodes_.
void nest::NodeManager::change_number_of_threads() override
Change the number of threads.
Many data structures within the different managers depend on the number of threads. This function is called on each manager upon a change of that number and allows the manager to re-allocate data structures accordingly.
References initialize.
void nest::NodeManager::set_status(const DictionaryDatum &) override
Referenced by nest::set_node_status.
void nest::NodeManager::get_status(DictionaryDatum &) override
References nest::names::d, nest::Stopwatch::elapsed, nest::names::network_size, size, sw_construction_create_, nest::names::time_construction_create.
Referenced by nest::get_node_status, get_nodes.
DictionaryDatum nest::NodeManager::get_status(index)
Get properties of a node.
The specified node must exist. nest::UnknownNode Target does not exist in the network.
References nest::names::d, get_mpi_local_node_or_device_head, nest::names::target.
void nest::NodeManager::set_status(index, const DictionaryDatum &)
Set properties of a Node.
The specified node must exist. nest::UnknownNode Target does not exist in the network. nest::UnaccessedDictionaryEntry Non-proxy target did not read dict entry. TypeMismatch Array is not a flat & homogeneous array of integers.
References nest::names::d, nest::VPManager::get_num_threads, nest::kernel, local_nodes_, set_status_single_node_, nest::KernelManager::vp_manager.
NodeCollectionPTR nest::NodeManager::add_node(index m, long n=1)
Add a number of nodes to the network.
This function creates n Node objects of Model m and adds them to the Network at the current position. m valid Model ID. n Number of Nodes to be created. Defaults to 1 if not specified. NodeCollection as lock pointer
References add_devices_, add_music_nodes_, add_neurons_, nest::ModelRangeManager::add_range, nest::KernelManager::connection_manager, nest::KernelManager::event_delivery_manager, exceptions_raised_, nest::ModelManager::get_node_model, nest::VPManager::get_num_threads, have_nodes_changed_, nest::kernel, local_nodes_, LOG, nest::M_ERROR, nest::M_INFO, nest::names::model, nest::names::model_id, nest::KernelManager::model_manager, nest::KernelManager::modelrange_manager, nest::names::n, nest::ConnectionManager::resize_target_table_devices_to_number_of_neurons, nest::ConnectionManager::resize_target_table_devices_to_number_of_synapse_types, nest::EventDeliveryManager::set_off_grid_communication, nest::Stopwatch::start, nest::Stopwatch::stop, sw_construction_create_, boost::tuples::swap, nest::KernelManager::vp_manager.
Referenced by nest::create, nest::AbstractLayer::create_layer.
NodeCollectionPTR nest::NodeManager::get_nodes(const DictionaryDatum &dict, const bool local_only)
Get node ID's of all nodes with the given properties.
Only node ID's of nodes matching the properties given in the dictionary exactly will be returned. If the dictionary is empty, all nodes will be returned. If the local_only bool is true, only node IDs of nodes simulated on the local MPI process will be returned. dict parameter dictionary of selection properties local_only bool indicating whether all nodes, or just mpi local nodes should be returned. NodeCollection as lock pointer
References nest::MPIManager::communicate, nest::NodeCollection::create, get_local_nodes, nest::VPManager::get_num_threads, get_status, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::mpi_manager, nest::names::params, nest::sort, nest::KernelManager::vp_manager.
Referenced by nest::get_nodes.
index nest::NodeManager::size() const
Return total number of network nodes.
References local_nodes_.
Referenced by nest::RecordingBackendASCII::compute_vp_node_id_string_, ensure_valid_thread_local_ids, get_max_num_local_nodes, get_node_or_proxy, get_status, nest::SPManager::get_synaptic_elements, nest::ConnBuilder::loop_over_targets_, print.
index nest::NodeManager::get_max_num_local_nodes() const
Returns the maximal number of nodes per virtual process.
References nest::kernel, size.
Referenced by nest::TargetTable::prepare.
index nest::NodeManager::get_num_thread_local_devices(thread t) const
Returns the number of devices per thread.
References num_thread_local_devices_.
void nest::NodeManager::print(std::ostream &) const
Print network information.
References nest::ModelManager::get_node_model, nest::kernel, nest::mod, nest::KernelManager::model_manager, size.
Referenced by nest::print_nodes_to_stream.
bool nest::NodeManager::is_local_node(Node *) const
Return true, if the given Node is on the local machine.
References nest::VPManager::is_local_vp, nest::kernel, nest::names::n, nest::KernelManager::vp_manager.
Referenced by nest::Node::get_status_base.
bool nest::NodeManager::is_local_node_id(index node_id) const
Return true, if the given node ID is on the local machine.
References nest::VPManager::is_local_vp, nest::kernel, nest::VPManager::node_id_to_vp, nest::names::vp, nest::KernelManager::vp_manager.
Referenced by nest::displacement, nest::distance.
Node * nest::NodeManager::get_node_or_proxy(index node_id, thread tid)
Return pointer to the specified Node.
The function expects that the given node ID and thread are valid. If they are not, an assertion will fail. In case the given Node does not exist on the fiven thread, a proxy is returned instead. node_id index of the Node tid local thread index of the Node
References nest::ModelManager::get_proxy_node, nest::kernel, local_nodes_, nest::KernelManager::model_manager, size.
Referenced by nest::apply, nest::ConnBuilder::change_connected_synaptic_elements, nest::ConnectionManager::connect, nest::OneToOneBuilder::connect_, nest::AllToAllBuilder::connect_, nest::FixedInDegreeBuilder::connect_, nest::FixedOutDegreeBuilder::connect_, nest::FixedTotalNumberBuilder::connect_, nest::BernoulliBuilder::connect_, nest::SymmetricBernoulliBuilder::connect_, nest::SPBuilder::connect_, nest::ConnectionManager::connect_arrays, nest::ConnectionManager::connection_required, nest::SPManager::delete_synapse, nest::disconnect, nest::SPManager::disconnect, nest::OneToOneBuilder::disconnect_, nest::AllToAllBuilder::disconnect_, nest::distance, nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_, nest::TargetTableDevices::get_connections_from_devices_, nest::get_position, nest::ConnectionManager::get_synapse_status, nest::ConnectionCreator::pairwise_bernoulli_on_source_, nest::ConnectionCreator::pairwise_bernoulli_on_target_, nest::Connector< ConnectionT >::send_weight_event, nest::STDPDopaCommonProperties::set_status, nest::ConnectionManager::set_synapse_status, nest::OneToOneBuilder::sp_connect_, nest::AllToAllBuilder::sp_connect_, nest::OneToOneBuilder::sp_disconnect_, nest::AllToAllBuilder::sp_disconnect_, nest::ConnectionManager::split_to_neuron_device_vectors_.
Node * nest::NodeManager::get_node_or_proxy(index)
Return pointer of the specified Node.
i Index of the specified Node.
References nest::ModelManager::get_proxy_node, nest::kernel, local_nodes_, nest::KernelManager::model_manager, nest::VPManager::node_id_to_vp, size, nest::names::vp, nest::KernelManager::vp_manager, nest::VPManager::vp_to_thread.
Node * nest::NodeManager::get_mpi_local_node_or_device_head(index)
References nest::ModelManager::get_proxy_node, nest::Node::has_proxies, nest::kernel, local_nodes_, nest::KernelManager::model_manager, nest::KernelManager::vp_manager, nest::VPManager::vp_to_thread.
Referenced by get_status, nest::FreeLayer< D >::set_status.
std::vector< Node * > nest::NodeManager::get_thread_siblings(index n) const
Return a vector that contains the thread siblings.
i Index of the specified Node. nest::NoThreadSiblingsAvailable Node does not have thread siblings.
References nest::VPManager::get_num_threads, nest::kernel, local_nodes_, nest::KernelManager::vp_manager.
Referenced by nest::multimeter::get_status, nest::spike_recorder::get_status, nest::spin_detector::get_status, nest::weight_recorder::get_status.
void nest::NodeManager::ensure_valid_thread_local_ids()
Ensure that all nodes in the network have valid thread-local IDs.
Create up-to-date vector of local nodes, nodes_vec_. This method also sets the thread-local ID on all local nodes.
References nest::SparseNodeArray::NodeEntry::get_node, nest::VPManager::get_num_threads, nest::kernel, local_nodes_, size, nest::KernelManager::vp_manager, wfr_is_used_, wfr_network_size_, wfr_nodes_vec_.
Referenced by initialize, nest::SimulationManager::prepare, nest::TargetIdentifierIndex::set_target.
Node * nest::NodeManager::thread_lid_to_node(thread t, targetindex thread_local_id) const
References local_nodes_, nest::names::thread_local_id.
Referenced by nest::TargetIdentifierIndex::get_target_ptr.
const std::vector< Node * > & nest::NodeManager::get_wfr_nodes_on_thread(thread) const
Get list of nodes on given thread.
References wfr_nodes_vec_.
Referenced by nest::SimulationManager::update_.
void nest::NodeManager::prepare_nodes()
Prepare nodes for simulation and register nodes in node_list.
Calls prepare_node_() for each pertaining Node. prepare_node_()
References numerics::e, nest::VPManager::get_num_threads, nest::VPManager::get_thread_id, nest::kernel, local_nodes_, LOG, nest::M_INFO, num_active_nodes_, prepare_node_, nest::KernelManager::vp_manager.
Referenced by nest::SimulationManager::prepare.
size_t nest::NodeManager::get_num_active_nodes()
Get the number of nodes created by last prepare_nodes() call.
prepare_nodes() number of active nodes
References num_active_nodes_.
Referenced by nest::SimulationManager::call_update_.
void nest::NodeManager::post_run_cleanup()
Invoke post_run_cleanup() on all nodes.
References nest::VPManager::get_thread_id, nest::kernel, local_nodes_, nest::names::n, nest::KernelManager::vp_manager.
void nest::NodeManager::finalize_nodes()
Invoke finalize() on all nodes.
This function is called only if the thread data structures are properly set up.
References nest::VPManager::get_thread_id, nest::kernel, local_nodes_, nest::names::n, nest::KernelManager::vp_manager.
Referenced by nest::SimulationManager::cleanup.
bool nest::NodeManager::wfr_is_used() const
Returns whether any node uses waveform relaxation.
References wfr_is_used_.
void nest::NodeManager::check_wfr_use()
Checks whether waveform relaxation is used by any node.
References nest::MPIManager::any_true, nest::kernel, nest::KernelManager::mpi_manager, nest::DataSecondaryEvent< double, DelayedRateConnectionEvent >::set_coeff_length, nest::DataSecondaryEvent< double, DiffusionConnectionEvent >::set_coeff_length, nest::DataSecondaryEvent< double, InstantaneousRateConnectionEvent >::set_coeff_length, nest::DataSecondaryEvent< double, GapJunctionEvent >::set_coeff_length, wfr_is_used_.
Referenced by nest::ConnectionManager::get_connections, nest::SimulationManager::prepare.
const SparseNodeArray & nest::NodeManager::get_local_nodes(thread) const
Return a reference to the thread-local nodes of thread t.
References local_nodes_.
Referenced by nest::OneToOneBuilder::connect_, nest::AllToAllBuilder::connect_, nest::FixedInDegreeBuilder::connect_, nest::BernoulliBuilder::connect_, get_nodes, nest::SPManager::get_synaptic_elements, nest::SimulationManager::update_.
bool nest::NodeManager::have_nodes_changed() const
References have_nodes_changed_.
void nest::NodeManager::set_have_nodes_changed(const bool changed)
References have_nodes_changed_.
Referenced by nest::SimulationManager::update_connection_infrastructure.
void nest::NodeManager::init_()
Initialize the network data structures.
init_() is used by the constructor and by reset(). reset()
void nest::NodeManager::destruct_nodes_()
References nest::VPManager::get_thread_id, nest::kernel, local_nodes_, nest::KernelManager::vp_manager.
Referenced by finalize, ~NodeManager.
void nest::NodeManager::set_status_single_node_(Node &, const DictionaryDatum &, bool clear_flags=true)
Helper function to set properties on single node.
node to set properties for dictionary containing properties if true (default), access flags are called before each call so Node::set_status_() UnaccessedDictionaryEntry
References ALL_ENTRIES_ACCESSED, nest::names::d, nest::names::target.
Referenced by set_status.
void nest::NodeManager::prepare_node_(Node *)
Initialized buffers, register in list of nodes to update/finalize.
prepare_nodes_()
References nest::names::n.
Referenced by prepare_nodes.
void nest::NodeManager::add_neurons_(Model &model, index min_node_id, index max_node_id, NodeCollectionPTR nc_ptr)
Add normal neurons.
Each neuron is added to exactly one virtual process. On all other VPs, it is represented by a proxy. model Model of neuron to create. min_node_id node ID of first neuron to create. max_node_id node ID of last neuron to create (inclusive).
References exceptions_raised_, nest::VPManager::get_num_virtual_processes, nest::VPManager::get_thread_id, nest::kernel, local_nodes_, nest::names::model, nest::VPManager::node_id_to_vp, nest::Node::set_initialized, nest::Node::set_model_id, nest::Node::set_nc_, nest::Node::set_node_id_, nest::Node::set_thread, nest::Node::set_vp, nest::VPManager::thread_to_vp, nest::names::vp, nest::KernelManager::vp_manager.
Referenced by add_node.
void nest::NodeManager::add_devices_(Model &model, index min_node_id, index max_node_id, NodeCollectionPTR nc_ptr)
Add device nodes.
For device nodes, a clone of the node is added to every virtual process. model Model of neuron to create. min_node_id node ID of first neuron to create. max_node_id node ID of last neuron to create (inclusive).
References exceptions_raised_, nest::VPManager::get_thread_id, nest::kernel, local_nodes_, nest::names::model, num_thread_local_devices_, nest::Node::set_initialized, nest::Node::set_local_device_id, nest::Node::set_model_id, nest::Node::set_nc_, nest::Node::set_node_id_, nest::Node::set_thread, nest::Node::set_vp, nest::KernelManager::vp_manager.
Referenced by add_node.
void nest::NodeManager::add_music_nodes_(Model &model, index min_node_id, index max_node_id, NodeCollectionPTR nc_ptr)
Add MUSIC nodes.
Nodes for MUSIC communication are added once per MPI process and are always placed on thread 0. model Model of neuron to create. min_node_id node ID of first neuron to create. max_node_id node ID of last neuron to create (inclusive).
References exceptions_raised_, nest::VPManager::get_thread_id, nest::kernel, local_nodes_, nest::names::model, num_thread_local_devices_, nest::Node::set_initialized, nest::Node::set_local_device_id, nest::Node::set_model_id, nest::Node::set_nc_, nest::Node::set_node_id_, nest::Node::set_thread, nest::Node::set_vp, nest::KernelManager::vp_manager.
Referenced by add_node.