nest::Time
friend class TimeConverter
friend struct step
Referenced by nest::SimulationManager::advance_time_, nest::EventDeliveryManager::deliver_events_, nest::ConnectionManager::deliver_secondary_events, nest::SimulationManager::get_previous_slice_origin, nest::SimulationManager::get_time, nest::multimeter::Parameters_::set, nest::SimulationManager::set_status, nest::gamma_sup_generator::update, nest::ppd_sup_generator::update, nest::spike_generator::update, nest::spike_train_injector::update.
friend struct tic
Referenced by pred, succ.
friend struct ms
Referenced by nest::inhomogeneous_poisson_generator::Parameters_::assert_valid_rate_time_and_insert, nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_, nest::spike_train_injector::Parameters_::assert_valid_spike_time_and_insert_, nest::TimeConverter::from_old_steps, nest::TimeConverter::from_old_tics, nest::binary_neuron< TGainfunction >::pre_run_hook, nest::run, nest::correlation_detector::Parameters_::set, nest::correlomatrix_detector::Parameters_::set, nest::correlospinmatrix_detector::Parameters_::set, nest::noise_generator::Parameters_::set, nest::spike_generator::set_status, nest::spike_train_injector::set_status, nest::binary_neuron< TGainfunction >::update, nest::Device::Parameters_::update_, nest::step_current_generator::Parameters_::validate_time_, nest::step_rate_generator::Parameters_::validate_time_.
friend struct ms_stamp
Referenced by nest::inhomogeneous_poisson_generator::Parameters_::assert_valid_rate_time_and_insert, nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_, nest::spike_train_injector::Parameters_::assert_valid_spike_time_and_insert_, nest::poisson_generator_ps::event_hook, nest::step_current_generator::Parameters_::validate_time_, nest::step_rate_generator::Parameters_::validate_time_.
bool operator==(const Time &t1, const Time &t2)
bool operator!=(const Time &t1, const Time &t2)
bool operator<(const Time &t1, const Time &t2)
bool operator>(const Time &t1, const Time &t2)
bool operator<=(const Time &t1, const Time &t2)
bool operator>=(const Time &t1, const Time &t2)
Time operator+(const Time &t1, const Time &t2)
Time operator-(const Time &t1, const Time &t2)
Time operator*(const long factor, const Time &t)
Time operator*(const Time &t, long factor)
std::ostream& operator<<)(std::ostream &, const Time &)
tic_t nest::Time::tics
Referenced by advance, compute_max, get_ms, get_steps, get_tics, is_finite, is_grid_time, is_multiple_of, is_neg_inf, is_pos_inf, is_step, operator+=, pred, range, set_to_zero, succ.
Time::Limit Time::LIM_MAX
Referenced by fromstamp, max, range, reset_resolution, set_resolution.
Time::Limit Time::LIM_MIN
Referenced by fromstamp, min, reset_resolution, set_resolution.
struct nest::Time::LimitPosInf nest::Time::LIM_POS_INF
Referenced by nest::TimeConverter::from_old_steps, nest::TimeConverter::from_old_tics, fromstamp, get_steps, is_finite, is_pos_inf, pos_inf, range.
struct nest::Time::LimitNegInf nest::Time::LIM_NEG_INF
Referenced by nest::TimeConverter::from_old_steps, nest::TimeConverter::from_old_tics, fromstamp, get_steps, is_finite, is_neg_inf, neg_inf, range.
tic_t Time::compute_max()
References nest::Time::Range::INF_MARGIN, nest::names::max, tics, nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_INV.
Referenced by reset_resolution, set_resolution.
tic_t Time::fromstamp(ms_stamp)
References LIM_MAX, LIM_MIN, LIM_NEG_INF, LIM_POS_INF, nest::Time::Limit::ms, nest::Time::Range::MS_PER_STEP, nest::names::n, nest::Time::ms_stamp::t, nest::Time::LimitPosInf::tics, nest::Time::LimitNegInf::tics, nest::Time::Range::TICS_PER_MS, nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_INV.
void Time::set_resolution(double tics_per_ms)
References compute_max, dround, LIM_MAX, LIM_MIN, max, nest::Time::Range::MS_PER_STEP, nest::Time::Range::STEPS_PER_MS, nest::Time::Range::TICS_PER_MS, nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_INV, nest::Time::Range::TICS_PER_STEP_RND.
Referenced by set_resolution, nest::SimulationManager::set_status.
void Time::set_resolution(double tics_per_ms, double ms_per_step)
References nest::Time::Range::MS_PER_TIC, set_resolution, nest::names::tics_per_ms, nest::Time::Range::TICS_PER_MS.
void Time::reset_resolution()
References compute_max, LIM_MAX, LIM_MIN, max, nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_DEFAULT, nest::Time::Range::TICS_PER_STEP_INV, nest::Time::Range::TICS_PER_STEP_RND.
Referenced by nest::SimulationManager::initialize.
void Time::reset_to_defaults()
References nest::Time::Range::MS_PER_STEP, nest::Time::Range::MS_PER_TIC, nest::Time::Range::STEPS_PER_MS, nest::Time::Range::TICS_PER_MS, nest::Time::Range::TICS_PER_MS_DEFAULT, nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_DEFAULT, nest::Time::Range::TICS_PER_STEP_INV, nest::Time::Range::TICS_PER_STEP_RND.
Referenced by nest::SimulationManager::initialize.
static Time nest::Time::get_resolution()
References nest::Time::Range::TICS_PER_STEP, Time.
Referenced by nest::DelayChecker::assert_two_valid_delays_steps, nest::DelayChecker::assert_valid_delay_ms, nest::SimulationManager::assert_valid_simtime, nest::SimulationManager::call_update_, nest::RecordingBackendSIONlib::close_files_, nest::Na::f_numstep, nest::K::f_numstep, nest::correlation_detector::Parameters_::get_default_delta_tau, nest::correlomatrix_detector::Parameters_::get_default_delta_tau, nest::correlospinmatrix_detector::Parameters_::get_default_delta_tau, nest::noise_generator::Parameters_::get_default_dt, nest::ConnectionManager::get_max_delay_time_, nest::SimulationManager::get_status, nest::InvalidDefaultResolution::message, nest::InvalidTimeInModel::message, nest::StepMultipleRequired::message, nest::AMPA::pre_run_hook, nest::GABA::pre_run_hook, nest::NMDA::pre_run_hook, nest::AMPA_NMDA::pre_run_hook, nest::Compartment::pre_run_hook, nest::ac_generator::pre_run_hook, nest::amat2_psc_exp::pre_run_hook, nest::gamma_sup_generator::pre_run_hook, nest::gif_psc_exp::pre_run_hook, nest::gif_psc_exp_multisynapse::pre_run_hook, nest::glif_psc::pre_run_hook, nest::iaf_chs_2007::pre_run_hook, nest::iaf_psc_alpha::pre_run_hook, nest::iaf_psc_alpha_multisynapse::pre_run_hook, nest::iaf_psc_alpha_ps::pre_run_hook, nest::iaf_psc_delta::pre_run_hook, nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_exp::pre_run_hook, nest::iaf_psc_exp_htum::pre_run_hook, nest::iaf_psc_exp_multisynapse::pre_run_hook, nest::iaf_psc_exp_ps::pre_run_hook, nest::iaf_psc_exp_ps_lossless::pre_run_hook, nest::inhomogeneous_poisson_generator::pre_run_hook, nest::mat2_psc_exp::pre_run_hook, nest::mip_generator::pre_run_hook, nest::noise_generator::pre_run_hook, nest::poisson_generator::pre_run_hook, nest::pp_psc_delta::pre_run_hook, nest::ppd_sup_generator::pre_run_hook, nest::rate_neuron_ipn< TNonlinearities >::pre_run_hook, nest::rate_neuron_opn< TNonlinearities >::pre_run_hook, nest::sinusoidal_poisson_generator::pre_run_hook, nest::SimulationManager::prepare, nest::SimulationManager::print_progress_, nest::SimulationManager::run_duration, nest::SimulationManager::run_end_time, nest::SimulationManager::run_start_time, nest::cont_delay_synapse< targetidentifierT >::send, nest::multimeter::Parameters_::set, nest::izhikevich::Parameters_::set, nest::DelayChecker::set_min_max_delay_, nest::SimulationManager::set_status, nest::cont_delay_synapse< targetidentifierT >::set_status, nest::ConnectionManager::set_stdp_eps, nest::iaf_psc_exp::update, nest::GrowthCurveGaussian::update, nest::GrowthCurveSigmoid::update, nest::gif_psc_exp::update, nest::gif_psc_exp_multisynapse::update, nest::iaf_psc_delta::update, nest::izhikevich::update, nest::SimulationManager::update_, nest::ConnectionManager::update_delay_extrema_, nest::ClopathArchivingNode::write_LTP_history, nest::UrbanczikArchivingNode< urbanczik_parameters >::write_urbanczik_history.
static bool nest::Time::resolution_is_default()
References nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_DEFAULT.
static Time nest::Time::max()
References LIM_MAX, nest::Time::Limit::tics, Time.
Referenced by nest::SimulationManager::assert_valid_simtime, nest::SimulationManager::get_status, reset_resolution, set_resolution.
static Time nest::Time::min()
References LIM_MIN, nest::Time::Limit::tics, Time.
Referenced by nest::SimulationManager::get_status.
static double nest::Time::get_ms_per_tic()
References nest::Time::Range::MS_PER_TIC.
Referenced by nest::SimulationManager::get_status, nest::SimulationManager::set_status.
static Time nest::Time::neg_inf()
References LIM_NEG_INF, nest::Time::LimitNegInf::tics, Time.
Referenced by nest::SPManager::builder_max_delay, nest::DelayChecker::calibrate, nest::poisson_generator_ps::init_buffers_, nest::poisson_generator_ps::pre_run_hook, nest::correlospinmatrix_detector::State_::reset, nest::poisson_generator_ps::set_status.
static Time nest::Time::pos_inf()
References LIM_POS_INF, nest::Time::LimitPosInf::tics, Time.
Referenced by nest::SPManager::builder_min_delay, nest::DelayChecker::calibrate, nest::ConnectionManager::get_min_delay_time_, nest::ConnectionManager::update_delay_extrema_.
static tic_t nest::Time::get_tics_per_step()
References nest::Time::Range::TICS_PER_STEP.
Referenced by nest::SimulationManager::get_status, nest::TimeConverter::TimeConverter.
static double nest::Time::get_tics_per_ms()
References nest::Time::Range::TICS_PER_MS.
Referenced by nest::SimulationManager::get_status, nest::SimulationManager::set_status, nest::TimeConverter::TimeConverter.
static double nest::Time::delay_steps_to_ms(delay steps)
Convert between delays given in steps and milliseconds.
This is not a reversible operation, since steps have a finite rounding resolution. This is not a truncation, but rounding as per ld_round, which is different from ms_stamp --> Time mapping, which rounds up. See #903.
References nest::Time::Range::MS_PER_STEP.
Referenced by nest::DelayChecker::assert_two_valid_delays_steps, nest::DelayChecker::assert_valid_delay_ms, nest::SynIdDelay::get_delay_ms, nest::GenericConnectorModel< ConnectionT >::used_default_delay.
static delay nest::Time::delay_ms_to_steps(double ms)
References ld_round, nest::Time::Range::STEPS_PER_MS.
Referenced by nest::DelayChecker::assert_valid_delay_ms, nest::ClopathArchivingNode::init_clopath_buffers, nest::SynIdDelay::set_delay_ms, nest::cont_delay_synapse< targetidentifierT >::set_status.
Time::Limit nest::Time::limit(const tic_t &)
nest::Time::Time(tic_t tics)
nest::Time::Time()
Referenced by get_resolution, max, min, neg_inf, pos_inf.
nest::Time::Time(tic t)
nest::Time::Time(step t)
nest::Time::Time(ms t)
nest::Time::Time(ms_stamp t)
void nest::Time::set_to_zero()
References tics.
void nest::Time::advance()
References range, tics, nest::Time::Range::TICS_PER_STEP.
Time nest::Time::succ() const
References tic, tics, nest::Time::Range::TICS_PER_STEP.
Time nest::Time::pred() const
References tic, tics, nest::Time::Range::TICS_PER_STEP.
bool nest::Time::is_finite() const
References LIM_NEG_INF, LIM_POS_INF, tics, nest::Time::LimitPosInf::tics, nest::Time::LimitNegInf::tics.
Referenced by nest::SimulationManager::assert_valid_simtime, nest::DataLoggingRequest::get_recording_interval, nest::DataLoggingRequest::get_recording_offset, nest::run, nest::Device::Parameters_::update_.
bool nest::Time::is_neg_inf() const
References LIM_NEG_INF, tics, nest::Time::LimitNegInf::tics.
Referenced by get_ms, get_steps, operator<<.
bool nest::Time::is_pos_inf() const
References LIM_POS_INF, tics, nest::Time::LimitPosInf::tics.
Referenced by get_ms, get_steps, operator<<.
bool nest::Time::is_grid_time() const
References tics, nest::Time::Range::TICS_PER_STEP.
Referenced by nest::inhomogeneous_poisson_generator::Parameters_::assert_valid_rate_time_and_insert, is_step, nest::run, nest::Device::Parameters_::update_, nest::step_current_generator::Parameters_::validate_time_, nest::step_rate_generator::Parameters_::validate_time_.
bool nest::Time::is_step() const
References is_grid_time, tics.
Referenced by nest::correlation_detector::Parameters_::Parameters_, nest::correlomatrix_detector::Parameters_::Parameters_, nest::correlospinmatrix_detector::Parameters_::Parameters_, nest::noise_generator::Parameters_::Parameters_.
bool nest::Time::is_multiple_of(const Time &divisor) const
References tics.
void nest::Time::range()
References LIM_MAX, LIM_NEG_INF, LIM_POS_INF, tics, nest::Time::Limit::tics, nest::Time::LimitPosInf::tics, nest::Time::LimitNegInf::tics, nest::time_abs.
Referenced by advance, calibrate, operator+=.
void nest::Time::calibrate()
References range.
Referenced by nest::DelayChecker::DelayChecker, nest::correlation_detector::Parameters_::Parameters_, nest::correlomatrix_detector::Parameters_::Parameters_, nest::correlospinmatrix_detector::Parameters_::Parameters_, nest::multimeter::Parameters_::Parameters_, nest::noise_generator::Parameters_::Parameters_, nest::Device::Parameters_::Parameters_.
Time& nest::Time::operator+=(const Time &t)
References range, tics.
tic_t nest::Time::get_tics() const
References tics.
Referenced by nest::poisson_generator_ps::calibrate_time, operator<<.
double nest::Time::get_ms() const
References is_neg_inf, is_pos_inf, LIM_NEG_INF_ms, LIM_POS_INF_ms, nest::Time::Range::MS_PER_TIC, tics.
Referenced by nest::DelayChecker::calibrate, nest::correlation_detector::calibrate_time, nest::correlomatrix_detector::calibrate_time, nest::correlospinmatrix_detector::calibrate_time, nest::noise_generator::calibrate_time, nest::SimulationManager::call_update_, nest::RecordingBackendSIONlib::close_files_, nest::poisson_generator_ps::event_hook, nest::Na::f_numstep, nest::K::f_numstep, nest::RecordingBackendSIONlib::open_files_, operator<<, nest::AMPA::pre_run_hook, nest::GABA::pre_run_hook, nest::NMDA::pre_run_hook, nest::AMPA_NMDA::pre_run_hook, nest::Compartment::pre_run_hook, nest::ac_generator::pre_run_hook, nest::amat2_psc_exp::pre_run_hook, nest::gamma_sup_generator::pre_run_hook, nest::gif_psc_exp::pre_run_hook, nest::gif_psc_exp_multisynapse::pre_run_hook, nest::glif_psc::pre_run_hook, nest::iaf_chs_2007::pre_run_hook, nest::iaf_psc_alpha::pre_run_hook, nest::iaf_psc_alpha_multisynapse::pre_run_hook, nest::iaf_psc_alpha_ps::pre_run_hook, nest::iaf_psc_delta::pre_run_hook, nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_exp::pre_run_hook, nest::iaf_psc_exp_htum::pre_run_hook, nest::iaf_psc_exp_multisynapse::pre_run_hook, nest::iaf_psc_exp_ps::pre_run_hook, nest::iaf_psc_exp_ps_lossless::pre_run_hook, nest::inhomogeneous_poisson_generator::pre_run_hook, nest::mat2_psc_exp::pre_run_hook, nest::noise_generator::pre_run_hook, nest::pp_psc_delta::pre_run_hook, nest::ppd_sup_generator::pre_run_hook, nest::rate_neuron_ipn< TNonlinearities >::pre_run_hook, nest::rate_neuron_opn< TNonlinearities >::pre_run_hook, nest::sinusoidal_poisson_generator::pre_run_hook, nest::SimulationManager::prepare, nest::SimulationManager::print_progress_, nest::RecordingBackendMemory::DeviceData::push_back, nest::stdp_facetshw_synapse_hom< targetidentifierT >::send, nest::izhikevich::Parameters_::set, nest::DelayChecker::set_min_max_delay_, nest::ArchivingNode::set_spiketime, nest::StructuralPlasticityNode::set_spiketime, nest::SimulationManager::set_status, nest::cont_delay_synapse< targetidentifierT >::set_status, nest::iaf_psc_exp::update, nest::volume_transmitter::update, nest::GrowthCurveGaussian::update, nest::GrowthCurveSigmoid::update, nest::iaf_psc_delta::update, nest::izhikevich::update, nest::ppd_sup_generator::update, nest::SimulationManager::update_, nest::RecordingBackendMPI::write, nest::ClopathArchivingNode::write_clopath_history, nest::ClopathArchivingNode::write_LTP_history, nest::UrbanczikArchivingNode< urbanczik_parameters >::write_urbanczik_history.
delay nest::Time::get_steps() const
References is_neg_inf, is_pos_inf, LIM_NEG_INF, LIM_POS_INF, nest::Time::LimitPosInf::steps, nest::Time::LimitNegInf::steps, tics, nest::Time::Range::TICS_PER_STEP_INV, nest::Time::Range::TICS_PER_STEP_RND.
Referenced by nest::SPManager::builder_max_delay, nest::SPManager::builder_min_delay, nest::Connection< targetidentifierT >::calibrate, nest::RecordingBackendSIONlib::enroll, nest::Event::get_rel_delivery_steps, nest::correlation_detector::handle, nest::correlomatrix_detector::handle, nest::correlospinmatrix_detector::handle, nest::EventDeliveryManager::init_moduli, nest::pp_psc_delta::init_state_, nest::spike_train_injector::is_active, nest::StimulationDevice::is_active, nest::PseudoRecordingDevice::is_active, nest::RecordingDevice::is_active, operator<<, nest::amat2_psc_exp::pre_run_hook, nest::gif_psc_exp::pre_run_hook, nest::gif_psc_exp_multisynapse::pre_run_hook, nest::glif_psc::pre_run_hook, nest::iaf_psc_alpha::pre_run_hook, nest::iaf_psc_alpha_multisynapse::pre_run_hook, nest::iaf_psc_alpha_ps::pre_run_hook, nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_exp::pre_run_hook, nest::iaf_psc_exp_htum::pre_run_hook, nest::iaf_psc_exp_multisynapse::pre_run_hook, nest::iaf_psc_exp_ps::pre_run_hook, nest::iaf_psc_exp_ps_lossless::pre_run_hook, nest::mat2_psc_exp::pre_run_hook, nest::pp_psc_delta::pre_run_hook, nest::RecordingBackendMemory::DeviceData::push_back, nest::SimulationManager::run, nest::DelayChecker::set_min_max_delay_, nest::pp_psc_delta::update, nest::pulsepacket_generator::update, nest::spike_generator::update, nest::spike_train_injector::update, nest::SPBuilder::update_delay, nest::ConnectionManager::update_delay_extrema_, nest::EventDeliveryManager::update_moduli.