SLIModule
virtual SLIModule::~SLIModule()
virtual void SLIModule::init(SLIInterpreter *)=0
Initialize the module.
When this function is called, most of the interpreter's facilities are up and running. However, depending on where in the interpreter's bootstrap sequence the module is initialized, not all services may be available.
Referenced by install.
virtual const std::string SLIModule::name() const =0
Return name of the module.
Referenced by SLIInterpreter::addmodule, install.
const std::string SLIModule::commandstring() const
Return sli command sequence to be executed for initialization.
Referenced by SLIInterpreter::addlinkedusermodule, SLIInterpreter::addmodule.
void SLIModule::install(std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
References init, SLIInterpreter::message, name.
Referenced by SLIInterpreter::addlinkedusermodule, SLIInterpreter::addmodule.