Token
friend class Datum
friend class TokenArrayObj
Datum* Token::p
Referenced by assign_by_pointer, assign_by_ref, clear, contains, datum, detach, empty, info, init_by_copy, init_by_pointer, init_by_ref, init_move, TokenArrayObj::insert_move, is_a, move, operator not, operator*, operator->, operator=, operator==, pprint, swap, Token, ~Token.
bool Token::accessed_
Flag for access control.
Is set by getValue() and setValue() via datum().
Referenced by accessed, clear_access_flag, datum, set_access_flag.
Token::~Token()
References p, Datum::removeReference.
Token::Token(const Token &c_s)
References Datum::get_ptr, p.
Token::Token(Datum *p_s=nullptr)
use existing pointer to datum, token takes responsibility of the pointer.
Token::Token(const Datum &d)
copy datum object and store its pointer.
References p.
Token::Token(int)
References p.
Token::Token(unsigned int)
References p.
Token::Token(long)
References p.
Token::Token(bool)
References p.
Token::Token(unsigned long)
References p.
Token::Token(double)
References p.
Token::Token(const char *)
References p.
Token::Token(std::string)
References p.
Token::Token(const std::vector< double > &)
References p.
Token::Token(const std::vector< long > &)
References p.
Token::Token(const std::vector< size_t > &)
References p.
Token::operator size_t() const
References getValue< long >.
Token::operator long() const
References getValue< long >.
Token::operator double() const
References getValue< double >.
Token::operator bool() const
References getValue< bool >.
Token::operator std::string() const
References getValue< std::string >.
void Token::detach()
If the contained datum has more than one reference, clone it, so it can be modified.
References Datum::clone, Datum::numReferences, p, Datum::removeReference.
void Token::move(Token &c)
References p, Datum::removeReference.
Referenced by SLIArrayModule::ArrayloadFunction::execute, DictconstructFunction::execute, TrieInfoFunction::execute, Cva_tFunction::execute, TypeFunction::execute, Dictionary::insert_move, TypeTrie::insert_move, Parser::operator(), Scanner::operator(), DictionaryStack::top.
void Token::init_move(Token &rhs)
Initialize the token by moving a datum from another token.
This function assumes that the token does not point to a valid datum and that the argument token does point to a valid datum. This function does not change the reference count of the datum.
References p.
void Token::init_by_copy(const Token &rhs)
Initialize the token by moving a datum from another token.
This function assumes that the token does not point to a valid datum and that the argument token does point to a valid datum. This function does not change the reference count of the datum.
References Datum::get_ptr, p.
void Token::init_by_ref(const Token &rhs)
Initialize the token with a reference.
This function assumes that the token does not point to a valid datum and that the argument token does point to a valid datum. This function increases the reference count of the argument.
References Datum::addReference, p.
void Token::init_by_pointer(Datum *rhs)
Initialize the token with a datum pointer.
This function assumes that the token does not point to a valid datum. The function assumes that the datum is new and DOES NOT increases its reference count.
References p.
void Token::assign_by_ref(const Token &rhs)
References Datum::get_ptr, p, Datum::removeReference.
Referenced by TrietypeFunction::execute.
void Token::assign_by_pointer(Datum *rhs)
References Datum::addReference, p, Datum::removeReference.
void Token::swap(Token &c)
References p.
Referenced by nest::NestModule::Cva_CFunction::execute, Cvx_aFunction::execute, Cvlit_nFunction::execute, Cvlit_pFunction::execute, Cvlp_pFunction::execute, Cvn_sFunction::execute, Cvn_lFunction::execute, Cvi_sFunction::execute, Cvd_sFunction::execute, IntegerFunction::execute, DoubleFunction::execute, TypeTrie::getalternative.
void Token::clear()
References p, Datum::removeReference.
Referenced by Scanner::operator(), operator=.
bool Token::contains(const Datum &d) const
References Datum::equals, p.
Referenced by StopFunction::execute, IparsestdinFunction::execute, ParsestdinFunction::execute, IparseFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, Parser::operator().
bool Token::empty() const
References p.
Referenced by append_property, append_property< std::vector< double > >, append_property< std::vector< long > >, nest::ModelManager::copy_model, KeysFunction::execute, nest::ConnectionManager::get_connections, nest::ModelManager::get_synapse_model_id, initialize_property_array, initialize_property_doublevector, initialize_property_intvector, SLIInterpreter::raiseagain, nest::ModelManager::set_model_defaults, updateValue, valid.
bool Token::operator not() const
References p.
Datum * Token::datum() const
References accessed_, p.
Referenced by accumulate_property, SLIInterpreter::addlinkedusermodule, SLIInterpreter::addmodule, append_property, append_property< std::vector< double > >, append_property< std::vector< long > >, SLIArrayModule::IMapFunction::backtrace, SLIArrayModule::IMap_ivFunction::backtrace, SLIArrayModule::IMap_dvFunction::backtrace, SLIArrayModule::IMapThreadFunction::backtrace, SLIArrayModule::IMapIndexedFunction::backtrace, SLIArrayModule::Iforall_ivFunction::backtrace, SLIArrayModule::Iforall_dvFunction::backtrace, IiterateFunction::backtrace, IloopFunction::backtrace, IrepeatFunction::backtrace, IforFunction::backtrace, IforallarrayFunction::backtrace, IforallindexedarrayFunction::backtrace, IforallindexedstringFunction::backtrace, IforallstringFunction::backtrace, nest::ConnParameter::create, nest::AbstractLayer::create_layer, nest::NestModule::create_mask, nest::NestModule::create_parameter, eq_execute, StrFunction::execute, FilesystemModule::FileNamesFunction::execute, FilesystemModule::CompareFilesFunction::execute, OOSupportModule::CallMemberFunction::execute, Processes::Sysexec_aFunction::execute, Processes::WaitPIDFunction::execute, Processes::KillFunction::execute, Processes::Dup2_is_isFunction::execute, Processes::Dup2_os_osFunction::execute, Processes::Dup2_is_osFunction::execute, Processes::Dup2_os_isFunction::execute, Processes::AvailableFunction::execute, Processes::MkfifoFunction::execute, Processes::SetNonblockFunction::execute, Processes::Isatty_isFunction::execute, Processes::Isatty_osFunction::execute, MathLinkPutStringFunction::execute, XIfstreamFunction::execute, IfstreamFunction::execute, OfstreamFunction::execute, OfsopenFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IClearFunction::execute, OClearFunction::execute, IFailFunction::execute, OGoodFunction::execute, Cvx_fFunction::execute, IEofFunction::execute, OEofFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, NametypeFunction::execute, ProceduretypeFunction::execute, LitproceduretypeFunction::execute, FunctiontypeFunction::execute, CallbacktypeFunction::execute, TrietypeFunction::execute, SLIArrayModule::MapFunction::execute, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::MapThreadFunction::execute, SLIArrayModule::IMapThreadFunction::execute, SLIArrayModule::MapIndexedFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, SLIArrayModule::RangeFunction::execute, SLIArrayModule::ArraystoreFunction::execute, SLIArrayModule::ArrayloadFunction::execute, SLIArrayModule::ReverseFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::FlattenFunction::execute, SLIArrayModule::TransposeFunction::execute, SLIArrayModule::PartitionFunction::execute, SLIArrayModule::ValidFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::DoubleVector2ArrayFunction::execute, SLIArrayModule::IntVector2ArrayFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Add_i_ivFunction::execute, SLIArrayModule::Neg_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Mul_i_ivFunction::execute, SLIArrayModule::Mul_d_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Add_d_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Mul_d_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Neg_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, SLIArrayModule::Length_dvFunction::execute, SLIArrayModule::Length_ivFunction::execute, SLIArrayModule::Get_iv_iFunction::execute, SLIArrayModule::Get_iv_ivFunction::execute, SLIArrayModule::Get_dv_ivFunction::execute, SLIArrayModule::Get_dv_iFunction::execute, SLIArrayModule::Put_dv_i_dFunction::execute, SLIArrayModule::Put_iv_i_iFunction::execute, SLIArrayModule::Zeros_ivFunction::execute, SLIArrayModule::Zeros_dvFunction::execute, SLIArrayModule::Ones_dvFunction::execute, SLIArrayModule::Ones_ivFunction::execute, SLIArrayModule::ArangeFunction::execute, SLIArrayModule::Forall_ivFunction::execute, SLIArrayModule::Forall_dvFunction::execute, SLIArrayModule::Iforall_ivFunction::execute, SLIArrayModule::Iforall_dvFunction::execute, IsetcallbackFunction::execute, IiterateFunction::execute, IloopFunction::execute, IrepeatFunction::execute, IforFunction::execute, IforallarrayFunction::execute, IforallindexedarrayFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute, LoopFunction::execute, IfFunction::execute, IfelseFunction::execute, RepeatFunction::execute, IparseFunction::execute, DefFunction::execute, SetFunction::execute, LoadFunction::execute, LookupFunction::execute, ForFunction::execute, Forall_aFunction::execute, Forallindexed_aFunction::execute, Forallindexed_sFunction::execute, Forall_sFunction::execute, RaiseerrorFunction::execute, Token_sFunction::execute, Token_isFunction::execute, Symbol_sFunction::execute, SetGuardFunction::execute, MessageFunction::execute, SetVerbosityFunction::execute, Get_aFunction::execute, Get_a_aFunction::execute, Get_pFunction::execute, Get_lpFunction::execute, Append_aFunction::execute, Append_pFunction::execute, Append_sFunction::execute, Prepend_aFunction::execute, Prepend_pFunction::execute, Prepend_sFunction::execute, Join_sFunction::execute, Join_aFunction::execute, Join_pFunction::execute, Insert_sFunction::execute, Insert_aFunction::execute, InsertElement_sFunction::execute, InsertElement_aFunction::execute, Replace_sFunction::execute, Replace_aFunction::execute, Erase_sFunction::execute, Erase_aFunction::execute, Erase_pFunction::execute, Length_sFunction::execute, Length_aFunction::execute, Length_pFunction::execute, Length_lpFunction::execute, Capacity_aFunction::execute, Size_aFunction::execute, Reserve_aFunction::execute, Resize_aFunction::execute, Empty_aFunction::execute, References_aFunction::execute, Shrink_aFunction::execute, Capacity_sFunction::execute, Size_sFunction::execute, Reserve_sFunction::execute, Resize_sFunction::execute, Empty_sFunction::execute, Getinterval_sFunction::execute, Getinterval_aFunction::execute, Cvx_aFunction::execute, Cvlit_nFunction::execute, Cvlit_pFunction::execute, Cvlp_pFunction::execute, Cvn_sFunction::execute, Cvn_lFunction::execute, Cvi_sFunction::execute, Cvd_sFunction::execute, Get_sFunction::execute, Put_sFunction::execute, Put_aFunction::execute, Put_pFunction::execute, Put_lpFunction::execute, Search_sFunction::execute, Search_aFunction::execute, IrepeatanyFunction::execute, DictputFunction::execute, DictgetFunction::execute, DictbeginFunction::execute, DictinfoFunction::execute, DicttopinfoFunction::execute, WhoFunction::execute, DictconstructFunction::execute, Length_dFunction::execute, Empty_DFunction::execute, CleardictFunction::execute, ClonedictFunction::execute, UndefFunction::execute, KnownFunction::execute, Cva_dFunction::execute, KeysFunction::execute, ValuesFunction::execute, RestoredstackFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, Add_diFunction::execute, Add_iiFunction::execute, Add_idFunction::execute, Add_ddFunction::execute, Sub_diFunction::execute, Sub_iiFunction::execute, Sub_idFunction::execute, Sub_ddFunction::execute, Mul_diFunction::execute, Mul_iiFunction::execute, Mul_idFunction::execute, Mul_ddFunction::execute, Div_diFunction::execute, Div_iiFunction::execute, Div_idFunction::execute, Div_ddFunction::execute, Mod_iiFunction::execute, Sin_dFunction::execute, Asin_dFunction::execute, Cos_dFunction::execute, Acos_dFunction::execute, Exp_dFunction::execute, Ln_dFunction::execute, Log_dFunction::execute, Sqr_dFunction::execute, Sqrt_dFunction::execute, Pow_ddFunction::execute, Pow_diFunction::execute, Modf_dFunction::execute, Frexp_dFunction::execute, Ldexp_diFunction::execute, Dexp_iFunction::execute, Abs_iFunction::execute, Abs_dFunction::execute, Neg_iFunction::execute, Neg_dFunction::execute, Inv_dFunction::execute, EqFunction::execute, NeqFunction::execute, AndFunction::execute, OrFunction::execute, And_iiFunction::execute, Or_iiFunction::execute, XorFunction::execute, Not_bFunction::execute, Not_iFunction::execute, Geq_iiFunction::execute, Geq_idFunction::execute, Geq_diFunction::execute, Geq_ddFunction::execute, Leq_iiFunction::execute, Leq_idFunction::execute, Leq_diFunction::execute, Leq_ddFunction::execute, Gt_iiFunction::execute, Gt_ddFunction::execute, Gt_idFunction::execute, Gt_diFunction::execute, Gt_ssFunction::execute, Lt_iiFunction::execute, Lt_ddFunction::execute, Lt_idFunction::execute, Lt_diFunction::execute, Lt_ssFunction::execute, IntegerFunction::execute, DoubleFunction::execute, UnitStep_iFunction::execute, UnitStep_dFunction::execute, UnitStep_iaFunction::execute, UnitStep_daFunction::execute, Round_dFunction::execute, Floor_dFunction::execute, Ceil_dFunction::execute, Max_i_iFunction::execute, Max_i_dFunction::execute, Max_d_iFunction::execute, Max_d_dFunction::execute, Min_i_iFunction::execute, Min_i_dFunction::execute, Min_d_iFunction::execute, Min_d_dFunction::execute, RegexpModule::RegcompFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute, NpopFunction::execute, IndexFunction::execute, RollFunction::execute, CopyFunction::execute, RestoreestackFunction::execute, RestoreostackFunction::execute, SLIStartup::GetenvFunction::execute, TrieFunction::execute, TrieInfoFunction::execute, AddtotrieFunction::execute, Cva_tFunction::execute, Cvt_aFunction::execute, nest::Time::ms::fromtoken, get_double_in_range, get_long_in_range, SLIInterpreter::getcurrentname, getValue, getValue< bool >, getValue< double >, getValue< long >, getValue< std::string >, Processes::init, neststartup, Parser::operator(), SLIInterpreter::print_error, provide_property, nest::FreeLayer< D >::set_status, setValue, setValue< bool >, setValue< double >, setValue< long >, setValue< std::string >, SLIInterpreter::stack_backtrace, Processes::systemerror, nest::updateValueParam.
bool Token::valid() const
References empty.
Datum * Token::operator->() const
References p.
Datum & Token::operator*() const
References p.
const std::type_info & Token::type() const
Referenced by info.
Token & Token::operator=(const Token &c_s)
References clear, Datum::get_ptr, p, Datum::removeReference.
Token & Token::operator=(Datum *p_s)
References p, Datum::removeReference.
bool Token::operator==(const Token &t) const
References Datum::equals, p.
bool Token::operator!=(const Token &t) const
void Token::info(std::ostream &) const
References Datum::info, p, type.
void Token::pprint(std::ostream &) const
References p, Datum::pprint.
Referenced by SLIInterpreter::debug_commandline, TokenStack::dump, SLIArrayModule::IMapFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::IMapIndexedFunction::execute, IforallindexedstringFunction::execute, IforallstringFunction::execute.
void Token::clear_access_flag()
Clear accessed flag.
References accessed_.
void Token::set_access_flag() const
References accessed_.
bool Token::accessed() const
Check for access.
Access control does not differentiate between read and write access, and relies on getValue<>, setValue<> to use datum() to access the data in the Token. The access flag should be cleared before entering the code for which access is to be checked.
References accessed_.
bool Token::is_a() const
Check whether Token contains a Datum of a given type.
true if Token is of type given by template parameter.
References p.
Referenced by nest::AbstractLayer::create_layer, nest::weight_recorder::Parameters_::set, nest::FreeLayer< D >::set_status.
bool Token::matches_as_string(const Token &rhs) const
Returns true if token equals rhs as string.
The main purpose of this method is to allow seamless comparison of LiteralDatum and StringDatum tokens.
References getValue< std::string >.
Referenced by nest::NodeManager::get_nodes.