FunctionDatum
sli::pool FunctionDatum::memory
Referenced by operator delete, operator new.
Name FunctionDatum::name
Referenced by execute, getname, info, operator=, print.
std::string FunctionDatum::deprecation_info_
If not empty string, it should contain string with version for which feature is deprecated.
Referenced by execute.
bool FunctionDatum::deprecation_warning_issued_
Referenced by execute.
Datum * FunctionDatum::clone() const override
Virtual copy constructor.
Use this function to lazily copy a datum.
Datum * FunctionDatum::get_ptr() override
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
The prefix const indicates that the pointer should be trated as const because changes affect all other references as well.
References Datum::addReference.
SLIFunction const & FunctionDatum::operator=(SLIFunction const &f)
References Datum::action, name.
FunctionDatum::FunctionDatum(FunctionDatum const &fd)
References Datum::set_executable.
FunctionDatum::FunctionDatum(Name const &n, SLIFunction const *f, const std::string &deprecation_info)
References Datum::action, Datum::set_executable.
void FunctionDatum::execute(SLIInterpreter *i) override
References Datum::action, deprecation_info_, deprecation_warning_issued_, SLIFunction::execute, SLIInterpreter::M_DEPRECATED, SLIInterpreter::message, name, Name::toString.
Referenced by FunctiontypeFunction::execute.
void FunctionDatum::print(std::ostream &o) const override
References name.
Referenced by pprint.
void FunctionDatum::pprint(std::ostream &o) const override
References print.
Referenced by FunctiontypeFunction::execute.
void FunctionDatum::info(std::ostream &out) const override
References name.
bool FunctionDatum::equals(Datum const *dat) const override
References Datum::action.
const Name & FunctionDatum::getname() const
References name.
Referenced by SLIInterpreter::getcurrentname.
void FunctionDatum::backtrace(SLIInterpreter *, int) const
References Datum::action, SLIFunction::backtrace.
Referenced by SLIInterpreter::stack_backtrace.
static void * FunctionDatum::operator new(size_t size)
References sli::pool::alloc, memory.
static void FunctionDatum::operator delete(void *p, size_t size)
References sli::pool::free, memory.