nest::GrowthCurve
const Name nest::GrowthCurve::name_
Referenced by get_name, is.
virtual nest::GrowthCurve::~GrowthCurve()
virtual void nest::GrowthCurve::get(DictionaryDatum &d) const =0
virtual void nest::GrowthCurve::set(const DictionaryDatum &d)=0
Referenced by nest::SynapticElement::operator=, nest::SynapticElement::set, nest::SynapticElement::SynapticElement.
virtual double nest::GrowthCurve::update(double t, double t_minus, double Ca_minus, double z, double tau_Ca, double growth_rate) const =0
virtual bool nest::GrowthCurve::is(Name n)
References nest::names::n, name_.
Name nest::GrowthCurve::get_name()
References name_.
Referenced by nest::SynapticElement::SynapticElement.
nest::GrowthCurve::GrowthCurve(const Name name)