nest::SendBufferPosition
thread nest::SendBufferPosition::begin_rank_
Referenced by rank_to_index_.
thread nest::SendBufferPosition::end_rank_
Referenced by rank_to_index_.
thread nest::SendBufferPosition::max_size_
Referenced by rank_to_index_.
size_t nest::SendBufferPosition::num_spike_data_written_
Referenced by are_all_chunks_filled, increase.
size_t nest::SendBufferPosition::send_recv_count_per_rank_
Referenced by are_all_chunks_filled.
std::vector< thread > nest::SendBufferPosition::idx_
Referenced by are_all_chunks_filled, idx, increase, SendBufferPosition.
std::vector< thread > nest::SendBufferPosition::begin_
Referenced by begin, SendBufferPosition.
std::vector< thread > nest::SendBufferPosition::end_
Referenced by end, SendBufferPosition.
thread nest::SendBufferPosition::rank_to_index_(const thread rank) const
References begin_rank_, end_rank_, max_size_.
Referenced by begin, end, idx, increase.
nest::SendBufferPosition::SendBufferPosition(const AssignedRanks &assigned_ranks, const unsigned int send_recv_count_per_rank)
References nest::AssignedRanks::begin, begin_, nest::AssignedRanks::end, end_, idx_, nest::AssignedRanks::max_size, nest::AssignedRanks::size.
unsigned int nest::SendBufferPosition::idx(const thread rank) const
Returns current index of specified rank in MPI buffer.
References idx_, rank_to_index_.
Referenced by nest::EventDeliveryManager::collocate_spike_data_buffers_, nest::EventDeliveryManager::collocate_target_data_buffers_, is_chunk_filled, nest::EventDeliveryManager::set_end_and_invalid_markers_.
unsigned int nest::SendBufferPosition::begin(const thread rank) const
Returns begin index of specified rank in MPI buffer.
References begin_, rank_to_index_.
Referenced by nest::EventDeliveryManager::collocate_target_data_buffers_, nest::EventDeliveryManager::set_end_and_invalid_markers_.
unsigned int nest::SendBufferPosition::end(const thread rank) const
Returns end index of specified rank in MPI buffer.
References end_, rank_to_index_.
Referenced by nest::EventDeliveryManager::collocate_target_data_buffers_, is_chunk_filled, nest::EventDeliveryManager::reset_complete_marker_spike_data_, nest::EventDeliveryManager::set_complete_marker_spike_data_, nest::EventDeliveryManager::set_complete_marker_target_data_, nest::EventDeliveryManager::set_end_and_invalid_markers_.
bool nest::SendBufferPosition::is_chunk_filled(const thread rank) const
Returns whether the part of the buffer on the specified rank has been filled.
rank Rank denoting which part of the buffer we check
References end, idx.
Referenced by nest::EventDeliveryManager::collocate_spike_data_buffers_, nest::EventDeliveryManager::collocate_target_data_buffers_.
bool nest::SendBufferPosition::are_all_chunks_filled() const
Returns whether the parts of the MPI buffer assigned to this thread has been filled.
References idx_, num_spike_data_written_, send_recv_count_per_rank_.
Referenced by nest::EventDeliveryManager::collocate_spike_data_buffers_, nest::EventDeliveryManager::collocate_target_data_buffers_.
void nest::SendBufferPosition::increase(const thread rank)
References idx_, num_spike_data_written_, rank_to_index_.
Referenced by nest::EventDeliveryManager::collocate_spike_data_buffers_, nest::EventDeliveryManager::collocate_target_data_buffers_.