nest::StimulationDevice
Type
struct nest::StimulationDevice::Parameters_ nest::StimulationDevice::P_
Referenced by get_status, set_status.
synindex nest::StimulationDevice::first_syn_id_
Synapse type of the first outgoing connection made by the Device.
Used to check that devices connect using only a single synapse type, see #481 and #737. Since this value must survive resets, it is stored here, even though it is an implementation detail.
DictionaryDatum nest::StimulationDevice::backend_params_
Referenced by get_status, set_status.
nest::StimulationDevice::StimulationDevice()
References nest::invalid_synindex.
nest::StimulationDevice::StimulationDevice(StimulationDevice const &)
nest::StimulationDevice::~StimulationDevice() override=default
bool nest::StimulationDevice::is_active(const Time &) const override
Determine whether device is active.
The argument is the value of the simulation time. class comment for details.
References CURRENT_GENERATOR, DELAYED_RATE_CONNECTION_GENERATOR, DOUBLE_DATA_GENERATOR, nest::Time::get_steps.
Referenced by nest::ac_generator::update, nest::dc_generator::update, nest::gamma_sup_generator::update, nest::inhomogeneous_poisson_generator::update, nest::mip_generator::update, nest::noise_generator::update, nest::poisson_generator::update, nest::ppd_sup_generator::update, nest::pulsepacket_generator::update, nest::sinusoidal_poisson_generator::update, nest::spike_generator::update, nest::step_rate_generator::update, nest::step_current_generator::update.
void nest::StimulationDevice::get_status(DictionaryDatum &d) const override
References backend_params_, nest::names::element_type, nest::StimulationDevice::Parameters_::get, nest::Node::get_node_id, nest::Device::get_status, P_, nest::names::stimulator.
Referenced by nest::ac_generator::get_status, nest::dc_generator::get_status, nest::gamma_sup_generator::get_status, nest::inhomogeneous_poisson_generator::get_status, nest::mip_generator::get_status, nest::noise_generator::get_status, nest::poisson_generator::get_status, nest::poisson_generator_ps::get_status, nest::ppd_sup_generator::get_status, nest::pulsepacket_generator::get_status, nest::sinusoidal_poisson_generator::get_status, nest::spike_dilutor::get_status, nest::spike_generator::get_status, nest::step_current_generator::get_status, nest::step_rate_generator::get_status.
void nest::StimulationDevice::set_status(const DictionaryDatum &) override
References backend_params_, nest::IOManager::enroll_stimulator, nest::Node::get_node_id, nest::KernelManager::io_manager, nest::kernel, Name::lookup, P_, nest::StimulationDevice::Parameters_::set, nest::Device::set_status, nest::StimulationDevice::Parameters_::stimulus_source_.
Referenced by nest::ac_generator::set_status, nest::dc_generator::set_status, nest::gamma_sup_generator::set_status, nest::inhomogeneous_poisson_generator::set_status, nest::mip_generator::set_status, nest::noise_generator::set_status, nest::poisson_generator::set_status, nest::poisson_generator_ps::set_status, nest::ppd_sup_generator::set_status, nest::pulsepacket_generator::set_status, nest::sinusoidal_poisson_generator::set_status, nest::spike_dilutor::set_status, nest::spike_generator::set_status, nest::step_current_generator::set_status, nest::step_rate_generator::set_status.
bool nest::StimulationDevice::has_proxies() const override
Returns true if the node has proxies on remote threads.
This is used to discriminate between different types of nodes, when adding new nodes to the network.
Name nest::StimulationDevice::get_element_type() const override
Return the element type of the node.
The returned Name is a free label describing the class of network elements a node belongs to. Currently used values are "neuron", "recorder", "stimulator", and "other", which are all defined as static Name objects in the names namespace. This function is overwritten with a corresponding value in the derived classes
References nest::names::stimulator.
void nest::StimulationDevice::pre_run_hook() override
Set internal variables before calls to SimulationManager::run()
References nest::Device::pre_run_hook.
Referenced by nest::ac_generator::pre_run_hook, nest::dc_generator::pre_run_hook, nest::gamma_sup_generator::pre_run_hook, nest::inhomogeneous_poisson_generator::pre_run_hook, nest::mip_generator::pre_run_hook, nest::noise_generator::pre_run_hook, nest::poisson_generator::pre_run_hook, nest::poisson_generator_ps::pre_run_hook, nest::ppd_sup_generator::pre_run_hook, nest::pulsepacket_generator::pre_run_hook, nest::sinusoidal_poisson_generator::pre_run_hook, nest::spike_generator::pre_run_hook, nest::step_current_generator::pre_run_hook, nest::step_rate_generator::pre_run_hook.
void nest::StimulationDevice::enforce_single_syn_type(synindex)
Throws IllegalConnection if synapse id differs from initial synapse id.
References nest::invalid_synindex.
Referenced by nest::ac_generator::send_test_event, nest::dc_generator::send_test_event, nest::gamma_sup_generator::send_test_event, nest::inhomogeneous_poisson_generator::send_test_event, nest::mip_generator::send_test_event, nest::noise_generator::send_test_event, nest::poisson_generator::send_test_event, nest::poisson_generator_ps::send_test_event, nest::ppd_sup_generator::send_test_event, nest::pulsepacket_generator::send_test_event, nest::sinusoidal_poisson_generator::send_test_event, nest::spike_dilutor::send_test_event, nest::spike_generator::send_test_event, nest::step_current_generator::send_test_event, nest::step_rate_generator::send_test_event.
virtual Type nest::StimulationDevice::get_type() const
const std::string & nest::StimulationDevice::get_label() const
Referenced by nest::StimulationBackendMPI::get_port.
virtual void nest::StimulationDevice::set_data_from_stimulation_backend(std::vector< double > &)
void nest::StimulationDevice::update(Time const &, const long, const long) override
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to. Time network time at beginning of time slice. long initial step inside time slice long post-final step inside time slice
virtual void nest::Device::init_buffers()
Reset buffers.
Referenced by nest::ac_generator::init_buffers_, nest::dc_generator::init_buffers_, nest::gamma_sup_generator::init_buffers_, nest::inhomogeneous_poisson_generator::init_buffers_, nest::mip_generator::init_buffers_, nest::noise_generator::init_buffers_, nest::poisson_generator::init_buffers_, nest::ppd_sup_generator::init_buffers_, nest::pulsepacket_generator::init_buffers_, nest::sinusoidal_poisson_generator::init_buffers_, nest::spike_generator::init_buffers_, nest::step_current_generator::init_buffers_, nest::step_rate_generator::init_buffers_.
virtual void nest::Device::init_state()
Reset dynamic state to that of model.
Referenced by nest::ac_generator::init_state_, nest::dc_generator::init_state_, nest::gamma_sup_generator::init_state_, nest::inhomogeneous_poisson_generator::init_state_, nest::mip_generator::init_state_, nest::noise_generator::init_state_, nest::poisson_generator::init_state_, nest::poisson_generator_ps::init_state_, nest::ppd_sup_generator::init_state_, nest::pulsepacket_generator::init_state_, nest::sinusoidal_poisson_generator::init_state_, nest::spike_generator::init_state_, nest::step_current_generator::init_state_, nest::step_rate_generator::init_state_.
void nest::Device::pre_run_hook()
Set internal variables before calls to SimulationManager::run()
virtual void nest::Node::pre_run_hook()=0
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
void nest::StimulationDevice::set_initialized_() final
References nest::IOManager::enroll_stimulator, nest::KernelManager::io_manager, nest::kernel.