nest::BaseRandomGenerator
virtual nest::BaseRandomGenerator::~BaseRandomGenerator()
virtual unsigned long nest::BaseRandomGenerator::operator()(std::uniform_int_distribution< unsigned long > &d)=0
Calls the provided distribution with the wrapped RNG engine.
One operator per distribution must be defined. d Distribution that will be called.
virtual double nest::BaseRandomGenerator::operator()(std::uniform_real_distribution<> &d)=0
virtual unsigned long nest::BaseRandomGenerator::operator()(std::poisson_distribution< unsigned long > &d)=0
virtual double nest::BaseRandomGenerator::operator()(std::normal_distribution<> &d)=0
virtual double nest::BaseRandomGenerator::operator()(std::lognormal_distribution<> &d)=0
virtual unsigned long nest::BaseRandomGenerator::operator()(std::binomial_distribution< unsigned long > &d)=0
virtual double nest::BaseRandomGenerator::operator()(std::gamma_distribution<> &d)=0
virtual double nest::BaseRandomGenerator::operator()(std::exponential_distribution<> &d)=0
virtual unsigned long nest::BaseRandomGenerator::operator()(std::discrete_distribution< unsigned long > &d)=0
virtual unsigned long nest::BaseRandomGenerator::operator()(std::uniform_int_distribution< unsigned long > &d, std::uniform_int_distribution< unsigned long >::param_type &p)=0
Calls the provided distribution with the wrapped RNG engine, using provided distribution parameters.
One operator per distribution must be defined. d Distribution that will be called. p Distribution parameters.
virtual double nest::BaseRandomGenerator::operator()(std::uniform_real_distribution<> &d, std::uniform_real_distribution<>::param_type &p)=0
virtual unsigned long nest::BaseRandomGenerator::operator()(std::poisson_distribution< unsigned long > &d, std::poisson_distribution< unsigned long >::param_type &p)=0
virtual double nest::BaseRandomGenerator::operator()(std::normal_distribution<> &d, std::normal_distribution<>::param_type &p)=0
virtual double nest::BaseRandomGenerator::operator()(std::lognormal_distribution<> &d, std::lognormal_distribution<>::param_type &p)=0
virtual unsigned long nest::BaseRandomGenerator::operator()(std::binomial_distribution< unsigned long > &d, std::binomial_distribution< unsigned long >::param_type &p)=0
virtual double nest::BaseRandomGenerator::operator()(std::gamma_distribution<> &d, std::gamma_distribution<>::param_type &p)=0
virtual double nest::BaseRandomGenerator::operator()(std::exponential_distribution<> &d, std::exponential_distribution<>::param_type &p)=0
virtual unsigned long nest::BaseRandomGenerator::operator()(std::discrete_distribution< unsigned long > &d, std::discrete_distribution< unsigned long >::param_type &p)=0
virtual double nest::BaseRandomGenerator::drand()=0
Uses the wrapped RNG engine to draw a double from a uniform distribution in the range [0, 1).
Referenced by nest::ConnectionCreator::connect_to_target_, nest::mip_generator::event_hook, nest::poisson_generator_ps::event_hook, nest::BernoulliBuilder::inner_connect_, nest::gainfunction_erfc::operator(), nest::gainfunction_ginzburg::operator(), nest::bernoulli_synapse< targetidentifierT >::send, nest::quantal_stp_synapse< targetidentifierT >::send, nest::UniformParameter::value, nest::ExponentialParameter::value.
virtual unsigned long nest::BaseRandomGenerator::ulrand(unsigned long N)=0
Uses the wrapped RNG engine to draw an unsigned long from a uniform distribution in the range [0, N).
N Maximum value that can be drawn.
Referenced by nest::FixedOutDegreeBuilder::connect_, nest::FixedTotalNumberBuilder::connect_, nest::SymmetricBernoulliBuilder::connect_, nest::ConnectionCreator::fixed_indegree_, nest::SPManager::global_shuffle, nest::FixedInDegreeBuilder::inner_connect_, nest::UniformIntParameter::value.