nest::Compartment
double nest::Compartment::xx_
double nest::Compartment::yy_
long nest::Compartment::comp_index
Referenced by nest::CompTree::add_compartment, nest::CompTree::get_compartment, nest::cm_default::get_status, nest::CompTree::print_tree.
long nest::Compartment::p_index
Referenced by nest::cm_default::get_status, nest::CompTree::set_parents.
Compartment* nest::Compartment::parent
Referenced by nest::CompTree::print_tree, nest::CompTree::set_parents, nest::CompTree::solve_matrix_downsweep.
std::vector< Compartment > nest::Compartment::children
Referenced by nest::CompTree::add_compartment, nest::CompTree::get_compartment, nest::CompTree::solve_matrix_downsweep, nest::CompTree::solve_matrix_upsweep.
CompartmentCurrents nest::Compartment::compartment_currents
Referenced by nest::cm_default::add_receptor_, Compartment, nest::cm_default::get_status.
RingBuffer nest::Compartment::currents
Referenced by nest::cm_default::handle.
double nest::Compartment::v_comp
Referenced by Compartment.
double nest::Compartment::ca
Referenced by Compartment, nest::CompTree::print_tree.
double nest::Compartment::gc
Referenced by Compartment, nest::CompTree::print_tree.
double nest::Compartment::gl
Referenced by Compartment, nest::CompTree::print_tree.
double nest::Compartment::el
Referenced by Compartment, nest::CompTree::print_tree.
double nest::Compartment::gg0
double nest::Compartment::ca__div__dt
double nest::Compartment::gl__div__2
double nest::Compartment::gc__div__2
double nest::Compartment::gl__times__el
double nest::Compartment::ff
double nest::Compartment::gg
double nest::Compartment::hh
int nest::Compartment::n_passed
Referenced by nest::CompTree::solve_matrix_downsweep.
nest::Compartment::Compartment(const long compartment_index, const long parent_index)
References compartment_currents, el, v_comp.
nest::Compartment::Compartment(const long compartment_index, const long parent_index, const DictionaryDatum &compartment_params)
References nest::names::C_m, ca, compartment_currents, nest::names::e_L, el, nest::names::g_C, nest::names::g_L, gc, gl, v_comp.
nest::Compartment::~Compartment()
void nest::Compartment::pre_run_hook()
References nest::names::dt, nest::Time::get_ms, nest::Time::get_resolution.
std::map< Name, double * > nest::Compartment::get_recordables()
References nest::names::recordables.
void nest::Compartment::construct_matrix_element(const long lag)
void nest::Compartment::gather_input(const std::pair< double, double > &in)
Referenced by nest::CompTree::solve_matrix_downsweep.
std::pair< double, double > nest::Compartment::io()
Referenced by nest::CompTree::solve_matrix_downsweep.
double nest::Compartment::calc_v(const double v_in)
Referenced by nest::CompTree::solve_matrix_upsweep.