IAFPropagatorExp
IAFPropagatorExp::IAFPropagatorExp()
Empty constructor needed for initialization of buffers.
IAFPropagatorExp::IAFPropagatorExp(double tau_syn, double tau_m, double c_m)
tau_syn Time constant of synaptic current in ms tau_m Membrane time constant in ms c_m Membrane capacitance in pF
double IAFPropagatorExp::evaluate(double h) const
Calculate propagator mapping I_syn to V_m for given time step.
h time step P_VI
References IAFPropagator::evaluate_P32_.
Referenced by nest::gif_psc_exp::pre_run_hook, nest::gif_psc_exp_multisynapse::pre_run_hook, nest::iaf_psc_exp::pre_run_hook, nest::iaf_psc_exp_htum::pre_run_hook, nest::iaf_psc_exp_multisynapse::pre_run_hook.