IAFPropagatorAlpha
IAFPropagatorAlpha::IAFPropagatorAlpha()
Empty constructor needed for initialization of buffers.
IAFPropagatorAlpha::IAFPropagatorAlpha(double tau_syn, double tau_m, double c_m)
tau_syn Time constant of synaptic current in ms tau Membrane time constant in ms Membrane capacitance in pF
std::tuple< double, double > IAFPropagatorAlpha::evaluate(double h) const
Calculate propagator mapping I_syn and dI_syn to V_m for given time step.
h time step tuple with P_VdI and P_VI
References IAFPropagator::beta_, IAFPropagator::evaluate_P32_, IAFPropagator::gamma_, IAFPropagator::h_min_regular_, IAFPropagator::inv_c_m_, IAFPropagator::inv_tau_m_.
Referenced by nest::glif_psc::pre_run_hook, nest::iaf_psc_alpha::pre_run_hook, nest::iaf_psc_alpha_multisynapse::pre_run_hook.