nest::RateConnectionDelayed
typedef CommonSynapseProperties nest::RateConnectionDelayed< targetidentifierT >::CommonPropertiesType
typedef Connection< targetidentifierT > nest::RateConnectionDelayed< targetidentifierT >::ConnectionBase
constexpr ConnectionModelProperties nest::RateConnectionDelayed< targetidentifierT >::properties
double nest::RateConnectionDelayed< targetidentifierT >::weight_
connection weight
Referenced by nest::RateConnectionDelayed< targetidentifierT >::send, nest::RateConnectionDelayed< targetidentifierT >::set_weight.
nest::RateConnectionDelayed< targetidentifierT >::RateConnectionDelayed()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
SecondaryEvent * nest::RateConnectionDelayed< targetidentifierT >::get_secondary_event()
void nest::RateConnectionDelayed< targetidentifierT >::check_connection(Node &s, Node &t, rport receptor_type, const CommonPropertiesType &)
References nest::Node::handles_test_event, nest::names::receptor_type, nest::Node::sends_secondary_event, nest::Event::set_sender.
void nest::RateConnectionDelayed< targetidentifierT >::send(Event &e, thread t, const CommonSynapseProperties &)
Send an event to the receiver of this connection.
e The event to send p The port under which this connection is stored in the Connector.
References numerics::e, nest::RateConnectionDelayed< targetidentifierT >::get_delay_steps, nest::RateConnectionDelayed< targetidentifierT >::get_rport, nest::RateConnectionDelayed< targetidentifierT >::get_target, nest::RateConnectionDelayed< targetidentifierT >::weight_.
void nest::RateConnectionDelayed< targetidentifierT >::get_status(DictionaryDatum &d) const
References nest::names::d, nest::names::size_of, nest::names::weight.
void nest::RateConnectionDelayed< targetidentifierT >::set_status(const DictionaryDatum &d, ConnectorModel &cm)
References nest::names::d, nest::names::weight.
void nest::RateConnectionDelayed< targetidentifierT >::set_weight(double w)
References nest::names::w, nest::RateConnectionDelayed< targetidentifierT >::weight_.
long nest::Connection< targetidentifierT >::get_delay_steps() const
Return the delay of the connection in steps.
Referenced by nest::RateConnectionDelayed< targetidentifierT >::send.
rport nest::Connection< targetidentifierT >::get_rport() const
Referenced by nest::RateConnectionDelayed< targetidentifierT >::send.
Node* nest::Connection< targetidentifierT >::get_target(const thread tid) const
Referenced by nest::RateConnectionDelayed< targetidentifierT >::send.