nest::TargetDataFields
unsigned int nest::TargetDataFields::lcid_
Referenced by get_lcid, set_lcid.
unsigned int nest::TargetDataFields::tid_
Referenced by get_tid, set_tid.
unsigned int nest::TargetDataFields::syn_id_
Referenced by get_syn_id, set_syn_id.
void nest::TargetDataFields::set_lcid(const index lcid)
Sets the local connection ID.
References lcid_.
Referenced by nest::SourceTable::populate_target_data_fields_.
index nest::TargetDataFields::get_lcid() const
Returns the local connection ID.
References lcid_.
Referenced by nest::TargetTable::add_target.
void nest::TargetDataFields::set_tid(const thread tid)
Sets the target ID.
References tid_.
Referenced by nest::SourceTable::populate_target_data_fields_.
thread nest::TargetDataFields::get_tid() const
Returns the target ID.
References tid_.
Referenced by nest::TargetTable::add_target.
void nest::TargetDataFields::set_syn_id(const synindex syn_id)
Sets the synapse-type ID.
References syn_id_.
Referenced by nest::SourceTable::populate_target_data_fields_.
synindex nest::TargetDataFields::get_syn_id() const
Returns the synapse-type ID.
References syn_id_.
Referenced by nest::TargetTable::add_target.