nest::RecordingBackendSIONlib::SIONBuffer
char* nest::RecordingBackendSIONlib::SIONBuffer::buffer_
size_t nest::RecordingBackendSIONlib::SIONBuffer::ptr_
size_t nest::RecordingBackendSIONlib::SIONBuffer::max_size_
nest::RecordingBackendSIONlib::SIONBuffer::SIONBuffer()
nest::RecordingBackendSIONlib::SIONBuffer::SIONBuffer(size_t size)
References reserve.
nest::RecordingBackendSIONlib::SIONBuffer::~SIONBuffer()
void nest::RecordingBackendSIONlib::SIONBuffer::reserve(size_t size)
Referenced by nest::RecordingBackendSIONlib::open_files_, SIONBuffer.
void nest::RecordingBackendSIONlib::SIONBuffer::ensure_space(size_t size)
Referenced by nest::RecordingBackendSIONlib::write.
void nest::RecordingBackendSIONlib::SIONBuffer::write(const char *v, size_t n)
References LOG, nest::M_ERROR.
size_t nest::RecordingBackendSIONlib::SIONBuffer::get_capacity()
Referenced by nest::RecordingBackendSIONlib::write.
size_t nest::RecordingBackendSIONlib::SIONBuffer::get_size()
Referenced by nest::RecordingBackendSIONlib::close_files_, nest::RecordingBackendSIONlib::post_step_hook, nest::RecordingBackendSIONlib::write.
size_t nest::RecordingBackendSIONlib::SIONBuffer::get_free()
Referenced by nest::RecordingBackendSIONlib::write.
void nest::RecordingBackendSIONlib::SIONBuffer::clear()
Referenced by nest::RecordingBackendSIONlib::close_files_, nest::RecordingBackendSIONlib::open_files_, nest::RecordingBackendSIONlib::post_step_hook, nest::RecordingBackendSIONlib::write.
char * nest::RecordingBackendSIONlib::SIONBuffer::read()
Referenced by nest::RecordingBackendSIONlib::close_files_, nest::RecordingBackendSIONlib::post_step_hook, nest::RecordingBackendSIONlib::write.
SIONBuffer & nest::RecordingBackendSIONlib::SIONBuffer::operator<<(const T data)
nest::RecordingBackendSIONlib::SIONBuffer & nest::RecordingBackendSIONlib::SIONBuffer::operator<<(const T data)
References nest::RecordingBackendSIONlib::write.