DictionaryStack
const Token DictionaryStack::VoidToken
Referenced by baselookup, lookup.
std::list< DictionaryDatum > DictionaryStack::d
Referenced by clear, clear_dict_from_cache, def, def_move, info, known, lookup2, operator=, pop, push, set_basedict, size, toArray, top, top_info, undef, ~DictionaryStack.
DictionaryDatum DictionaryStack::base_
Referenced by basedef, basedef_move, baseknown, baselookup, set_basedict.
std::vector< const Token* > DictionaryStack::cache_
Referenced by cache_token, clear_cache, clear_token_from_cache, known, lookup2, operator=.
std::vector< const Token* > DictionaryStack::basecache_
Referenced by basecache_token, baseknown, baselookup, clear_token_from_basecache.
DictionaryStack::DictionaryStack(const Token &=Token())
DictionaryStack::DictionaryStack(const DictionaryStack &)
DictionaryStack::~DictionaryStack()
References d.
void DictionaryStack::cache_token(const Name &n, const Token *result)
Add a token to the cache.
References cache_, Name::num_handles, Name::toIndex.
Referenced by baseknown, baselookup, def, def_move, known, lookup2.
void DictionaryStack::basecache_token(const Name &n, const Token *result)
References basecache_, Name::num_handles, Name::toIndex.
Referenced by basedef, basedef_move, baseknown, baselookup.
void DictionaryStack::clear_token_from_cache(const Name &n)
Clear a name from the cache.
This function should be called in each def variant.
References cache_, Name::toIndex.
Referenced by basedef, basedef_move, clear_dict_from_cache, DictputFunction::execute, UndefFunction::execute, undef.
void DictionaryStack::clear_token_from_basecache(const Name &n)
References basecache_, Name::toIndex.
Referenced by undef.
void DictionaryStack::clear_dict_from_cache(DictionaryDatum d)
References clear_token_from_cache, d.
Referenced by CleardictFunction::execute, pop, push.
void DictionaryStack::clear_cache()
Clear the entire cache.
This should be called whenever a dictionary is pushed or poped. Alternative, one could just clear the names from the moved dictionary.
References cache_.
Referenced by clear.
const Token & DictionaryStack::lookup(const Name &n)
References lookup2, VoidToken.
Referenced by SLIInterpreter::lookup.
const Token & DictionaryStack::lookup2(const Name &n)
References cache_, cache_token, d, Name::toIndex, Name::toString.
Referenced by lookup, SLIInterpreter::lookup2.
const Token & DictionaryStack::baselookup(const Name &n)
Lookup a name searching only the bottom level dictionary.
If the Name is not found, VoidToken is returned.
References base_, basecache_, basecache_token, cache_token, Name::toIndex, VoidToken.
Referenced by SLIInterpreter::baselookup.
bool DictionaryStack::known(const Name &n)
Test for a name searching all dictionaries on the stack.
References cache_, cache_token, d, Name::toIndex.
Referenced by SLIInterpreter::createcommand, SLIInterpreter::known.
bool DictionaryStack::baseknown(const Name &n)
Test for a name in the bottom level dictionary.
References base_, basecache_, basecache_token, cache_token, Name::toIndex.
Referenced by SLIInterpreter::baseknown.
void DictionaryStack::def(const Name &, const Token &)
Bind a Token to a Name in the top level dictionary.
The Token is copied.
References cache_token, d.
Referenced by SLIInterpreter::def.
void DictionaryStack::undef(const Name &)
Unbind a previously defined Name from its token.
Seach in all dictionaries.
References clear_token_from_basecache, clear_token_from_cache, d, Name::toString.
Referenced by SLIInterpreter::undef.
void DictionaryStack::basedef(const Name &n, const Token &t)
Bind a Token to a Name in the bottom level dictionary.
The Token is copied.
References base_, basecache_token, clear_token_from_cache.
Referenced by SLIInterpreter::basedef.
void DictionaryStack::def_move(const Name &, Token &)
Bind a Token to a Name in the top level dictionary.
The Token is moved.
References cache_token, d.
Referenced by SLIInterpreter::createcommand, SLIInterpreter::createconstant, SLIInterpreter::createdouble, SLIInterpreter::def_move.
void DictionaryStack::set_basedict()
This function must be called once to initialize the systemdict cache.
References base_, d.
Referenced by SLIInterpreter::initdictionaries.
void DictionaryStack::basedef_move(const Name &n, Token &t)
Bind a Token to a Name in the bottom level dictionary.
The Token is moved.
References base_, basecache_token, clear_token_from_cache.
Referenced by SLIInterpreter::basedef_move.
void DictionaryStack::pop()
References clear_dict_from_cache, d.
Referenced by DictendFunction::execute, CleardictstackFunction::execute, SLIInterpreter::~SLIInterpreter.
void DictionaryStack::top(Token &) const
References d, Token::move.
Referenced by CurrentdictFunction::execute.
void DictionaryStack::push(const DictionaryDatum &)
References clear_dict_from_cache, d.
Referenced by OOSupportModule::CallMemberFunction::execute, DictbeginFunction::execute, RestoredstackFunction::execute, SLIInterpreter::initdictionaries, push.
void DictionaryStack::push(Token &)
References d, push.
void DictionaryStack::clear()
References clear_cache, d.
void DictionaryStack::toArray(TokenArray &) const
References d, TokenArray::erase, TokenArray::push_back.
Referenced by DictstackFunction::execute, SLIInterpreter::raiseerror.
size_t DictionaryStack::size() const
References d.
Referenced by DictendFunction::execute, CountdictstackFunction::execute, CleardictstackFunction::execute.
void DictionaryStack::info(std::ostream &) const
References d.
Referenced by WhoFunction::execute, top_info.
void DictionaryStack::top_info(std::ostream &) const
References d, info.
Referenced by DicttopinfoFunction::execute.
const DictionaryStack & DictionaryStack::operator=(const DictionaryStack &)
References cache_, d.