lockPTR
std::shared_ptr< PointerObject > lockPTR< D >::obj
Referenced by lockPTR< D >::deletable, lockPTR< D >::get, lockPTR< D >::islocked, lockPTR< D >::lock, lockPTR< D >::lockPTR, lockPTR< D >::operator not, lockPTR< D >::operator!=, lockPTR< D >::operator*, lockPTR< D >::operator->, lockPTR< D >::operator=, lockPTR< D >::operator==, lockPTR< D >::references, lockPTR< D >::unlock, lockPTR< D >::valid, lockPTR< D >::~lockPTR.
lockPTR< D >::lockPTR(D *p=nullptr)
References lockPTR< D >::obj.
lockPTR< D >::lockPTR(D &p_o)
References lockPTR< D >::obj.
lockPTR< D >::lockPTR(const lockPTR< D > &spd)
References lockPTR< D >::obj.
virtual lockPTR< D >::~lockPTR()
References lockPTR< D >::obj.
lockPTR< D > lockPTR< D >::operator=(const lockPTR< D > &spd)
References lockPTR< D >::obj.
lockPTR< D > lockPTR< D >::operator=(D &s)
References lockPTR< D >::obj.
lockPTR< D > lockPTR< D >::operator=(D const &s)
References lockPTR< D >::obj.
D * lockPTR< D >::get()
References lockPTR< D >::obj.
Referenced by StrFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute.
D * lockPTR< D >::get() const
References lockPTR< D >::obj.
D * lockPTR< D >::operator->() const
References lockPTR< D >::obj.
D * lockPTR< D >::operator->()
References lockPTR< D >::obj.
D & lockPTR< D >::operator*()
References lockPTR< D >::obj.
const D & lockPTR< D >::operator*() const
References lockPTR< D >::obj.
bool lockPTR< D >::operator not() const
< returns true if and only if not obj->pointee
References lockPTR< D >::obj.
bool lockPTR< D >::operator==(const lockPTR< D > &p) const
References lockPTR< D >::obj.
Referenced by lockPTRDatum< D, slt >::equals.
bool lockPTR< D >::operator!=(const lockPTR< D > &p) const
References lockPTR< D >::obj.
bool lockPTR< D >::valid() const
< returns true if and only if obj->pointee
References lockPTR< D >::obj.
Referenced by Processes::AvailableFunction::execute, Processes::SetNonblockFunction::execute, PrintFunction::execute, PrettyprintFunction::execute, CloseistreamFunction::execute, FlushFunction::execute, EndlFunction::execute, EndsFunction::execute, EatwhiteFunction::execute, SetwFunction::execute, SetprecisionFunction::execute, IOSFixedFunction::execute, IOSScientificFunction::execute, IOSDefaultFunction::execute, IOSShowpointFunction::execute, IOSNoshowpointFunction::execute, IOSShowbaseFunction::execute, IOSNoshowbaseFunction::execute, IOSDecFunction::execute, IOSHexFunction::execute, IOSOctFunction::execute, IOSLeftFunction::execute, IOSRightFunction::execute, IOSInternalFunction::execute, GetcFunction::execute, GetsFunction::execute, GetlineFunction::execute, IGoodFunction::execute, IClearFunction::execute, OClearFunction::execute, IFailFunction::execute, OGoodFunction::execute, IEofFunction::execute, OEofFunction::execute, In_AvailFunction::execute, ReadDoubleFunction::execute, ReadIntFunction::execute, ReadWordFunction::execute, IparseFunction::execute, PgetrusageFunction::getinfo_, SLIStartup::init.
bool lockPTR< D >::islocked() const
References lockPTR< D >::obj.
bool lockPTR< D >::deletable() const
References lockPTR< D >::obj.
void lockPTR< D >::lock() const
References lockPTR< D >::obj.
void lockPTR< D >::unlock() const
References lockPTR< D >::obj.
Referenced by StrFunction::execute, CloseistreamFunction::execute, CloseostreamFunction::execute, RegexpModule::RegexecFunction::execute, RegexpModule::RegerrorFunction::execute.
void lockPTR< D >::unlock()
References lockPTR< D >::obj.
size_t lockPTR< D >::references() const
References lockPTR< D >::obj.