nest::SPManager
double nest::SPManager::structural_plasticity_update_interval_
Time interval for structural plasticity update (creation/deletion of synapses).
Referenced by get_status, get_structural_plasticity_update_interval, initialize, set_status.
bool nest::SPManager::structural_plasticity_enabled_
Indicates whether the Structrual Plasticity functionality is On (True) of Off (False).
Referenced by initialize, is_structural_plasticity_enabled.
std::vector< SPBuilder* > nest::SPManager::sp_conn_builders_
Referenced by builder_max_delay, builder_min_delay, disconnect, finalize, get_status, set_status, update_structural_plasticity.
std::vector< GenericGrowthCurveFactory* > nest::SPManager::growthcurve_factories_
GrowthCurve factories, indexed by growthcurvedict_ elements.
Referenced by new_growth_curve, register_growth_curve.
DictionaryDatum nest::SPManager::growthcurvedict_
Dictionary for growth rules.
Referenced by get_status, register_growth_curve.
nest::SPManager::SPManager()
nest::SPManager::~SPManager() override
References finalize.
void nest::SPManager::initialize() override
Prepare manager for operation.
After this method has completed, the manager should be completely initialized and "ready for action". Initialization of any given manager may depend on other managers having been initialized before. KernelManager::initialize() is responsible for calling the initialization routines on the specific managers in correct order. finalize()
References structural_plasticity_enabled_, structural_plasticity_update_interval_.
void nest::SPManager::finalize() override
Take down manager after operation.
After this method has completed, all dynamic data structures created by the manager shall be deallocated and containers emptied. Plain variables need not be reset. Finalization of any given manager may depend on other managers not having been finalized yet. KernelManager::finalize() is responsible for calling the initialization routines on the specific managers in correct order, i.e., the opposite order of initialize() calls. initialize()
References sp_conn_builders_.
Referenced by ~SPManager.
void nest::SPManager::get_status(DictionaryDatum &) override
References nest::names::d, nest::names::growth_curves, growthcurvedict_, nest::kernel, nest::names::post_synaptic_element, nest::names::pre_synaptic_element, sp_conn_builders_, nest::names::structural_plasticity_synapses, nest::names::structural_plasticity_update_interval, structural_plasticity_update_interval_, nest::names::synapse_model.
void nest::SPManager::set_status(const DictionaryDatum &) override
Set status of synaptic plasticity variables: synaptic update interval, synapses and synaptic elements.
d Dictionary containing the values to be set
References nest::names::allow_autapses, nest::names::allow_multapses, nest::names::d, nest::ConnBuilder::get_default_delay, nest::kernel, sp_conn_builders_, nest::names::structural_plasticity_synapses, nest::names::structural_plasticity_update_interval, structural_plasticity_update_interval_, nest::names::targets.
GrowthCurve * nest::SPManager::new_growth_curve(Name name)
Create a new Growth Curve object using the GrowthCurve Factory.
name which defines the type of NC to be created a new Growth Curve object of the type indicated by name
References growthcurve_factories_.
Referenced by nest::SynapticElement::operator=, nest::SynapticElement::set, nest::SynapticElement::SynapticElement.
void nest::SPManager::register_growth_curve(const std::string &name)
Add a growth curve for MSP.
References growthcurve_factories_, growthcurvedict_.
Referenced by nest::NestModule::init.
void nest::SPManager::disconnect(NodeCollectionPTR, NodeCollectionPTR, DictionaryDatum &, DictionaryDatum &)
Disconnect two collections of nodes.
Obtains the right connection builder and performs a synapse deletion according to the specified connection specs. The connection is established on the thread/process that owns the target node. sources Node collection of the source Nodes. targets Node collection of the target Nodes. connectivityParams connectivity Dictionary synapseParams synapse parameters Dictionary sources collection of sources targets collection of targets conn_spec disconnection specs. For now only all to all and one to one rules are implemented. syn_spec synapse specs
References ALL_ENTRIES_ACCESSED, nest::KernelManager::connection_manager, nest::ConnBuilder::disconnect, nest::ConnectionManager::get_conn_builder, nest::VPManager::get_thread_id, nest::kernel, nest::names::rule, nest::ConnectionManager::set_connections_have_changed, nest::ConnBuilder::set_post_synaptic_element_name, nest::ConnBuilder::set_pre_synaptic_element_name, nest::KernelManager::simulation_manager, sp_conn_builders_, nest::names::synapse_model, nest::names::targets, nest::SimulationManager::update_connection_infrastructure, nest::KernelManager::vp_manager.
Referenced by nest::disconnect, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::ConnBuilder::single_disconnect_.
void nest::SPManager::disconnect(const index snode_id, Node *target, thread target_thread, const index syn_id)
Disconnect two nodes.
Deletes synapses between a source and a target. The source node is defined by its global ID. The target node is defined by the node. The connection is established on the thread/process that owns the target node. snode_id node ID of the sending Node. target Pointer to target Node. target_thread Thread that hosts the target node. syn_id The synapse model to use. snode_id target target_thread syn_id
References nest::KernelManager::connection_manager, nest::ConnectionManager::disconnect, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_num_threads, nest::kernel, nest::KernelManager::node_manager, nest::names::source, nest::names::target, nest::names::target_thread, nest::KernelManager::vp_manager.
void nest::SPManager::update_structural_plasticity()
References sp_conn_builders_.
Referenced by nest::SimulationManager::update_.
void nest::SPManager::update_structural_plasticity(SPBuilder *)
Handles the general dynamic creation and deletion of synapses when structural plasticity is enabled.
Retrieves the number of available synaptic elements to create new synapses. Retrieves the number of deleted synaptic elements to delete already created synapses. sp_builder The structural plasticity connection builder to use
References nest::MPIManager::communicate, nest::KernelManager::connection_manager, create_synapses, delete_synapses_from_post, delete_synapses_from_pre, nest::SPBuilder::get_post_synaptic_element_name, nest::SPBuilder::get_pre_synaptic_element_name, nest::ConnBuilder::get_synapse_model, get_synaptic_elements, nest::kernel, nest::KernelManager::mpi_manager, nest::ConnectionManager::set_connections_have_changed.
void nest::SPManager::enable_structural_plasticity()
Enable structural plasticity.
References nest::kernel.
Referenced by nest::NestModule::EnableStructuralPlasticity_Function::execute.
void nest::SPManager::disable_structural_plasticity()
Disable structural plasticity.
Referenced by nest::NestModule::DisableStructuralPlasticity_Function::execute.
bool nest::SPManager::is_structural_plasticity_enabled() const
References structural_plasticity_enabled_.
double nest::SPManager::get_structural_plasticity_update_interval() const
References structural_plasticity_update_interval_.
delay nest::SPManager::builder_min_delay() const
Returns the minimum delay of all SP builders.
This influences the min_delay of the kernel, as the connections are build during the simulation. Hence, the ConnectionManager::min_delay() methods have to respect this delay as well.
References nest::Time::get_steps, nest::names::min, nest::names::min_delay, nest::Time::pos_inf, sp_conn_builders_.
delay nest::SPManager::builder_max_delay() const
Returns the maximum delay of all SP builders.
This influences the max_delay of the kernel, as the connections are build during the simulation. Hence, the ConnectionManager::max_delay() methods have to respect this delay as well.
References nest::Time::get_steps, nest::names::max, nest::names::max_delay, nest::Time::neg_inf, sp_conn_builders_.
bool nest::SPManager::create_synapses(std::vector< index > &pre_vacant_id, std::vector< int > &pre_vacant_n, std::vector< index > &post_vacant_id, std::vector< int > &post_vacant_n, SPBuilder *sp_conn_builder)
Dynamic creation of synapses.
pre_id source id pre_n number of available synaptic elements in the pre node post_id target id post_n number of available synaptic elements in the post node sp_conn_builder structural plasticity connection builder to use true if synapses are created
References global_shuffle, serialize_id, nest::SPBuilder::sp_connect.
Referenced by update_structural_plasticity.
void nest::SPManager::delete_synapses_from_pre(const std::vector< index > &pre_deleted_id, std::vector< int > &pre_deleted_n, const index synapse_model, const std::string &se_pre_name, const std::string &se_post_name)
Deletion of synapses due to the loss of a pre synaptic element.
The corresponding pre synaptic element will still remain available for a new connection on the following updates in connectivity pre_deleted_id Id of the node with the deleted pre synaptic element pre_deleted_n number of deleted pre synaptic elements synapse_model model name se_pre_name pre synaptic element name se_post_name postsynaptic element name
References nest::MPIManager::communicate, nest::KernelManager::connection_manager, delete_synapse, nest::ConnectionManager::get_targets, global_shuffle, nest::kernel, nest::KernelManager::mpi_manager, nest::names::synapse_model.
Referenced by update_structural_plasticity.
void nest::SPManager::delete_synapses_from_post(std::vector< index > &post_deleted_id, std::vector< int > &post_deleted_n, index synapse_model, std::string se_pre_name, std::string se_post_name)
Deletion of synapses due to the loss of a postsynaptic element.
The corresponding pre synaptic element will still remain available for a new connection on the following updates in connectivity post_deleted_id Id of the node with the deleted postsynaptic element post_deleted_n number of deleted postsynaptic elements synapse_model model name se_pre_name pre synaptic element name se_post_name postsynaptic element name
References nest::MPIManager::communicate, nest::KernelManager::connection_manager, delete_synapse, nest::ConnectionManager::get_sources, global_shuffle, nest::kernel, nest::KernelManager::mpi_manager, nest::names::synapse_model.
Referenced by update_structural_plasticity.
void nest::SPManager::delete_synapse(index source, index target, long syn_id, std::string se_pre_name, std::string se_post_name)
Handles the deletion of synapses between source and target nodes.
The deletion is defined by the pre and postsynaptic elements and the synapse type. Updates the number of connected synaptic elements in the source and target. snode_id source id tnode_id target id syn_id synapse type se_pre_name name of the pre synaptic element se_post_name name of the postsynaptic element
References nest::KernelManager::connection_manager, nest::ConnectionManager::disconnect, nest::NodeManager::get_node_or_proxy, nest::VPManager::get_thread_id, nest::kernel, nest::KernelManager::node_manager, nest::names::source, nest::names::target, nest::names::target_thread, nest::KernelManager::vp_manager.
Referenced by delete_synapses_from_post, delete_synapses_from_pre.
void nest::SPManager::get_synaptic_elements(std::string se_name, std::vector< index > &se_vacant_id, std::vector< int > &se_vacant_n, std::vector< index > &se_deleted_id, std::vector< int > &se_deleted_n)
References nest::SparseNodeArray::begin, nest::SparseNodeArray::end, nest::NodeManager::get_local_nodes, nest::VPManager::get_num_threads, nest::Node::get_synaptic_elements_vacant, nest::kernel, nest::names::n, nest::KernelManager::node_manager, nest::NodeManager::size, nest::KernelManager::vp_manager.
Referenced by update_structural_plasticity.
void nest::SPManager::serialize_id(std::vector< index > &id, std::vector< int > &n, std::vector< index > &res)
References nest::names::n.
Referenced by create_synapses.
void nest::SPManager::global_shuffle(std::vector< index > &v)
Referenced by create_synapses, delete_synapses_from_post, delete_synapses_from_pre.
void nest::SPManager::global_shuffle(std::vector< index > &v, size_t n)
References nest::get_rank_synced_rng, nest::names::N, nest::names::n, nest::BaseRandomGenerator::ulrand.