nest::ConnectorBase
virtual nest::ConnectorBase::~ConnectorBase()
virtual synindex nest::ConnectorBase::get_syn_id() const =0
Return syn_id_ of the synapse type of this Connector (index in list of synapse prototypes).
virtual size_t nest::ConnectorBase::size() const =0
Return the number of connections in this Connector.
Referenced by nest::ConnectionManager::get_connections.
virtual void nest::ConnectorBase::get_synapse_status(const thread tid, const index lcid, DictionaryDatum &dict) const =0
Write status of the connection at position lcid to the dictionary dict.
virtual void nest::ConnectorBase::set_synapse_status(const index lcid, const DictionaryDatum &dict, ConnectorModel &cm)=0
Set status of the connection at position lcid according to the dictionary dict.
virtual void nest::ConnectorBase::get_connection(const index source_node_id, const index target_node_id, const thread tid, const index lcid, const long synapse_label, std::deque< ConnectionID > &conns) const =0
Add ConnectionID with given source_node_id and lcid to conns.
If target_node_id is given, only add connection if target_node_id matches the node_id of the target of the connection.
Referenced by nest::ConnectionManager::get_connections.
virtual void nest::ConnectorBase::get_connection_with_specified_targets(const index source_node_id, const std::vector< size_t > &target_neuron_node_ids, const thread tid, const index lcid, const long synapse_label, std::deque< ConnectionID > &conns) const =0
Add ConnectionID with given source_node_id and lcid to conns.
If target_neuron_node_ids is given, only add connection if target_neuron_node_ids contains the node ID of the target of the connection.
Referenced by nest::ConnectionManager::get_connections.
virtual void nest::ConnectorBase::get_all_connections(const index source_node_id, const index target_node_id, const thread tid, const long synapse_label, std::deque< ConnectionID > &conns) const =0
Add ConnectionIDs with given source_node_id to conns, looping over all lcids.
If target_node_id is given, only add connection if target_node_id matches the node ID of the target of the connection.
virtual void nest::ConnectorBase::get_source_lcids(const thread tid, const index target_node_id, std::vector< index > &source_lcids) const =0
For a given target_node_id add lcids of all connections with matching node ID of target to source_lcids.
virtual void nest::ConnectorBase::get_target_node_ids(const thread tid, const index start_lcid, const std::string &post_synaptic_element, std::vector< index > &target_node_ids) const =0
For a given start_lcid add node IDs of all targets that belong to the same source to target_node_ids.
virtual index nest::ConnectorBase::get_target_node_id(const thread tid, const unsigned int lcid) const =0
For a given lcid return the node ID of the target of the connection.
virtual void nest::ConnectorBase::send_to_all(const thread tid, const std::vector< ConnectorModel * > &cm, Event &e)=0
Send the event e to all connections of this Connector.
virtual index nest::ConnectorBase::send(const thread tid, const index lcid, const std::vector< ConnectorModel * > &cm, Event &e)=0
Send the event e to the connection at position lcid.
Return bool indicating whether the following connection belongs to the same source.
virtual void nest::ConnectorBase::send_weight_event(const thread tid, const unsigned int lcid, Event &e, const CommonSynapseProperties &cp)=0
virtual void nest::ConnectorBase::trigger_update_weight(const long vt_node_id, const thread tid, const std::vector< spikecounter > &dopa_spikes, const double t_trig, const std::vector< ConnectorModel * > &cm)=0
Update weights of dopamine modulated STDP connections.
virtual void nest::ConnectorBase::sort_connections(BlockVector< Source > &)=0
Sort connections according to source node IDs.
virtual void nest::ConnectorBase::set_source_has_more_targets(const index lcid, const bool has_more_targets)=0
Set a flag in the connection indicating whether the following connection belongs to the same source.
virtual index nest::ConnectorBase::find_first_target(const thread tid, const index start_lcid, const index target_node_id) const =0
Return lcid of the first connection after start_lcid (inclusive) where the node_id of the target matches target_node_id.
If there are no matches, the function returns invalid_index.
virtual index nest::ConnectorBase::find_matching_target(const thread tid, const std::vector< index > &matching_lcids, const index target_node_id) const =0
Return lcid of first connection where the node ID of the target matches target_node_id; consider only the connections with lcids given in matching_lcids.
If there is no match, the function returns invalid_index.
virtual void nest::ConnectorBase::disable_connection(const index lcid)=0
Disable the transfer of events through the connection at position lcid.
virtual void nest::ConnectorBase::remove_disabled_connections(const index first_disabled_index)=0
Remove disabled connections from the connector.