dictutils.cc
void initialize_property_array(DictionaryDatum &d, Name propname)
Create a property of type ArrayDatum in the dictionary, if it does not already exist.
References Token::empty, Name::lookup.
Referenced by nest::RecordingBackendASCII::DeviceData::get_status.
void initialize_property_doublevector(DictionaryDatum &d, Name propname)
Create a property of type DoubleVectorDatum in the dictionary, if it does not already exist.
References Token::empty, Name::lookup.
Referenced by nest::RecordingBackendMemory::DeviceData::get_status.
void initialize_property_intvector(DictionaryDatum &d, Name propname)
Create a property of type IntVectorDatum in the dictionary, if it does not already exist.
References Token::empty, Name::lookup.
Referenced by nest::RecordingBackendMemory::DeviceData::get_status.
void provide_property(DictionaryDatum &d, Name propname, const std::vector< double > &prop)
Provide a value to a property DoubleVectorDatum in the dictionary.
In contrast to append_property, this function adds the value only once to the property. On all subsequent events, it ensures that the value passed in is identical to the value present. This is needed by recording_decive.
References Token::datum.
void provide_property(DictionaryDatum &d, Name propname, const std::vector< long > &prop)
Provide a value to a property IntVectorDatum in the dictionary.
In contrast to append_property, this function adds the value only once to the property. On all subsequent events, it ensures that the value passed in is identical to the value present. This is needed by recording_decive.
References Token::datum.
void accumulate_property(DictionaryDatum &d, Name propname, const std::vector< double > &prop)
Add values of a vector<double> to a property DoubleVectorDatum in the dictionary.
This variant of append_property is for adding vector<double>s to vector<double>s of the same size. It is required for collecting data across threads when multimeter is running in accumulation mode.
References Token::datum.