iaf_psc_delta_data
Parameters_ nest::iaf_psc_delta_ps::P_
Referenced by nest::iaf_psc_delta_ps::get_status, nest::iaf_psc_delta_ps::get_V_m_, nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::set_status, nest::iaf_psc_delta_ps::update.
State_ nest::iaf_psc_delta_ps::S_
Referenced by nest::iaf_psc_delta_ps::get_status, nest::iaf_psc_delta_ps::get_V_m_, nest::iaf_psc_delta_ps::set_status, nest::iaf_psc_delta_ps::update.
Variables_ nest::iaf_psc_delta_ps::V_
Referenced by nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
Buffers_ nest::iaf_psc_delta_ps::B_
Referenced by nest::iaf_psc_delta_ps::handle, nest::iaf_psc_delta_ps::handles_test_event, nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Parameters_::tau_m_
Membrane time constant in ms.
Referenced by nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Parameters_::c_m_
Membrane capacitance in pF.
Referenced by nest::iaf_psc_delta_ps::pre_run_hook.
double nest::iaf_psc_delta_ps::Parameters_::t_ref_
Refractory period in ms.
Referenced by nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Parameters_::E_L_
Resting potential in mV.
Referenced by nest::iaf_psc_delta_ps::get_V_m_.
double nest::iaf_psc_delta_ps::Parameters_::I_e_
External DC current [pA].
Referenced by nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Parameters_::U_th_
Threshold, RELATIVE TO RESTING POTENTAIL(!).
I.e. the real threshold is U_th_ + E_L_.
Referenced by nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Parameters_::U_min_
Lower bound, RELATIVE TO RESTING POTENTAIL(!).
I.e. the real lower bound is U_min_+E_L_.
Referenced by nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Parameters_::U_reset_
Reset potential.
At threshold crossing, the membrane potential is reset to this value. Relative to resting potential.
double nest::iaf_psc_delta_ps::State_::U_
This is the membrane potential RELATIVE TO RESTING POTENTIAL.
Referenced by nest::iaf_psc_delta_ps::get_V_m_, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::State_::I_
This is the current to be applied during this time step.
Referenced by nest::iaf_psc_delta_ps::update.
long nest::iaf_psc_delta_ps::State_::last_spike_step_
step of last spike, for reporting in status dict
Referenced by nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::State_::last_spike_offset_
offset of last spike, for reporting in status dict
Referenced by nest::iaf_psc_delta_ps::update.
bool nest::iaf_psc_delta_ps::State_::is_refractory_
flag for refractoriness
Referenced by nest::iaf_psc_delta_ps::update.
bool nest::iaf_psc_delta_ps::State_::with_refr_input_
spikes arriving during refractory period are counted
Referenced by nest::iaf_psc_delta_ps::update.
SliceRingBuffer nest::iaf_psc_delta_ps::Buffers_::events_
Queue for incoming events.
Return from refractoriness is stored as events "spikes" with weight == numerics::NaN
Referenced by nest::iaf_psc_delta_ps::handle, nest::iaf_psc_delta_ps::update.
RingBuffer nest::iaf_psc_delta_ps::Buffers_::currents_
Queue for incoming current events.
Referenced by nest::iaf_psc_delta_ps::handle, nest::iaf_psc_delta_ps::update.
UniversalDataLogger< iaf_psc_delta_ps > nest::iaf_psc_delta_ps::Buffers_::logger_
Logger for all analog data.
Referenced by nest::iaf_psc_delta_ps::handles_test_event, nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Variables_::exp_t_
$ e^{-t/\tau_m} $
Referenced by nest::iaf_psc_delta_ps::pre_run_hook.
double nest::iaf_psc_delta_ps::Variables_::expm1_t_
$ e^{-t/\tau_m} - 1 $
Referenced by nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Variables_::R_
$ \frac{\tau_m}{c_m} $
Referenced by nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Variables_::h_ms_
duration of time step [ms]
Referenced by nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
long nest::iaf_psc_delta_ps::Variables_::refractory_steps_
refractory time in steps
Referenced by nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_delta_ps::update.
double nest::iaf_psc_delta_ps::Variables_::refr_spikes_buffer_
Accumulate spikes arriving during refractory period, discounted for decay until end of refractory period.
Referenced by nest::iaf_psc_delta_ps::update.
RecordablesMap< iaf_psc_delta_ps > nest::iaf_psc_delta_ps::recordablesMap_
Mapping of recordables names to access functions.
Referenced by nest::iaf_psc_delta_ps::get_status, nest::iaf_psc_delta_ps::handles_test_event, nest::iaf_psc_delta_ps::iaf_psc_delta_ps.
nest::iaf_psc_delta_ps::Parameters_::Parameters_()
Sets default parameter values.
void nest::iaf_psc_delta_ps::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::C_m, nest::names::d, nest::names::E_L, nest::names::I_e, nest::names::t_ref, nest::names::tau_m, nest::names::V_min, nest::names::V_reset, nest::names::V_th.
Referenced by nest::iaf_psc_delta_ps::get_status.
double nest::iaf_psc_delta_ps::Parameters_::set(const DictionaryDatum &, Node *)
Set values from dictionary.
Change in reversal potential E_L, to be passed to State_::set()
References nest::names::C_m, nest::names::d, nest::names::E_L, nest::names::I_e, nest::names::t_ref, nest::names::tau_m, nest::names::V_min, nest::names::V_reset, nest::names::V_th.
Referenced by nest::iaf_psc_delta_ps::set_status.
nest::iaf_psc_delta_ps::State_::State_()
Default initialization.
void nest::iaf_psc_delta_ps::State_::get(DictionaryDatum &, const Parameters_ &) const
References nest::names::d, nest::names::is_refractory, nest::names::p, nest::names::refractory_input, nest::names::V_m.
Referenced by nest::iaf_psc_delta_ps::get_status.
void nest::iaf_psc_delta_ps::State_::set(const DictionaryDatum &, const Parameters_ &, double, Node *)
Set values from dictionary.
dictionary to take data from current parameters Change in reversal potential E_L specified by this dict
References nest::names::d, nest::names::p, nest::names::V_m.
Referenced by nest::iaf_psc_delta_ps::set_status.
nest::iaf_psc_delta_ps::Buffers_::Buffers_(iaf_psc_delta_ps &)
nest::iaf_psc_delta_ps::Buffers_::Buffers_(const Buffers_ &, iaf_psc_delta_ps &)