SP_functions
virtual double nest::Node::get_Ca_minus() const
Return the Ca_minus value at time Ca_t which corresponds to the time of the last update in Calcium concentration which is performed each time a Node spikes.
Return 0.0 if not overridden
virtual double nest::Node::get_synaptic_elements(Name) const
Get the number of synaptic element for the current Node at Ca_t which corresponds to the time of the last spike.
Return 0.0 if not overridden
virtual int nest::Node::get_synaptic_elements_vacant(Name) const
Get the number of vacant synaptic element for the current Node Return 0 if not overridden.
Referenced by nest::SPManager::get_synaptic_elements.
virtual int nest::Node::get_synaptic_elements_connected(Name) const
Get the number of connected synaptic element for the current Node Return 0 if not overridden.
virtual std::map< Name, double > nest::Node::get_synaptic_elements() const
Get the number of all synaptic elements for the current Node at time t Return an empty map if not overridden.
virtual void nest::Node::update_synaptic_elements(double)
Triggers the update of all SynapticElements stored in the synaptic_element_map_.
It also updates the calcium concentration. t double time when the update is being performed
Referenced by nest::SimulationManager::update_.
virtual void nest::Node::decay_synaptic_elements_vacant()
Is used to reduce the number of synaptic elements in the node through time.
This amount is defined by tau_vacant.
Referenced by nest::SimulationManager::update_.
virtual void nest::Node::connect_synaptic_element(Name, int)
Is used to update the number of connected synaptic elements (SynapticElement::z_connected_) when a synapse is formed or deleted.
type Name, name of the synaptic element to connect n int number of new connections of the given type