SLIMessaging
void SLIInterpreter::verbosity(int)
Set the verbosity level of the SLI messaging mechanism.
Only messages having an error level that is equal to or greater than this level will be displayed by the interpreter. verbosity(void), message(), debug(), status(), info(), warning(), error(), fatal()
References SLIInterpreter::verbositylevel.
Referenced by SetVerbosityFunction::execute, VerbosityFunction::execute, SLIStartup::init.
int SLIInterpreter::verbosity() const
Retrieve the current verbosity level of the SLI messaging mechanism.
Only messages having an error level that is equal to or greater than this level will be displayed by the interpreter. You may use any positive integer here. For conveniency, there exist five predifined error levels: SLIInterpreter::M_ALL=0, display all messages SLIInterpreter::M_DEBUG=5, display debugging messages and above SLIInterpreter::M_STATUS=7, display status messages and above SLIInterpreter::M_INFO=10, display information messages and above SLIInterpreter::M_PROGRESS=15, display test-related messages and above SLIInterpreter::M_DEPRECATED=18, display deprecation warnings and above SLIInterpreter::M_WARNING=20, display warning messages and above SLIInterpreter::M_ERROR=30, display error messages and above SLIInterpreter::M_FATAL=40, display failure messages and above SLIInterpreter::M_QUIET=100, suppress all messages Thus, by calling verbosity(SLIInterpreter::M_WARNING) you indicate that you are interested in seeing error messages and more important messages only. verbosity(void), message(), debug(), status(), info(), warning(), error(), fatal()
References SLIInterpreter::verbositylevel.
void SLIInterpreter::message(int level, const char from[], const char text[], const char errorname[]="") const
Display a message.
level The error level that shall be associated with the message. You may use any positive integer here. For convenience, there exist five predefined error levels: (SLIInterpreter::M_ALL=0, for use with verbosity(int) only, see there), SLIInterpreter::M_DEBUG=5, a debugging message SLIInterpreter::M_STATUS=7, a status message SLIInterpreter::M_INFO=10, an informational message SLIInterpreter::M_PROGRESS=15, a test-related message SLIInterpreter::M_DEPRECATED=18, a deprecation warning SLIInterpreter::M_WARNING=20, a warning message SLIInterpreter::M_ERROR=30, an error message SLIInterpreter::M_FATAL=40, a failure message. (SLIInterpreter::M_QUIET=100, for use with verbosity(int) only, see there), from A string specifying the name of the function that sends the message. test A string specifying the message text. The message will ony be displayed if the current verbosity level is greater than or equal to the specified level. If two or more messages are issued after each other, that have the same from and level argument, the messages will be grouped together in the output. verbosity(void), verbosity(int)
References SLIInterpreter::M_ALL_NAME, SLIInterpreter::M_DEBUG, SLIInterpreter::M_DEBUG_NAME, SLIInterpreter::M_DEPRECATED, SLIInterpreter::M_DEPRECATED_NAME, SLIInterpreter::M_ERROR, SLIInterpreter::M_ERROR_NAME, SLIInterpreter::M_FATAL, SLIInterpreter::M_FATAL_NAME, SLIInterpreter::M_INFO, SLIInterpreter::M_INFO_NAME, SLIInterpreter::M_PROGRESS, SLIInterpreter::M_PROGRESS_NAME, SLIInterpreter::M_STATUS, SLIInterpreter::M_STATUS_NAME, SLIInterpreter::M_WARNING, SLIInterpreter::M_WARNING_NAME, SLIInterpreter::message, SLIInterpreter::verbositylevel.
Referenced by SLIInterpreter::addmodule, SLIInterpreter::backtrace_off, SLIInterpreter::backtrace_on, Processes::ForkFunction::execute, SLIArrayModule::IMap_ivFunction::execute, SLIArrayModule::IMap_dvFunction::execute, SLIArrayModule::ArraycreateFunction::execute, SLIArrayModule::SortFunction::execute, SLIArrayModule::Put_a_a_tFunction::execute, SLIArrayModule::AreaFunction::execute, SLIArrayModule::Area2Function::execute, SLIArrayModule::Cv1dFunction::execute, SLIArrayModule::Cv2dFunction::execute, SLIArrayModule::GetMaxFunction::execute, SLIArrayModule::GetMinFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::Add_iv_ivFunction::execute, SLIArrayModule::Sub_iv_ivFunction::execute, SLIArrayModule::Mul_iv_ivFunction::execute, SLIArrayModule::Div_iv_ivFunction::execute, SLIArrayModule::Add_dv_dvFunction::execute, SLIArrayModule::Sub_dv_dvFunction::execute, SLIArrayModule::Mul_dv_dvFunction::execute, SLIArrayModule::Div_dv_dvFunction::execute, SLIArrayModule::Inv_dvFunction::execute, CloseinputFunction::execute, StopFunction::execute, StartFunction::execute, RaiseerrorFunction::execute, PclocksFunction::execute, PclockspersecFunction::execute, PgetrusageFunction::execute, MessageFunction::execute, Get_a_aFunction::execute, Join_sFunction::execute, DictconstructFunction::execute, SLIgraphics::ReadPGMFunction::execute, SLIgraphics::WritePGMFunction::execute, AddtotrieFunction::execute, FunctionDatum::execute, SLIInterpreter::execute_, SLIInterpreter::execute_debug_, SLIStartup::init, SLIModule::install, SLIInterpreter::message, SLIInterpreter::print_error, sli_logging, SLIInterpreter::terminate, SLIInterpreter::toggle_stack_display.