iaf_psc_exp_ps_lossless_data
Parameters_ nest::iaf_psc_exp_ps_lossless::P_
Referenced by nest::iaf_psc_exp_ps_lossless::get_status, nest::iaf_psc_exp_ps_lossless::get_V_m_, nest::iaf_psc_exp_ps_lossless::set_status.
State_ nest::iaf_psc_exp_ps_lossless::S_
Referenced by nest::iaf_psc_exp_ps_lossless::get_I_syn_, nest::iaf_psc_exp_ps_lossless::get_I_syn_ex_, nest::iaf_psc_exp_ps_lossless::get_I_syn_in_, nest::iaf_psc_exp_ps_lossless::get_status, nest::iaf_psc_exp_ps_lossless::get_V_m_, nest::iaf_psc_exp_ps_lossless::set_status.
Variables_ nest::iaf_psc_exp_ps_lossless::V_
Buffers_ nest::iaf_psc_exp_ps_lossless::B_
Referenced by nest::iaf_psc_exp_ps_lossless::handles_test_event.
double nest::iaf_psc_exp_ps_lossless::Parameters_::tau_m_
Membrane time constant in ms.
double nest::iaf_psc_exp_ps_lossless::Parameters_::tau_ex_
Time constant of exc.
synaptic current in ms.
double nest::iaf_psc_exp_ps_lossless::Parameters_::tau_in_
Time constant of inh.
synaptic current in ms.
double nest::iaf_psc_exp_ps_lossless::Parameters_::c_m_
Membrane capacitance in pF.
double nest::iaf_psc_exp_ps_lossless::Parameters_::t_ref_
Refractory period in ms.
double nest::iaf_psc_exp_ps_lossless::Parameters_::E_L_
Resting potential in mV.
Referenced by nest::iaf_psc_exp_ps_lossless::get_V_m_.
double nest::iaf_psc_exp_ps_lossless::Parameters_::I_e_
External DC current [pA].
double nest::iaf_psc_exp_ps_lossless::Parameters_::U_th_
Threshold, RELATIVE TO RESTING POTENTAIL(!).
I.e. the real threshold is U_th_ + E_L_.
double nest::iaf_psc_exp_ps_lossless::Parameters_::U_min_
Lower bound, RELATIVE TO RESTING POTENTAIL(!).
I.e. the real lower bound is U_min_+E_L_.
double nest::iaf_psc_exp_ps_lossless::Parameters_::U_reset_
Reset potential.
At threshold crossing, the membrane potential is reset to this value. Relative to resting potential.
double nest::iaf_psc_exp_ps_lossless::State_::y0_
External input current.
double nest::iaf_psc_exp_ps_lossless::State_::I_syn_ex_
Exc. exponential current.
Referenced by nest::iaf_psc_exp_ps_lossless::get_I_syn_, nest::iaf_psc_exp_ps_lossless::get_I_syn_ex_.
double nest::iaf_psc_exp_ps_lossless::State_::I_syn_in_
Inh. exponential current.
Referenced by nest::iaf_psc_exp_ps_lossless::get_I_syn_, nest::iaf_psc_exp_ps_lossless::get_I_syn_in_.
double nest::iaf_psc_exp_ps_lossless::State_::y2_
Membrane potential (relative to resting potential)
Referenced by nest::iaf_psc_exp_ps_lossless::get_V_m_.
bool nest::iaf_psc_exp_ps_lossless::State_::is_refractory_
True while refractory.
long nest::iaf_psc_exp_ps_lossless::State_::last_spike_step_
Time stamp of most recent spike.
double nest::iaf_psc_exp_ps_lossless::State_::last_spike_offset_
Offset of most recent spike.
SliceRingBuffer nest::iaf_psc_exp_ps_lossless::Buffers_::events_
Queue for incoming events.
Handles also pseudo-events marking return from refractoriness.
RingBuffer nest::iaf_psc_exp_ps_lossless::Buffers_::currents_
UniversalDataLogger< iaf_psc_exp_ps_lossless > nest::iaf_psc_exp_ps_lossless::Buffers_::logger_
Logger for all analog data.
Referenced by nest::iaf_psc_exp_ps_lossless::handles_test_event.
double nest::iaf_psc_exp_ps_lossless::Variables_::h_ms_
Time resolution [ms].
long nest::iaf_psc_exp_ps_lossless::Variables_::refractory_steps_
Refractory time in steps.
double nest::iaf_psc_exp_ps_lossless::Variables_::expm1_tau_m_
expm1(-h/tau_m)
double nest::iaf_psc_exp_ps_lossless::Variables_::exp_tau_ex_
exp(-h/tau_ex)
double nest::iaf_psc_exp_ps_lossless::Variables_::exp_tau_in_
exp(-h/tau_in)
double nest::iaf_psc_exp_ps_lossless::Variables_::P20_
Progagator matrix element, 2nd row.
double nest::iaf_psc_exp_ps_lossless::Variables_::P21_in_
Progagator matrix element, 2nd row.
double nest::iaf_psc_exp_ps_lossless::Variables_::P21_ex_
Progagator matrix element, 2nd row.
double nest::iaf_psc_exp_ps_lossless::Variables_::y0_before_
y0_ at beginning of ministep
double nest::iaf_psc_exp_ps_lossless::Variables_::I_syn_ex_before_
I_syn_ex_ at beginning of ministep.
double nest::iaf_psc_exp_ps_lossless::Variables_::I_syn_in_before_
I_syn_in_ at beginning of ministep.
double nest::iaf_psc_exp_ps_lossless::Variables_::y2_before_
y2_ at beginning of ministep
double nest::iaf_psc_exp_ps_lossless::Variables_::a1_
Pre-computed constants for inequality V < g(h, I_e)
double nest::iaf_psc_exp_ps_lossless::Variables_::a2_
double nest::iaf_psc_exp_ps_lossless::Variables_::a3_
double nest::iaf_psc_exp_ps_lossless::Variables_::a4_
double nest::iaf_psc_exp_ps_lossless::Variables_::b1_
Pre-computed constants for inequality V < f(h, I)
double nest::iaf_psc_exp_ps_lossless::Variables_::b2_
double nest::iaf_psc_exp_ps_lossless::Variables_::b3_
double nest::iaf_psc_exp_ps_lossless::Variables_::b4_
double nest::iaf_psc_exp_ps_lossless::Variables_::c1_
Pre-computed constants for inequality V < b(I_e)
double nest::iaf_psc_exp_ps_lossless::Variables_::c2_
double nest::iaf_psc_exp_ps_lossless::Variables_::c3_
double nest::iaf_psc_exp_ps_lossless::Variables_::c4_
double nest::iaf_psc_exp_ps_lossless::Variables_::c5_
double nest::iaf_psc_exp_ps_lossless::Variables_::c6_
nest::RecordablesMap< nest::iaf_psc_exp_ps_lossless > nest::iaf_psc_exp_ps_lossless::recordablesMap_
Mapping of recordables names to access functions.
Referenced by nest::iaf_psc_exp_ps_lossless::get_status, nest::iaf_psc_exp_ps_lossless::handles_test_event, nest::iaf_psc_exp_ps_lossless::iaf_psc_exp_ps_lossless.
nest::iaf_psc_exp_ps_lossless::Parameters_::Parameters_()
Sets default parameter values.
void nest::iaf_psc_exp_ps_lossless::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::C_m, nest::names::d, nest::names::E_L, nest::names::I_e, nest::names::t_ref, nest::names::tau_m, nest::names::tau_syn_ex, nest::names::tau_syn_in, nest::names::V_min, nest::names::V_reset, nest::names::V_th.
Referenced by nest::iaf_psc_exp_ps_lossless::get_status.
double nest::iaf_psc_exp_ps_lossless::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::C_m, nest::names::d, nest::names::E_L, nest::names::I_e, nest::names::t_ref, nest::names::tau_m, nest::names::tau_syn_ex, nest::names::tau_syn_in, nest::names::V_min, nest::names::V_reset, nest::names::V_th.
Referenced by nest::iaf_psc_exp_ps_lossless::set_status.
nest::iaf_psc_exp_ps_lossless::State_::State_()
Default initialization.
void nest::iaf_psc_exp_ps_lossless::State_::get(DictionaryDatum &, const Parameters_ &) const
References nest::names::d, nest::names::I_syn, nest::names::I_syn_ex, nest::names::I_syn_in, nest::names::is_refractory, nest::names::offset, nest::names::p, nest::names::V_m.
Referenced by nest::iaf_psc_exp_ps_lossless::get_status.
void nest::iaf_psc_exp_ps_lossless::State_::set(const DictionaryDatum &, const Parameters_ &, double delta_EL, Node *)
References nest::names::d, nest::names::I_syn_ex, nest::names::I_syn_in, nest::names::p, nest::names::V_m.
Referenced by nest::iaf_psc_exp_ps_lossless::set_status.
nest::iaf_psc_exp_ps_lossless::Buffers_::Buffers_(iaf_psc_exp_ps_lossless &)
nest::iaf_psc_exp_ps_lossless::Buffers_::Buffers_(const Buffers_ &, iaf_psc_exp_ps_lossless &)