interpret.cc
void init_slidict(SLIInterpreter *)
References cleardictfunction, cleardictstackfunction, clonedictfunction, countdictstackfunction, SLIInterpreter::createcommand, currentdictfunction, cva_dfunction, dictbeginfunction, dictconstructfunction, dictendfunction, dictfunction, dictgetfunction, dictinfofunction, dictputfunction, dictstackfunction, dicttopinfofunction, empty_Dfunction, SLIInterpreter::end_name, keysfunction, knownfunction, length_dfunction, restoredstackfunction, undeffunction, valuesfunction, whofunction.
Referenced by SLIInterpreter::initexternals.
void init_slicontrol(SLIInterpreter *)
@BeginDocumentation Name: mark - puts a mark on the stack
Description: A mark is a token which is lying on the stack and can be found by the user. The mark is used : 1) by using it as command mark 2) by using it as [ when creating an array 3) by using it as << when creating a dict Examples: [ 1 2 add ] -> [3] mark 1 2 add ] -> [3] Author: docu by Marc Oliver Gewaltig and Sirko Straube SeeAlso: counttomark, arraystore, switch, case
References backtrace_offfunction, backtrace_onfunction, casefunction, closeinputfunction, codeaccessedfunction, codeexecutedfunction, counttomarkfunction, SLIInterpreter::createcommand, currentnamefunction, cyclesfunction, debugfunction, debugofffunction, debugonfunction, SLIInterpreter::def, deffunction, estackdumpfunction, execfunction, exitfunction, SLIInterpreter::false_name, forall_afunction, forall_sfunction, forallindexed_afunction, forallindexed_sfunction, forfunction, ifelsefunction, iffunction, iparsefunction, iparsestdinfunction, SLIInterpreter::istopped_name, loadfunction, lookupfunction, loopfunction, SLIInterpreter::mark_name, messagefunction, SLIInterpreter::newerror_name, noopfunction, ostackdumpfunction, parsestdinfunction, pclocksfunction, pclockspersecfunction, pgetrusagefunction, printerrorfunction, quitfunction, raiseagainfunction, raiseerrorfunction, SLIInterpreter::recordstacks_name, removeguardfunction, repeatfunction, setfunction, setguardfunction, setverbosityfunction, sleep_dfunction, startfunction, stopfunction, stoppedfunction, switchdefaultfunction, switchfunction, symbol_sfunction, timefunction, token_isfunction, token_sfunction, SLIInterpreter::true_name, typeinfofunction, verbosityfunction.
Referenced by SLIInterpreter::initexternals.
void init_sli_io(SLIInterpreter *)
References closeistreamfunction, closeostreamfunction, SLIInterpreter::createcommand, cvx_ffunction, SLIInterpreter::def_move, eatwhitefunction, endlfunction, endsfunction, flushfunction, getcfunction, getlinefunction, getsfunction, iclearfunction, ieoffunction, ifailfunction, ifstreamfunction, igoodfunction, in_availfunction, iosdecfunction, iosdefaultfunction, iosfixedfunction, ioshexfunction, iosinternalfunction, iosleftfunction, iosnoshowbasefunction, iosnoshowpointfunction, iosoctfunction, iosrightfunction, iosscientificfunction, iosshowbasefunction, iosshowpointfunction, mathlinkputstringfunction, oclearfunction, oeoffunction, ofsopenfunction, ofstreamfunction, ogoodfunction, ostrstreamfunction, prettyprintfunction, printfunction, readdoublefunction, readintfunction, readwordfunction, setprecisionfunction, setwfunction, strfunction, xifstreamfunction.
Referenced by SLIInterpreter::initexternals.
void init_slistack(SLIInterpreter *)
References clearfunction, copyfunction, countfunction, SLIInterpreter::createcommand, dupfunction, exchfunction, execstackfunction, indexfunction, npopfunction, operandstackfunction, overfunction, popfunction, restoreestackfunction, restoreostackfunction, rolldfunction, rollfunction, rollufunction, rotfunction.
Referenced by SLIInterpreter::initexternals.
void init_slimath(SLIInterpreter *)
References abs_dfunction, abs_ifunction, acos_dfunction, add_ddfunction, add_difunction, add_idfunction, add_iifunction, and_iifunction, andfunction, asin_dfunction, ceil_dfunction, cos_dfunction, SLIInterpreter::createcommand, dexp_ifunction, div_ddfunction, div_difunction, div_idfunction, div_iifunction, doublefunction, eqfunction, exp_dfunction, floor_dfunction, frexp_dfunction, geq_ddfunction, geq_difunction, geq_idfunction, geq_iifunction, gt_ddfunction, gt_difunction, gt_idfunction, gt_iifunction, gt_ssfunction, integerfunction, inv_dfunction, ldexp_difunction, leq_ddfunction, leq_difunction, leq_idfunction, leq_iifunction, ln_dfunction, log_dfunction, lt_ddfunction, lt_difunction, lt_idfunction, lt_iifunction, lt_ssfunction, max_d_dfunction, max_d_ifunction, max_i_dfunction, max_i_ifunction, min_d_dfunction, min_d_ifunction, min_i_dfunction, min_i_ifunction, mod_iifunction, modf_dfunction, mul_ddfunction, mul_difunction, mul_idfunction, mul_iifunction, neg_dfunction, neg_ifunction, neqfunction, not_bfunction, not_ifunction, or_iifunction, orfunction, pow_ddfunction, pow_difunction, round_dfunction, sin_dfunction, sqr_dfunction, sqrt_dfunction, sub_ddfunction, sub_difunction, sub_idfunction, sub_iifunction, unitstep_dafunction, unitstep_dfunction, unitstep_iafunction, unitstep_ifunction, xorfunction.
Referenced by SLIInterpreter::initexternals.
void init_slitypecheck(SLIInterpreter *)
References addtotriefunction, SLIInterpreter::createcommand, cva_tfunction, cvt_afunction, triefunction, trieinfofunction, typefunction.
Referenced by SLIInterpreter::initexternals.
void init_slidata(SLIInterpreter *)
References allocations_afunction, append_afunction, append_pfunction, append_sfunction, capacity_afunction, capacity_sfunction, SLIInterpreter::createcommand, cvd_sfunction, cvi_sfunction, cvlit_nfunction, cvlit_pfunction, cvlp_pfunction, cvn_lfunction, cvn_sfunction, cvx_afunction, empty_afunction, empty_sfunction, erase_afunction, erase_pfunction, erase_sfunction, get_a_afunction, get_afunction, get_lpfunction, get_pfunction, get_sfunction, getinterval_afunction, getinterval_sfunction, insert_afunction, insert_sfunction, insertelement_afunction, insertelement_sfunction, irepeatanyfunction, join_afunction, join_pfunction, join_sfunction, length_afunction, length_lpfunction, length_pfunction, length_sfunction, prepend_afunction, prepend_pfunction, prepend_sfunction, put_afunction, put_lpfunction, put_pfunction, put_sfunction, references_afunction, repeatanyfunction, replace_afunction, replace_sfunction, reserve_afunction, reserve_sfunction, resize_afunction, resize_sfunction, search_afunction, search_sfunction, shrink_afunction, size_afunction, size_sfunction.
Referenced by SLIInterpreter::initexternals.
void init_slistring(SLIInterpreter *)
References SLIInterpreter::createcommand, tolowercase_sfunction, touppercase_sfunction.
Referenced by SLIInterpreter::initexternals.