numerics
const double numerics::e
Referenced by nest::beta_normalization_factor, SLIInterpreter::initbuiltins, nest::glif_psc::pre_run_hook, nest::iaf_psc_alpha::pre_run_hook, nest::iaf_psc_alpha_multisynapse::pre_run_hook, nest::iaf_psc_alpha_ps::pre_run_hook.
const double numerics::pi
Referenced by nest::BoxMask< D >::BoxMask, nest::EllipseMask< D >::EllipseMask, SLIArrayModule::GaborFunction::execute, nest::sinusoidal_poisson_generator::Parameters_::get, SLIInterpreter::initbuiltins, nest::ac_generator::pre_run_hook, nest::noise_generator::pre_run_hook, nest::ppd_sup_generator::pre_run_hook, nest::sinusoidal_poisson_generator::Parameters_::set.
const double numerics::nan
Referenced by nest::ConnectionManager::connect_arrays, nest::ConnectionCreator::ConnectionCreator, IAFPropagator::evaluate_P32_, nest::ConnectionCreator::extract_params_, nest::rate_neuron_ipn< TNonlinearities >::init_buffers_, nest::rate_neuron_opn< TNonlinearities >::init_buffers_, nest::iaf_psc_exp_ps_lossless::is_spike_, nest::ConnBuilder::single_connect_, nest::rate_neuron_ipn< TNonlinearities >::update_, nest::rate_neuron_opn< TNonlinearities >::update_.
double numerics::expm1(double x)
Supply expm1() function independent of system.
Implemented inline for efficiency.
Referenced by IAFPropagator::evaluate_P32_, nest::iaf_psc_exp_ps_lossless::is_spike_, nest::gif_psc_exp::pre_run_hook, nest::gif_psc_exp_multisynapse::pre_run_hook, nest::iaf_psc_alpha::pre_run_hook, nest::iaf_psc_alpha_ps::pre_run_hook, nest::iaf_psc_delta_ps::pre_run_hook, nest::iaf_psc_exp_ps::pre_run_hook, nest::iaf_psc_exp_ps_lossless::pre_run_hook, nest::rate_neuron_ipn< TNonlinearities >::pre_run_hook, nest::rate_neuron_opn< TNonlinearities >::pre_run_hook, nest::iaf_psc_alpha_ps::propagate_, nest::iaf_psc_delta_ps::propagate_, nest::iaf_psc_exp_ps::propagate_, nest::iaf_psc_exp_ps_lossless::propagate_, nest::iaf_psc_alpha_ps::threshold_distance, nest::iaf_psc_exp_ps::threshold_distance, nest::iaf_psc_exp_ps_lossless::threshold_distance, nest::gif_psc_exp::update, nest::gif_psc_exp_multisynapse::update, nest::pp_psc_delta::update, nest::stdp_dopamine_synapse< targetidentifierT >::update_weight_.
bool numerics::is_nan(T f)
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection, nest::iaf_psc_exp_ps_lossless::update.