boost::tuples
void boost::tuples::swap(boost::tuple< T &, U & > a, boost::tuple< T &, U & > b) noexcept
Exchanges values of two two-element tuples.
T Type of the first value in the tuples. U Type of the second value in the tuples.
References nest::names::a, nest::names::b.
Referenced by nest::NodeManager::add_node, nest::ConnBuilder::connect, nest::TargetTable::finalize, nest::TargetTableDevices::finalize, nest::ConnectionManager::finalize, nest::EventDeliveryManager::finalize, nest::insertion_sort, nest::quicksort3way.
bool boost::tuples::operator<(const cons< T1, T2 > &lhs, const cons< S1, S2 > &rhs)
Less than relational operator for Boost tuples.
lhs First operand. rhs Second operand. Modified operator, based on the less than operator from the Boost library. Have to implement a custom operator to only compare the first values of the tuples.
Referenced by bv_iterator< value_type_, ref_, ptr_ >::operator<=.