nest
severity_t
RegisterConnectionModelFlags
SignalType
enum_status_spike_data_id
enum_status_target_id
enum_status_target_data_id
typedef void(* nest::deliver_logging_event_ptr) (const LoggingEvent &e))(const LoggingEvent &e)
typedef binary_neuron< nest::gainfunction_erfc > nest::erfc_neuron
typedef rate_neuron_ipn< nest::nonlinearities_gauss_rate > nest::gauss_rate_ipn
typedef rate_transformer_node< nest::nonlinearities_gauss_rate > nest::rate_transformer_gauss
typedef binary_neuron< nest::gainfunction_ginzburg > nest::ginzburg_neuron
typedef rate_neuron_ipn< nest::nonlinearities_lin_rate > nest::lin_rate_ipn
typedef rate_neuron_opn< nest::nonlinearities_lin_rate > nest::lin_rate_opn
typedef rate_transformer_node< nest::nonlinearities_lin_rate > nest::rate_transformer_lin
typedef nest::binary_neuron< nest::gainfunction_mcculloch_pitts > nest::mcculloch_pitts_neuron
typedef rate_neuron_ipn< nest::nonlinearities_sigmoid_rate > nest::sigmoid_rate_ipn
typedef rate_transformer_node< nest::nonlinearities_sigmoid_rate > nest::rate_transformer_sigmoid
typedef rate_neuron_ipn< nest::nonlinearities_sigmoid_rate_gg_1998 > nest::sigmoid_rate_gg_1998_ipn
typedef rate_transformer_node< nest::nonlinearities_sigmoid_rate_gg_1998 > nest::rate_transformer_sigmoid_gg_1998
typedef rate_neuron_ipn< nest::nonlinearities_tanh_rate > nest::tanh_rate_ipn
typedef rate_neuron_opn< nest::nonlinearities_tanh_rate > nest::tanh_rate_opn
typedef rate_transformer_node< nest::nonlinearities_tanh_rate > nest::rate_transformer_tanh
typedef rate_neuron_ipn< nest::nonlinearities_threshold_lin_rate > nest::threshold_lin_rate_ipn
typedef rate_neuron_opn< nest::nonlinearities_threshold_lin_rate > nest::threshold_lin_rate_opn
typedef rate_transformer_node< nest::nonlinearities_threshold_lin_rate > nest::rate_transformer_threshold_lin
typedef MPIManager::OffGridSpike nest::OffGridSpike
typedef std::shared_ptr< AbstractLayer > nest::AbstractLayerPTR
typedef sharedPtrDatum< AbstractMask, &NestModule::MaskType > nest::MaskDatum
typedef long nest::tic_t
Type for Time tics.
typedef size_t nest::index
Unsigned long type for enumerations.
typedef unsigned int nest::synindex
For enumerations of synapse types.
typedef unsigned short nest::targetindex
Unsigned short type for compact target representation.
See Kunkel et al, Front Neuroinform 8:78 (2014). target index into thread local node vector
typedef int nest::thread
Thread index type.
NEST threads are assigned non-negative numbers for identification. For invalid or undefined threads, the value -1 is used.
typedef long nest::rport
Connection port number to distinguish incoming connections, also called receiver port.
Connections between Nodes are assigned port numbers. Valid port numbers start at zero (0). The value -1 is used for invalid or unassigned ports.
typedef long nest::port
Connection port number to distinguish outgoing connections.
Connections between Nodes are assigned port numbers. Valid port numbers start at zero (0). The value -1 is used for invalid or unassigned ports.
typedef double nest::weight
Weight of a connection.
Connections have a weight which is used to scale the influence of an event. A weight of 0 should have the same influence on the receiving node as a non-existing connection. Otherwise, there is no default range for connection weights.
typedef long nest::delay
Delay of a connection.
The delay defines the number of simulation steps which elapse before an Event arrives at the receiving Node. Delays must be equal or larger than one.
using nest::NodeCollectionPTR = typedef std::shared_ptr< NodeCollection >
using nest::NodeCollectionMetadataPTR = typedef std::shared_ptr< NodeCollectionMetadata >
using nest::RngPtr = typedef BaseRandomGenerator*
using nest::uniform_int_distribution = typedef RandomDistribution< std::uniform_int_distribution< unsigned long > >
using nest::uniform_real_distribution = typedef RandomDistribution< std::uniform_real_distribution<> >
using nest::poisson_distribution = typedef RandomDistribution< std::poisson_distribution< unsigned long > >
using nest::normal_distribution = typedef RandomDistribution< std::normal_distribution<> >
using nest::lognormal_distribution = typedef RandomDistribution< std::lognormal_distribution<> >
using nest::binomial_distribution = typedef RandomDistribution< std::binomial_distribution< unsigned long > >
using nest::gamma_distribution = typedef RandomDistribution< std::gamma_distribution<> >
using nest::exponential_distribution = typedef RandomDistribution< std::exponential_distribution<> >
using nest::discrete_distribution = typedef RandomDistribution< std::discrete_distribution< unsigned long > >
using nest::success_spike_data_size = typedef StaticAssert< sizeof( SpikeData ) == 8 >::success
check legal size
using nest::success_offgrid_spike_data_size = typedef StaticAssert< sizeof( OffGridSpikeData ) == 16 >::success
check legal size
using nest::success_syn_id_delay_data_size = typedef StaticAssert< sizeof( SynIdDelay ) == 4 >::success
check legal size
using nest::success_target_size = typedef StaticAssert< sizeof( Target ) == 8 >::success
using nest::success_target_data_fields_size = typedef StaticAssert< sizeof( TargetDataFields ) == 8 >::success
check legal size
using nest::success_secondary_target_data_fields_size = typedef StaticAssert< sizeof( SecondaryTargetDataFields ) == 8 >::success
check legal size
using nest::success_target_data_size = typedef StaticAssert< sizeof( TargetData ) == 12 >::success
check legal size
const long nest::UNLABELED_CONNECTION
Connections are unlabeled by default.
Unlabeled connections cannot be specified as a search criterion in the GetConnections function. ConnectionLabel
Referenced by nest::Connector< ConnectionT >::get_connection, nest::Connector< ConnectionT >::get_connection_with_specified_targets, nest::ConnectionManager::get_connections, nest::Connection< targetidentifierT >::get_label, nest::TargetTableDevices::is_device_connected.
const RegisterConnectionModelFlags nest::default_connection_model_flags
Referenced by nest::ModelsModule::init.
const RegisterConnectionModelFlags nest::default_secondary_connection_model_flags
const Time nest::TimeZero
Referenced by nest::SimulationManager::set_status.
constexpr uint8_t nest::NUM_BITS_RANK
constexpr uint8_t nest::NUM_BITS_TID
constexpr uint8_t nest::NUM_BITS_SYN_ID
constexpr uint8_t nest::NUM_BITS_LCID
constexpr uint8_t nest::NUM_BITS_PROCESSED_FLAG
constexpr uint8_t nest::NUM_BITS_MARKER_SPIKE_DATA
constexpr uint8_t nest::NUM_BITS_LAG
constexpr uint8_t nest::NUM_BITS_DELAY
constexpr uint8_t nest::NUM_BITS_NODE_ID
constexpr uint64_t nest::MAX_LCID
Referenced by nest::ConnectionManager::increase_connection_count, nest::SpikeData::set, nest::OffGridSpikeData::set, nest::Target::set_lcid, nest::Target::Target.
constexpr int64_t nest::MAX_RANK
Referenced by nest::Target::set_rank, nest::Target::Target.
constexpr int64_t nest::MAX_TID
Referenced by nest::SpikeData::set, nest::OffGridSpikeData::set, nest::TargetData::set_source_tid, nest::Target::set_tid, nest::Target::Target.
constexpr uint64_t nest::MAX_SYN_ID
Referenced by nest::ModelManager::copy_connection_model_, nest::ModelManager::get_status, nest::SpikeData::set, nest::OffGridSpikeData::set, nest::Target::set_syn_id, nest::Target::Target.
constexpr uint64_t nest::DISABLED_NODE_ID
Referenced by nest::Source::disable, nest::Source::is_disabled.
constexpr uint64_t nest::MAX_NODE_ID
Referenced by nest::Source::set_node_id, nest::Source::Source.
const tic_t nest::tic_t_max
const tic_t nest::tic_t_min
const synindex nest::invalid_synindex
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection_, nest::ModelManager::copy_connection_model_, nest::ConnectionManager::disconnect, nest::StimulationDevice::enforce_single_syn_type, nest::ModelManager::get_num_connection_models, nest::SourceTable::pack_source_node_id_and_syn_id, nest::StimulationDevice::StimulationDevice.
const targetindex nest::invalid_targetindex
Referenced by nest::TargetIdentifierIndex::get_status, nest::TargetIdentifierIndex::get_target_ptr.
const thread nest::invalid_thread
Value for invalid connection port number.
Referenced by nest::SymmetricBernoulliBuilder::connect_, nest::Node::is_model_prototype.
const rport nest::invalid_port
Value for invalid connection port number.
Referenced by nest::bernoulli_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::clopath_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::cont_delay_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::ht_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::jonke_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::quantal_stp_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::static_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::static_synapse_hom_w< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_dopamine_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_nn_pre_centered_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_nn_restr_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_nn_symm_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_pl_synapse_hom< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_facetshw_synapse_hom< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_synapse_hom< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::stdp_triplet_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::tsodyks2_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::tsodyks_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::tsodyks_synapse_hom< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::urbanczik_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::vogels_sprekeler_synapse< targetidentifierT >::ConnTestDummyNode::handles_test_event, nest::gamma_sup_generator::send_test_event, nest::multimeter::send_test_event, nest::noise_generator::send_test_event, nest::poisson_generator_ps::send_test_event, nest::ppd_sup_generator::send_test_event.
const long nest::delay_min
const long nest::delay_max
struct nest::PrimitiveSortObject nest::primitiveSort
Referenced by nest::NodeCollectionComposite::NodeCollectionComposite, nest::NodeCollectionComposite::operator+.
double nest::beta_normalization_factor(const double tau_rise, const double tau_decay)
Computes the normalization constant for the beta function.
tau_rise Synaptic rise time constant, in ms tau_decay Synaptic decay time constant, in ms Calculates the factor used to normalize the synaptic conductance such that incoming spike causes a peak conductance of 1 nS. The solution to the beta function ODE obtained by the solver is g(t) = c / ( a - b ) * ( e^(-b t) - e^(-a t) ) with a = 1/tau_rise, b = 1/tau_decay, a != b. The maximum of this function is at t* = 1/(a-b) ln a/b We want to scale the function so that max g == g(t*) == g_peak We thus need to set c = g_peak * ( a - b ) / ( e^(-b t*) - e^(-a t*) ) See Rotter & Diesmann, Biol Cybern 81:381 (1999) and Roth and van Rossum, Ch 6, in De Schutter, Computational Modeling Methods for Neuroscientists, MIT Press, 2010. The denominator, tau_difference, that appears in the expression of the peak time is computed here to check that it is not zero. Another denominator, peak_value, appears in the expression of the normalization factor. Both tau_difference and peak_value are zero if tau_decay = tau_rise. But they can also be zero if tau_decay and tau_rise are not equal but very close to each other, due to the numerical precision limits. In such case the beta function reduces to the alpha function, and the normalization factor for the alpha function should be used.
References numerics::e.
bool nest::updateValueParam(DictionaryDatum const &d, Name const n, VT &value, nest::Node *node)
Update a variable from a dictionary entry if it exists, skip call if it doesn't.
If the dictionary entry is a parameter, return value generated from the parameter parameter.
References Token::datum, get_vp_specific_rng, kernel, Name::lookup, nest::VPManager::node_id_to_vp, nest::KernelManager::vp_manager, nest::VPManager::vp_to_thread.
std::enable_if< EnableBitMaskOperators< Enum >::enable, Enum >::type nest::operator|(Enum lhs, Enum rhs)
std::enable_if< EnableBitMaskOperators< Enum >::enable, Enum >::type nest::operator&(Enum lhs, Enum rhs)
std::enable_if< EnableBitMaskOperators< Enum >::enable, Enum >::type nest::operator^(Enum &lhs, Enum rhs)
std::enable_if< EnableBitMaskOperators< Enum >::enable, Enum >::type nest::operator|=(Enum &lhs, Enum rhs)
std::enable_if< EnableBitMaskOperators< Enum >::enable, Enum >::type nest::operator&=(Enum &lhs, Enum rhs)
std::enable_if< EnableBitMaskOperators< Enum >::enable, Enum >::type nest::operator^=(Enum &lhs, Enum rhs)
bool nest::enumFlagSet(const Enum en, const Enum flag)
Referenced by nest::ModelManager::register_connection_model, nest::ModelManager::register_secondary_connection_model.
std::ostream & nest::operator<<(std::ostream &out, const LoggingEvent &e)
double nest::regula_falsi(const CN &node, const double dt)
Localize threshold crossing by using Illinois algorithm of regula falsi method.
See https://en.wikipedia.org/wiki/Regula_falsi#The_Illinois_algorithm for details on the algorithm. Node model object that call function double length of interval since previous event time from previous event to threshold crossing
Referenced by nest::iaf_psc_exp_ps::emit_spike_, nest::iaf_psc_exp_ps_lossless::emit_spike_, nest::iaf_psc_alpha_ps::emit_spike_.
size_t nest::median3_(const BlockVector< T > &vec, const size_t i, const size_t j, const size_t k)
Calculates the median of three elements.
See http://algs4.cs.princeton.edu/23quicksort/QuickX.java.html.
Referenced by quicksort3way.
void nest::insertion_sort(BlockVector< T1 > &vec_sort, BlockVector< T2 > &vec_perm, const size_t lo, const size_t hi)
Insertion sort, adapted from Sedgewick & Wayne (2011), Algorithms 4th edition, p251ff.
Sorts the two vectors vec_sort and vec_perm, by sorting the entries in vec_sort and applying the same exchanges to vec_perm.
Referenced by quicksort3way.
void nest::quicksort3way(BlockVector< T1 > &vec_sort, BlockVector< T2 > &vec_perm, const size_t lo, const size_t hi)
Quicksort with 3-way partitioning, adapted from Sedgewick & Wayne (2011), Algorithms 4th edition, p296ff (see http://algs4.cs.princeton.edu/23quicksort/QuickX.java.html).
Recursively sorts the two vectors vec_sort and vec_perm, by sorting the entries in vec_sort and applying the same exchanges to vec_perm.
References insertion_sort, INSERTION_SORT_CUTOFF, median3_, quicksort3way, BlockVector< value_type_ >::size.
Referenced by quicksort3way, sort.
void nest::sort(BlockVector< T1 > &vec_sort, BlockVector< T2 > &vec_perm)
Sorts two vectors according to elements in first vector.
Convenience function.
References BlockVector< value_type_ >::begin, BlockVector< value_type_ >::end, make_iterator_pair, quicksort3way, BlockVector< value_type_ >::size.
Referenced by nest::Connector< ConnectionT >::sort_connections.
std::ostream & nest::operator<<(std::ostream &os, const Stopwatch &stopwatch)
static bool nest::node_id_less(const std::pair< Position< D >, index > &a, const std::pair< Position< D >, index > &b)
nest::KernelManager & nest::kernel()
References nest::KernelManager::get_kernel_manager.
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection, nest::TargetTableDevices::add_connection_from_device, nest::TargetTableDevices::add_connection_to_device, nest::NodeManager::add_devices_, nest::SparseNodeArray::add_local_node, nest::NodeManager::add_music_nodes_, nest::NodeManager::add_neurons_, nest::NodeManager::add_node, nest::SliceRingBuffer::add_spike, nest::TargetTable::add_target, nest::SimulationManager::advance_time_, apply, nest::NodeCollectionPrimitive::assert_consistent_model_ids_, nest::DelayChecker::assert_two_valid_delays_steps, nest::DelayChecker::assert_valid_delay_ms, nest::inhomogeneous_poisson_generator::Parameters_::assert_valid_rate_time_and_insert, nest::RecordingBackendSIONlib::build_filename_, nest::ConnectionManager::calibrate, nest::ModelManager::calibrate, nest::SimulationManager::call_update_, nest::ConnBuilder::change_connected_synaptic_elements, nest::RandomManager::check_rng_synchrony, nest::ConnectionManager::check_secondary_connections_exist, nest::stdp_dopamine_synapse< targetidentifierT >::check_synapse_params, nest::NodeManager::check_wfr_use, cleanup, nest::RecordingBackendMPI::cleanup, nest::SimulationManager::cleanup, nest::StimulationBackendMPI::cleanup, nest::RecordingBackendSIONlib::close_files_, nest::EventDeliveryManager::collocate_target_data_buffers_, nest::FreeLayer< D >::communicate_positions_, nest::ModelManager::compare_model_by_id_, nest::SourceTable::compute_buffer_pos_for_unique_secondary_sources, nest::ConnectionManager::compute_compressed_secondary_recv_buffer_positions, nest::RecordingBackendASCII::DeviceData::compute_filename_, nest::ConnectionManager::compute_target_data_buffer_size, nest::RecordingBackendASCII::compute_vp_node_id_string_, nest::EventDeliveryManager::configure_secondary_buffers, nest::EventDeliveryManager::configure_spike_data_buffers, nest::EventDeliveryManager::configure_spike_register, nest::ConnBuilder::ConnBuilder, nest::ConnBuilder::connect, connect, nest::ConnectionManager::connect, nest::OneToOneBuilder::connect_, nest::AllToAllBuilder::connect_, nest::FixedInDegreeBuilder::connect_, nest::FixedOutDegreeBuilder::connect_, nest::FixedTotalNumberBuilder::connect_, nest::BernoulliBuilder::connect_, nest::SymmetricBernoulliBuilder::connect_, nest::SPBuilder::connect_, nest::ConnectionManager::connect_, nest::ConnectionManager::connect_arrays, connect_arrays, connect_layers, nest::ConnectionCreator::connect_to_target_, nest::ConnectionManager::connection_required, nest::ConnectionCreator::ConnectionCreator, nest::ModelManager::copy_connection_model_, copy_model, nest::ModelManager::copy_node_model_, create, nest::NodeCollection::create_, nest::AbstractLayer::create_layer, nest::SPManager::delete_synapse, nest::SPManager::delete_synapses_from_post, nest::SPManager::delete_synapses_from_pre, nest::EventDeliveryManager::deliver_events_, nest::EventDeliveryManager::deliver_secondary_events, nest::ConnectionManager::deliver_secondary_events, nest::NodeManager::destruct_nodes_, nest::SliceRingBuffer::discard_events, nest::ConnBuilder::disconnect, disconnect, nest::SPManager::disconnect, nest::OneToOneBuilder::disconnect_, nest::AllToAllBuilder::disconnect_, displacement, distance, nest::EventDeliveryManager::distribute_target_data_buffers_, nest::Layer< D >::dump_connections, nest::iaf_psc_exp_ps::emit_instant_spike_, nest::iaf_psc_exp_ps_lossless::emit_instant_spike_, nest::iaf_psc_alpha_ps::emit_instant_spike_, nest::iaf_psc_delta_ps::emit_instant_spike_, nest::iaf_psc_exp_ps::emit_spike_, nest::iaf_psc_exp_ps_lossless::emit_spike_, nest::iaf_psc_delta_ps::emit_spike_, nest::iaf_psc_alpha_ps::emit_spike_, enable_dryrun_mode, nest::SPManager::enable_structural_plasticity, nest::NodeManager::ensure_valid_thread_local_ids, nest::NestModule::GetStatus_CFunction::execute, nest::NestModule::GetStatus_aFunction::execute, nest::NestModule::SetStatus_aaFunction::execute, nest::NestModule::CopyModel_l_l_DFunction::execute, nest::NestModule::Disconnect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_DFunction::execute, nest::NestModule::Connect_g_g_D_aFunction::execute, nest::NestModule::MemoryInfoFunction::execute, nest::NestModule::RankFunction::execute, nest::NestModule::NumProcessesFunction::execute, nest::NestModule::SyncProcessesFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::ProcessorNameFunction::execute, nest::NestModule::EnableStructuralPlasticity_Function::execute, nest::NestModule::DisableStructuralPlasticity_Function::execute, nest::NestModule::SetStdpEps_dFunction::execute, nest::NestModule::ConnectLayers_g_g_DFunction::execute, nest::ConnectionCreator::extract_params_, nest::SourceTable::fill_compressed_spike_data, nest::NodeManager::finalize_nodes, nest::SourceTable::find_maximal_position, nest::ConnectionCreator::fixed_indegree_, nest::ConnectionCreator::fixed_outdegree_, nest::EventDeliveryManager::gather_secondary_events, nest::EventDeliveryManager::gather_spike_data_, nest::EventDeliveryManager::gather_target_data, get_connection_status, get_connections, nest::ConnectionManager::get_connections, nest::TargetTableDevices::get_connections_from_devices_, nest::TargetTableDevices::get_connections_to_device_for_lid_, nest::TargetTableDevices::get_connections_to_devices_, nest::ModelManager::get_connector_defaults, nest::ConnectionManager::get_delay_checker, nest::VPManager::get_end_rank_per_thread, nest::ArchivingNode::get_history, nest::RingBuffer::get_index_, nest::MultRBuffer::get_index_, nest::ListRingBuffer::get_index_, nest::ArchivingNode::get_K_value, nest::ArchivingNode::get_K_values, get_kernel_status, nest::ListRingBuffer::get_list, nest::ClopathArchivingNode::get_LTD_value, nest::NodeManager::get_max_num_local_nodes, nest::Node::get_model_, get_model_defaults, nest::ModelRangeManager::get_model_of_node_id, nest::NodeManager::get_mpi_local_node_or_device_head, nest::Node::get_name, nest::SourceTable::get_next_target_data, nest::SourceTable::get_node_id, nest::NodeManager::get_node_or_proxy, get_node_status, nest::NodeManager::get_nodes, get_nodes, nest::VPManager::get_num_assigned_ranks_per_thread, nest::VPManager::get_num_virtual_processes, nest::RecordingBackendMPI::get_port, nest::StimulationBackendMPI::get_port, get_position, nest::SimulationManager::get_previous_slice_origin, nest::ModelManager::get_proxy_node, get_rank_synced_rng, nest::ConnectionManager::get_sources, nest::Model::get_status, nest::multimeter::get_status, nest::spike_recorder::get_status, nest::spin_detector::get_status, nest::weight_recorder::get_status, nest::GenericConnectorModel< ConnectionT >::get_status, nest::proxynode::get_status, nest::RecordingDevice::get_status, nest::SPManager::get_status, nest::Node::get_status_base, nest::ConnectionManager::get_synapse_status, nest::TargetTableDevices::get_synapse_status_to_device, nest::SPManager::get_synaptic_elements, nest::TargetIdentifierIndex::get_target_ptr, nest::ConnectionManager::get_targets, nest::NodeManager::get_thread_siblings, nest::RingBuffer::get_value, nest::MultRBuffer::get_value, nest::RingBuffer::get_value_wfr_update, nest::VPManager::get_vp, get_vp_specific_rng, get_vp_synced_rng, nest::glif_psc::handle, nest::amat2_psc_exp::handle, nest::binary_neuron< TGainfunction >::handle, nest::cm_default::handle, nest::correlomatrix_detector::handle, nest::correlospinmatrix_detector::handle, nest::gif_psc_exp::handle, nest::gif_psc_exp_multisynapse::handle, nest::iaf_chs_2007::handle, nest::iaf_psc_alpha::handle, nest::iaf_psc_alpha_multisynapse::handle, nest::iaf_psc_alpha_ps::handle, nest::iaf_psc_delta::handle, nest::iaf_psc_delta_ps::handle, nest::iaf_psc_exp::handle, nest::iaf_psc_exp_htum::handle, nest::iaf_psc_exp_multisynapse::handle, nest::iaf_psc_exp_ps::handle, nest::iaf_psc_exp_ps_lossless::handle, nest::izhikevich::handle, nest::mat2_psc_exp::handle, nest::parrot_neuron::handle, nest::parrot_neuron_ps::handle, nest::pp_psc_delta::handle, nest::spike_dilutor::handle, nest::volume_transmitter::handle, nest::noise_generator::handles_test_event, nest::ModelsModule::init, nest::NestModule::init, nest::rate_neuron_ipn< TNonlinearities >::init_buffers_, nest::rate_neuron_opn< TNonlinearities >::init_buffers_, nest::rate_transformer_node< TNonlinearities >::init_buffers_, nest::ClopathArchivingNode::init_clopath_buffers, nest::EventDeliveryManager::init_moduli, nest::MPIManager::init_mpi, init_nest, nest::spike_dilutor::init_state_, nest::SourceTable::initialize, nest::TargetTable::initialize, nest::TargetTableDevices::initialize, nest::ConnectionManager::initialize, nest::EventDeliveryManager::initialize, nest::ModelManager::initialize, nest::NodeManager::initialize, nest::RecordingBackendASCII::initialize, nest::RecordingBackendMemory::initialize, nest::RecordingBackendMPI::initialize, nest::RecordingBackendScreen::initialize, nest::RecordingBackendSIONlib::initialize, nest::StimulationBackendMPI::initialize, nest::NodeManager::is_local_node, nest::NodeManager::is_local_node_id, nest::VPManager::is_local_vp, nest::FreeLayer< D >::lid_to_position_id_, nest::NodeCollectionPrimitive::local_begin, nest::NodeCollectionComposite::local_begin, nest::LognormalParameter::LognormalParameter, nest::ConnBuilder::loop_over_targets_, nest::NodeCollectionPrimitive::MPI_local_begin, nest::NodeCollectionComposite::MPI_local_begin, nestshutdown, nest::NodeCollectionPrimitive::NodeCollectionPrimitive, nest::NormalParameter::NormalParameter, nest::RecordingBackendASCII::DeviceData::open_file, nest::RecordingBackendSIONlib::open_files_, nest::SynapticElement::operator=, nest::ConnectionCreator::pairwise_bernoulli_on_source_, nest::ConnectionCreator::pairwise_bernoulli_on_target_, nest::SourceTable::populate_target_data_fields_, nest::NodeManager::post_run_cleanup, nest::RecordingBackendSIONlib::post_step_hook, nest::ac_generator::pre_run_hook, nest::noise_generator::pre_run_hook, nest::pulsepacket_generator::pre_run_hook, nest::sinusoidal_poisson_generator::pre_run_hook, nest::volume_transmitter::pre_run_hook, nest::RecordingDevice::pre_run_hook, prepare, nest::RecordingBackendMPI::prepare, nest::SimulationManager::prepare, nest::StimulationBackendMPI::prepare, nest::TargetTable::prepare, nest::SliceRingBuffer::prepare_delivery, nest::NodeManager::prepare_nodes, nest::NodeManager::print, nest::NodeCollectionComposite::print_me, print_nodes_to_stream, nest::NodeCollectionPrimitive::print_primitive, nest::stdp_dopamine_synapse< targetidentifierT >::process_dopa_spikes_, nest::rate_neuron_ipn< TNonlinearities >::rate_neuron_ipn, nest::rate_neuron_opn< TNonlinearities >::rate_neuron_opn, nest::rate_transformer_node< TNonlinearities >::rate_transformer_node, register_connection_model, nest::ModelManager::register_connection_model_, register_logger_client, nest::ModelManager::register_node_model_, register_secondary_connection_model, nest::ArchivingNode::register_stdp_connection, reset_kernel, nest::RandomManager::reset_rngs_, nest::RingBuffer::resize, nest::MultRBuffer::resize, nest::ListRingBuffer::resize, nest::MultiChannelInputBuffer< num_channels >::resize, nest::SliceRingBuffer::resize, nest::SourceTable::resize_compressible_sources, nest::ConnectionManager::resize_connections, nest::EventDeliveryManager::resize_send_recv_buffers_spike_data_, nest::EventDeliveryManager::resize_send_recv_buffers_target_data, nest::SourceTable::resize_sources, nest::EventDeliveryManager::resize_spike_register_, nest::TargetTableDevices::resize_to_number_of_neurons, nest::TargetTableDevices::resize_to_number_of_synapse_types, nest::Event::retrieve_sender_node_id_from_source_table, run, nest::SimulationManager::run, nest::stdp_nn_pre_centered_synapse< targetidentifierT >::send, nest::stdp_nn_restr_synapse< targetidentifierT >::send, nest::stdp_nn_symm_synapse< targetidentifierT >::send, nest::stdp_synapse< targetidentifierT >::send, nest::stdp_triplet_synapse< targetidentifierT >::send, nest::vogels_sprekeler_synapse< targetidentifierT >::send, nest::jonke_synapse< targetidentifierT >::send, nest::stdp_dopamine_synapse< targetidentifierT >::send, nest::stdp_facetshw_synapse_hom< targetidentifierT >::send, nest::stdp_synapse_hom< targetidentifierT >::send, nest::stdp_pl_synapse_hom< targetidentifierT >::send, nest::EventDeliveryManager::send, nest::ConnectionManager::send_from_device, nest::EventDeliveryManager::send_local_, nest::EventDeliveryManager::send_off_grid_remote, nest::EventDeliveryManager::send_remote, nest::EventDeliveryManager::send_secondary, nest::proxynode::send_test_event, nest::TargetTableDevices::send_to_device, nest::ConnectionManager::send_to_devices, nest::Connector< ConnectionT >::send_weight_event, nest::proxynode::sends_secondary_event, nest::proxynode::sends_signal, nest::RecordingDevice::Parameters_::set, nest::StimulationDevice::Parameters_::set, nest::SynapticElement::set, set_connection_status, nest::ConnectionManager::set_connections_have_changed, nest::ConnBuilder::set_default_weight_or_delay_, nest::StimulationDevice::set_initialized_, nest::RecordingDevice::set_initialized_, set_kernel_status, set_model_defaults, set_node_status, nest::VPManager::set_num_threads, nest::ArchivingNode::set_spiketime, nest::DelayChecker::set_status, nest::FreeLayer< D >::set_status, nest::RecordingBackendASCII::DeviceData::set_status, nest::RecordingBackendMemory::DeviceData::set_status, nest::spike_generator::set_status, nest::ConnectionManager::set_status, nest::GenericConnectorModel< ConnectionT >::set_status, nest::RecordingDevice::set_status, nest::SimulationManager::set_status, nest::SPManager::set_status, nest::StimulationDevice::set_status, nest::VPManager::set_status, nest::cont_delay_synapse< targetidentifierT >::set_status, nest::STDPDopaCommonProperties::set_status, nest::Connection< targetidentifierT >::set_status, nest::NodeManager::set_status, nest::ModelManager::set_synapse_defaults_, nest::ConnBuilder::set_synapse_model_, nest::ConnBuilder::set_synapse_params, nest::ConnectionManager::set_synapse_status, nest::TargetTableDevices::set_synapse_status_to_device, nest::TargetIdentifierIndex::set_target, nest::Model::set_threads, nest::ConnBuilder::single_connect_, nest::ConnBuilder::single_disconnect_, slice_positions_if_sliced_nc, nest::SourceTable::source_should_be_processed_, nest::SPBuilder::sp_connect, nest::OneToOneBuilder::sp_connect_, nest::AllToAllBuilder::sp_connect_, nest::OneToOneBuilder::sp_disconnect_, nest::AllToAllBuilder::sp_disconnect_, nest::ConnectionManager::split_to_neuron_device_vectors_, nest::SynapticElement::SynapticElement, nest::ConnectionManager::sync_has_primary_connections, nest::VPManager::thread_to_vp, nest::ConnectionManager::trigger_update_weight, nest::iaf_chs_2007::update, nest::iaf_psc_exp::update, nest::volume_transmitter::update, nest::glif_psc::update, nest::ac_generator::update, nest::amat2_psc_exp::update, nest::binary_neuron< TGainfunction >::update, nest::cm_default::update, nest::dc_generator::update, nest::gamma_sup_generator::update, nest::gif_psc_exp::update, nest::gif_psc_exp_multisynapse::update, nest::iaf_psc_alpha::update, nest::iaf_psc_alpha_multisynapse::update, nest::iaf_psc_delta::update, nest::iaf_psc_delta_ps::update, nest::iaf_psc_exp_htum::update, nest::iaf_psc_exp_multisynapse::update, nest::inhomogeneous_poisson_generator::update, nest::izhikevich::update, nest::mat2_psc_exp::update, nest::mip_generator::update, nest::multimeter::update, nest::noise_generator::update, nest::parrot_neuron::update, nest::parrot_neuron_ps::update, nest::poisson_generator::update, nest::poisson_generator_ps::update, nest::pp_psc_delta::update, nest::ppd_sup_generator::update, nest::pulsepacket_generator::update, nest::sinusoidal_poisson_generator::update, nest::spike_dilutor::update, nest::spike_generator::update, nest::step_rate_generator::update, nest::step_current_generator::update, nest::iaf_psc_alpha_ps::update, nest::iaf_psc_exp_ps::update, nest::iaf_psc_exp_ps_lossless::update, nest::SimulationManager::update_, nest::rate_neuron_ipn< TNonlinearities >::update_, nest::rate_neuron_opn< TNonlinearities >::update_, nest::rate_transformer_node< TNonlinearities >::update_, nest::SimulationManager::update_connection_infrastructure, nest::SPBuilder::update_delay, nest::ConnectionManager::update_delay_extrema_, nest::StimulationBackendMPI::update_device, nest::EventDeliveryManager::update_moduli, nest::ConnBuilder::update_param_dict_, nest::SPManager::update_structural_plasticity, updateValueParam, nest::GenericConnectorModel< ConnectionT >::used_default_delay, nest::NodeCollection::valid, nest::NormalParameter::value, nest::LognormalParameter::value, nest::VPManager::vp_to_thread, nest::RecordingDevice::write, nest::RecordingBackendMPI::write, nest::EventDeliveryManager::write_done_marker_secondary_events_, nest::EventDeliveryManager::write_toggle.
void nest::test_link(int, int)
void nest::test_links()
void nest::init_nest(int *argc, char **argv[])
References nest::KernelManager::create_kernel_manager, nest::MPIManager::init_mpi, nest::KernelManager::initialize, kernel, nest::KernelManager::mpi_manager.
Referenced by neststartup.
void nest::fail_exit(int)
void nest::install_module(const std::string &)
void nest::reset_kernel()
References kernel, nest::KernelManager::reset.
Referenced by nest::NestModule::ResetKernelFunction::execute.
void nest::enable_dryrun_mode(const index n_procs)
References kernel, nest::KernelManager::mpi_manager, nest::MPIManager::set_num_processes.
Referenced by nest::NestModule::SetFakeNumProcesses_iFunction::execute.
void nest::register_logger_client(const deliver_logging_event_ptr client_callback)
References kernel, nest::KernelManager::logging_manager, nest::LoggingManager::register_logging_client.
void nest::print_nodes_to_stream(std::ostream &ostr)
References kernel, nest::KernelManager::node_manager, nest::NodeManager::print.
Referenced by nest::NestModule::PrintNodesFunction::execute, nest::NestModule::PrintNodesToStreamFunction::execute.
RngPtr nest::get_rank_synced_rng()
References nest::RandomManager::get_rank_synced_rng, kernel, nest::KernelManager::random_manager.
Referenced by nest::Parameter::apply, apply, nest::FixedOutDegreeBuilder::connect_, nest::FixedTotalNumberBuilder::connect_, nest::ConnectionCreator::fixed_outdegree_, get_value, nest::SPManager::global_shuffle, nest::FreeLayer< D >::set_status.
RngPtr nest::get_vp_synced_rng(thread tid)
References nest::RandomManager::get_vp_synced_rng, kernel, nest::KernelManager::random_manager.
Referenced by nest::SymmetricBernoulliBuilder::connect_, nest::mip_generator::update.
RngPtr nest::get_vp_specific_rng(thread tid)
References nest::RandomManager::get_vp_specific_rng, kernel, nest::KernelManager::random_manager.
Referenced by nest::OneToOneBuilder::connect_, nest::AllToAllBuilder::connect_, nest::FixedInDegreeBuilder::connect_, nest::FixedOutDegreeBuilder::connect_, nest::FixedTotalNumberBuilder::connect_, nest::BernoulliBuilder::connect_, nest::SPBuilder::connect_, nest::ConnectionCreator::connect_to_target_, nest::gamma_sup_generator::event_hook, nest::inhomogeneous_poisson_generator::event_hook, nest::mip_generator::event_hook, nest::poisson_generator::event_hook, nest::poisson_generator_ps::event_hook, nest::ppd_sup_generator::event_hook, nest::sinusoidal_poisson_generator::event_hook, nest::spike_dilutor::event_hook, nest::ConnectionCreator::fixed_indegree_, nest::rate_neuron_ipn< TNonlinearities >::init_buffers_, nest::rate_neuron_opn< TNonlinearities >::init_buffers_, nest::binary_neuron< TGainfunction >::pre_run_hook, nest::gif_psc_exp::pre_run_hook, nest::gif_psc_exp_multisynapse::pre_run_hook, nest::iaf_psc_exp::pre_run_hook, nest::pp_psc_delta::pre_run_hook, nest::bernoulli_synapse< targetidentifierT >::send, nest::quantal_stp_synapse< targetidentifierT >::send, nest::OneToOneBuilder::sp_connect_, nest::AllToAllBuilder::sp_connect_, nest::noise_generator::update, nest::pulsepacket_generator::update, nest::sinusoidal_poisson_generator::update, nest::rate_neuron_ipn< TNonlinearities >::update_, nest::rate_neuron_opn< TNonlinearities >::update_, updateValueParam.
void nest::set_kernel_status(const DictionaryDatum &dict)
References ALL_ENTRIES_ACCESSED, kernel, nest::KernelManager::set_status.
Referenced by nest::NestModule::SetKernelStatus_DFunction::execute.
DictionaryDatum nest::get_kernel_status()
References nest::KernelManager::get_status, kernel.
Referenced by nest::NestModule::GetKernelStatus_Function::execute.
void nest::set_node_status(const index node_id, const DictionaryDatum &dict)
References kernel, nest::KernelManager::node_manager, nest::NodeManager::set_status.
Referenced by nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::CreateLayer_D_DFunction::execute.
DictionaryDatum nest::get_node_status(const index node_id)
References nest::NodeManager::get_status, kernel, nest::KernelManager::node_manager.
Referenced by nest::NestModule::GetStatus_gFunction::execute, nest::NestModule::GetStatus_iFunction::execute.
void nest::set_connection_status(const ConnectionDatum &conn, const DictionaryDatum &dict)
References ALL_ENTRIES_ACCESSED2, nest::KernelManager::connection_manager, getValue< long >, kernel, nest::names::port, nest::ConnectionManager::set_synapse_status, nest::names::source, nest::names::synapse_modelid, nest::names::target, nest::names::target_thread.
Referenced by nest::NestModule::SetStatus_CDFunction::execute.
DictionaryDatum nest::get_connection_status(const ConnectionDatum &conn)
References nest::KernelManager::connection_manager, nest::ConnectionManager::get_synapse_status, kernel.
NodeCollectionPTR nest::create(const Name &model_name, const index n_nodes)
References nest::NodeManager::add_node, nest::ModelManager::get_node_model_id, kernel, nest::KernelManager::model_manager, nest::KernelManager::node_manager.
Referenced by nest::NestModule::Create_l_iFunction::execute.
NodeCollectionPTR nest::get_nodes(const DictionaryDatum &params, const bool local_only)
References nest::NodeManager::get_nodes, kernel, nest::KernelManager::node_manager.
Referenced by nest::NestModule::GetNodes_D_b::execute.
void nest::connect(NodeCollectionPTR sources, NodeCollectionPTR targets, const DictionaryDatum &connectivity, const std::vector< DictionaryDatum > &synapse_params)
References nest::ConnectionManager::connect, nest::KernelManager::connection_manager, kernel.
Referenced by nest::ConnectionManager::connect_arrays.
void nest::connect_arrays(long *sources, long *targets, double *weights, double *delays, std::vector< std::string > &p_keys, double *p_values, size_t n, std::string syn_model)
Connect arrays of node IDs one-to-one.
Connects an array of sources to an array of targets, with weights and delays from specified arrays, using the one-to-one rule. Additional synapse parameters can be specified with p_keys and p_values. Sources, targets, weights, delays, and receptor types are given as pointers to the first element. All arrays must have the same length, n. Weights, delays, and receptor types can be unspecified by passing a nullptr. The p_keys vector contains keys of additional synapse parameters, with associated values in the flat array p_values. If there are n sources and targets, and M additional synapse parameters, p_keys has a size of M, and the p_values array has length of M*n.
References nest::ConnectionManager::connect_arrays, nest::KernelManager::connection_manager, kernel.
ArrayDatum nest::get_connections(const DictionaryDatum &dict)
References ALL_ENTRIES_ACCESSED, nest::KernelManager::connection_manager, nest::ConnectionManager::get_connections, kernel.
Referenced by nest::NestModule::GetConnections_DFunction::execute, nest::ConnectionManager::get_connections.
void nest::disconnect(const ArrayDatum &conns)
References nest::SPManager::disconnect, nest::NodeManager::get_node_or_proxy, kernel, nest::KernelManager::node_manager, nest::KernelManager::sp_manager.
Referenced by nest::NestModule::Disconnect_aFunction::execute.
void nest::simulate(const double &t)
References cleanup, prepare, run.
Referenced by nest::NestModule::SimulateFunction::execute.
void nest::run(const double &time)
Run a partial simulation for time ms.
Runs a partial simulation for time ms after a call to prepare() and before a cleanup(). Can be called multiple times between a prepare()/cleanup() pair to divide a simulation into multiple pieces with access to the API in between. Thus, simulate(t) = prepare(); run(t/2); run(t/2); cleanup() prepare() cleanup()
References nest::Time::is_finite, nest::Time::is_grid_time, kernel, nest::SimulationManager::run, nest::KernelManager::simulation_manager.
Referenced by nest::NestModule::RunFunction::execute, simulate.
void nest::prepare()
do calibrations for network, open files, ... before run()
Prepares a simulation before calling any number of run(t_n) calls to actually run the simulation run() cleanup()
References kernel, nest::KernelManager::prepare.
Referenced by nest::NestModule::PrepareFunction::execute, simulate.
void nest::cleanup()
do cleanup after a simulation, such as closing files
Do cleanup to end a simulation using run() commands. After calling cleanup(), further run() calls must only happen after another call to prepare() run() prepare()
References nest::KernelManager::cleanup, kernel.
Referenced by nest::NestModule::CleanupFunction::execute, simulate, nest::RecordingBackendSIONlib::~RecordingBackendSIONlib.
void nest::copy_model(const Name &oldmodname, const Name &newmodname, const DictionaryDatum &dict)
References nest::ModelManager::copy_model, kernel, nest::KernelManager::model_manager.
void nest::set_model_defaults(const std::string component, const DictionaryDatum &dict)
References nest::KernelManager::io_manager, kernel, nest::IOManager::set_recording_backend_status.
Referenced by nest::NestModule::SetDefaults_l_DFunction::execute.
DictionaryDatum nest::get_model_defaults(const std::string component)
References nest::ModelManager::get_connector_defaults, nest::ModelManager::get_node_model, nest::ModelManager::get_node_model_id, nest::IOManager::get_recording_backend_status, nest::Model::get_status, nest::ModelManager::get_synapse_model_id, nest::KernelManager::io_manager, kernel, nest::KernelManager::model_manager.
Referenced by nest::NestModule::GetDefaults_lFunction::execute.
ParameterDatum nest::create_parameter(const DictionaryDatum &param_dict)
References ALL_ENTRIES_ACCESSED, nest::NestModule::create_parameter.
Referenced by nest::NestModule::CreateParameter_DFunction::execute.
double nest::get_value(const ParameterDatum &param)
References get_rank_synced_rng.
Referenced by nest::NestModule::GetValue_PFunction::execute.
bool nest::is_spatial(const ParameterDatum &param)
Referenced by nest::NestModule::IsSpatial_PFunction::execute.
std::vector< double > nest::apply(const ParameterDatum &param, const NodeCollectionDatum &nc)
References nest::NodeManager::get_node_or_proxy, get_rank_synced_rng, kernel, nest::KernelManager::node_manager.
Referenced by nest::NestModule::Apply_P_DFunction::execute, nest::NestModule::Apply_P_gFunction::execute.
std::vector< double > nest::apply(const ParameterDatum &param, const DictionaryDatum &positions)
References Name::lookup, nest::names::source, nest::names::targets.
Datum * nest::node_collection_array_index(const Datum *datum, const long *array, unsigned long n)
References nest::NodeCollection::create.
Datum * nest::node_collection_array_index(const Datum *datum, const bool *array, unsigned long n)
References nest::NodeCollection::create.
void nest::slice_positions_if_sliced_nc(DictionaryDatum &dict, const NodeCollectionDatum &nc)
Get only positions of the sliced nodes if metadata contains node positions and the NodeCollection is sliced.
Puts an array of positions sliced the same way as a sliced NodeCollection into dict. Positions have to be sliced on introspection because metadata of a sliced NodeCollection for internal consistency and efficiency points to the metadata of the original NodeCollection.
References kernel, nest::names::positions, TokenArray::push_back.
Referenced by nest::NestModule::GetMetadata_gFunction::execute.
void nest::register_connection_model(const std::string &name, const RegisterConnectionModelFlags flags=default_connection_model_flags)
Register connection model (i.e.
an instance of a class inheriting from Connection).
References kernel, nest::KernelManager::model_manager, nest::ModelManager::register_connection_model.
void nest::register_secondary_connection_model(const std::string &name, const RegisterConnectionModelFlags flags=default_secondary_connection_model_flags)
Register secondary connection models (e.g.
gap junctions, rate-based models).
References kernel, nest::KernelManager::model_manager, nest::ModelManager::register_secondary_connection_model.
N nest::time_abs(const N n)
Class to handle simulation time and realtime.
Main idea: All times given in multiples of "tics": A "tic" is a microsecond by default, but may be changed through the option -Dtics_per_ms to configure. User access to time only through accessor functions: Times can be added, subtracted, and multiplied by ints All real world time is given in ms as double All computation is done based on tics Three time variables are kept: #- time in tics #- time in ms #- time in steps The largest representable time is available through Time::max(). @NOTE The time base (tics per millisecond) can only be set at compile time and by the Time::set_resolution(). Times in ms are rounded up to the next tic interval. This ensures that the time intervals (0, h] are open at the left point and closed at the right point. It also ensures compatibility with precise timing, namely that the offset u fulfills -h > u >= 0. The resolution (tics per step) can only be set before the first node is created and before the simulation starts. The resolution can be changed after the network has been deleted and the time reset. Implementers of models or methods containing persistent (member variable) Time objects, must ensure that these are recalibrated before the simulation starts. This is necessary to ensure that step values are updated after a change in resolution. The default resolution can be changed using the with-tics_per_step option to configure. @NOTE The step-time counter is NOT changed when the resolution is changed. This is of no consequence, since changes in resolution are permitted at t=0 only. @NOTE Neurons update themselves in min-delay intervals. During such a min-delay update step, time is in a sense undefined, since it is up to the model how it takes its dynamics across the interval. Any spikes emitted and voltage information returned must be fixed to time grid points. One may later consider to introduce per-tread simulation time variables. @NOTE Delays must be added to current time, and moduloed each time a spike is inserted into a ring buffer. That operation must be very fast, and there is no time for conversions. Thus, delays must be stored in steps. Given the large number of delays in a system, we cannot use class Time with its three member variables to store delays. Delays must thus be stored explicitly as delay steps. Markus Diesmann, 2008-01-25 Hans Ekkehard Plesser, 2004-01-25, 2006-12-18 Marc-Oliver Gewaltig, 2004-01-27
Referenced by nest::Time::range.
long long nest::time_abs(long long n)
bool nest::operator==(const Time &t1, const Time &t2)
Referenced by operator!=.
bool nest::operator!=(const Time &t1, const Time &t2)
bool nest::operator<(const Time &t1, const Time &t2)
Referenced by operator>, operator>=.
bool nest::operator>(const Time &t1, const Time &t2)
Referenced by operator<=.
bool nest::operator<=(const Time &t1, const Time &t2)
bool nest::operator>=(const Time &t1, const Time &t2)
Time nest::operator+(const Time &t1, const Time &t2)
Time nest::operator-(const Time &t1, const Time &t2)
Time nest::operator*(const long factor, const Time &t)
Time nest::operator*(const Time &t, long factor)
constexpr uint64_t nest::generate_bit_mask(const uint8_t num_bits, const uint8_t bit_position)
constexpr uint64_t nest::generate_max_value(const uint8_t num_bits)
nest::__attribute__((__unused__)) const index invalid_index
static AbstractMask * nest::create_doughnut(const DictionaryDatum &d)
References nest::names::anchor, getValue< double >, nest::names::inner_radius, nest::names::outer_radius.
Referenced by nest::NestModule::init.
NodeCollectionPTR nest::operator+(NodeCollectionPTR lhs, NodeCollectionPTR rhs)
static double nest::mod(double x, double p)
Referenced by nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::masked_iterator, nest::ModelManager::memory_info, nest::NodeManager::print.
std::shared_ptr< Parameter > nest::multiply_parameter(const std::shared_ptr< Parameter > first, const std::shared_ptr< Parameter > second)
Create the product of one parameter with another.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Mul_P_PFunction::execute.
std::shared_ptr< Parameter > nest::divide_parameter(const std::shared_ptr< Parameter > first, const std::shared_ptr< Parameter > second)
Create the quotient of one parameter with another.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Div_P_PFunction::execute.
std::shared_ptr< Parameter > nest::add_parameter(const std::shared_ptr< Parameter > first, const std::shared_ptr< Parameter > second)
Create the sum of one parameter with another.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Add_P_PFunction::execute.
std::shared_ptr< Parameter > nest::subtract_parameter(const std::shared_ptr< Parameter > first, const std::shared_ptr< Parameter > second)
Create the difference between one parameter and another.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Sub_P_PFunction::execute.
std::shared_ptr< Parameter > nest::compare_parameter(const std::shared_ptr< Parameter > first, const std::shared_ptr< Parameter > second, const DictionaryDatum &d)
Create comparison of one parameter with another.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Compare_P_P_DFunction::execute.
std::shared_ptr< Parameter > nest::conditional_parameter(const std::shared_ptr< Parameter > condition, const std::shared_ptr< Parameter > if_true, const std::shared_ptr< Parameter > if_false)
Create a parameter that chooses between two other parameters, based on a given condition parameter.
The resulting value of the condition parameter is treated as a bool, meaning that a zero value evaluates as false, and all other values evaluate as true. a new dynamically allocated parameter.
Referenced by nest::NestModule::Conditional_P_P_PFunction::execute.
std::shared_ptr< Parameter > nest::min_parameter(const std::shared_ptr< Parameter > parameter, const double other)
Create parameter whose value is the minimum of a given parameter's value and the given value.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Min_P_dFunction::execute.
std::shared_ptr< Parameter > nest::max_parameter(const std::shared_ptr< Parameter > parameter, const double other)
Create parameter whose value is the maximum of a given parameter's value and the given value.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Max_P_dFunction::execute.
std::shared_ptr< Parameter > nest::redraw_parameter(const std::shared_ptr< Parameter > parameter, const double min, const double max)
Create parameter redrawing the value if the value of a parameter is outside the set limits.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Redraw_P_d_dFunction::execute.
std::shared_ptr< Parameter > nest::exp_parameter(const std::shared_ptr< Parameter > parameter)
Create the exponential of a parameter.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Exp_PFunction::execute.
std::shared_ptr< Parameter > nest::sin_parameter(const std::shared_ptr< Parameter > parameter)
Create the sine of a parameter.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Sin_PFunction::execute.
std::shared_ptr< Parameter > nest::cos_parameter(const std::shared_ptr< Parameter > parameter)
Create the cosine of a parameter.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Cos_PFunction::execute.
std::shared_ptr< Parameter > nest::pow_parameter(const std::shared_ptr< Parameter > parameter, const double exponent)
Create a parameter raised to the power of an exponent.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Pow_P_dFunction::execute.
std::shared_ptr< Parameter > nest::dimension_parameter(const std::shared_ptr< Parameter > x_parameter, const std::shared_ptr< Parameter > y_parameter)
Create a parameter that can generate position vectors from a given set of parameters.
a new dynamically allocated parameter.
Referenced by nest::NestModule::Dimension2d_P_PFunction::execute, nest::NestModule::Dimension3d_P_P_PFunction::execute.
std::shared_ptr< Parameter > nest::dimension_parameter(const std::shared_ptr< Parameter > x_parameter, const std::shared_ptr< Parameter > y_parameter, const std::shared_ptr< Parameter > z_parameter)
std::ostream & nest::operator<<(std::ostream &os, const Position< D, T > &pos)
size_t nest::number_of_uints_covered()
This template function returns the number of uints covered by a variable of type T.
This function is used to determine the storage demands for a variable of type T in the NEST communication buffer, which is of type std::vector<unsigned int>.
void nest::write_to_comm_buffer(T d, std::vector< unsigned int >::iterator &pos)
This template function writes data of type T to a given position of a std::vector< unsigned int >.
Please note that this function does not increase the size of the vector, it just writes the data to the position given by the iterator. The function is used to write data from SecondaryEvents to the NEST communication buffer. The pos iterator is advanced during execution. For a discussion on the functionality of this function see github issue #181 and pull request #184.
Referenced by nest::DataSecondaryEvent< DataType, Subclass >::operator>>.
void nest::read_from_comm_buffer(T &d, std::vector< unsigned int >::iterator &pos)
This template function reads data of type T from a given position of a std::vector< unsigned int >.
The function is used to read SecondaryEvents data from the NEST communication buffer. The pos iterator is advanced during execution. For a discussion on the functionality of this function see github issue #181 and pull request #184.
Referenced by nest::DataSecondaryEvent< DataType, Subclass >::get_coeffvalue.
bool nest::operator<(const Source &lhs, const Source &rhs)
bool nest::operator>(const Source &lhs, const Source &rhs)
bool nest::operator==(const Source &lhs, const Source &rhs)
bool nest::operator==(const SourceTablePosition &lhs, const SourceTablePosition &rhs)
References nest::SourceTablePosition::lcid, nest::SourceTablePosition::syn_id, nest::SourceTablePosition::tid.
bool nest::operator!=(const SourceTablePosition &lhs, const SourceTablePosition &rhs)
References operator==.
bool nest::operator<(const SourceTablePosition &lhs, const SourceTablePosition &rhs)
References nest::SourceTablePosition::lcid, nest::SourceTablePosition::syn_id, nest::SourceTablePosition::tid.
bool nest::operator>(const SourceTablePosition &lhs, const SourceTablePosition &rhs)
References operator<.
bool nest::operator<=(const SourceTablePosition &lhs, const SourceTablePosition &rhs)
References operator>.
bool nest::operator>=(const SourceTablePosition &lhs, const SourceTablePosition &rhs)
References operator<.
void nest::print_vector(const std::vector< T > &vec)
AbstractLayerPTR nest::get_layer(NodeCollectionPTR nc)
References nest::LayerMetadata::get_layer.
Referenced by connect_layers, nest::AbstractLayer::create_layer, displacement, distance, dump_layer_connections, dump_layer_nodes, nest::NestModule::SelectNodesByMask_g_a_MFunction::execute, get_position.
NodeCollectionPTR nest::create_layer(const DictionaryDatum &layer_dict)
References ALL_ENTRIES_ACCESSED, nest::AbstractLayer::create_layer.
Referenced by nest::NestModule::CreateLayer_D_DFunction::execute.
ArrayDatum nest::get_position(NodeCollectionPTR layer_nc)
References get_layer, kernel.
Referenced by nest::FreeLayer< D >::communicate_positions_, nest::Layer< D >::compute_displacement, displacement, distance, nest::Layer< D >::dump_nodes, nest::NestModule::GetPosition_gFunction::execute, nest::Layer< D >::get_position_vector.
std::vector< double > nest::get_position(const index node_id)
References get_layer, nest::Node::get_nc, nest::NodeManager::get_node_or_proxy, kernel, nest::KernelManager::node_manager.
ArrayDatum nest::displacement(NodeCollectionPTR layer_to_nc, NodeCollectionPTR layer_from_nc)
References get_layer, get_position, nest::NodeManager::is_local_node_id, kernel, nest::KernelManager::node_manager.
Referenced by nest::Layer< D >::compute_displacement, nest::Layer< D >::compute_distance, nest::NestModule::Displacement_g_gFunction::execute, nest::NestModule::Displacement_a_gFunction::execute.
ArrayDatum nest::displacement(NodeCollectionPTR layer_nc, const ArrayDatum point)
References get_layer, kernel.
std::vector< double > nest::distance(NodeCollectionPTR layer_to_nc, NodeCollectionPTR layer_from_nc)
References get_layer, get_position, nest::NodeManager::is_local_node_id, kernel, nest::KernelManager::node_manager.
Referenced by nest::NestModule::Distance_g_gFunction::execute, nest::NestModule::Distance_a_gFunction::execute, nest::NestModule::Distance_aFunction::execute.
std::vector< double > nest::distance(NodeCollectionPTR layer_nc, const ArrayDatum point)
References get_layer, kernel.
std::vector< double > nest::distance(const ArrayDatum conns)
References get_layer, nest::Node::get_nc, nest::NodeManager::get_node_or_proxy, get_position, kernel, nest::KernelManager::node_manager.
MaskDatum nest::create_mask(const DictionaryDatum &mask_dict)
References ALL_ENTRIES_ACCESSED, nest::NestModule::create_mask.
Referenced by nest::NestModule::CreateMask_DFunction::execute.
BoolDatum nest::inside(const std::vector< double > &point, const MaskDatum &mask)
Referenced by nest::NestModule::Inside_a_MFunction::execute, nest::BallMask< D >::inside, nest::EllipseMask< D >::inside, nest::BoxMask< D >::inside, nest::Mask< D >::inside.
MaskDatum nest::intersect_mask(const MaskDatum &mask1, const MaskDatum &mask2)
Referenced by nest::NestModule::And_M_MFunction::execute.
MaskDatum nest::union_mask(const MaskDatum &mask1, const MaskDatum &mask2)
Referenced by nest::NestModule::Or_M_MFunction::execute.
MaskDatum nest::minus_mask(const MaskDatum &mask1, const MaskDatum &mask2)
Referenced by nest::NestModule::Sub_M_MFunction::execute.
void nest::connect_layers(NodeCollectionPTR source_nc, NodeCollectionPTR target_nc, const DictionaryDatum &connection_dict)
References ALL_ENTRIES_ACCESSED, nest::KernelManager::connection_manager, get_layer, kernel, nest::ConnectionManager::set_connections_have_changed.
Referenced by nest::NestModule::ConnectLayers_g_g_DFunction::execute.
void nest::dump_layer_nodes(NodeCollectionPTR layer_nc, OstreamDatum &out)
References get_layer.
Referenced by nest::NestModule::DumpLayerNodes_os_gFunction::execute.
void nest::dump_layer_connections(const Token &syn_model, NodeCollectionPTR source_layer_nc, NodeCollectionPTR target_layer_nc, OstreamDatum &out)
References get_layer.
Referenced by nest::NestModule::DumpLayerConnections_os_g_g_lFunction::execute.
DictionaryDatum nest::get_layer_status(NodeCollectionPTR)
Referenced by nest::NestModule::GetLayerStatus_gFunction::execute.