neststartup.cpp
SLIInterpreter* sli_engine
Referenced by get_engine, neststartup, sli_logging.
SLIInterpreter & get_engine()
References sli_engine.
void sli_logging(const nest::LoggingEvent &e)
References SLIInterpreter::message, sli_engine.
Referenced by neststartup.
int neststartup(int *argc, char ***argv, SLIInterpreter &engine)
References SLIInterpreter::addmodule, SLIInterpreter::baselookup, SLIInterpreter::commandstring_name, Token::datum, nest::init_nest, sli_engine, sli_logging, SLIInterpreter::startup.
Referenced by main.
void nestshutdown(int exitcode)
References nest::KernelManager::destroy_kernel_manager, nest::KernelManager::finalize, nest::kernel, nest::MPIManager::mpi_finalize, nest::KernelManager::mpi_manager.
Referenced by main.