numerics.cpp
long ld_round(double x)
Round to nearest int, rounding midpoints upwards.
Result as long [-1/2, 1/2) -> 0 and in general [ (2n-1)/2, (2n+1)/2 ) -> n dround
Referenced by nest::Time::delay_ms_to_steps.
double dround(double x)
Round to nearest int, rounding midpoints upwards.
Result as double [-1/2, 1/2) -> 0 and in general [ (2n-1)/2, (2n+1)/2 ) -> n ld_round
Referenced by nest::Time::set_resolution.
double dtruncate(double x)
Return integer part of argument.
bool is_integer(double n)
Returns true if n is integer up to rounding error.
bool
Referenced by nest::SimulationManager::set_status.