numerics.h
long ld_round(double)
Round to nearest int, rounding midpoints upwards.
Result as long [-1/2, 1/2) -> 0 and in general [ (2n-1)/2, (2n+1)/2 ) -> n dround
References nest::names::x.
Referenced by nest::Time::delay_ms_to_steps.
double dround(double)
Round to nearest int, rounding midpoints upwards.
Result as double [-1/2, 1/2) -> 0 and in general [ (2n-1)/2, (2n+1)/2 ) -> n ld_round
References nest::names::x.
Referenced by nest::Time::set_resolution.
double dtruncate(double)
Return integer part of argument.
References nest::names::x.
bool is_integer(double)
Returns true if n is integer up to rounding error.
bool
References nest::names::n.
Referenced by nest::SimulationManager::set_status.