nest::step_current_generator::Parameters_
std::vector< Time > nest::step_current_generator::Parameters_::amp_time_stamps_
Times of amplitude changes.
std::vector< double > nest::step_current_generator::Parameters_::amp_values_
Amplitude values activated at given times.
bool nest::step_current_generator::Parameters_::allow_offgrid_amp_times_
Allow and round up amplitude times not on steps.
nest::step_current_generator::Parameters_::Parameters_()
Sets default parameter values.
nest::step_current_generator::Parameters_::Parameters_(const Parameters_ &, Buffers_ &)
nest::step_current_generator::Parameters_::Parameters_(const Parameters_ &)
nest::step_current_generator::Parameters_ & nest::step_current_generator::Parameters_::operator=(const Parameters_ &p)
References nest::names::p.
void nest::step_current_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary Set values from dictionary.
References nest::names::allow_offgrid_times, nest::names::amplitude_times, nest::names::amplitude_values.
Referenced by nest::step_current_generator::get_status.
void nest::step_current_generator::Parameters_::set(const DictionaryDatum &, Buffers_ &, Node *)
References nest::names::allow_offgrid_times, nest::names::amplitude_times, nest::names::amplitude_values, nest::names::b, nest::names::d.
Referenced by nest::step_current_generator::set_data_from_stimulation_backend, nest::step_current_generator::set_status.
nest::Time nest::step_current_generator::Parameters_::validate_time_(double, const Time &)
Return time as Time object if valid, otherwise throw BadProperty.
amplitude time, ms previous time stamp
References nest::Time::is_grid_time, nest::Time::ms, nest::Time::ms_stamp.