nest::poisson_generator_ps::Parameters_
double nest::poisson_generator_ps::Parameters_::rate_
process rate [Hz]
double nest::poisson_generator_ps::Parameters_::dead_time_
dead time [ms]
size_t nest::poisson_generator_ps::Parameters_::num_targets_
Number of targets.
This is a hidden parameter; must be placed in parameters, even though it is an implementation detail, since it concerns the connections and must not be affected by resets.
Referenced by nest::poisson_generator_ps::send_test_event, nest::poisson_generator_ps::set_status.
nest::poisson_generator_ps::Parameters_::Parameters_()
Sets default parameter values.
void nest::poisson_generator_ps::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::dead_time, nest::names::rate.
Referenced by nest::poisson_generator_ps::get_status.
void nest::poisson_generator_ps::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::d, nest::names::dead_time, nest::names::rate.
Referenced by nest::poisson_generator_ps::set_data_from_stimulation_backend, nest::poisson_generator_ps::set_status.