nest::inhomogeneous_poisson_generator::Parameters_
std::vector< Time > nest::inhomogeneous_poisson_generator::Parameters_::rate_times_
std::vector< double > nest::inhomogeneous_poisson_generator::Parameters_::rate_values_
bool nest::inhomogeneous_poisson_generator::Parameters_::allow_offgrid_times_
Allow and round up rate times not on steps;.
nest::inhomogeneous_poisson_generator::Parameters_::Parameters_()
Sets default parameter values.
nest::inhomogeneous_poisson_generator::Parameters_::Parameters_(const Parameters_ &, Buffers_ &)
Store current values in dictionary.
void nest::inhomogeneous_poisson_generator::Parameters_::get(DictionaryDatum &) const
Set values from dictionary.
References nest::names::allow_offgrid_times, nest::names::rate_times, nest::names::rate_values.
Referenced by nest::inhomogeneous_poisson_generator::get_status.
void nest::inhomogeneous_poisson_generator::Parameters_::set(const DictionaryDatum &, Buffers_ &, Node *)
Align rate time to grid if necessary and insert it into rate_times_.
References nest::names::allow_offgrid_times, Name::lookup, nest::names::rate_times, nest::names::rate_values.
Referenced by nest::inhomogeneous_poisson_generator::set_data_from_stimulation_backend, nest::inhomogeneous_poisson_generator::set_status.
void nest::inhomogeneous_poisson_generator::Parameters_::assert_valid_rate_time_and_insert(const double t)
References nest::Time::is_grid_time, nest::kernel.