nest::correlospinmatrix_detector::Parameters_
Time nest::correlospinmatrix_detector::Parameters_::delta_tau_
width of correlation histogram bins
Referenced by Parameters_.
Time nest::correlospinmatrix_detector::Parameters_::tau_max_
maximum time difference of events to detect
Referenced by Parameters_.
Time nest::correlospinmatrix_detector::Parameters_::Tstart_
start of recording
Referenced by Parameters_.
Time nest::correlospinmatrix_detector::Parameters_::Tstop_
end of recording
Referenced by Parameters_.
long nest::correlospinmatrix_detector::Parameters_::N_channels_
number of channels
Referenced by nest::correlospinmatrix_detector::handles_test_event.
nest::correlospinmatrix_detector::Parameters_::Parameters_()
Sets default parameter values.
nest::correlospinmatrix_detector::Parameters_::Parameters_(const Parameters_ &)
Recalibrate all times.
References nest::Time::calibrate, delta_tau_, get_default_delta_tau, nest::Time::is_step, tau_max_, Tstart_, Tstop_.
nest::correlospinmatrix_detector::Parameters_ & nest::correlospinmatrix_detector::Parameters_::operator=(const Parameters_ &)
References nest::names::p.
void nest::correlospinmatrix_detector::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::delta_tau, nest::names::N_channels, nest::names::tau_max, nest::names::Tstart, nest::names::Tstop.
Referenced by nest::correlospinmatrix_detector::get_status.
bool nest::correlospinmatrix_detector::Parameters_::set(const DictionaryDatum &, const correlospinmatrix_detector &, Node *)
Set values from dictionary.
true if the state needs to be reset after a change of binwidth or tau_max.
References nest::names::d, nest::names::delta_tau, nest::Time::ms, nest::names::N, nest::names::n, nest::names::N_channels, nest::names::tau_max, nest::names::Tstart, nest::names::Tstop.
Referenced by nest::correlospinmatrix_detector::set_status.
Time nest::correlospinmatrix_detector::Parameters_::get_default_delta_tau()
References nest::Time::get_resolution.
Referenced by Parameters_.