nest::noise_generator::Parameters_
double nest::noise_generator::Parameters_::mean_
mean current, in pA
double nest::noise_generator::Parameters_::std_
standard deviation of current, in pA
double nest::noise_generator::Parameters_::std_mod_
standard deviation of current modulation, in pA
double nest::noise_generator::Parameters_::freq_
Standard frequency in Hz.
double nest::noise_generator::Parameters_::phi_deg_
Phase of sinusodial noise modulation (0-360 deg)
Time nest::noise_generator::Parameters_::dt_
time interval between updates
Referenced by Parameters_.
size_t nest::noise_generator::Parameters_::num_targets_
Number of targets.
This is a hidden parameter; must be placed in parameters, even though it is an implementation detail, since it concerns the connections and must not be affected by resets.
Referenced by nest::noise_generator::set_data_from_stimulation_backend, nest::noise_generator::set_status.
nest::noise_generator::Parameters_::Parameters_()
Sets default parameter values.
nest::noise_generator::Parameters_::Parameters_(const Parameters_ &)
References nest::Time::calibrate, dt_, get_default_dt, nest::Time::is_step.
nest::noise_generator::Parameters_ & nest::noise_generator::Parameters_::operator=(const Parameters_ &p)
void nest::noise_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::dt, nest::names::frequency, nest::names::mean, nest::names::phase, nest::names::std, nest::names::std_mod.
Referenced by nest::noise_generator::get_status.
void nest::noise_generator::Parameters_::set(const DictionaryDatum &, const noise_generator &, Node *node)
Set values from dictionary.
References nest::names::dt, nest::names::frequency, nest::names::mean, nest::names::phase, nest::names::std, nest::names::std_mod.
Referenced by nest::noise_generator::set_data_from_stimulation_backend, nest::noise_generator::set_status.
Time nest::noise_generator::Parameters_::get_default_dt()
References nest::Time::get_resolution.
Referenced by Parameters_.