nest::mip_generator::Parameters_
double nest::mip_generator::Parameters_::rate_
process rate in Hz
double nest::mip_generator::Parameters_::p_copy_
copy probability for each spike in the parent process
nest::mip_generator::Parameters_::Parameters_()
Sets default parameter values.
void nest::mip_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::p_copy, nest::names::rate.
Referenced by nest::mip_generator::get_status.
void nest::mip_generator::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::d, nest::names::p_copy, nest::names::rate.
Referenced by nest::mip_generator::set_data_from_stimulation_backend, nest::mip_generator::set_status.