nest::iaf_psc_alpha_multisynapse::Parameters_
double nest::iaf_psc_alpha_multisynapse::Parameters_::Tau_
Membrane time constant in ms.
Referenced by nest::iaf_psc_alpha_multisynapse::pre_run_hook.
double nest::iaf_psc_alpha_multisynapse::Parameters_::C_
Membrane capacitance in pF.
Referenced by nest::iaf_psc_alpha_multisynapse::pre_run_hook.
double nest::iaf_psc_alpha_multisynapse::Parameters_::refractory_time_
Refractory period in ms.
Referenced by nest::iaf_psc_alpha_multisynapse::pre_run_hook.
double nest::iaf_psc_alpha_multisynapse::Parameters_::E_L_
Resting potential in mV.
Referenced by nest::iaf_psc_alpha_multisynapse::get_state_element.
double nest::iaf_psc_alpha_multisynapse::Parameters_::I_e_
External current in pA.
Referenced by nest::iaf_psc_alpha_multisynapse::update.
double nest::iaf_psc_alpha_multisynapse::Parameters_::V_reset_
Reset value of the membrane potential.
Referenced by nest::iaf_psc_alpha_multisynapse::update.
double nest::iaf_psc_alpha_multisynapse::Parameters_::Theta_
Threshold, RELATIVE TO RESTING POTENTIAL(!).
I.e. the real threshold is (E_L_+Theta_).
Referenced by nest::iaf_psc_alpha_multisynapse::update.
double nest::iaf_psc_alpha_multisynapse::Parameters_::LowerBound_
Lower bound, RELATIVE TO RESTING POTENTIAL(!).
I.e. the real lower bound is (LowerBound_+Theta_).
Referenced by nest::iaf_psc_alpha_multisynapse::update.
std::vector< double > nest::iaf_psc_alpha_multisynapse::Parameters_::tau_syn_
Time constants of synaptic currents in ms.
Referenced by nest::iaf_psc_alpha_multisynapse::insert_current_recordables, n_receptors_, nest::iaf_psc_alpha_multisynapse::pre_run_hook, nest::iaf_psc_alpha_multisynapse::set_status.
bool nest::iaf_psc_alpha_multisynapse::Parameters_::has_connections_
Referenced by nest::iaf_psc_alpha_multisynapse::handles_test_event.
size_t nest::iaf_psc_alpha_multisynapse::Parameters_::n_receptors_() const
Returns the size of tau_syn_.
References tau_syn_.
Referenced by nest::iaf_psc_alpha_multisynapse::handles_test_event, nest::iaf_psc_alpha_multisynapse::pre_run_hook, nest::iaf_psc_alpha_multisynapse::update.
nest::iaf_psc_alpha_multisynapse::Parameters_::Parameters_()
Sets default parameter values.
void nest::iaf_psc_alpha_multisynapse::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::C_m, nest::names::d, nest::names::E_L, nest::names::has_connections, nest::names::I_e, nest::names::n_synapses, nest::names::t_ref, nest::names::tau_m, nest::names::tau_syn, nest::names::V_min, nest::names::V_reset, nest::names::V_th.
Referenced by nest::iaf_psc_alpha_multisynapse::get_status.
double nest::iaf_psc_alpha_multisynapse::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
Change in reversal potential E_L, to be passed to State_::set()
References nest::names::C_m, nest::names::d, nest::names::E_L, nest::names::I_e, nest::names::t_ref, nest::names::tau_m, nest::names::V_min, nest::names::V_reset, nest::names::V_th.
Referenced by nest::iaf_psc_alpha_multisynapse::set_status.