nest::gamma_sup_generator::Parameters_
double nest::gamma_sup_generator::Parameters_::rate_
rate of component gamma process [Hz]
unsigned long nest::gamma_sup_generator::Parameters_::gamma_shape_
gamma shape parameter [1]
unsigned long nest::gamma_sup_generator::Parameters_::n_proc_
number of component processes
size_t nest::gamma_sup_generator::Parameters_::num_targets_
Number of targets.
This is a hidden parameter; must be placed in parameters, even though it is an implementation detail, since it concerns the connections and must not be affected by resets.
Referenced by nest::gamma_sup_generator::send_test_event.
nest::gamma_sup_generator::Parameters_::Parameters_()
Sets default parameter values.
void nest::gamma_sup_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::gamma_shape, nest::names::n_proc, nest::names::rate.
Referenced by nest::gamma_sup_generator::get_status.
void nest::gamma_sup_generator::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::d, nest::names::gamma_shape, nest::names::n_proc, nest::names::rate.
Referenced by nest::gamma_sup_generator::set_data_from_stimulation_backend, nest::gamma_sup_generator::set_status.