nest::ac_generator::Parameters_
double nest::ac_generator::Parameters_::amp_
Amplitude of sine-current.
double nest::ac_generator::Parameters_::offset_
Offset of sine-current.
double nest::ac_generator::Parameters_::freq_
Standard frequency in Hz.
double nest::ac_generator::Parameters_::phi_deg_
Phase of sine current (0-360 deg)
nest::ac_generator::Parameters_::Parameters_()
Sets default parameter values.
nest::ac_generator::Parameters_::Parameters_(const Parameters_ &)
nest::ac_generator::Parameters_ & nest::ac_generator::Parameters_::operator=(const Parameters_ &p)
References nest::names::p.
void nest::ac_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::amplitude, nest::names::frequency, nest::names::offset, nest::names::phase.
Referenced by nest::ac_generator::get_status.
void nest::ac_generator::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::amplitude, nest::names::d, nest::names::frequency, nest::names::offset, nest::names::phase.
Referenced by nest::ac_generator::set_data_from_stimulation_backend, nest::ac_generator::set_status.