nest::poisson_generator::Parameters_
double nest::poisson_generator::Parameters_::rate_
process rate in Hz
nest::poisson_generator::Parameters_::Parameters_()
Sets default parameter values.
void nest::poisson_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::d, nest::names::rate.
Referenced by nest::poisson_generator::get_status.
void nest::poisson_generator::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::d, nest::names::rate.
Referenced by nest::poisson_generator::set_data_from_stimulation_backend, nest::poisson_generator::set_status.