nest::sinusoidal_poisson_generator::Parameters_
double nest::sinusoidal_poisson_generator::Parameters_::om_
Temporal frequency in radian/ms.
double nest::sinusoidal_poisson_generator::Parameters_::phi_
Phase in radian.
double nest::sinusoidal_poisson_generator::Parameters_::rate_
Mean firing rate in spikes/ms.
double nest::sinusoidal_poisson_generator::Parameters_::amplitude_
Firing rate modulation amplitude in spikes/ms.
bool nest::sinusoidal_poisson_generator::Parameters_::individual_spike_trains_
Emit individual spike trains for each target, or same for all?
Referenced by nest::sinusoidal_poisson_generator::has_proxies.
nest::sinusoidal_poisson_generator::Parameters_::Parameters_()
Sets default parameter values.
nest::sinusoidal_poisson_generator::Parameters_::Parameters_(const Parameters_ &)
nest::sinusoidal_poisson_generator::Parameters_ & nest::sinusoidal_poisson_generator::Parameters_::operator=(const Parameters_ &p)
void nest::sinusoidal_poisson_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::amplitude, nest::names::frequency, nest::names::individual_spike_trains, nest::names::phase, numerics::pi, nest::names::rate.
Referenced by nest::sinusoidal_poisson_generator::get_status.
void nest::sinusoidal_poisson_generator::Parameters_::set(const DictionaryDatum &, const sinusoidal_poisson_generator &, Node *)
Set values from dictionary.
State is passed so that the position can be reset if the spike_times_ vector has been filled with new data.
References nest::names::amplitude, nest::names::frequency, nest::names::individual_spike_trains, nest::names::phase, numerics::pi, nest::names::rate.
Referenced by nest::sinusoidal_poisson_generator::set_data_from_stimulation_backend, nest::sinusoidal_poisson_generator::set_status.