nest::pulsepacket_generator::Parameters_
std::vector< double > nest::pulsepacket_generator::Parameters_::pulse_times_
times of pulses
long nest::pulsepacket_generator::Parameters_::a_
number of pulses in a packet
double nest::pulsepacket_generator::Parameters_::sdev_
standard deviation of the packet
double nest::pulsepacket_generator::Parameters_::sdev_tolerance_
nest::pulsepacket_generator::Parameters_::Parameters_()
Sets default parameter values.
void nest::pulsepacket_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::activity, nest::names::pulse_times, nest::names::sdev.
Referenced by nest::pulsepacket_generator::get_status.
void nest::pulsepacket_generator::Parameters_::set(const DictionaryDatum &, pulsepacket_generator &, Node *)
Set values from dictionary.
Buffer is passed so that the position etc can be reset parameters have been changed.
References nest::names::activity, nest::pulsepacket_generator::B_, nest::names::d, nest::names::sdev, nest::sort, nest::pulsepacket_generator::Buffers_::spiketimes_.
Referenced by nest::pulsepacket_generator::set_data_from_stimulation_backend, nest::pulsepacket_generator::set_status.