nest::ppd_sup_generator::Parameters_
double nest::ppd_sup_generator::Parameters_::rate_
process rate [Hz]
double nest::ppd_sup_generator::Parameters_::dead_time_
dead time [ms]
unsigned long nest::ppd_sup_generator::Parameters_::n_proc_
number of component processes
double nest::ppd_sup_generator::Parameters_::frequency_
rate modulation frequency [Hz]
double nest::ppd_sup_generator::Parameters_::amplitude_
rate modulation amplitude [Hz]
size_t nest::ppd_sup_generator::Parameters_::num_targets_
Number of targets.
This is a hidden parameter; must be placed in parameters, even though it is an implementation detail, since it concerns the connections and must not be affected by resets.
Referenced by nest::ppd_sup_generator::send_test_event.
nest::ppd_sup_generator::Parameters_::Parameters_()
Sets default parameter values.
void nest::ppd_sup_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::dead_time, nest::names::frequency, nest::names::n_proc, nest::names::rate, nest::names::relative_amplitude.
Referenced by nest::ppd_sup_generator::get_status.
void nest::ppd_sup_generator::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::d, nest::names::dead_time, nest::names::frequency, nest::names::n_proc, nest::names::rate, nest::names::relative_amplitude.
Referenced by nest::ppd_sup_generator::set_data_from_stimulation_backend, nest::ppd_sup_generator::set_status.