nest::SynIdDelay
unsigned int nest::SynIdDelay::delay
Referenced by nest::Connection< targetidentifierT >::get_delay_steps, nest::Connection< targetidentifierT >::set_delay_steps.
unsigned int nest::SynIdDelay::syn_id
Referenced by nest::Connection< targetidentifierT >::get_syn_id, nest::Connection< targetidentifierT >::set_syn_id.
bool nest::SynIdDelay::more_targets
Referenced by set_source_has_more_targets, source_has_more_targets.
bool nest::SynIdDelay::disabled
Referenced by disable, is_disabled.
nest::SynIdDelay::SynIdDelay(double d)
References nest::names::d, set_delay_ms.
nest::SynIdDelay::SynIdDelay(const SynIdDelay &s)=default
SynIdDelay& nest::SynIdDelay::operator=(const SynIdDelay &s)=default
double nest::SynIdDelay::get_delay_ms() const
Return the delay of the connection in ms.
References nest::Time::delay_steps_to_ms.
Referenced by nest::Connection< targetidentifierT >::get_delay.
void nest::SynIdDelay::set_delay_ms(const double d)
Set the delay of the connection specified in ms.
References nest::names::d, nest::Time::delay_ms_to_steps.
Referenced by nest::Connection< targetidentifierT >::set_delay, SynIdDelay.
void nest::SynIdDelay::set_source_has_more_targets(const bool more_targets)
References more_targets.
Referenced by nest::Connection< targetidentifierT >::set_source_has_more_targets.
bool nest::SynIdDelay::source_has_more_targets() const
References more_targets.
Referenced by nest::Connection< targetidentifierT >::source_has_more_targets.
void nest::SynIdDelay::disable()
Disables the synapse.
is_disabled
References disabled.
Referenced by nest::Connection< targetidentifierT >::disable.
bool nest::SynIdDelay::is_disabled() const
Returns a flag denoting if the synapse is disabled.
disable
References disabled.
Referenced by nest::Connection< targetidentifierT >::is_disabled.