nest::gif_psc_exp_multisynapse::Parameters_
double nest::gif_psc_exp_multisynapse::Parameters_::g_L_
double nest::gif_psc_exp_multisynapse::Parameters_::E_L_
double nest::gif_psc_exp_multisynapse::Parameters_::V_reset_
double nest::gif_psc_exp_multisynapse::Parameters_::Delta_V_
double nest::gif_psc_exp_multisynapse::Parameters_::V_T_star_
double nest::gif_psc_exp_multisynapse::Parameters_::lambda_0_
double nest::gif_psc_exp_multisynapse::Parameters_::t_ref_
1/ms
Refractory period in ms.
double nest::gif_psc_exp_multisynapse::Parameters_::c_m_
Membrane capacitance in pF.
std::vector< double > nest::gif_psc_exp_multisynapse::Parameters_::tau_stc_
We use stc and sfa, respectively instead of eta and gamma (mentioned in the references).
List of spike triggered current time constant in ms.
std::vector< double > nest::gif_psc_exp_multisynapse::Parameters_::q_stc_
List of spike triggered current jumps in nA.
std::vector< double > nest::gif_psc_exp_multisynapse::Parameters_::tau_sfa_
List of adaptive threshold time constant in ms.
std::vector< double > nest::gif_psc_exp_multisynapse::Parameters_::q_sfa_
List of adaptive threshold jumps in mV.
std::vector< double > nest::gif_psc_exp_multisynapse::Parameters_::tau_syn_
Time constants of synaptic currents in ms.
Referenced by n_receptors_.
bool nest::gif_psc_exp_multisynapse::Parameters_::has_connections_
boolean flag which indicates whether the neuron has connections
Referenced by nest::gif_psc_exp_multisynapse::handles_test_event.
double nest::gif_psc_exp_multisynapse::Parameters_::I_e_
External DC current.
nest::gif_psc_exp_multisynapse::Parameters_::Parameters_()
Sets default parameter values.
void nest::gif_psc_exp_multisynapse::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::C_m, nest::names::Delta_V, nest::names::E_L, nest::names::g_L, nest::names::has_connections, nest::names::I_e, nest::names::lambda_0, nest::names::n_receptors, nest::names::q_sfa, nest::names::q_stc, nest::names::t_ref, nest::names::tau_sfa, nest::names::tau_stc, nest::names::tau_syn, nest::names::V_reset, nest::names::V_T_star.
Referenced by nest::gif_psc_exp_multisynapse::get_status.
void nest::gif_psc_exp_multisynapse::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::C_m, nest::names::Delta_V, nest::names::E_L, nest::names::g_L, nest::names::I_e, nest::names::lambda_0, nest::names::q_sfa, nest::names::q_stc, nest::names::t_ref, nest::names::tau_sfa, nest::names::tau_stc, nest::names::tau_syn, updateValue, nest::names::V_reset, nest::names::V_T_star.
Referenced by nest::gif_psc_exp_multisynapse::set_status.
size_t nest::gif_psc_exp_multisynapse::Parameters_::n_receptors_() const
Return the number of receptor ports.
References tau_syn_.
Referenced by nest::gif_psc_exp_multisynapse::handle, nest::gif_psc_exp_multisynapse::handles_test_event.