nest::dc_generator::Parameters_
double nest::dc_generator::Parameters_::amp_
stimulation amplitude, in pA
nest::dc_generator::Parameters_::Parameters_()
Sets default parameter values.
nest::dc_generator::Parameters_::Parameters_(const Parameters_ &)
nest::dc_generator::Parameters_ & nest::dc_generator::Parameters_::operator=(const Parameters_ &p)
References nest::names::p.
void nest::dc_generator::Parameters_::get(DictionaryDatum &) const
Store current values in dictionary.
References nest::names::amplitude, nest::names::d.
Referenced by nest::dc_generator::get_status.
void nest::dc_generator::Parameters_::set(const DictionaryDatum &, Node *node)
Set values from dictionary.
References nest::names::amplitude, nest::names::d.
Referenced by nest::dc_generator::set_data_from_stimulation_backend, nest::dc_generator::set_status.