tokenutils.h
FT getValue(const Token &t)
getValue provides easy read-access to a Token's contents.
getValue returns the value of the Datum contained inside the Token. The general getValue function assumes that the datum was directly derived from a C++ type (most probably some container or stream). All other cases will be handled by specialization of this template. For example, AggregateDatum types are directly derived from a C++ type. SLI Datum derived from C++ type ------------------------------------------ BoolDatum Name HandleDatum DatumHandle (whatever that might be...) LiteralDatum Name NameDatum Name ParserDatum Parser StringDatum string SymbolDatum Name (What else?) Hence, getValue may be used in the following ways: call can be used on Token containing SLI-type -------------------------------------------------------------------- Name getValue<Name> {Bool|Literal|Name|Symbol}Datum DatumHandle getValue<DatumHandle> HandleDatum Parser getValue<Parser> ParserDatum string getValue<string> StringDatum The following specialized variants of getValue() can be used in addition: call can be used on Token containing SLI-type ------------------------------------------------------------------------- long GetValue<long> IntegerDatum double GetValue<double> DoubleDatum bool GetValue<bool> BoolDatum string GetValue<string> NameDatum string GetValue<string> LiteralDatum string GetValue<string> SymbolDatum vector<long> GetValue<vector<long> > ArrayDatum vector<double> GetValue<vector<double> > ArrayDatum What about the rest? (ElementFactoryDatum, el_prtdatum, FunctionDatum, GenericDatum, NumericDatum, lockPTRDatum, ReferenceDatum, SmartPtrDatum, TrieDatum) TypeMismatch The specified fundamental datatype does not match the Token's contents, or a template specialization for this type is missing.
References Token::datum.
void setValue(const Token &t, FT const &value)
setValue provides easy write-access to a Token's contents.
setValue updates the value of the Datum contained inside the Token. setValue(Token, value) can be called on the same value/Datum pairs getValue handles. Note that the template parameter to setValue does not need to be specified explicitely, as it can be derived from the second argument. TypeMismatch The specified fundamental datatype does not match the Token's contents, or a template specialization for this type is missing.
References Token::datum.
Token newToken2(FT const &value)
Create a new Token from a fundamental data type.
Specify the desired Datum type as the second template parameter!
Token newToken(FT const &value)
Create a new Token from a fundamental data type.
This template is specialized for the most fundamental types. If it does not work, use newToken2() and specify the Datum type explicitely.
long getValue< long >(const Token &)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by nest::cm_default::add_compartment_, nest::cm_default::add_receptor_, nest::NodeCollection::create, nest::AbstractLayer::create_layer, nest::Layer< D >::dump_connections, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::SetFakeNumProcesses_iFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::Get_g_iFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIInterpreter::execute_, SLIInterpreter::execute_debug_, nest::ConnectionCreator::extract_params_, Token::operator long, Token::operator size_t, nest::set_connection_status, SLIInterpreter::terminate.
void setValue< long >(const Token &, long const &value)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by setValue< std::vector< long > >.
Token newToken< long >(long const &value)
double getValue< double >(const Token &)
References Token::datum, GenericDatum< D, slt >::get, Datum::gettypename, Name::toString.
Referenced by nest::AMPA::AMPA, nest::AMPA_NMDA::AMPA_NMDA, nest::BallMask< D >::BallMask, nest::BoxMask< D >::BoxMask, nest::ConstantParameter::ConstantParameter, nest::create_doughnut, nest::Layer< D >::dump_connections, nest::EllipseMask< D >::EllipseMask, nest::NestModule::SetStdpEps_dFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Pow_P_dFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, nest::ExpDistParameter::ExpDistParameter, nest::GABA::GABA, nest::GammaParameter::GammaParameter, nest::Gaussian2DParameter::Gaussian2DParameter, nest::GaussianParameter::GaussianParameter, nest::K::K, nest::Na::Na, nest::NMDA::NMDA, Token::operator double, nest::SPBuilder::update_delay.
void setValue< double >(const Token &, double const &value)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by setValue< std::vector< double > >.
Token newToken< double >(double const &value)
bool getValue< bool >(const Token &)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by nest::ConnectionCreator::ConnectionCreator, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::ConnectionCreator::extract_params_, Token::operator bool, nest::Layer< D >::set_status, nest::SPManager::set_status.
void setValue< bool >(const Token &, bool const &value)
References Token::datum, Datum::gettypename, Name::toString.
Token newToken< bool >(bool const &value)
std::string getValue< std::string >(const Token &)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by nest::cm_default::add_receptor_, nest::ConnectionManager::connect, nest::AbstractLayer::create_layer, nest::SPManager::disconnect, nest::NestModule::SetDefaults_l_DFunction::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::ConnectionManager::get_connections, Token::matches_as_string, Token::operator std::string, nest::multimeter::Parameters_::set, nest::SynapticElement::set, nest::ConnBuilder::set_structural_plasticity_parameters.
void setValue< std::string >(const Token &, std::string const &value)
References Token::datum, Datum::gettypename, Name::toString.
Token newToken< std::string >(std::string const &value)
std::vector< long > getValue< std::vector< long > >(const Token &)
void setValue< std::vector< long > >(const Token &, std::vector< long > const &value)
References setValue< long >, Name::toString.
Token newToken< std::vector< long > >(std::vector< long > const &value)
std::vector< double > getValue< std::vector< double > >(const Token &)
void setValue< std::vector< double > >(const Token &, std::vector< double > const &value)
References setValue< double >, Name::toString.
Token newToken< std::vector< double > >(std::vector< double > const &value)