tokenutils.cc
long getValue< long >(const Token &t)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by nest::cm_default::add_compartment_, nest::cm_default::add_receptor_, nest::NodeCollection::create, nest::AbstractLayer::create_layer, nest::Layer< D >::dump_connections, nest::NestModule::GetStatus_iFunction::execute, nest::NestModule::SetStatus_idFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::NestModule::SetFakeNumProcesses_iFunction::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::NestModule::TimeCommunicationv_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute, nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute, nest::NestModule::Cvnodecollection_i_iFunction::execute, nest::NestModule::MemberQ_g_iFunction::execute, nest::NestModule::Find_g_iFunction::execute, nest::NestModule::Get_g_iFunction::execute, SLIArrayModule::RotateFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIInterpreter::execute_, SLIInterpreter::execute_debug_, nest::ConnectionCreator::extract_params_, Token::operator long, Token::operator size_t, nest::set_connection_status, SLIInterpreter::terminate.
void setValue< long >(const Token &t, long const &value)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by setValue< std::vector< long > >.
Token newToken< long >(long const &value)
double getValue< double >(const Token &t)
References Token::datum, GenericDatum< D, slt >::get, Datum::gettypename, Name::toString.
Referenced by nest::AMPA::AMPA, nest::AMPA_NMDA::AMPA_NMDA, nest::BallMask< D >::BallMask, nest::BoxMask< D >::BoxMask, nest::ConstantParameter::ConstantParameter, nest::create_doughnut, nest::Layer< D >::dump_connections, nest::EllipseMask< D >::EllipseMask, nest::NestModule::SetStdpEps_dFunction::execute, nest::NestModule::Min_P_dFunction::execute, nest::NestModule::Max_P_dFunction::execute, nest::NestModule::Redraw_P_d_dFunction::execute, nest::NestModule::Pow_P_dFunction::execute, SLIArrayModule::GaborFunction::execute, SLIArrayModule::Gauss2dFunction::execute, SLIArrayModule::FiniteQ_dFunction::execute, nest::ExpDistParameter::ExpDistParameter, nest::GABA::GABA, nest::GammaParameter::GammaParameter, nest::Gaussian2DParameter::Gaussian2DParameter, nest::GaussianParameter::GaussianParameter, nest::K::K, nest::Na::Na, nest::NMDA::NMDA, Token::operator double, nest::SPBuilder::update_delay.
void setValue< double >(const Token &t, double const &value)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by setValue< std::vector< double > >.
Token newToken< double >(double const &value)
bool getValue< bool >(const Token &t)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by nest::ConnectionCreator::ConnectionCreator, nest::NestModule::GetNodes_D_b::execute, nest::NestModule::TimeCommunication_i_i_bFunction::execute, nest::ConnectionCreator::extract_params_, Token::operator bool, nest::Layer< D >::set_status, nest::SPManager::set_status.
void setValue< bool >(const Token &t, bool const &value)
References Token::datum, Datum::gettypename, Name::toString.
Token newToken< bool >(bool const &value)
std::string getValue< std::string >(const Token &t)
References Token::datum, Datum::gettypename, Name::toString.
Referenced by nest::cm_default::add_receptor_, nest::ConnectionManager::connect, nest::AbstractLayer::create_layer, nest::SPManager::disconnect, nest::NestModule::SetDefaults_l_DFunction::execute, nest::NestModule::GetDefaults_lFunction::execute, nest::NestModule::Create_l_iFunction::execute, nest::ConnectionManager::get_connections, Token::matches_as_string, Token::operator std::string, nest::multimeter::Parameters_::set, nest::SynapticElement::set, nest::ConnBuilder::set_structural_plasticity_parameters.
void setValue< std::string >(const Token &t, std::string const &value)
References Token::datum, Datum::gettypename, Name::toString.
Token newToken< std::string >(std::string const &value)
std::vector< double > getValue< std::vector< double > >(const Token &t)
void setValue< std::vector< double > >(const Token &t, std::vector< double > const &value)
References setValue< double >, Name::toString.
Token newToken< std::vector< double > >(std::vector< double > const &value)
std::vector< long > getValue< std::vector< long > >(const Token &t)
void setValue< std::vector< long > >(const Token &t, std::vector< long > const &value)
References setValue< long >, Name::toString.
Token newToken< std::vector< long > >(std::vector< long > const &value)