# Conda environment specification for NEST Simulator
#
# This file specifies a conda environment for those who would
# like to compile NEST or build NEST documentation themselves.
# If you just want to execute NEST, you should install NEST
# directly as described in https://www.nest-simulator.org/installation.
#
#
# The environment specification below is comprehensive: it includes
# all packages required to build and run NEST with OpenMP and MPI
# parallelisation, GSL-dependent models, NumPy and Pandas-dependent
# features of PyNEST and examples requiring Matplotlib, and to run
# the NEST testsuite. It also comprises all tools required to build
# NEST documentation and to run NEST server. The requirements for the
# documentation and server are marked in separate sections below so
# you can remove them if you would like a leaner environment.
#
# NOTE: Do NOT delete the PIP section at the end of the file. Environment files
#       allow just a single PIP section. All dependencies not satisfied by
#       conda-forge are placed there.
#
# NOTE: If you are working on Apple Silicon (M1 CPU), you must comment out the
#       NEST Server section below because conda-forge does not provide uwsgi
#       for osx-arm64 yet.
#
# NOTE: libneurosim, MUSIC and SIONLib are not included in this environment.
#
# The default name of the environment is nest-simulator-dev, since it is mainly
# aimed at NEST developers. You can specify a different name by passing
# -n my_name to the conda env create command.

name: nest-simulator-dev
channels:
  - conda-forge

dependencies:
  # Basics ------------------
  - python >= 3.8
  - pip

  # Building NEST -----------
  - cmake >= 3.12
  - cython
  - openmpi
  - boost >= 1.69
  - gsl >= 1.11
  - libtool
  - readline

  # Testing NEST ------------
  - nose
  - pytest
  - numpy
  - pandas
  - scipy
  - mpi4py
  - terminaltables
  - pep8

  # Working with NEST ------
  - ipython
  - matplotlib
  - jupyter
  - jupyterlab

  # Building NEST documentation
  - PyYAML>=4.2b1
  - breathe
  - csvkit
  - docutils
  - doxygen
  - mock
  - nbsphinx
  - numpydoc
  - path.py
  - pydot
  - recommonmark
  - sphinx-tabs
  - sphinx >= 2
  - sphinx_rtd_theme
  - jinja2 < 3
  - tqdm
  - yamllint

  # Running NEST Server ----
  - flask
  - flask_cors
  - requests
  - uwsgi
  - werkzeug

  # PIP dependencies -- do not delete
  - pip:
    # For testsuite
    - junitparser >= 2
    # For documentation
    - example
    - Image
    - sphinx_autobuild
    - sphinx_gallery
