name: Mirror to Codebase Helmholtz Cloud

on:
  push:
    branches: [ master ]

jobs:
  sync_to_jsc:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'nest' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: sycnmaster
        uses: wei/git-sync@55c6b63b4f21607da0e9877ca9b4d11a29fc6d83
        with:
          source_repo: "nest/nest-simulator"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.HGF_GITLAB_TOKEN }}@codebase.helmholtz.cloud/nest/nest-simulator.git"
          destination_branch: "master"
      - name: synctags
        uses: wei/git-sync@55c6b63b4f21607da0e9877ca9b4d11a29fc6d83
        with:
          source_repo: "nest/nest-simulator"
          source_branch: "refs/tags/v*"
          destination_repo: "https://ghpusher:${{ secrets.HGF_GITLAB_TOKEN }}@codebase.helmholtz.cloud/nest/nest-simulator.git"
          destination_branch: "refs/tags/v*"
