name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install wheel building requirements
        run: |
          sudo apt-get install libomp-dev
          python -m pip install cibuildwheel==2.2.0a1 wheel cython

      - name: Prepare wheel building environment
        run: |
          source extras/wheelbuild/wheelbuild.sh
      - name: Build wheels
        run: |
          echo "STARTING CIBUILDWHEEL"
          pwd
          python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
