name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install OpenMP (MacOS)
        if: runner.os == 'macOS'
        run: brew install libomp
      - name: Install OpenMP (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install libomp-dev
      - name: Install Python wheel building prep requirements
        run: |
          python -m pip install wheel cython
      - name: Clone wheel building environment
        uses: actions/checkout@v2
        with:
          path: build_wheel_env
      - name: Prepare wheel building environment
        run: |
          source extras/wheelbuild/wheelbuild.sh
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.3
        with:
          output-dir: ../wheelhouse
      - name: Build wheels
        run: |
          cd build_wheel_env
          python -m cibuildwheel --output-dir ../wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
