name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install OpenMP (MacOS)
        if: runner.os == 'macOS'
        run: brew install libomp

      - name: Install OpenMP (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install libomp-dev

      - name: Install Python wheel building requirements
        run: |
          python -m pip install cibuildwheel==2.2.0a1 wheel cython

      - name: Clone wheel building environment
        uses: actions/checkout@v2
        with:
          path: build_wheel_env
      - name: Prepare wheel building environment
        run: |
          echo "STARTING WHEEL ENV PREP"
          pwd
          source extras/wheelbuild/wheelbuild.sh
          echo "FINISHED WHEEL ENV PREP"
          pwd
      - name: Build wheels
        run: |
          echo "STARTING CIBUILDWHEEL"
          cd build_wheel_env
          pwd
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: NEST_CMAKE_BUILDWHEEL=ON
          CIBW_BEFORE_BUILD_LINUX: apt-get update && apt-get install python-dev python3-dev

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
