rule all:
    input:
        'NetworkSketch_TwoPopulationNetworkPlastic.svg'

rule convert_network_sketch_to_pdf:
    """
    Convert libreoffice draw sketch (fodg format) to pdf.
    """
    input:
        'NetworkSketch_TwoPopulationNetworkPlastic.fodg'
     	        
    output:
        'NetworkSketch_TwoPopulationNetworkPlastic.pdf'        

    run:
        shell('libreoffice --convert-to pdf:draw_pdf_Export {input}')        

rule convert_network_sketch_to_svg:
    """
    Convert pdf to svg.
    """
    input:
        'NetworkSketch_TwoPopulationNetworkPlastic.pdf'
     	        
    output:
        'NetworkSketch_TwoPopulationNetworkPlastic.svg'        

    run:
        shell('inkscape --export-type=svg {input}')        

rule clean:
    run:
        shell("rm *.pdf *.svg")
